### ISSUE TITLE
这是用户爆满了的意思吗

### ISSUE THREAD

**Issue by SakuragiKuroko** [ikechan8370/chatgpt-plugin#100]
![image](https://user-images.githubusercontent.com/103973922/212633265-1a5bee11-55e2-416d-bca4-cc819726404e.png)

**Comment by ikechan8370** [comment]
对。等会就好了 或者换个地区的节点可能也有效果

**Comment by SakuragiKuroko** [comment]
> 对。等会就好了 或者换个地区的节点可能也有效果

好
