### ISSUE TITLE
更新以后一直卡在队列里，前面的问题一直无法处理

### ISSUE THREAD

**Issue by zfztty** [ikechan8370/chatgpt-plugin#103]
更新以后一直显示前方的问题都在队列里等待，始终无法回答

**Comment by ikechan8370** [comment]
已知可能有这个问题。原因可能是网络等问题卡住了。暂时用redis-cli进入用`lpop CHATGPT:CHAT_QUEUE`移出最前面的问题吧。（lpop每次移出最前面的一个）后续可能加个超时和手动清理的命令

**Comment by zfztty** [comment]
> 已知可能有这个问题。原因可能是网络等问题卡住了。暂时用redis-cli进入用`lpop CHATGPT:CHAT_QUEUE`移出最前面的问题吧。（lpop每次移出最前面的一个）后续可能加个超时和手动清理的命令

好的，谢谢佬
