### ISSUE TITLE
更新以后报错

### ISSUE THREAD

**Issue by zfztty** [ikechan8370/chatgpt-plugin#107]
请问一下这个报错是什么原因Error: Invalid environment: global fetch not defined

**Comment by ikechan8370** [comment]
> 请问一下这个报错是什么原因Error: Invalid environment: global fetch not defined

nodejs版本要高于18。执行node -v检查一下。如果低了，方便的话可以升级nodejs。否则可以去看看chatgpt-api给出的解决方案，它的readme有说。

**Comment by zfztty** [comment]
hao'd

> > 请问一下这个报错是什么原因Error: Invalid environment: global fetch not defined
> 
> nodejs版本要高于18。执行node -v检查一下。如果低了，方便的话可以升级nodejs。否则可以去看看chatgpt-api给出的解决方案，它的readme有说。

好的，升级以后就好了，谢谢佬
