### ISSUE TITLE
qq有字数限制 能不能设置成分段发的

### ISSUE THREAD

**Issue by akmioto** [ikechan8370/chatgpt-plugin#11]

**Comment by ikechan8370** [comment]
qq字数限制远高于chatgpt本身输出的字数限制，所以应该不会存在这个问题的。
如果输出不全，你可以试着使用#chatgpt Continue让他继续讲下去。
#3

**Comment by ayakasuki** [comment]
[YzBot][16:30:22.565][WARN] 群消息可能被风控，将尝试使用分片发送

估计他说的是这个

**Comment by Stonewalling** [comment]
function splitCode(code) {
  let lines = ''
  
  if(code.includes('}')){
      lines = code.split('}')
  }else{
      lines = code.split(/[.!]/)
  }
  console.log("lines",lines)
  const blocks = [];
  let currentBlock = '';

  for (const line of lines) {
    if (currentBlock.length + line.length <= 199) {
      currentBlock += line;
    } else {
      if(code.includes('}')){
        blocks.push(currentBlock + "}");
      }else{
          blocks.push(currentBlock);
      }
      currentBlock = line;
    }
  }

  blocks.push(currentBlock);

  return blocks;
}
