### ISSUE TITLE
与OpenAI通信异常，请稍后重试：Error: ChatGPT error 404

### ISSUE THREAD

**Issue by Fanrito** [ikechan8370/chatgpt-plugin#111]
正常对话一段时间后出现了这个报错，更换api-key重启也没用，有大佬知道怎么回事吗
与OpenAI通信异常，请稍后重试：Error: ChatGPT error 404: {
    "error": {
        "message": "That model does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

**Comment by ikechan8370** [comment]
> 正常对话一段时间后出现了这个报错，更换api-key重启也没用，有大佬知道怎么回事吗
> 
> 与OpenAI通信异常，请稍后重试：Error: ChatGPT error 404: {
> 
>     "error": {
> 
>         "message": "That model does not exist",
> 
>         "type": "invalid_request_error",
> 
>         "param": null,
> 
>         "code": null
> 
>     }
> 
> }

更新chatgpt依赖版本。昨晚夜间openai屏蔽了官方api，大佬们讨论了一晚上，暂时用davinci-03平替。

**Comment by ikechan8370** [comment]
更新chatgpt版本到4.1.1可解决
