### ISSUE TITLE
SyntaxError: Unexpected token '}'

### ISSUE THREAD

**Issue by Nana1337mi** [ikechan8370/chatgpt-plugin#112]
[YzBot][12:01:47.278][ERRO] 载入插件错误：chat
[YzBot][12:01:47.278][ERRO] SyntaxError: Unexpected token '}'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:117:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:361:14)
使用的系统是Centos7.6，由于无法更新node18，所以使用了 #110 的方案，但在启动时出现了上述error，在issue中搜到的解决方案是#4，但我并未找到有关sessionToken的设置

**Comment by SanQianQVQ** [comment]
请麻烦重新安装一下插件，看看能否复现错误
此外，您可能需要在执行 https://github.com/ikechan8370/chatgpt-plugin/pull/110 中给出的对 fetch 的修改前先运行一次插件。

**Comment by Nana1337mi** [comment]
> 

重新安装并未解决该问题

**Comment by Nana1337mi** [comment]
已解决，改index.js的时候少删一个{
...
