### ISSUE TITLE
与OpenAI通信异常，请稍后重试：Error: ERR invalid expire time in set

### ISSUE THREAD

**Issue by Nana1337mi** [ikechan8370/chatgpt-plugin#113]
启动正常，api是今天刚创的号申请的，也是没问题的。
关于index.js的填写也没有问题

**Comment by SanQianQVQ** [comment]
同出现此错误，我一会再看看

**Comment by ikechan8370** [comment]
更新再试试

**Comment by Nana1337mi** [comment]
> 更新再试试

更新了chatgpt@4.1.1但还是同样的问题

**Comment by ikechan8370** [comment]
> > 更新再试试
> 
> 更新了chatgpt@4.1.1但还是同样的问题

更新本项目

**Comment by Nana1337mi** [comment]
> > > 更新再试试
> > 
> > 
> > 更新了chatgpt@4.1.1但还是同样的问题
> 
> 更新本项目

解决了
