### ISSUE TITLE
在进行对话时总是提示在等待，然后一直不回。但程序没有报错。

### ISSUE THREAD

**Issue by GoahMidi** [ikechan8370/chatgpt-plugin#114]
![image](https://user-images.githubusercontent.com/28920970/216590133-16e33c07-2046-42d5-b0bf-42f13e973be1.png)

**Comment by ikechan8370** [comment]
更新一下，然后使用 `#清空chat队列` 命令清一下。前面可能卡死了。

**Comment by GoahMidi** [comment]
> 更新一下，然后使用 `#清空chat队列` 命令清一下。前面可能卡死了。

大佬大佬，又出现这个问题
![image](https://user-images.githubusercontent.com/28920970/216632530-edfbc58f-415f-4f40-91d7-4c190a9d5c4e.png)
下面是日志
![image](https://user-images.githubusercontent.com/28920970/216632750-e574d249-6d5f-4e39-9e14-8c8338c044c4.png)

**Comment by ikechan8370** [comment]
> > 更新一下，然后使用 `#清空chat队列` 命令清一下。前面可能卡死了。
> 
> 
> 
> 大佬大佬，又出现这个问题
> 
> ![image](https://user-images.githubusercontent.com/28920970/216632530-edfbc58f-415f-4f40-91d7-4c190a9d5c4e.png)
> 
> 下面是日志
> 
> ![image](https://user-images.githubusercontent.com/28920970/216632750-e574d249-6d5f-4e39-9e14-8c8338c044c4.png)
> 
> 

更新chatgpt至4.1.1。这几天上游更新会比较频繁，最好时刻保持最新。
