### ISSUE TITLE
与OpenAI通信异常，请稍后重试：Error: ChatGPT error 404

### ISSUE THREAD

**Issue by yukino-yuki** [ikechan8370/chatgpt-plugin#115]
与OpenAI通信异常，请稍后重试：Error: ChatGPT error 404: {
    "error": {
        "message": "That model does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}
突然之间就变成这样了。是chatgpt@4.0.4，请问这如何解决呢？

**Comment by yukino-yuki** [comment]
> 与OpenAI通信异常，请稍后重试：Error: ChatGPT error 404: { "error": { "message": "That model does not exist", "type": "invalid_request_error", "param": null, "code": null } } 突然之间就变成这样了。是chatgpt@4.0.4。请问这如何解决呢？

**Comment by ikechan8370** [comment]
> 与OpenAI通信异常，请稍后重试：Error: ChatGPT error 404: {
> 
>     "error": {
> 
>         "message": "That model does not exist",
> 
>         "type": "invalid_request_error",
> 
>         "param": null,
> 
>         "code": null
> 
>     }
> 
> }
> 
> 突然之间就变成这样了。是chatgpt@4.0.4

升到4.1.1
