### ISSUE TITLE
与OpenAI通信异常，请稍后重试：TypeError: fetch failed

### ISSUE THREAD

**Issue by GallWang** [ikechan8370/chatgpt-plugin#116]
![image](https://user-images.githubusercontent.com/77223220/216756137-a3936156-dfe9-470a-997e-2ab34a10e4b4.png)

**Comment by ikechan8370** [comment]
网络问题，调用openAI服务器超时了。目前不支持代理，未来支持proxy后可以用proxy，否则建议找个网络环境好的服务器
