### ISSUE TITLE
[Feature] 调整监听机制

### ISSUE THREAD

**Issue by SanQianQVQ** [ikechan8370/chatgpt-plugin#117]
看控制台输出目前似乎会监听所有消息，能否改为只监听 @机器人 后发送的不带 # 的消息？
目前监听方式会和一些插件的功能监听起冲突

**Comment by ikechan8370** [comment]
暂时可以通过把优先级数字调大缓解这个问题

**Comment by yzfylyw** [comment]
@ikechan8370 修改优先级这个办法并不能解决指令冲突得问题，至少yunzai里添加得表情都不会触发了。
yunzai v3里return默认是return true，应该把消息监听那几行return改为return false才行。

**Comment by ikechan8370** [comment]
改为用prefix模式吧
