### ISSUE TITLE
相比网页版，对话内容明显偏短

### ISSUE THREAD

**Issue by Oishiimono** [ikechan8370/chatgpt-plugin#118]
跟网页版的ChatGPT比较起来内容明显偏短，想请教下大佬们是否知道原因？能否手动解除其回复内容的长短限制？

**Comment by ikechan8370** [comment]
可能是调用模型prompt的原因，由于未知官方的一些参数，所用的都是大家摸索出来的参数，加上模型为去年年底版本，回复文本的偏向、性格等与网页版肯定有所差异。感兴趣可以去看看上游库的实现与讨论，我也看看能否把一些参数暴露出来让用户可以调整。

**Comment by ikechan8370** [comment]
> 跟网页版的ChatGPT比较起来内容明显偏短，想请教下大佬们是否知道原因？能否手动解除其回复内容的长短限制？

长短倒没有限制，个人经验感觉多聊几句他就说的多了。或者你让他多说一点。

**Comment by ikechan8370** [comment]
新加了个配置项，`promptPrefixOverride`。有兴趣可以研究一下。默认的里面有一句You answer as concisely as possible for each response (e.g. don’t be verbose)，导致他回复会尽可能简洁偏短。

**Comment by Oishiimono** [comment]
> 

厉害啊，这么快就被大佬找到原因了……不过纯小白只会按你们给的步骤来搭建，等以后有操作指南了我来参照调整一个。谢谢啦！

**Comment by ikechan8370** [comment]
有人发现了最新的模型，我写在了默认配置项`model`中，可以更新一下
