### ISSUE TITLE
如何使用插件啊？

### ISSUE THREAD

**Issue by AmandaloveYang** [ikechan8370/chatgpt-plugin#12]
这个项目的index.js放在YUNZAIbot的目录里面吗？

**Comment by AmandaloveYang** [comment]
[YzBot][15:19:09.888][MARK] chatgpt-plugin-main 缺少依赖：chatgpt
[YzBot][15:19:09.888][MARK] 请执行安装依赖命令：pnpm add chatgpt -w

**Comment by ikechan8370** [comment]
按照README操作
