### ISSUE TITLE
请问下大佬，这个可以更改触发方式吗

### ISSUE THREAD

**Issue by PoorGarry** [ikechan8370/chatgpt-plugin#121]
比如通过#指令然后触发，而不通过@直接触发对话

**Comment by ikechan8370** [comment]
[最新的提交](https://github.com/ikechan8370/chatgpt-plugin/commit/233fc7417c096109ed11615587276916e9e81149) 在配置文件中提供了触发方式的修改，以及一些其他的配置项，欢迎试用。
