### ISSUE TITLE
与OpenAI通信异常 chatgpt error 404

### ISSUE THREAD

**Issue by FenChenXingLong** [ikechan8370/chatgpt-plugin#122]
<img width="763" alt="image" src="https://user-images.githubusercontent.com/104333676/217399876-7b5b15e7-4b77-4537-9387-16df0ef365ff.png">
版本为：
<img width="371" alt="image" src="https://user-images.githubusercontent.com/104333676/217399896-8615be02-bf61-4260-a120-38209ae7eea1.png">

**Comment by yzfylyw** [comment]
今天遇到了同样的问题，昨天还好着。以为是openai那边出了问题，结果网页登录又正常。

**Comment by ikashana** [comment]
我今天也遇到同样问题了

**Comment by ikechan8370** [comment]
没错。OpenAI再一次封锁了这个模型。再更新chatgpt的版本，暂时用davinci模型吧。看来这种破解的方式并不稳定。似乎需要把之前的浏览器模式作为备选了。

**Comment by FenChenXingLong** [comment]
> 

请问现在是只需要更新chatgpt依赖包的版本吗？替换模型需要什么操作吗，更新到多少呢？谢谢

**Comment by ikashana** [comment]
> 没错。OpenAI再一次封锁了这个模型。再更新chatgpt的版本，暂时用davinci模型吧。看来这种破解的方式并不稳定。似乎需要把之前的浏览器模式作为备选了。

请问怎么换成davinci模型？之前游览器模式感觉也不是很稳定，我本来以为是昨天国内chatgpt连拿几个热搜，访问量激增，让chatgpt炸了

**Comment by ikechan8370** [comment]
> > 
> 
> 
> 
> 请问现在是只需要更新chatgpt依赖包的版本吗？替换模型需要什么操作吗，更新到多少呢？谢谢

更新到最新就行。那个作者还是更新很及时的。

**Comment by ikechan8370** [comment]
[chatgpt-api最新版本](https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.2.0)

**Comment by FenChenXingLong** [comment]
> [chatgpt-api最新版本](https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.2.0)

收到，刚刚也去npm社区看到了，谢谢回复

**Comment by ikechan8370** [comment]
> 
> 
> 
> 
> 
> 
> > 没错。OpenAI再一次封锁了这个模型。再更新chatgpt的版本，暂时用davinci模型吧。看来这种破解的方式并不稳定。似乎需要把之前的浏览器模式作为备选了。
> 
> 
> 
> 请问怎么换成davinci模型？之前游览器模式感觉也不是很稳定，我本来以为是昨天国内chatgpt连拿几个热搜，访问量激增，让chatgpt炸了

浏览器模式还是比较稳的，除了速度比较慢和容易遇到at capacity之外没什么毛病。

**Comment by FenChenXingLong** [comment]
已经修复了，感谢作者大大的回复，提示：pnpm update如果node版本在18以下记得去修改global fetch

**Comment by yzfylyw** [comment]
> [chatgpt-api最新版本](https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.2.0)

请问应该用什么指令更新版本呢？

**Comment by FenChenXingLong** [comment]
> > [chatgpt-api最新版本](https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.2.0)
> 
> 请问应该用什么指令更新版本呢？

在yunzai根目录输入pnpm update

**Comment by yzfylyw** [comment]
> 

感谢

**Comment by ikashana** [comment]
> > > [chatgpt-api最新版本](https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.2.0)
> > 
> > 
> > 请问应该用什么指令更新版本呢？
> 
> 在yunzai根目录输入pnpm update

遇到了点小问题..更新过程疯狂报 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/diff: request to https://registry.npmjs.org/diff failed, reason: connect ETIMEDOUT 2606:4700::6810:1b23:443

之前好像并没有遇到过。请教一下处理方法。

**Comment by chenxinglon** [comment]
> 

试试：
npm config set proxy false
npm cache clean

**Comment by ikechan8370** [comment]
`pnpm install -w chatgpt@4.2.0` 这样可以只更新单个依赖到指定版本。你这是网络不太好可能，要么使用代理，要么试试用中国镜像：
`pnpm install --registry=https://registry.npmmirror.com`

**Comment by ikashana** [comment]
> 

最后显示倒是好像也完成了...我先测一下能不能正常用，不行我就试试你的办法哈哈哈，谢谢

**Comment by ikashana** [comment]
> `pnpm install -w chatgpt@4.2.0` 这样可以只更新单个依赖到指定版本。你这是网络不太好可能，要么使用代理，要么试试用中国镜像： `pnpm install --registry=https://registry.npmmirror.com`

........然后发现单个依赖更新也有这个报错，开了代理也有这个报错。中国镜像依旧有...(ㄒoㄒ)

**Comment by ikashana** [comment]
可以了。折腾了半天都报错，把能查到的方法都试了。结果重启了一下服务器就不报错了

**Comment by ikechan8370** [comment]
https://github.com/transitive-bullshit/chatgpt-api/issues/311#issuecomment-1421976950
https://github.com/acheong08/ChatGPT/issues/600#issuecomment-1421982770
似乎那个模型又恢复了，我试了一下安装回chatgpt 4.1.3版本确实又可以了。你们可以先装回4.1.3版本，因为4.2.0的版本既收费效果又欠缺。

**Comment by FenChenXingLong** [comment]
That model is currently overloaded with other requests.
现在的4.1.3是这个错误，等待官方修复吗？

**Comment by ikechan8370** [comment]
> That model is currently overloaded with other requests. 现在的4.1.3是这个错误，等待官方修复吗？

刚刚还可以，现在又overloaded了，等一会吧，估计是服务器负载太高了。

**Comment by Oishiimono** [comment]
>新京报贝壳财经报道，北京时间2月7日22:49，新京报贝壳财经记者登录ChatGPT官方网站发现，该网站首页出现了提示称其“已经满负荷了”。

ChatGPT在官网表示，许多人在“最近一小时内蜂拥而至我们的网站，但我们的（网络）资源是有限制的。”并用莎士比亚文风表示“啊，亲爱的用户，您不是唯一一个想与我们尊敬的AI聊天机器人打交道的……随着时间的推移，我们将及时提供您访问ChatGPT的机会，在此之前我们向您告别，祝您好运。”

**Comment by Oishiimono** [comment]
> > That model is currently overloaded with other requests. 现在的4.1.3是这个错误，等待官方修复吗？
> 
> 刚刚还可以，现在又overloaded了，等一会吧，估计是服务器负载太高了。

请问恢复到4.1.3需要怎么操作呀？（小白探头

**Comment by FenChenXingLong** [comment]
> > > That model is currently overloaded with other requests. 现在的4.1.3是这个错误，等待官方修复吗？
> > 
> > 
> > 刚刚还可以，现在又overloaded了，等一会吧，估计是服务器负载太高了。
> 
> 请问恢复到4.1.3需要怎么操作呀？（小白探头

pnpm install -w chatgpt@4.1.3

**Comment by Oishiimono** [comment]
> > > > That model is currently overloaded with other requests. 现在的4.1.3是这个错误，等待官方修复吗？
> > > 
> > > 
> > > 刚刚还可以，现在又overloaded了，等一会吧，估计是服务器负载太高了。
> > 
> > 
> > 请问恢复到4.1.3需要怎么操作呀？（小白探头
> 
> pnpm install -w chatgpt@4.1.3

谢谢！安装好啦，还是提示“Error 503...That model is currently overloaded with other requests. ” 感觉要等后续更新了

**Comment by FenChenXingLong** [comment]
> > > > > That model is currently overloaded with other requests. 现在的4.1.3是这个错误，等待官方修复吗？
> > > > 
> > > > 
> > > > 刚刚还可以，现在又overloaded了，等一会吧，估计是服务器负载太高了。
> > > 
> > > 
> > > 请问恢复到4.1.3需要怎么操作呀？（小白探头
> > 
> > 
> > pnpm install -w chatgpt@4.1.3
> 
> 谢谢！安装好啦，还是提示“Error 503...That model is currently overloaded with other requests. ” 感觉要等后续更新了

嗯，4.1.3的模型负载太高了，一直不能成功返回，我暂时先用4.2的等后续更新

**Comment by Oishiimono** [comment]
![1373163b8c90df694abab632ace000e](https://user-images.githubusercontent.com/34758515/217541132-50e6bb89-95f6-4664-bce1-f96f2cc2ae00.png)
![3d9878989241ce04b0799eec5b1eaae](https://user-images.githubusercontent.com/34758515/217541168-379b47d1-7f6a-4b6b-9d9a-b762e763720a.png)
看起来像是在停服扩容，为了推出付费版ChatGPT

**Comment by ikechan8370** [comment]
> ![1373163b8c90df694abab632ace000e](https://user-images.githubusercontent.com/34758515/217541132-50e6bb89-95f6-4664-bce1-f96f2cc2ae00.png) ![3d9878989241ce04b0799eec5b1eaae](https://user-images.githubusercontent.com/34758515/217541168-379b47d1-7f6a-4b6b-9d9a-b762e763720a.png) 看起来像是在停服扩容，为了推出付费版ChatGPT

暂时用text-davinci-003代替一下。等大佬们商讨更好的解决方案

**Comment by Oishiimono** [comment]
> 

大佬可以详细说说这个使用步骤么（text-davinci-003的切换过程）

**Comment by ikechan8370** [comment]
> > 
> 
> 大佬可以详细说说这个使用步骤么（text-davinci-003的切换过程）

chatgpt依赖更新到最新（4.2.0）就已经默认用了这个模型了。这个模型效果略差一点，而且还收费，所以只是次选。不过OpenAI新用户都有三个月的18刀 Credit，暂时还够用。此外我最新版本配置文件也提供了一个配置项可以手动填写模型名称。

**Comment by Oishiimono** [comment]
> 

谢谢大佬，已经升级回了4.2.0，把这个插件也更新了，index.js里的参数也调整好啦。目前还是反馈OpenAI连接不上，等后面看看什么时候恢复上线。

目前的反馈为：
与OpenAI通信异常，请稍后重试：Error: ChatGPT error 429: {
  "error": {
    "message": "The server had an error while processing your request. Sorry about that!",
    "type": "server_error",
    "param": null,
    "code": null
  }
}

**Comment by ikechan8370** [comment]
> > 
> 
> 谢谢大佬，已经升级回了4.2.0，把这个插件也更新了，index.js里的参数也调整好啦。目前还是反馈OpenAI连接不上，等后面看看什么时候恢复上线。
> 
> 目前的反馈为： 与OpenAI通信异常，请稍后重试：Error: ChatGPT error 429: { "error": { "message": "The server had an error while processing your request. Sorry about that!", "type": "server_error", "param": null, "code": null } }

这个我也遇到了，是偶发的，再试一次应该就行了。虽然是429但看起来还是服务器问题，他们服务器估计还是有点炸

**Comment by Oishiimono** [comment]
> > > 
> > 
> > 
> > 谢谢大佬，已经升级回了4.2.0，把这个插件也更新了，index.js里的参数也调整好啦。目前还是反馈OpenAI连接不上，等后面看看什么时候恢复上线。
> > 目前的反馈为： 与OpenAI通信异常，请稍后重试：Error: ChatGPT error 429: { "error": { "message": "The server had an error while processing your request. Sorry about that!", "type": "server_error", "param": null, "code": null } }
> 
> 这个我也遇到了，是偶发的，再试一次应该就行了。虽然是429但看起来还是服务器问题，他们服务器估计还是有点炸

恢复上线，完美！赞美大佬！

**Comment by Oishiimono** [comment]
> 

三个月后是否自行购买ChatGPT Plus就可以自动续一下我账户里的API使用权呢？还是说API是单独一项收费服务？

**Comment by Oishiimono** [comment]
> > 
> 
> 三个月后是否自行购买ChatGPT Plus就可以自动续一下我账户里的API使用权呢？还是说API是单独一项收费服务？

刚查到了，原来是按调用次数，单独收费的 https://openai.com/api/pricing/

**Comment by ikechan8370** [comment]
暂时告一段落，用GPT-3平替。上游大佬已经支持bing版本，据说速度稳定性高很多，待我拿到bing资格再测试添加该方式。
