### ISSUE TITLE
与OpenAI通信异常，请稍后重试：ReferenceError: AbortController is not defined

### ISSUE THREAD

**Issue by xueqiuchuyun** [ikechan8370/chatgpt-plugin#123]
![图片](https://user-images.githubusercontent.com/96030324/217471102-47a70cdc-32f6-42db-9731-c470977635c5.png)
![图片](https://user-images.githubusercontent.com/96030324/217471308-8f971ff9-cb94-413a-9d91-eed198efb327.png)

**Comment by ikechan8370** [comment]
检查nodejs版本，升级试试。

**Comment by MrWamG** [comment]
AbortContoller was only added to the Node.js API in v15:[nodejs.org/api/globals.html#globals_class_abortcontroller](https://nodejs.org/api/globals.html#globals_class_abortcontroller)
