### ISSUE TITLE
可以取消回复前的那一句想一想以及延迟撤回吗？

### ISSUE THREAD

**Issue by yzfylyw** [ikechan8370/chatgpt-plugin#124]
每次对话都会先发一句正在思考，过一会儿又撤回，稍微有些影响体验

**Comment by ikechan8370** [comment]
请问有什么好的建议吗？因为早期没有这个回复的话，回复时间比较长的情况下不知道机器人有没有收到响应。
做成一个可管理的配置开关？由主人决定是否需要这句回复。

**Comment by yzfylyw** [comment]
> 请问有什么好的建议吗？因为早期没有这个回复的话，回复时间比较长的情况下不知道机器人有没有收到响应。 做成一个可管理的配置开关？由主人决定是否需要这句回复。

增加配置开关不错。顺便消息监听那一块儿的return是否应该改成return false，因为v3 云崽里return默认为return true，会导致所有消息被监听抢指令。

**Comment by ikechan8370** [comment]
[最新的提交](https://github.com/ikechan8370/chatgpt-plugin/commit/233fc7417c096109ed11615587276916e9e81149) 在配置文件中提供了触发方式的修改，以及一些其他的关于模型本身的配置项，欢迎试用。
