### ISSUE TITLE
这个错误代码是什么原因造成的？

### ISSUE THREAD

**Issue by GoahMidi** [ikechan8370/chatgpt-plugin#125]
与OpenAI通信异常，请稍后重试：Error: ChatGPT error 503: {
  "error": {
    "message": "That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 500d9fff2057e4af93a280f67002c342 in your message.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}

**Comment by ikechan8370** [comment]
#122 参见这里的讨论
