### ISSUE TITLE
yunzai功能关闭

### ISSUE THREAD

**Issue by Jonekadsen** [ikechan8370/chatgpt-plugin#129]
怎么关yunzai的功能啊，只是想当个chatgpt机器人来用，老是回复原神的东西

**Comment by CC-3301** [comment]
与本插件无关，请去yunzai的gitee仓库提问

**Comment by ikechan8370** [comment]
试试[这个轻量版](https://github.com/Nwflower/yunzai-bot-lite)？我没试过
