### ISSUE TITLE
为什么安装依赖过后chatgpt版本不是4.0以上？

### ISSUE THREAD

**Issue by lyf1984** [ikechan8370/chatgpt-plugin#130]
怎么才能更新chatgpt的版本

**Comment by ikechan8370** [comment]
试试`pnpm install -w chatgpt@4.2.0` 安装制定的版本

**Comment by lyf1984** [comment]
> 试试`pnpm install -w chatgpt@4.2.0` 安装制定的版本

现在可以了，感谢！
