### ISSUE TITLE
载入插件错误 cannot find package ‘random’

### ISSUE THREAD

**Issue by No65536** [ikechan8370/chatgpt-plugin#131]
载入插件错误 cannot find package ‘random’
![(~@_P70KAHGW3F4$M4(06%K](https://user-images.githubusercontent.com/125142480/218267108-70206487-1f0b-4efb-a92d-02ff7141bc25.png)

**Comment by ikechan8370** [comment]
新增的浏览器模式需要这个依赖。如果继续使用API可以忽略，或者`pnpm add -w random`安装一下即可。
