### ISSUE TITLE
请问API2模式当中的ChatGPT AccessToken是在哪里配置呢

### ISSUE THREAD

**Issue by ferretgeek** [ikechan8370/chatgpt-plugin#135]
![QQ截图20230212214447](https://user-images.githubusercontent.com/22911884/218314749-18d98ef5-a675-4b62-8d9e-b4c3e1eba92d.png)

如图，在API_Key填入了token，但机器人仍然提示token无效
![image](https://user-images.githubusercontent.com/22911884/218314679-93a332ad-b545-4d2b-b4ea-95599072877d.png)

token在谷歌浏览器下正常获取

**Comment by 693093880** [comment]
切换到API2后发送 #chatgpt设置token

**Comment by ferretgeek** [comment]
> 

没有反应，机器人不恢复，CMD那边也没有报错

**Comment by ferretgeek** [comment]
> 

已解决问题，通过查看management.js知道了指令为：#chatgpt设置token
