### ISSUE TITLE
centos7安装插件遇到了问题

### ISSUE THREAD

**Issue by aazhaoyoukino** [ikechan8370/chatgpt-plugin#136]
按照大佬提供的步骤安装时，修改配置的步骤找不到对应文件，进入.pnpm找不到chatgpt，这个是需要自己下载还是什么？如果大佬愿意的话，能不能加我qq帮助我一下 2364783840 谢谢大佬！

**Comment by ikechan8370** [comment]
是clone下来的项目目录下面找配置文件。不用去.pnpm下面找。
就是Yunzai-bot/plugins/chatgpt-plugin下面找

**Comment by aazhaoyoukino** [comment]
![image](https://user-images.githubusercontent.com/125206670/218324416-397d353a-2767-4775-8f57-d789f75926de.png)就是这步修改 Yunzai根目录/node_modules/.pnpm/chatgpt@4.1.0/node_modules/chatgpt/build/index.js 在哪找，在Yunzai-bot/plugins/chatgpt-plugin位置里找哪个文件

**Comment by ikechan8370** [comment]
@SanQianQVQ 能否帮帮看下，这里我没也实际操作过。

**Comment by hanhan258** [comment]
> ![图像](https://user-images.githubusercontent.com/125206670/218324416-397d353a-2767-4775-8f57-d789f75926de.png)就是这一步修改Yunzai根目录/node_modules/.pnpm/chatgpt@4.1.0/node_modules/chatgpt/build/index.js 在哪找，在yunzai-bot/plugins/chatgpt-plugin位置里找哪个文件
可以看一下我的博客里面 修改配置 那里https://blog.hanhanz.top/?p=309

**Comment by SanQianQVQ** [comment]
@ikechan8370 
哇哦，看起来更新了好多内容 ><，唔，我可能需要一些时间来验证最新的插件是否/如何在 CentOS7 上使用

**Comment by SanQianQVQ** [comment]
> 按照大佬提供的步骤安装时，修改配置的步骤找不到对应文件，进入.pnpm找不到chatgpt，这个是需要自己下载还是什么？如果大佬愿意的话，能不能加我qq帮助我一下 2364783840 谢谢大佬！


通常来说，这与你使用的包管理器有关，请问你是否正在使用 pnpm 来管理依赖？
