### ISSUE TITLE
API2  Error: Failed to send message. HTTP 429

### ISSUE THREAD

**Issue by laChristmas** [ikechan8370/chatgpt-plugin#137]
在API2模式下对话1会报错Error: Failed to send message. HTTP 429 - {"status":false,"error":"You are rate-limited Rate-limited or API key is invalid"}

![图片](https://user-images.githubusercontent.com/94898374/218327757-e5a02c5c-a8f7-436d-8548-9b5fe807f92f.png)

在API模式下是正常的，API key用的是同一个。

CentOS7系统

**Comment by ikechan8370** [comment]
API2下要绑定token而不是Key。参照ReadMe获取SessionToken绑定。ey开头的一长串

**Comment by laChristmas** [comment]
感谢！绑定Token后可以使用了！
