### ISSUE TITLE
Error: ChatGPTAPI error 404

### ISSUE THREAD

**Issue by kiookp** [ikechan8370/chatgpt-plugin#138]
## 问题描述

[YzBot][02:10:22.973][ERRO] Error: ChatGPTAPI error 404
    at ChatGPTPuppeteer.sendMessage (file:///root/Yunzai-Bot/plugins/chatgpt-plugin/utils/browser.js:519:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async chatgpt.chatgptBrowserBased (file:///root/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:436:12)
    at async chatgpt.sendMessage (file:///root/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:332:14)
    at async chatgpt (file:///root/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:255:25)
    at async PluginsLoader.deal (file:///root/Yunzai-Bot/lib/plugins/loader.js:251:52) {
  statusCode: 404,
  statusText: ''
}

## 环境
debian：11
Node :[v18.12.0]

在qq 发送消息后，bash可以调用打开浏览器。然后会出现上面的报错。

**Comment by ikechan8370** [comment]
404可能是你之前用的其他模式切换到浏览器模式，二者对话不继承。#结束对话 试试。

**Comment by kiookp** [comment]
非常感谢🙏 ，#结束对话后正常了。

**Comment by kiookp** [comment]
但是我在更换了另一个有plus的账号后，又出现了这个问题。

[![e1c449374b98e0d4280669520c80aa74.th.jpg](https://img.gejiba.com/images/e1c449374b98e0d4280669520c80aa74.th.jpg)](https://img.gejiba.com/image/EsW0hZ)

**Comment by ikechan8370** [comment]
> 但是我在更换了另一个有plus的账号后，又出现了这个问题。
> 
> 
> 
> [![e1c449374b98e0d4280669520c80aa74.th.jpg](https://img.gejiba.com/images/e1c449374b98e0d4280669520c80aa74.th.jpg)](https://img.gejiba.com/image/EsW0hZ)
> 
> 
> 
> 

有日志吗？浏览器模式确实没有适配过plus模型，不知道有没有什么不一样

**Comment by kiookp** [comment]
[YzBot][20:03:20.890][MARK] Yunzai-Bot ???? ??v3.0.0
[YzBot][20:03:20.890][MARK] https://github.com/Le-niao/Yunzai-Bot
[YzBot][20:03:20.896][INFO] ?????..
[YzBot][20:03:22.739][INFO] ??????[2?]
[YzBot][20:03:22.739][INFO] ??????[15?]
[YzBot][20:03:22.740][INFO] -----------
[YzBot][20:03:33.690][INFO] recv from: [Private: 2871(friend)] ??
[YzBot][20:03:33.708][MARK] [chatgpt][chatgpt][??][strange(2871)] ??
[YzBot][20:03:33.710][INFO] chatgpt prompt: ??
[YzBot][20:03:33.711][INFO] chatgpt prompt: ??
chatgpt re-authenticating lxxx@gmail.com
[YzBot][20:03:33.713][INFO] init chatgpt browser
[YzBot][20:03:33.863][MARK] chatgpt puppeteer ???...
[YzBot][20:03:35.587][MARK] chatgpt puppeteer ????
[YzBot][20:03:41.463][INFO] ????
[YzBot][20:03:41.747][ERRO] Error: ChatGPTAPI error 400
    at ChatGPTPuppeteer.sendMessage (file:///root/Yunzai-Bot/plugins/chatgpt-plugin/utils/browser.js:519:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async chatgpt.chatgptBrowserBased (file:///root/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:436:12)
    at async chatgpt.sendMessage (file:///root/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:332:14)
    at async chatgpt (file:///root/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:255:25)
    at async PluginsLoader.deal (file:///root/Yunzai-Bot/lib/plugins/loader.js:251:52) {
  statusCode: 400,
  statusText: ''
}
[YzBot][20:03:41.974][INFO] succeed to send: [Private(2871)] [??]?OpenAI???????????Error: ChatGPTAPI error 400
[YzBot][20:03:41.976][MARK] [chatgpt][chatgpt] ?? ???? 8267ms


可以打开Chromlum 浏览器，登录完成后在输入框那个页面就弹出了这个400 异常
正常账号也是这个情况
具体操作步骤：
系统：Debian 11
Node 版本：18.14.0
Redis: 6.2.4
机器人用的这个库 ：https://gitee.com/Le-niao/Yunzai-Bot.git
使用 pnpm 安装 Puppeteer 出现异常，就换成了cnpm安装。
chrome依赖库：
sudo apt-get install pango1.0 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxi6 libxtst6 libcups2 libxss1 libxrandr2 gconf2 libasound2 atk3.0 libgtk-3-0 libdrm2 libgbm1 libxshmfence1 libnss3 -y

安装完成全部依赖库后，测试机器人正常。
之后按照这个库给的教程安装了chatgpt插件的依赖：
pnpm install -w undici chatgpt showdown mathjax-node delay uuid remark strip-markdown random puppeteer-extra-plugin-recaptcha puppeteer-extra puppeteer-extra-plugin-stealth @waylaidwanderer/chatgpt-api keyv-file

安装这个依赖有几个依赖没有安装成功：
异常提示：
WARN  deprecated left-pad@1.3.0: use String.prototype.padStart()
 WARN  deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
 WARN  deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
 WARN  deprecated har-validator@5.1.5: this library is no longer supported
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 
 
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/101065744/218455007-b3f6c30b-5152-4960-9c5a-c11ba5bb383f.png">


之后拉取库后测试api 模式是正常运行。浏览器模式出现了400异常
以安装这个步骤安装桌面，并在桌面上操作的 node app 
以ubuntu为例给出一个可行的方案：

安装xvfb和fluxbox sudo apt-get install x11vnc xvfb fluxbox
启动桌面环境。建议用tmux或screen等使其能够后台运行。注意本命令使用默认5900端口和无密码，注意通过防火墙等保护。 x11vnc -create -env FD_PROG=/usr/bin/fluxbox -env X11VNC_FINDDISPLAY_ALWAYS_FAILS=1   -env X11VNC_CREATE_GEOM=${1:-1024x768x16}   -nopw -forever
使用vnc客户端连接至云桌面，右键Applications > Shells > Bash打开终端，然后进入Yunzai目录下运行node app即可。

**Comment by ikechan8370** [comment]
已修复
