### ISSUE TITLE
Error: Failed to send message. HTTP 429

### ISSUE THREAD

**Issue by KasumiYuku** [ikechan8370/chatgpt-plugin#139]
切换API2提示这个，我在配置文件已经填写了正确的key
Error: Failed to send message. HTTP 429 - {"status":false,"error":"You are rate-limited Rate-limited or API key is invalid"}

**Comment by ikechan8370** [comment]
这个错就是SessionToken不正确。检查是否按照README操作的。API2模式下不需要OpenAI API Key。

**Comment by Afkeru** [comment]
> 这个错就是SessionToken不正确。检查是否按照README操作的。API2模式下不需要OpenAI API Key。
步骤是按README中操作的，但在配置里好像没有看见Session Token的配置项

**Comment by KasumiYuku** [comment]
> 这个错就是SessionToken不正确。检查是否按照README操作的。API2模式下不需要OpenAI API Key。

谢谢，成功了
