### ISSUE TITLE
当我链接chatgpt时出现heartbeat timeout 没有报错

### ISSUE THREAD

**Issue by marshall-li** [ikechan8370/chatgpt-plugin#146]
**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

结合yunzai-bot使用将chatgpt引入到qq群中，之前是成功的，在我问了一些问题后，突然出现无应答的情况，等待一段时间后，powershell出现heartbeat timeout的error。且日志没有输出报错信息。

## 预期行为

无应答时希望有日志输出具体报错信息，以便修改

## 实际行为

实际需等待很久且无报错信息，无法得知哪里出现问题。

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息
timeout出现时：
![image](https://user-images.githubusercontent.com/81742076/218629440-2c7ac9b5-fbe6-49f9-bc11-10bb3ca326ae.png)
之前的正常情况下：
![image](https://user-images.githubusercontent.com/81742076/218630149-a74e1e68-3750-4450-811b-6d19a361c7bf.png)

**Comment by ikechan8370** [comment]
是Yunzai的问题，QQ登录掉了。和本插件无关

**Comment by marshall-li** [comment]
> 是Yunzai的问题，QQ登录掉了。和本插件无关

但是我QQ登录没有掉啊 我认为应该是连接chatgpt掉了 因为没有chatgpt prompt的信息

**Comment by marshall-li** [comment]
> 是Yunzai的问题，QQ登录掉了。和本插件无关

qq没掉哦 我又试了一下 QQ收到和发送的消息都能正常显示在控制台。就是缺少了chatgpt prompt 另外我新申请了一个apikey 将配置文件中的apikey换成了新申请的key。可以看到那个key是没有被使用过的。所以应该是连接ChatGPT出现了问题。这个怎么处理啊 大佬
![image](https://user-images.githubusercontent.com/81742076/218636120-9680deb7-462a-41c7-b2cf-fe16f9d7abd1.png)
