### ISSUE TITLE
切换api2模式报错503

### ISSUE THREAD

**Issue by zfztty** [ikechan8370/chatgpt-plugin#148]
与OpenAI通信异常，请稍后重试：Error: Failed to send message. HTTP 503 - <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
<script src="/cdn-cgi/apps/head/dYMkwc06fJ_hgAqAMinzib-CLyo.js"></script></head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p >
<hr>
<address>Apache/2.4.52 (Ubuntu) Server at chatgpt.pawan.krd Port 80</address>
<script>(function(){var js = "window['__CF$cv$params']={r:'7995d7ca7b242d1d',m:'tx5rEA0GIWz.wquotRuxzFlqx_xhtGWOzInsD.mcPag-1676378118-0-AfWFdfrjDi0Ryvfa9R547Zj2S7oI7Q7BJ9aYP999aho6whn1QcYDQdcwWStJc+OfRUUFhDoHy05Ud6N48GETbTViT9TN/tpfvNf9CIC0KXw4yWJsK+abRNq92ODcLT2oWg==',s:[0x70dc137838,0x46cd51d200],u:'/cdn-cgi/challenge-platform/h/b'};var _cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/h/b/scripts/cb/invisible.js?cb=7995d7ca7b242d1d',document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.nonce = '';_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();</script></body></html>
切换api2模式问问题的报错，已经绑定了accesstoken

**Comment by ikechan8370** [comment]
更新后使用API3把 API2暂时挂了，不知道还会不会修
