### ISSUE TITLE
更新后使用官方API访问出现Error: ChatGPT error: Unauthorized - Invalid access token

### ISSUE THREAD

**Issue by Ansellyu** [ikechan8370/chatgpt-plugin#150]
2月15日0点20分左右运行无问题；
2月15日9点30分左右更新，后访问官方API出现Unauthorized - Invalid access token；

- 尝试更新API_KEY，依旧“Error: ChatGPT error: Unauthorized - Invalid access token”，无法解决;
- 尝试切换API2，并更新access token，出现503错误，无法解决；
- 尝试切换API3，目前可用。

**Comment by ikechan8370** [comment]
API3最优，可用就行。
API昨晚代码出错了，今天更新应该就恢复了
API2挂了，暂时无法恢复
