### ISSUE TITLE
qq版本过低

### ISSUE THREAD

**Issue by Sunlazys** [ikechan8370/chatgpt-plugin#152]
2.14运行良好，2.15号提示各个设备的qq版本过低无法更新，不知该如何解决

**Comment by ikechan8370** [comment]
和本插件无关。参照Yunzai仓库的问题解决。https://gitee.com/Le-niao/Yunzai-Bot/commit/0f89314277e897e079c0642c8d3147032d38aaf7#git-issue-comments
