### ISSUE TITLE
如何对所有人的回复都使用图片模式

### ISSUE THREAD

**Issue by KasumiYuku** [ikechan8370/chatgpt-plugin#159]
配置里的defaultUsePicture属性改成true了，但回答好像还是文字
![$ FS8T2{E}VSRMB7YSMX4 2](https://user-images.githubusercontent.com/107661829/219582161-dcb12f40-3d53-4c28-b4be-d5bdcdbaff92.png)
![HWHJ( KJ4WSZU7F9)$3%6P3](https://user-images.githubusercontent.com/107661829/219582170-eec8ac0a-6d8d-4e68-9957-199ebeee8aa0.png)

**Comment by KasumiYuku** [comment]
抱歉，刚刚看了下，在这个issue里好像已经解决了 #27

**Comment by ikechan8370** [comment]
是一个bug，新版本修复了
