### ISSUE TITLE
反馈一些bug

### ISSUE THREAD

**Issue by yyk725** [ikechan8370/chatgpt-plugin#164]
![qq报错](https://user-images.githubusercontent.com/72236930/219703517-d56e6423-782d-43be-82e4-4972a4daec8c.png)
![日志报错](https://user-images.githubusercontent.com/72236930/219704483-1d134c2f-30f9-4788-95c0-4b6a03c4cda9.png)

如图，浏览器模式无法正常使用

**Comment by ikechan8370** [comment]
看起来，你需要在配置文件的chromePath处显式声明浏览器的路径。比如你可以安装google-chrome，然后通过`which google-chrome`找到可执行文件地址。
或者建议使用API3.浏览器目前还是API3的下位替代

**Comment by yyk725** [comment]
我用了win的edge("C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe")，现在能执行命令但是没法弹出登录窗口
但是我记得很久以前这个插件都还能直接调用puppeteer或者改用edge登录（

*其实我自己用的就是API3，只是碰到这个问题想问一下有没有办法解决罢了:（ 辛苦作者解答了

**Comment by ikechan8370** [comment]
我还真没试过edge 只试过chrome和brave这俩

**Comment by yyk725** [comment]
昨天换回API3之后就无法收到回复了，今天重装插件后问题依旧

**Comment by ikechan8370** [comment]
> 昨天换回API3之后就无法收到回复了，今天重装插件后问题依旧

#chatgpt开启确认 #清空队列 这些都有助于调试

**Comment by Dream-yyk** [comment]
有时候会莫名其妙提示这个![image](https://user-images.githubusercontent.com/72236930/219855144-c8b8c81e-e26b-4185-bdf6-6bbcea799249.png)

之前换到llq再换回API3可以解决，现在不可以了

**Comment by yyk725** [comment]
可以加个设置让一个群里的人共用一个对话吗qwq，想一起聊的人都得发一句加入对话感觉不太方便

**Comment by yyk725** [comment]
另外关闭对话无法正常工作，只有到官网选择clear conversation才能关闭

**Comment by dhzq** [comment]
必应，如果必应回复太长会出现"启动失败"，而且QQ里面不报错也不回复
![Uploading IMG_20230228_105113.jpg…]()

**Comment by dhzq** [comment]
必应回复太长会报错“启动失败”，而且QQ没什么提示，不报错也不回复
![IMG_20230228_105113](https://user-images.githubusercontent.com/120349387/221741967-f0ef383e-3415-4939-aa3b-f27043a3567a.jpg)
