### ISSUE TITLE
请问为什么填写必应token时出现这个

### ISSUE THREAD

**Issue by ghost** [ikechan8370/chatgpt-plugin#166]
## 问题描述
经检测，Bing Token无效。来自Bing的错误提示：Sorry, you are not allowed to access this service.
token直接在bing.com用js代码拿的

## 实际行为

token先是填写成功然后出现错误

## 可能的解决方案
试了用代理没有用
试了手动拿token没有用

## 附加
![uTools_1676711284540](https://user-images.githubusercontent.com/122252361/219851979-ad522084-c049-451d-8c07-ef55db423dbc.png)

**Comment by ikechan8370** [comment]
这个问题暂时不明确，也有人遇到过。最近bing服务一直不稳定所以不好确定问题。可以不用js手动去查_U cookie看看

**Comment by HalcyonAlcedo** [comment]
先确认在网页端能否正常对话，如果可以，在对话页面尝试获取cookie _U，如果网页端也没法对话的话，通常是bing本身出了问题或者你的账号出了问题

**Comment by ghost** [comment]
网页试了没问题但是获取到cookie也是不能用

**Comment by ghost** [comment]
网页试了没问题但是获取到cookie也是不能用

**Comment by Arama-Vanarana** [comment]
网页试了没问题但是获取到cookie也是不能用

**Comment by ghost** [comment]
???我咋发了这么多个wc

**Comment by HalcyonAlcedo** [comment]
有可能是获取的cookie还是有问题？试试去DevTools里的应用程序中找cookie，用这里面的_U试试

**Comment by ghost** [comment]
好()

**Comment by ghost** [comment]
我去可以了谢谢
