### ISSUE TITLE
需要安装的包太多，建议写入 package.json

### ISSUE THREAD

**Issue by TimeRainStarSky** [ikechan8370/chatgpt-plugin#173]
**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

需要安装的包太多

## 预期行为

直接 pnpm i 安装

## 实际行为

pnpm i 一大堆，并且安装到 Workspace Root，更新后容易掉依赖

## 可能的解决方案

写入 package.json 后直接 pnpm i 安装

## 附加信息

参考 https://github.com/TimeRainStarSky/TRSS-Plugin/blob/main/package.json

**Comment by ikechan8370** [comment]
谢谢佬提醒，不知道还有这种操作。
