### ISSUE TITLE
代码转义失败，文字不显示

### ISSUE THREAD

**Issue by 17-sdl** [ikechan8370/chatgpt-plugin#174]
**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述
静态缓存http://content.alcedogroup.com/SN9gi
问了个问题，渲染失败了，不知道为啥，作者叫我过来提issue，上面是静态缓存

## 预期行为

请描述您期望系统在出现问题时应该做什么。

## 实际行为

请描述您实际看到的行为。

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。

**Comment by HalcyonAlcedo** [comment]
最新版本已经修复了这个问题，如果后续再出现这种情况，请继续附上静态缓存连接，我将尽量排除问题所在
