### ISSUE TITLE
如何能够直接使用@xxx +消息 即可判断

### ISSUE THREAD

**Issue by smallandbigrice** [ikechan8370/chatgpt-plugin#18]
我尝试着去做，但是发现qq的@效果，读取出来是这样
![E218))GD~}9A8B04I2` FQ4](https://user-images.githubusercontent.com/120096448/206420383-6a6a5170-30d0-4605-872f-10fe710267b0.png)

![T`)CQCUCN0I@G~C2XBZ`~NA](https://user-images.githubusercontent.com/120096448/206420199-70e71d7e-6220-4e04-9b48-dd4c641204a2.png)

**Comment by ikechan8370** [comment]
更新了一下，你可以尝试使用[index_no#.js](https://github.com/ikechan8370/chatgpt-plugin/blob/main/index_no%23.js)。

**Comment by smallandbigrice** [comment]
仍旧不行，
![image](https://user-images.githubusercontent.com/120096448/206445823-69040519-d238-4d78-8d08-eeb8546c2540.png)
这个正则表达式似乎起不到作用
![image](https://user-images.githubusercontent.com/120096448/206445976-656f0a74-ef09-48da-8c93-54f6d7e43df3.png)

**Comment by ikechan8370** [comment]
其他配置你有改过吗？我这里是可以的，你看ReadMe新增加的几个示例图片

**Comment by smallandbigrice** [comment]
不知道哪有问题，我测试了一下，直接拿你的index_no.js代码，再次尝试后，仍旧不能识别

**Comment by smallandbigrice** [comment]
在之后我重启了一下电脑，成功了。
