### ISSUE TITLE
用API3时报错

### ISSUE THREAD

**Issue by TsukinaKasumi** [ikechan8370/chatgpt-plugin#182]
**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

请在此处描述您遇到的问题，包括出现问题的环境、您试图实现的功能以及错误信息等。请尽可能详细，以便其他人可以在自己的环境中复制问题。
切换到API3用的时候没法用
## 预期行为

请描述您期望系统在出现问题时应该做什么。

## 实际行为

请描述您实际看到的行为。

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。
![QQ图片20230222103317](https://user-images.githubusercontent.com/125511327/220506288-65ebcac9-d237-4eef-b346-dc7760f976e5.png)

**Comment by TsukinaKasumi** [comment]
设置了token的

**Comment by ikechan8370** [comment]
token格式错误

**Comment by TsukinaKasumi** [comment]
> token格式错误

![QQ图片20230222160932](https://user-images.githubusercontent.com/125511327/220560514-3a3cebbd-94ef-4a27-a7e4-86533d0ec8c7.png)
我这里显示token设置成功但还是没法用
![QQ图片20230222161106](https://user-images.githubusercontent.com/125511327/220560689-b10d2b4d-ef21-43ab-b642-9cadfc51212b.png)
是我文件配置的问题吗？

**Comment by ikechan8370** [comment]
你的token还带括号引号之类的呢 按照readme里面的要求配置。目前配置完没有检查是否是正确的token。
