### ISSUE TITLE
求助 更新后prefix设置失效

### ISSUE THREAD

**Issue by PoorGarry** [ikechan8370/chatgpt-plugin#189]
大佬请教下，windows环境，更新以后复制命名config.js里设置prefix模式无效，直接@才触发插件且运作正常，请问下可能会是什么原因
![QQ图片20230224011356](https://user-images.githubusercontent.com/106169676/220980618-7d640f09-ee70-45f1-b0dd-3641e094f172.png)

**Comment by Rosalie-Zhang** [comment]
遇到了同样的问题

**Comment by HalcyonAlcedo** [comment]
你只改了内容，并没有把注释取消掉，肯定是没生效的，现在支持锅巴面板进行配置了，推荐使用
