### ISSUE TITLE
使用index_no#.js时的TypeError问题

### ISSUE THREAD

**Issue by Blokura** [ikechan8370/chatgpt-plugin#19]
我在使用直接@机器人就会触发的index_no#.js时遇到了如下情况：
在正常未触发机器人的聊天过程中，发送单独一张图片时，会出现如下报错：
![image](https://user-images.githubusercontent.com/21168605/206625680-edc0710b-47c6-47d4-9289-b0da15da0b51.png)

**Comment by evilpss** [comment]
这个js文件里面的token也要填写哦

**Comment by ikechan8370** [comment]
应该是只有图片情况下e.msg为空。我看看

**Comment by RyanJiang184** [comment]
我也遇到了这个问题，没有发送图片。但是在用大量文字模拟Stable Diffusion模型。

**Comment by RyanJiang184** [comment]
0|Yunzai-Bot  | [YzBot][20:00:08.258][ERRO] [chatgpt][chatgpt]
0|Yunzai-Bot  | [YzBot][20:00:08.258][ERRO] TypeError: Cannot read properties of undefined (reading 'startsWith')
0|Yunzai-Bot  |     at chatgpt (file:///C:/Users/Administrator/Desktop/Yunzai/Yunzai-Bot/plugins/chatgpt/index.js:118:19)
0|Yunzai-Bot  |     at PluginsLoader.deal (file:///C:/Users/Administrator/Desktop/Yunzai/Yunzai-Bot/lib/plugins/loader.js:247:55)
0|Yunzai-Bot  |     at runMicrotasks (<anonymous>)
0|Yunzai-Bot  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
