### ISSUE TITLE
安装完成后无法使用，报错SyntaxError: Unexpected identifier 'https'

### ISSUE THREAD

**Issue by PrussianBlueCN** [ikechan8370/chatgpt-plugin#190]
**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

请在此处描述您遇到的问题，包括出现问题的环境、您试图实现的功能以及错误信息等。请尽可能详细，以便其他人可以在自己的环境中复制问题。
按照readme安装后重启云崽，前台相关指令无反应，后台日志报错如下：
[YzBot][03:56:56.038][ERRO] 载入插件错误：chat
0|Yunzai-B | [YzBot][03:56:56.039][ERRO] SyntaxError: Unexpected identifier 'https'
0|Yunzai-B |     at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
0|Yunzai-B |     at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:14)
0|Yunzai-B |     at async link (node:internal/modules/esm/module_job:68:21)
0|Yunzai-B | [YzBot][03:56:56.040][ERRO] 载入插件错误：help
0|Yunzai-B | [YzBot][03:56:56.040][ERRO] SyntaxError: Unexpected identifier 'https'
0|Yunzai-B |     at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
0|Yunzai-B |     at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:14)
0|Yunzai-B |     at async link (node:internal/modules/esm/module_job:68:21)
0|Yunzai-B | [YzBot][03:56:56.040][ERRO] 载入插件错误：management
0|Yunzai-B | [YzBot][03:56:56.040][ERRO] SyntaxError: Unexpected identifier 'https'
0|Yunzai-B |     at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
0|Yunzai-B |     at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:14)
0|Yunzai-B |     at async link (node:internal/modules/esm/module_job:68:21)

## 预期行为

请描述您期望系统在出现问题时应该做什么。
我期望他能直接告诉我掉了什么依赖→_→

## 实际行为

请描述您实际看到的行为。
实际看到的就是报错，上面已经说了，哦锅巴也报了类似的错误：
[YzBot][03:56:57.008][ERRO] [Guoba] 载入guoba.support.js失败：Unexpected identifier 'https'

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。
1. 按照readme安装本插件
2. 重启yunzai
3. 后台pnpm run log查看日志
4. 得到上述报错

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。
腾讯云 centos8 
node.js 19.2

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。
已尝试readme末尾部分的安装依赖指令，也已经尝试pnpm i，均未起作用

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。

**Comment by HalcyonAlcedo** [comment]
有可能是配置文件有问题，请检查一下Yunzai-Bot/plugins/chatgpt-plugin/config下面是否有index.js或config.js如果有的话麻烦发一下内容，如有敏感信息比如apikey注意打码

**Comment by PrussianBlueCN** [comment]
![ABF92919-1A64-47EE-B544-B8B166413966](https://user-images.githubusercontent.com/110645427/221099548-d2e7a5fc-ec7c-45f5-8fa3-fa4d11086ce5.jpeg)
难道是我擅作主张取消注释的原因吗，但是不取消注释会生效吗（

**Comment by HalcyonAlcedo** [comment]
你的配置文件中有一行不是配置的东西你给取消注释了
from https://github.com/acheong08/ChatGPT
这行内容就是注释内容，如果取消掉配置文件就错误了

**Comment by PrussianBlueCN** [comment]
谢谢提供帮助，注释掉这行和33行之后插件成功启动了，但是尝试使用时报错：

通信异常，错误信息如下 FetchError: request to
https://chatgpt.duti.tech/api/conversationfailed,reason:
connectECONNREFUSED127.0.0.1:7890

尝试给服务器防火墙添加规则开放7890端口，似乎没有起效：
![82F2A829-1DCE-4373-9F84-91E96967A14A](https://user-images.githubusercontent.com/110645427/221116687-1413acd8-e593-440f-9071-cda5db4cc7bb.jpeg)
希望佬能再帮忙看看，谢谢

**Comment by HalcyonAlcedo** [comment]
这个看似是你设置的代理有问题，你确认你的代理可以正常访问吗

**Comment by PrussianBlueCN** [comment]
啊……因为是香港服务器，习惯不需要代理了，这代理就没过脑子直接按着readme填上去的（捂脸）
小白还真不太清楚该怎么弄，不知道能不能烦请dalao指个教程的路什么的我去学一下……

**Comment by PrussianBlueCN** [comment]
> 啊……因为是香港服务器，习惯不需要代理了，这代理就没过脑子直接按着readme填上去的（捂脸）
> 小白还真不太清楚该怎么弄，不知道能不能烦请dalao指个教程的路什么的我去学一下……

哦我是不是可以用clash for Linux来实现

**Comment by ikechan8370** [comment]
香港的话就不要代理了

**Comment by PrussianBlueCN** [comment]
> 香港的话就不要代理了

多谢，把代理删掉后就可以正常使用了。多谢二位
