### ISSUE TITLE
在网页端清空对话历史后，之前曾经使用过本插件的用户再次使用会出现Error: {"detail":"Conversation not found"}

### ISSUE THREAD

**Issue by regaliaf** [ikechan8370/chatgpt-plugin#196]
之前在网页端不小心清空了对话历史。然后所有之前的用户在尝试对话的时候都会出现这个错误。必须每个人手动`#结束对话`才行。因为用户有父母亲戚等一些完全不理解程序原理的人，通知起来又很麻烦。我自己的处理办法是登入redis cli然后列出所有`ChatGPT: QQ_*` 相关的key，再手动跑删除。
能否在触发这个错误的时候自动清空redis数据库的相关键值？或者提供一个控制接口允许在出现错误的时候清空键值？

**Comment by ixuan789** [comment]
谢谢！我也遇到了这个问题，删除redis中CHATGPT:QQ*的所有键值对后解决了！

**Comment by ikechan8370** [comment]
> 谢谢！我也遇到了这个问题，删除redis中CHATGPT:QQ*的所有键值对后解决了！

可以直接使用#结束全部对话

**Comment by ixuan789** [comment]
> > 谢谢！我也遇到了这个问题，删除redis中CHATGPT:QQ*的所有键值对后解决了！
> 
> 可以直接使用#结束全部对话

这个我有尝试过，好像不会影响老版本残留的redis中内容
![(PU4J@5)A{UZAP2E)FR6DMA](https://user-images.githubusercontent.com/23429395/222877329-2379af56-f666-4d71-9f84-3a2455b7ba65.png)

**Comment by regaliaf** [comment]
最近的更新已经有了#全部结束对话，这ticket结了
