### ISSUE TITLE
使用API3模式报错“通信异常”

### ISSUE THREAD

**Issue by muyun618** [ikechan8370/chatgpt-plugin#198]
## 问题描述

win10本地部署的云崽，写了key，绑了token，API模式可以用，换成API3就一直用不了

## 预期行为

接上chatgpt正常聊天

## 实际行为

发送错误图片，如末尾的图一

## 复制过程

用git装好之后在config文件写上key保存，手机获取token用指令绑了，艾特说话就报错

## 环境

win10家庭中文版

## 可能的解决方案

更改API3配置项，还是报错

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。
![QQ图片20230226142538](https://user-images.githubusercontent.com/115034363/221395871-c7b483c0-95b7-431d-8b02-a6f9e4eb6c1c.jpg)
![2$R4 766QB`BZJFX3B1KKG](https://user-images.githubusercontent.com/115034363/221395877-310bb299-6dce-4729-b038-fbc9a3a6c7e3.png)

**Comment by ikechan8370** [comment]
这个错看起来是服务端的错，如果多次出现重试也不行，只能#结束对话然后重新开一个对话了。
