### ISSUE TITLE
插件无法识别换行符

### ISSUE THREAD

**Issue by lateautumn233** [ikechan8370/chatgpt-plugin#2]
https://github.com/ikechan8370/chatgpt-plugin/blob/09004accc1daad8a0ddecb4818a33e928fdb1e9b/index.js#L20

百度了一下应改为 ^#chatgpt([\s\S]*)

**Comment by ayakasuki** [comment]
感谢，换成你这个正则，识别率提高了，用默认那个总是会调用别的插件

**Comment by ikechan8370** [comment]
感谢提出的问题，是否方便提个pr？或者等我今天有空时改一下。
