### ISSUE TITLE
这是api改的不对吗？

### ISSUE THREAD

**Issue by 1592363624** [ikechan8370/chatgpt-plugin#20]
![Shell截图_20221209144222](https://user-images.githubusercontent.com/50036597/206641929-91573e42-0a8e-4fca-85cd-0d6fdc86747e.png)

**Comment by 1592363624** [comment]
是这个界面的api吧
![Shell截图_20221209144829](https://user-images.githubusercontent.com/50036597/206642259-ad98590a-8805-4701-9e36-8c34c005d19d.png)

**Comment by ikechan8370** [comment]
> 是这个界面的api吧 ![Shell截图_20221209144829](https://user-images.githubusercontent.com/50036597/206642259-ad98590a-8805-4701-9e36-8c34c005d19d.png)

不是。是Readme里那个。
