### ISSUE TITLE
能否关闭私聊触发，或者私聊触发增加条件

### ISSUE THREAD

**Issue by fsqhn** [ikechan8370/chatgpt-plugin#200]
现在私聊随便发点不带#的指令都会触发，但很多时候并不需要触发。希望能更加可控。
设置那里找了半天都没找到，toggleMode里我不清楚是配置了没生效还是配置错了，感觉不管怎么改都是会私聊触发。

**Comment by HalcyonAlcedo** [comment]
配置中有一个toggleMode项，改成prefix即可

**Comment by fsqhn** [comment]
好的，自己手动改配置不知道为什么没生效，还好锅巴可以改就生效了。谢谢。
