### ISSUE TITLE
centos下报：载入插件错误：chatgpt-plugin

### ISSUE THREAD

**Issue by veryIII** [ikechan8370/chatgpt-plugin#201]
**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

centos下报：载入插件错误：chatgpt-plugin

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。
![错误截图](https://user-images.githubusercontent.com/29143678/221534736-18262efc-893c-4e17-ace2-d913b330ada8.jpg)

**Comment by HalcyonAlcedo** [comment]
可能是node版本过低，你用的什么版本

**Comment by veryIII** [comment]
> 

用的是v18.14.2

**Comment by HalcyonAlcedo** [comment]
版本应该是可以的，这个报错没看出任何有用的信息

**Comment by ikechan8370** [comment]
可能是你在config目录下的配置文件修改出现了语法错误，检查是不是有引号没加之类的

**Comment by veryIII** [comment]
> 

发现了，是 以下为API3方式的配置下面的from链接没有加引号''和冒号:，感谢各位
