### ISSUE TITLE
API3的报错

### ISSUE THREAD

**Issue by dingte101** [ikechan8370/chatgpt-plugin#202]
![e6a04e4e83563ab15d0963216cf5d980](https://user-images.githubusercontent.com/107415353/221555344-f382d886-b6f6-4513-bba8-d2e9b31388b7.jpg)

**Comment by HalcyonAlcedo** [comment]
这是反代访问超时，建议更换反向代理地址，换成你服务器访问更好的地址

**Comment by chuanicefire** [comment]
> 这是反代访问超时，建议更换反向代理地址，换成你服务器访问更好的地址

请问反代地址怎么设置呢，而且不会找反代地址

**Comment by dingte101** [comment]
反代理地址我是在锅巴你设置的，可以改成：https://gpt.pawan.krd/backend-api/conversation
