### ISSUE TITLE
Fetcherror, reason: connect ECONNREFUSE 127.0.0.1.88

### ISSUE THREAD

**Issue by ZARALEON** [ikechan8370/chatgpt-plugin#205]
## 问题描述

![~490%3P5KD3Y 5 4KWMGQ{8](https://user-images.githubusercontent.com/72860784/221744478-89db8737-69a8-448b-b06a-ab666d3d05d2.jpg)

Ubuntu系统，相关端口已经开放，切换至API3模式时提示通信异常，请问为什么代理器会拒绝连接？

**Comment by HalcyonAlcedo** [comment]
设置了本地代理吗？
