### ISSUE TITLE
与Bing通讯时出错

### ISSUE THREAD

**Issue by chuanicefire** [ikechan8370/chatgpt-plugin#206]
[YzBot][20:28:53.172][ERRO] Throttled: Request is throttled.
Throttled: Request is throttled.

出现这个报错，但我可以正常使用bing

**Comment by zhikuangzhui4963** [comment]
有时会出现这个错误，而且用多了必应页面上会提示：很抱歉，你已达到可在24小时内发送到必应的邮件限制。请稍后回来查看

**Comment by c029384756** [comment]
我也出现了这个错误
<img width="730" alt="image" src="https://user-images.githubusercontent.com/13565332/222950854-f034e11c-52fd-43fe-ae0e-4f90714758fb.png">

**Comment by Err0rCM** [comment]
时间过于久远
