### ISSUE TITLE
API3 经常出现 502 BadGateway, 504: Gateway time-out，求帮助

### ISSUE THREAD

**Issue by Yuina-BingGan** [ikechan8370/chatgpt-plugin#207]
## 问题描述

API3 经常出现 502 BadGateway, 504: Gateway time-out，请问是我服务器这边的代理问题还是chatgpt那边的问题？

## 附加信息

![_TARO}U4G9(V%INJ0 M2M C](https://user-images.githubusercontent.com/55342875/221855206-19e88fdb-5622-4425-bd6c-f39a2151829e.png)

![WJ508A{UMO~W%39072Y(M@5](https://user-images.githubusercontent.com/55342875/221855216-f11236e6-5aad-4760-9212-640f2538ec59.png)

![IMG_6702(20230228-202602)(2)](https://user-images.githubusercontent.com/55342875/221855228-abd95175-f611-4d15-ac87-41da6b859d92.JPG)

**Comment by ikechan8370** [comment]
gpt.pawan.krd这个反代确实容易504，建议用默认的或者自己反代。或者加群用群里的

**Comment by Yuina-BingGan** [comment]
> gpt.pawan.krd这个反代确实容易504，建议用默认的或者自己反代的。或者加入群用群里的

哦哦，非常感谢

**Comment by Yuina-BingGan** [comment]
> gpt.pawan.krd这个反代确实容易504，建议用默认的或者自己反代的。或者加入群用群里的

有群号嘛？找了半天没找到哇

**Comment by ikechan8370** [comment]
> > gpt.pawan.krd这个反代确实容易504，建议用默认的或者自己反代的。或者加入群用群里的
> 
> 
> 
> 有群号嘛？找了半天没找到哇

559567232
