### ISSUE TITLE
某些特殊情况下redis中某些对话的CHATGPT:CONVERSATION_LAST_MESSAGE_ID值不正常，导致此对话报错（其他对话正常）

### ISSUE THREAD

**Issue by sst-huiyi** [ikechan8370/chatgpt-plugin#208]
**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

请在此处描述您遇到的问题，包括出现问题的环境、您试图实现的功能以及错误信息等。请尽可能详细，以便其他人可以在自己的环境中复制问题。

机器人回答问题的时候只答了一部分（可能是网络原因，在chatgpt的网站上看是完整的回答），导致redis中参数CHATGPT:CONVERSATION_LAST_MESSAGE_ID 值不是最新的。
之后新的提问都会报错（本对话失效，其他人的对话正常）
通信异常错误信息如下Error:detail”:"Something went wrong,please try reloadingthe conversation.”

![QQ图片20230228201437](https://user-images.githubusercontent.com/58673341/221851708-0bc824fe-cc7c-4937-a61b-ec40f96d3af0.jpg)

发生错误时qq中的部分回答：
![QQ图片20230228203359](https://user-images.githubusercontent.com/58673341/221855453-506b65bc-c501-4d67-949f-1cf06f53439f.png)

chatgpt官网的完整回答：
下午的时候是能查到的，现在官网上的那句回答消失了（整个消失）。

## 预期行为

请描述您期望系统在出现问题时应该做什么。

希望可以自动更新CHATGPT:CONVERSATION_LAST_MESSAGE_ID的值，我目前的解决方案是从官网那里找到的最新值把redis数据库的值改掉，恢复正常。

## 实际行为

请描述您实际看到的行为。

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。
centos7

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。
在官网获取到对应对话id（d59c95ba-98a3-4f8e-ae31-b7fee49e368c）的current_node值（响应json的最后一个值），在redis中修改对应key的值，修改后该对话恢复正常。
例：
set CHATGPT:CONVERSATION_LAST_MESSAGE_ID:d59c95ba-98a3-4f8e-ae31-b7fee49e368c 1b7870b3-fe47-4761-a71f-29564fb19ddf 

![QQ图片20230228203149](https://user-images.githubusercontent.com/58673341/221855061-12815275-7df4-40b0-b43b-c3c132ec6ec2.png)

![QQ图片20230228204436](https://user-images.githubusercontent.com/58673341/221857955-c8db3ada-79cb-4aa3-a88b-aed4d8aa0a37.png)

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。

**Comment by ikechan8370** [comment]
有一个想确定的事情，是redis中存的最新的messageId是官网上不存在的吗？然后由于parentId不存在才报了错？因为听你的描述似乎是反过来的，选择非最新的node作为parentId是允许的，不会报错，如果有报错可能是其他未知的原因。
如果能贴一下redis中的最新messageId和官网最后几条label为assistant的消息的id就好了。这种情况不是很好复现调试。

**Comment by 2445164645** [comment]
> 有一个想确定的事情，是redis中存在的最新的messageId是官网上不存在的吗？然后由于parentId不存在才报错了？因为听你的描述好像是反过来的，选择的非最新节点parentId是允许的，不会报错，如果有报错可能是其他人不知道的原因。 如果能贴下redis中的最新messageId和官网最后几条label为assistant的消息的id就好了。这种情况不行。复现调试。

最新的messageId是官网上不存在的吗？
答：是官网上不存在的，因为机器人回答的那句话官网上也不存在了，我只是推测是不是CONVERSATION_LAST_MESSAGE_ID值有问题，然后尝试修改，修改后恢复正常。后台发送请求时用的 parent_message_id ，官网上不存在。
    按照你的说法，我只要随便找一个官网上存在的值都能恢复正常喽。但是我现在进官网，开了f12就一直人机验证，不能重新查看参数了。我很确定发生问题时后台请求的parent_message_id参数从官网上拉下来的json里没有。

**Comment by sst-huiyi** [comment]
最新的messageId是官网上不存在的吗？
答：是官网上不存在的，机器人回答的那句话官网上也不存在了（不知道因为啥），我只是推测是不是CONVERSATION_LAST_MESSAGE_ID值有问题，然后尝试修改，修改后恢复正常。
   CONVERSATION_LAST_MESSAGE_ID值和官网上拉下来的json对比过，查不到相同的值。
     按照你的说法，我只要随便找一个官网上存在的值都能恢复正常喽。我现在进官网，开了f12就一直人机验证，应该是看不了json了。但是我很确定发生问题时机器人请求用的parent_message_id参数官网上拉下来的json里没有。

**Comment by sst-huiyi** [comment]
我是不是可以理解为，最开始，机器人收到了官网的响应结果，然后更新了redis中对应对话的CONVERSATION_LAST_MESSAGE_ID值，然后官网上的messageId不知道为啥消失了，然后后面和机器人对话后台发送请求使用的messageId官网不存在，就报错了。

**Comment by ikechan8370** [comment]
你这么说我就明白了，居然有这种情况。那可以加一个遇到这种特定错误再去官网拉取最新messageId的操作

**Comment by Err0rCM** [comment]
可能与 #133 关联

**Comment by Err0rCM** [comment]
时间过于久远
