### ISSUE TITLE
3.5接口开放了什么时候接入呢

### ISSUE THREAD

**Issue by nilfunc** [ikechan8370/chatgpt-plugin#210]
昨天官方发布新接口开放了，会考虑接入吗

**Comment by ikechan8370** [comment]
已经支持了 API模式 把chatgpt更新到最新（5.0.0以上） 重启机器人即可。之后我再改readme

**Comment by nilfunc** [comment]
好的谢谢，怎么看自己是什么版本呢

**Comment by ikechan8370** [comment]
pnpm list能看依赖版本 在本插件目录下pnpm install chatgpt@5.0.1来更新chatgpt。本插件不用更新
