### ISSUE TITLE
关于readme.md的GPT3.5 Turbo的描述

### ISSUE THREAD

**Issue by ayakasuki** [ikechan8370/chatgpt-plugin#212]
![image](https://user-images.githubusercontent.com/20859971/222481661-443bde27-a8bc-47b9-8e30-f60ba4bbd3f5.png)
好像价格已经不是GPT3的$0.02 / 1K 代币
是$0.002 / 1K 代币

**Comment by ikechan8370** [comment]
啊我写的不是0.002吗

**Comment by ikechan8370** [comment]
怪了 今天白天改的readme好像没提交上

**Comment by ayakasuki** [comment]
哈哈 看readme是0.02喔——

**Comment by ikechan8370** [comment]
今天明明改了好多readme 现在一看根本没改上 晕了
