### ISSUE TITLE
通信异常

### ISSUE THREAD

**Issue by nilfunc** [ikechan8370/chatgpt-plugin#213]
通信异常,错误信息如下FetchError: request to

https://api.openai.com/v1/chat/completions failed, reason: connect ETIMEDOUT 108.160.170.33:443

在升级为2.09后出现新错误
通信异常,错误信息如下Error: OpenAl missing required apiKey

但是这个sk是有用的

**Comment by CC-3301** [comment]
尝试代理

**Comment by W1NDes** [comment]
> 
使用代理出现报错
![image](https://user-images.githubusercontent.com/122395784/222918933-434dccbc-9d36-43a4-9584-21d5bcdcbc90.png)

**Comment by ikechan8370** [comment]
> > 
> 
> 使用代理出现报错
> 
> ![image](https://user-images.githubusercontent.com/122395784/222918933-434dccbc-9d36-43a4-9584-21d5bcdcbc90.png)
> 
> 

pnpm i然后重启再看看

**Comment by W1NDes** [comment]
> > > 
> > 
> > 
> > 使用代理出现报错
> > ![image](https://user-images.githubusercontent.com/122395784/222918933-434dccbc-9d36-43a4-9584-21d5bcdcbc90.png)
> 
> pnpm i然后重启再看看

成了，谢谢你🥰
