### ISSUE TITLE
请求增加群聊黑名单功能

### ISSUE THREAD

**Issue by Lovelumine** [ikechan8370/chatgpt-plugin#215]
希望能增加一个群聊黑名单功能
指定群聊中不回复

**Comment by CC-3301** [comment]
好像yunzai本体自带这个功能？
yunzai根目录下的config/config/other.yaml
里面有
#黑名单群
blackGroup:

**Comment by ikechan8370** [comment]
楼上正解，可以配置机器人在哪个群只启用哪些插件 锅巴面板也可以配
