### ISSUE TITLE
[Request]对话自动断开

### ISSUE THREAD

**Issue by CC-3301** [ikechan8370/chatgpt-plugin#218]
刚从远古版本升级上来，发现配置文件没有了对话经过多少秒后自动断开的配置项了，希望可以回归

**Comment by CC-3301** [comment]
顺便问下，配置文件里面的AI调教 支不支持中文？

**Comment by CC-3301** [comment]
一个小发现：当输入#结束对话的时候回复 “已结束当前对话，请@我进行聊天以开启新的对话” 明明触发方式改成了prefix（

**Comment by CC-3301** [comment]
群里的对话列表堆积了大量对话，如果继续调用会基于上次对话继续吗？

**Comment by Err0rCM** [comment]
> 刚从远古版本升级上来，发现配置文件没有了对话经过多少秒后自动断开的配置项了，希望可以回归

你可能说的是对话保留时长，该配置项还在，请在锅巴中配置

**Comment by Err0rCM** [comment]
> 顺便问下，配置文件里面的AI调教 支不支持中文？

支持

**Comment by Err0rCM** [comment]
> 一个小发现：当输入#结束对话的时候回复 “已结束当前对话，请@我进行聊天以开启新的对话” 明明触发方式改成了prefix（

可以无视

**Comment by Err0rCM** [comment]
> 群里的对话列表堆积了大量对话，如果继续调用会基于上次对话继续吗？

会的
