### ISSUE TITLE
error400 tokens

### ISSUE THREAD

**Issue by AzureSky** [ikechan8370/chatgpt-plugin#219]
通信异常,错误信息如下Error: OpenAl error 400: { "error":{ "message": "This model's maximum context length is 4096 tokens. However, you requested 4104tokens (3104 in the messages, 1000 in the completion). Please reduce the length of the messages or completion.", "type": "invalid_request_error","param": "messages", "code": "context_length_exceeded" } }

**Comment by teble** [comment]
https://platform.openai.com/docs/api-reference/completions/create#completions/create-max_tokens
这是模型的上下文长度限制，GPT3一次只能处理4096 token的上下文，但是目前有人做过60w token的尝试，V2EX上也有讨论：https://v2ex.com/t/920720
