### ISSUE TITLE
关于代码发送到QQ

### ISSUE THREAD

**Issue by ayakasuki** [ikechan8370/chatgpt-plugin#22]
感觉chatgdt发送代码到QQ可以转成图片再发送给chatgdt，类似nonebot的商店那个chatgpt一样

**Comment by ikechan8370** [comment]
可以考虑，有空我研究下，或者哪位大佬愿意动手欢迎贡献。

**Comment by ikechan8370** [comment]
v2分支上实现了图片模式，欢迎试用给出建议。
![M9X5775PQM~2 ED0PMF$2Q3](https://user-images.githubusercontent.com/21212372/206853841-447fb6b4-55fe-447c-a218-62b6ac4bf1b1.gif)

**Comment by RyanJiang184** [comment]
感谢大佬的更新，这个图片功能非常美观实用，可以有效防止刷屏。要说有什么建议的话希望能够增加一个全局开关图片模式的功能，目前图片模式好像是谁开启只有那个人自己有。。
