### ISSUE TITLE
语音模式遇到的问题

### ISSUE THREAD

**Issue by zfztty** [ikechan8370/chatgpt-plugin#220]
FetchError: request to https:// failed, reason: Client network socket disconnectedbefore secure TLS connection was established
已经填写了vits的api

**Comment by kicurry** [comment]
我也遇到一样的问题，并且初步怀疑是代理配置有误，但知识有限找不到具体原因。

下面补充下我的环境信息

## 环境变量

```
http_proxy=http://127.0.0.1:8123/
https_proxy=http://127.0.0.1:8123/
```

## 端口监听

1. 使用polipo监听本地8123端口，将http协议转为socks5协议，发送给父代理shadowsocks
2. 使用shadowsocks客户端连接代理服务器

## 补充信息

上述配置
1. 能够让我的终端能够访问外网，例如使用`curl`能够正确返回Google的响应头
2. 能够让本项目chatgpt插件在API模式正确调用chatgpt接口
3. Yunzaibot对墙内的一些请求似乎有问题，多数插件返回的图片全部挂掉（返回bad request 400）；对该问题我的解决方式是：打开YunzaiBot后再打开polipo监听
4. 填写duplicate space的app选项下方view api中获取的api：http:// xxxx/api/ generate；报错同本issue

**Comment by zfztty** [comment]
> 我也遇到一样的问题，并且初步怀疑是代理配置有误，但知识有限找不到具体原因。
> 
> 下面补充下我的环境信息
> ## 环境变量
> 
> ```
> http_proxy=http://127.0.0.1:8123/
> https_proxy=http://127.0.0.1:8123/
> ```
> 
> ## 端口监听
> 
>     1. 使用polipo监听本地8123端口，将http协议转为socks5协议，发送给父代理shadowsocks
> 
>     2. 使用shadowsocks客户端连接代理服务器
> 
> 
> ## 补充信息
> 
> 上述配置
> 
>     1. 能够让我的终端能够访问外网，例如使用`curl`能够正确返回Google的响应头
> 
>     2. 能够让本项目chatgpt插件在API模式正确调用chatgpt接口
> 
>     3. Yunzaibot对墙内的一些请求似乎有问题，多数插件返回的图片全部挂掉（返回bad request 400）；对该问题我的解决方式是：打开YunzaiBot后再打开polipo监听
> 
>     4. 填写duplicate space的app选项下方view api中获取的api：http:// xxxx/api/ generate；报错同本issue

其实是api地址填错了，api的内容只需要填到space那里就行了，再往后就不需要了

**Comment by kicurry** [comment]
@zfztty 原来如此，确实解决了，感恩的心

**Comment by lssl97** [comment]
大佬，我想问问怎么获取vits的api？我按锅巴插件里提示的网址，进去后不知道怎么操作

**Comment by kicurry** [comment]
> 大佬，我想问问怎么获取vits的api？我按锅巴插件里提示的网址，进去后不知道怎么操作

1. 首先duplicate一份仓库，然后在settings中将仓库设为公开
2. 在duplicate space首页apps选项下方点开view api（灰色字体，页面底部正下方，我也找了半天QAQ），有POST URL
3. 注意复制到space就行了

**注意**：不要复制锅巴插件配置中提示的网址的api，会抢占他人资源。hugging face提供免费的2核CPU，所以再次提醒要duplicate锅巴插件配置中的仓库

**Comment by ikechan8370** [comment]
如果不duplicate，那相当于你们在和我抢资源。一共就2核。改天我会关掉的，还是自己duplicate吧

**Comment by kicurry** [comment]
> 如果不duplicate，那相当于你们在和我抢资源。一共就2核。改天我会关掉的，还是自己duplicate吧

不好意思，我以为公开的仓库配置好一些，这就改掉0.0

**Comment by jiut** [comment]
> > 大佬，我想问问怎么获取vits的api？我按锅巴插件里提示的网址，进去后不知道怎么操作
> 
> 1. 首先duplicate一份仓库，然后在settings中将仓库设为公开
> 2. 在duplicate space首页apps选项下方点开view api（灰色字体，页面底部正下方，我也找了半天QAQ），有POST URL
> 3. 注意复制到space就行了
> 
> **注意**：不要复制锅巴插件配置中提示的网址的api，会抢占他人资源。hugging face提供免费的2核CPU，所以再次提醒要duplicate锅巴插件配置中的仓库

我在页面上是找不到，用f12搜索的，页面里没有显示这个元素。但是填这个链接会报错
![image](https://user-images.githubusercontent.com/52725935/224912998-96e6d236-8a88-46f4-b26f-1df513cf2fe1.png)
![image](https://user-images.githubusercontent.com/52725935/224913264-9bccbe10-2e9d-42d0-a434-cb2f19e924e7.png)

**Comment by jiut** [comment]
> > > 大佬，我想问问怎么获取vits的api？我按锅巴插件里提示的网址，进去后不知道怎么操作
> > 
> > 
> > 
> > 1. 首先duplicate一份仓库，然后在settings中将仓库设为公开
> > 2. 在duplicate space首页apps选项下方点开view api（灰色字体，页面底部正下方，我也找了半天QAQ），有POST URL
> > 3. 注意复制到space就行了
> > 
> > **注意**：不要复制锅巴插件配置中提示的网址的api，会抢占他人资源。hugging face提供免费的2核CPU，所以再次提醒要duplicate锅巴插件配置中的仓库
> 
> 我在页面上是找不到，用f12搜索的，页面里没有显示这个元素。但是填这个链接会报错 ![image](https://user-images.githubusercontent.com/52725935/224912998-96e6d236-8a88-46f4-b26f-1df513cf2fe1.png) ![image](https://user-images.githubusercontent.com/52725935/224913264-9bccbe10-2e9d-42d0-a434-cb2f19e924e7.png)

已解决，需要复制**这个库**：https://huggingface.co/spaces/ikechan8370/vits-uma-genshin-honkai ，而不是初始的[sayashi的这个库](https://huggingface.co/spaces/sayashi/vits-uma-genshin-honkai)
