### ISSUE TITLE
API3模式下使用报错access denied

### ISSUE THREAD

**Issue by PrussianBlueCN** [ikechan8370/chatgpt-plugin#223]
**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

请在此处描述您遇到的问题，包括出现问题的环境、您试图实现的功能以及错误信息等。请尽可能详细，以便其他人可以在自己的环境中复制问题。

之前已能正常使用，约2天前开始发送#chatxxx直接返回图片报错access denied ，具体如图所示
![image](https://user-images.githubusercontent.com/110645427/223069615-17a16ade-6dc7-4da7-91a0-34a170ad78ab.png)

## 预期行为

请描述您期望系统在出现问题时应该做什么。

正常连接ChatGPT并返回相应回答。

## 实际行为

请描述您实际看到的行为。

报错access denied，如上图。

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

无论群聊或私聊、无论是谁发送#chatxxx均返回图示结果。

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。

腾讯云centos8，nodejs 19.2 云崽与ChatGPT插件均已更新。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

没有太多头绪，直接访问chatgpt.duti.tech提示504。

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。

**Comment by ikechan8370** [comment]
chatgpt.duti.tech屏蔽了腾讯云。你是否使用的是腾讯云？

**Comment by PrussianBlueCN** [comment]
> chatgpt.duti.tech屏蔽了腾讯云。你是否使用的是腾讯云？

是腾讯云，那还有办法吗？还是只能官网直连走扣费的了

**Comment by ikechan8370** [comment]
付费那个效果很好 还特别便宜。或者加群找其他办法

**Comment by muyun618** [comment]
> 付费那个效果很好 还特别便宜。或者加群找其他办法

如果不是腾讯云而是本地部署的出现这个问题该怎么解决，今天突然出现的

**Comment by regaliaf** [comment]
本地部署出现了同样的问题。大概是用的太多被第三方封了。

**Comment by ikechan8370** [comment]
请更新，已解决
