### ISSUE TITLE
到底怎么运行或者重启Yunzai-Bot？

### ISSUE THREAD

**Issue by Lukangkang123** [ikechan8370/chatgpt-plugin#224]
**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

npnm执行完就没了，到底该怎么运行？重启Yunzai-Bot又该怎么重启？

## 预期行为

请描述您期望系统在出现问题时应该做什么。

## 实际行为

请描述您实际看到的行为。

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息
![image](https://user-images.githubusercontent.com/38984189/223110478-b8e39564-9b83-483d-b719-e504c2abfd21.png)

**Comment by Xing688** [comment]
yz

**Comment by Lukangkang123** [comment]
readme文件里连怎么运行都没说

**Comment by Xing688** [comment]
这个和插件无关，没人回复你的原因是这是机器人的最基本操作，输入yz启动，本体的教程没看明白，做插件的为什么要给你擦屁股

**Comment by Lukangkang123** [comment]
> 这个和插件无关，没人回复你的原因是这是机器人的最基本操作，输入yz启动，本体的教程没看明白，做插件的为什么要给你擦屁股
那你起码把本体教程的链接放进来吧，直接看到这个项目的一头雾水

**Comment by Xing688** [comment]
你没看过本体为啥来找插件啊

**Comment by Lukangkang123** [comment]
> 你没看过本体为啥来找插件啊

我搜chatGPT就找到你这个项目了啊

**Comment by Xing688** [comment]
下次理解了插件的意思在进行操作吧，至少也要搜下本体是啥

**Comment by Lukangkang123** [comment]
> 下次理解了插件的意思在进行操作吧，至少也要搜下本体是啥

起码得让我知道本体在哪儿吧

**Comment by Xing688** [comment]
自己搜好吧

**Comment by Xing688** [comment]
在git上，或者去b站直接搜索一键部署

**Comment by Lukangkang123** [comment]
> 在git上，或者去b站直接搜索一键部署

我倒可以现场搜，不过最好的方式还是在readme里添加一下Yunzai-Bot的链接和简单用法，因为不是所有人都是先看到本体再看到你这个项目的。当然，你的项目更不更新也随你。

**Comment by Xing688** [comment]
首先我不是拥有者，其次你才是少数人

**Comment by Lukangkang123** [comment]
> 首先我不是拥有者，其次你才是少数人

哈哈，那好
