### ISSUE TITLE
使用API模式通信异常

### ISSUE THREAD

**Issue by lssl97** [ikechan8370/chatgpt-plugin#225]
报错如下：
![ce506766875f1730d99461c21cfd0111](https://user-images.githubusercontent.com/83483454/223444381-a207b6e2-435d-4a21-8264-81ced1aa773a.jpg)
是不是国内都连不上啦？有什么解决办法吗，目前好像就Bing模式能正常用

**Comment by captainYE1** [comment]
我与遇到这个问题了，请问解决了吗

**Comment by lssl97** [comment]
> 我遇到这个问题了，请问解决了吗

我在锅巴插件里设置了代理，现在已经能用了，国内的网络直连应该是用不了

**Comment by captainYE1** [comment]
> 
我一直开着VPN，使用浏览器模式可以用，但是API模式不行，请问代理是指锅巴插件里的本地代理吗，这个代理地址在哪里找呢

**Comment by lssl97** [comment]
> > 
> 
> 我一直开着VPN，使用浏览器模式可以用，但是API模式不行，请问代理是指锅巴插件里的本地代理吗，这个代理地址在哪里找呢

我是这么设置的：
![QQ截图20230312220652](https://user-images.githubusercontent.com/83483454/224550143-300c0767-eaa6-4821-8b07-12178bcbf4e3.png)
这个端口号可以在你使用的梯子里找到：
![QQ图片20230312220730](https://user-images.githubusercontent.com/83483454/224550157-0386582e-a3cf-4bfe-9221-1cd1635340e0.png)
然后全程挂着梯子就行啦

**Comment by captainYE1** [comment]
> > > 
> > 
> > 
> > 我一直开着VPN，使用浏览器模式可以用，但是API模式不行，请问代理是指锅巴插件里的本地代理吗，这个代理地址在哪里找呢
> 
> 我是这么设置的： ![QQ截图20230312220652](https://user-images.githubusercontent.com/83483454/224550143-300c0767-eaa6-4821-8b07-12178bcbf4e3.png) 这个端口号可以在你使用的梯子里找到： ![QQ图片20230312220730](https://user-images.githubusercontent.com/83483454/224550157-0386582e-a3cf-4bfe-9221-1cd1635340e0.png) 然后全程挂着梯子就行啦

谢谢！！！
