### ISSUE TITLE
设置newbing的token一直无效

### ISSUE THREAD

**Issue by izumichan6** [ikechan8370/chatgpt-plugin#226]
已有newbing资格，网页用没问题，拿到token设置一直说无效，清缓存清ck用无痕都试过了还是不行，一直是经检测，Bing Token无效。来自Bing的错误提示：Sorry, you need to login first to access this service.

**Comment by ikechan8370** [comment]
更新再试试

**Comment by strongtz** [comment]
我这儿也突然这样了，刚更新了还是不行（

**Comment by strongtz** [comment]
```
[YzBot][20:46:40.156][INFO] chatgpt prompt: 你是谁
[YzBot][20:46:40.156][INFO] {
  previousConversation: {
    sender: {
      user_id: 2123808443,
      nickname: 'Sakuramist',
      card: 'Sakuramist',
      sex: 'male',
      age: 20,
      area: '',
      level: 2,
      role: 'member',
      title: ''
    },
    ctime: '2023-03-08T12:38:56.861Z',
    utime: '2023-03-08T12:38:56.861Z',
    num: 3,
    conversation: {}
  }
}
[YzBot][20:46:40.156][MARK] {
  conversation: {
    conversationId: undefined,
    parentMessageId: undefined,
    clientId: undefined,
    invocationId: undefined,
    conversationSignature: undefined
  }
}
[YzBot][20:46:40.156][MARK] using bing mode
{
  result: {
    value: 'UnauthorizedRequest',
    message: 'Sorry, you need to login first to access this service.'
  }
}
[YzBot][20:46:40.494][ERRO] Error: UnauthorizedRequest: Sorry, you need to login first to access this service.
    at SydneyAIClient.sendMessage (file:///D:/Greenify/Yunzai-Bot/plugins/chatgpt-plugin/utils/SydneyAIClient.js:226:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async chatgpt.sendMessage (file:///D:/Greenify/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:779:24)
    at async chatgpt (file:///D:/Greenify/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:580:25)
    at async PluginsLoader.deal (file:///D:/Greenify/Yunzai-Bot/lib/plugins/loader.js:252:52)
{
  result: {
    value: 'UnauthorizedRequest',
    message: 'Sorry, you need to login first to access this service.'
  }
}
[YzBot][20:46:40.816][ERRO] Error: UnauthorizedRequest: Sorry, you need to login first to access this service.
    at SydneyAIClient.sendMessage (file:///D:/Greenify/Yunzai-Bot/plugins/chatgpt-plugin/utils/SydneyAIClient.js:226:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async chatgpt.sendMessage (file:///D:/Greenify/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:779:24)
    at async chatgpt (file:///D:/Greenify/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:580:25)
    at async PluginsLoader.deal (file:///D:/Greenify/Yunzai-Bot/lib/plugins/loader.js:252:52)
{
  result: {
    value: 'UnauthorizedRequest',
    message: 'Sorry, you need to login first to access this service.'
  }
}
[YzBot][20:46:41.175][ERRO] Error: UnauthorizedRequest: Sorry, you need to login first to access this service.
    at SydneyAIClient.sendMessage (file:///D:/Greenify/Yunzai-Bot/plugins/chatgpt-plugin/utils/SydneyAIClient.js:226:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async chatgpt.sendMessage (file:///D:/Greenify/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:779:24)
    at async chatgpt (file:///D:/Greenify/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:580:25)
    at async PluginsLoader.deal (file:///D:/Greenify/Yunzai-Bot/lib/plugins/loader.js:252:52)
[YzBot][20:46:41.175][INFO] {
  text: 'UnauthorizedRequest: Sorry, you need to login first to access this service.'
}
```

edit：已解决

**Comment by V2233** [comment]
> ```
> [YzBot][20:46:40.156][INFO] chatgpt prompt: 你是谁
> [YzBot][20:46:40.156][INFO] {
>   previousConversation: {
>     sender: {
>       user_id: 2123808443,
>       nickname: 'Sakuramist',
>       card: 'Sakuramist',
>       sex: 'male',
>       age: 20,
>       area: '',
>       level: 2,
>       role: 'member',
>       title: ''
>     },
>     ctime: '2023-03-08T12:38:56.861Z',
>     utime: '2023-03-08T12:38:56.861Z',
>     num: 3,
>     conversation: {}
>   }
> }
> [YzBot][20:46:40.156][MARK] {
>   conversation: {
>     conversationId: undefined,
>     parentMessageId: undefined,
>     clientId: undefined,
>     invocationId: undefined,
>     conversationSignature: undefined
>   }
> }
> [YzBot][20:46:40.156][MARK] using bing mode
> {
>   result: {
>     value: 'UnauthorizedRequest',
>     message: 'Sorry, you need to login first to access this service.'
>   }
> }
> [YzBot][20:46:40.494][ERRO] Error: UnauthorizedRequest: Sorry, you need to login first to access this service.
>     at SydneyAIClient.sendMessage (file:///D:/Greenify/Yunzai-Bot/plugins/chatgpt-plugin/utils/SydneyAIClient.js:226:15)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async chatgpt.sendMessage (file:///D:/Greenify/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:779:24)
>     at async chatgpt (file:///D:/Greenify/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:580:25)
>     at async PluginsLoader.deal (file:///D:/Greenify/Yunzai-Bot/lib/plugins/loader.js:252:52)
> {
>   result: {
>     value: 'UnauthorizedRequest',
>     message: 'Sorry, you need to login first to access this service.'
>   }
> }
> [YzBot][20:46:40.816][ERRO] Error: UnauthorizedRequest: Sorry, you need to login first to access this service.
>     at SydneyAIClient.sendMessage (file:///D:/Greenify/Yunzai-Bot/plugins/chatgpt-plugin/utils/SydneyAIClient.js:226:15)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async chatgpt.sendMessage (file:///D:/Greenify/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:779:24)
>     at async chatgpt (file:///D:/Greenify/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:580:25)
>     at async PluginsLoader.deal (file:///D:/Greenify/Yunzai-Bot/lib/plugins/loader.js:252:52)
> {
>   result: {
>     value: 'UnauthorizedRequest',
>     message: 'Sorry, you need to login first to access this service.'
>   }
> }
> [YzBot][20:46:41.175][ERRO] Error: UnauthorizedRequest: Sorry, you need to login first to access this service.
>     at SydneyAIClient.sendMessage (file:///D:/Greenify/Yunzai-Bot/plugins/chatgpt-plugin/utils/SydneyAIClient.js:226:15)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async chatgpt.sendMessage (file:///D:/Greenify/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:779:24)
>     at async chatgpt (file:///D:/Greenify/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:580:25)
>     at async PluginsLoader.deal (file:///D:/Greenify/Yunzai-Bot/lib/plugins/loader.js:252:52)
> [YzBot][20:46:41.175][INFO] {
>   text: 'UnauthorizedRequest: Sorry, you need to login first to access this service.'
> }
> ```
> 
> edit：已解决

怎么解决的，求个路

**Comment by strongtz** [comment]
我也不太确定其实（
试试浏览器里重新登陆bing，然后用readme里面的方法手动获取cookie（不要用控制台命令那个方法）

**Comment by izumichan6** [comment]
> 

我还是不行，不管怎么弄都是提示经检测，Bing Token无效。来自Bing的错误提示：Sorry, you need to login first to access this service.
重新登陆，重启电脑，挂梯子，上代理，清cookie清缓存，无痕模式，啥都试过了都不行我吐了

**Comment by Err0rCM** [comment]
一般来说不会有这样的问题，没有更多信息无法定位问题，且问题与本插件无关

可以进交流群问问
