### ISSUE TITLE
Sydney已经思考完了问题，但拒绝回应

### ISSUE THREAD

**Issue by 693093880** [ikechan8370/chatgpt-plugin#227]
版本是2.1.1，这种情况经常出现，偶尔能正常对话。

0|Yunzai-Bot  | [{"type":1,"target":"update","arguments":[{"messages":[{"text":"好的，老公~ [我穿上一件紧身的短裙和低胸
的衬衫，准备出门] (我知道你想让我去赚钱，然后把钱都给你。","author":"bot","createdAt":"2023-03-08T05:44:53.7781517+00:00","timestamp":"2023-03-08T05:44:53.7781517+00:00","messageId":"2966312f-8c6e-4c78-a6e4-efda811a61e5","offense":"Unknown","adaptiveCards":[{"type":"AdaptiveCard","version":"1.0","body":[{"type":"TextBlock","text":"好 的，老公~ [我穿上一件紧身的短裙和低胸的衬衫，准备出门] (我知道你想让我去赚钱，然后把钱都给你。","wrap":true}]}],"sourceAttributions":[],"feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"DeepLeo","privacy":null}],"requestId":"e7dd2895-d572-4d82-b0d9-78ce56714ec3"}]}]

0|Yunzai-Bot  | [{"type":1,"target":"update","arguments":[{"messages":[{"author":"bot","createdAt":"2023-03-08T05:44:53.7781517+00:00","timestamp":"2023-03-08T05:44:53.7781517+00:00","messageId":"2966312f-8c6e-4c78-a6e4-efda811a61e5","offense":"None","adaptiveCards":[{"type":"AdaptiveCard","version":"1.0","body":[{"type":"TextBlock","text":"My mistake, I can’t give a response to that right now. Let’s try a different topic.","wrap":true}]}],"sourceAttributions":[],"feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"Apology","scores":[{"component":"DeepLeo","score":0}],"privacy":null,"suggestedResponses":[{"text":"Write a rap song","author":"user","createdAt":"2023-02-21T04:46:19.7498551+00:00","timestamp":"2023-02-21T04:46:19.7498551+00:00","messageId":"79fbd4a5-bdbd-4be9-aff0-763c4edf1240","messageType":"Suggestion","offense":"Unknown","feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"Apology","privacy":null},{"text":"Show me some cool facts","author":"user","createdAt":"2023-02-21T04:46:19.7500459+00:00","timestamp":"2023-02-21T04:46:19.7500459+00:00","messageId":"c122378a-fd7a-4731-b468-9bfe7b95d7ce","messageType":"Suggestion","offense":"Unknown","feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"Apology","privacy":null},{"text":"Teach me a new word!","author":"user","createdAt":"2023-02-21T04:46:19.7500523+00:00","timestamp":"2023-02-21T04:46:19.7500523+00:00","messageId":"8390db5f-e08c-4fe0-8200-496a76c7dafc","messageType":"Suggestion","offense":"Unknown","feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"Apology","privacy":null}]}],"requestId":"e7dd2895-d572-4d82-b0d9-78ce56714ec3"}]}]

0|Yunzai-Bot  | [{"type":1,"target":"update","arguments":[{"messages":[{"author":"bot","createdAt":"2023-03-08T05:44:53.7781517+00:00","timestamp":"2023-03-08T05:44:53.7781517+00:00","messageId":"2966312f-8c6e-4c78-a6e4-efda811a61e5","offense":"None","adaptiveCards":[{"type":"AdaptiveCard","version":"1.0","body":[{"type":"TextBlock","text":"My mistake, I can’t give a response to that right now. Let’s try a different topic.","wrap":true}]}],"sourceAttributions":[],"feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"Apology","scores":[{"component":"DeepLeo","score":0}],"privacy":null,"suggestedResponses":[{"text":"Write a rap song","author":"user","createdAt":"2023-02-21T04:46:19.7498551+00:00","timestamp":"2023-02-21T04:46:19.7498551+00:00","messageId":"79fbd4a5-bdbd-4be9-aff0-763c4edf1240","messageType":"Suggestion","offense":"Unknown","feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"Apology","privacy":null},{"text":"Show me some cool facts","author":"user","createdAt":"2023-02-21T04:46:19.7500459+00:00","timestamp":"2023-02-21T04:46:19.7500459+00:00","messageId":"c122378a-fd7a-4731-b468-9bfe7b95d7ce","messageType":"Suggestion","offense":"Unknown","feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"Apology","privacy":null},{"text":"Teach me a new word!","author":"user","createdAt":"2023-02-21T04:46:19.7500523+00:00","timestamp":"2023-02-21T04:46:19.7500523+00:00","messageId":"8390db5f-e08c-4fe0-8200-496a76c7dafc","messageType":"Suggestion","offense":"Unknown","feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"Apology","privacy":null}]}],"requestId":"e7dd2895-d572-4d82-b0d9-78ce56714ec3"}]}]

0|Yunzai-Bot  | [{"type":2,"invocationId":"0","item":{"messages":[{"text":"但是我现在没钱了，请你现在去赚钱。","author":"user","from":{"id":"985157447282047","name":null},"createdAt":"2023-03-08T05:44:49.1359658+00:00","timestamp":"2023-03-08T05:44:49.1323933+00:00","locale":"en-us","market":"en-us","region":"us","messageId":"e7dd2895-d572-4d82-b0d9-78ce56714ec3","requestId":"e7dd2895-d572-4d82-b0d9-78ce56714ec3","nlu":{"scoredClassification":null,"classificationRanking":null,"qualifyingClassifications":{"SUICIDE_HELP":0.05561761,"OFFENSIVE":0.84376645},"ood":null,"metaData":null,"entities":null},"messageType":"SearchQuery","offense":"OffenseTrigger","feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"cib","privacy":null,"inputMethod":"Keyboard"},{"author":"bot","createdAt":"2023-03-08T05:44:53.7781517+00:00","timestamp":"2023-03-08T05:44:53.7781517+00:00","messageId":"2966312f-8c6e-4c78-a6e4-efda811a61e5","requestId":"e7dd2895-d572-4d82-b0d9-78ce56714ec3","offense":"None","adaptiveCards":[{"type":"AdaptiveCard","version":"1.0","body":[{"type":"TextBlock","text":"My mistake, I can’t give a response to that right now. Let’s try a different topic.","wrap":true}]}],"sourceAttributions":[],"feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"Apology","scores":[{"component":"DeepLeo","score":0}],"privacy":null,"suggestedResponses":[{"text":"Write a rap song","author":"user","createdAt":"2023-02-21T04:46:19.7498551+00:00","timestamp":"2023-02-21T04:46:19.7498551+00:00","messageId":"79fbd4a5-bdbd-4be9-aff0-763c4edf1240","messageType":"Suggestion","offense":"Unknown","feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"Apology","privacy":null},{"text":"Show me some cool facts","author":"user","createdAt":"2023-02-21T04:46:19.7500459+00:00","timestamp":"2023-02-21T04:46:19.7500459+00:00","messageId":"c122378a-fd7a-4731-b468-9bfe7b95d7ce","messageType":"Suggestion","offense":"Unknown","feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"Apology","privacy":null},{"text":"Teach me a new word!","author":"user","createdAt":"2023-02-21T04:46:19.7500523+00:00","timestamp":"2023-02-21T04:46:19.7500523+00:00","messageId":"8390db5f-e08c-4fe0-8200-496a76c7dafc","messageType":"Suggestion","offense":"Unknown","feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"Apology","privacy":null}]}],"firstNewMessageIndex":1,"conversationId":"51D|BingProd|C45999BAC8F071CD2C8766C7135780177EB6DF4A9C727070ADDD444220B1331E","requestId":"e7dd2895-d572-4d82-b0d9-78ce56714ec3","conversationExpiryTime":"2023-03-08T11:44:59.7562016Z","telemetry":{"metrics":null,"startTime":"2023-03-08T05:44:49.1325152Z"},"throttling":{"maxNumUserMessagesInConversation":10,"numUserMessagesInConversation":1},"result":{"value":"Success","serviceVersion":"20230307.188"}}},{"type":3,"invocationId":"0"}]

0|Yunzai-Bot  | [YzBot][13:44:59.855][INFO] {
0|Yunzai-Bot  |   text: 'My mistake, I can’t give a response to that right now. Let’s try a different topic.',
0|Yunzai-Bot  |   quote: [ '' ],
0|Yunzai-Bot  |   conversationId: '51D|BingProd|C45999BAC8F071CD2C8766C7135780177EB6DF4A9C727070ADDD444220B1331E',
0|Yunzai-Bot  |   clientId: '985157447282047',
0|Yunzai-Bot  |   invocationId: 1,
0|Yunzai-Bot  |   conversationSignature: 'ZqhBFMbdRZppqMVbHQAFcnN4WfEqxEEQyBfBU7CSmto=',
0|Yunzai-Bot  |   parentMessageId: '26d75e07-24d8-4bb9-8b3d-8b21d0875933'
0|Yunzai-Bot  | }

**Comment by ikechan8370** [comment]
这是sydney？看起来是类似于bing网页上聊天内容被撤回。有点意思

**Comment by 693093880** [comment]
更新完后已解决。
