### ISSUE TITLE
能否设置仅在一个群工作

### ISSUE THREAD

**Issue by kae-mihara** [ikechan8370/chatgpt-plugin#228]
我的bot加了多个群，现在其中一个群的大佬提供了chatgpt api，并表示希望仅在此群内启用。

我知道可以手动对各个群设置闭嘴，但这样实在有些麻烦，并且bot每新加一个群就要设置一次闭嘴（而非默认不启用）。

请问现在有什么解决办法吗？

**Comment by Jiao0XY** [comment]
你可以使用锅巴插件，【配置管理】-【群组配置】中默认配置里面设置功能黑名单加上chatgpt，然后新增群配置，在功能白名单里添加你用的功能，这样的话chatgpt功能对于其他未添加白名单的群就不可用了
