### ISSUE TITLE
关于token更新问题

### ISSUE THREAD

**Issue by yydzjdwji** [ikechan8370/chatgpt-plugin#23]
现在我的Chatgpt聊天页面每隔几十秒就会更新一次token，请问这是该站的新策略还是我这边的问题，如果是我的问题请问应如何获取到有效的token。

**Comment by ikechan8370** [comment]
我的也是，就是openai的策略吧，复制一个就好。如果不能用就再去复制一遍新token。

**Comment by yydzjdwji** [comment]
试了几次，每次都是复制过去，尝试使用，返回了session token has expired，期待大佬进一步解答

**Comment by ikechan8370** [comment]
重新登录再复制试试呢？我偶尔会遇到这个，重新复制一下就好了

**Comment by yydzjdwji** [comment]
好的，谢谢大佬，有空我再试一下。

**Comment by yydzjdwji** [comment]
感谢大佬，按您说的重新登录再尝试复制，成功解决了问题
