### ISSUE TITLE
API模式似乎实际调用的是text-davinci模型而非3.5-turbo

### ISSUE THREAD

**Issue by PrussianBlueCN** [ikechan8370/chatgpt-plugin#231]
根据readme描述API模式将调用gpt-3.5-turbo，今天偶然在[https://platform.openai.com/account/usage](url)中查看了API用量发现这里显示全部的调用都是text-davinci模型？

ps说起来大佬有考虑开官方群吗（

**Comment by ikechan8370** [comment]
你没更新吧。更新一下依赖 群号日志里有
