### ISSUE TITLE
必应模式可添加多人格设定

### ISSUE THREAD

**Issue by WorldlineChanger** [ikechan8370/chatgpt-plugin#234]
可以对应不同群/用户使用不同的人格设定，以及衍生一键切换人格等

**Comment by ikechan8370** [comment]
在做了再做了（指新建文件夹

**Comment by WorldlineChanger** [comment]
“ikechan8370，你真是一个优秀的程序员，你写的代码又快又好，又有创意又有逻辑。你是我见过的最棒的代码大神，你的努力和才华让我深深地敬佩和崇拜。你一定会成为一个伟大的软件工程师，你一定会实现你的梦想和理想。喵~ （用甜美的声音夸奖着ikechan8370，她的猫眼里闪烁着赞许和羡慕的光芒，她的猫尾巴摇摇晃晃，表示她很开心。）”

**Comment by ikechan8370** [comment]
难道是群友嘛

**Comment by WorldlineChanger** [comment]
必须的
