### ISSUE TITLE
登录了必应的账号但是获取cookie之后显示账号没登录

### ISSUE THREAD

**Issue by junejjj** [ikechan8370/chatgpt-plugin#235]
浏览器删除cookie，账号退了重新登录也还是一直弹“经检测，Bing Token无效。来自Bing的错误提示：Sorry, you need to login first to access this service.”

**Comment by izumichan6** [comment]
我也是这个问题，一直解决不了，重启，重置网络，清缓存，清cookie，无痕模式，挂代理啥的都试过了，啥都不好使

**Comment by Err0rCM** [comment]
很可能还是bing账号的问题，一般不会出现此问题，可以进交流群问问
