### ISSUE TITLE
语音模式音频转码的问题

### ISSUE THREAD

**Issue by heisenyu** [ikechan8370/chatgpt-plugin#236]
[MiaoYz][17:01:14.350][INFO] 正在使用纳西妲（草神），基于文本：'今天在上海的天气是**晴朗的**，温度是**78.098华氏度**[1]。你想知道今天的风速和湿度吗？还是想知道未来几天的天气预报呢？'生成语音
[MiaoYz][17:01:14.350][INFO] 正在使用接口https://xxx/api/generate
[MiaoYz][17:01:26.135][INFO] {
  data: [
    '生成成功!',
    {
      name: '/tmp/tmpnj_o_197/tmpncjug7b7.wav',
      data: null,
      is_file: true
    },
    '生成耗时 10.58 s'
  ],
  is_generating: false,
  duration: 10.576157093048096,
  average_duration: 10.576157093048096
}
[MiaoYz][17:01:26.135][INFO] 生成成功! 生成耗时 10.58 s
[MiaoYz][17:01:28.068][ERRO] 发送消息错误:{"type":"record","file":"https://xxx/file=/tmp/tmpnj_o_197/tmpncjug7b7.wav"}
[MiaoYz][17:01:28.069][ERRO] ApiRejection { code: -60, message: '音频转码到amr失败，请确认你的ffmpeg可以处理此转换' }

**Comment by heisenyu** [comment]
已解决：安装ffmpeg即可

sudo yum install epel-release
sudo rpm -v --import http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro
sudo rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
sudo yum install ffmpeg ffmpeg-devel
ffmpeg -version

**Comment by sk856** [comment]
sudo不是内部或外部命令怎么解决
