### ISSUE TITLE
API3模式报错 Error::ok event:close data:

### ISSUE THREAD

**Issue by muyun618** [ikechan8370/chatgpt-plugin#237]
## 问题描述

在尝试安装py插件（py-plugin）后，重启，在API3模式下，无法对话，出现404报错，删除py插件后仍然报错；下午更新该插件之后报错改为“Error::ok event:close data:”

## 预期行为

正常对话

## 实际行为

报错并返回对应图片

## 复制过程

根据云崽插件目录的py插件安装教程进行安装，使用python3.10.8安装poetry，在插件目录安装python依赖时出现错误，然后放弃安装。回到QQ尝试对话即出现404报错。

## 环境

win10、python3.10.8、未配置代理

## 可能的解决方案

重装chatgpt插件，结果还是404

## 附加信息

py插件地址 https://gitee.com/realhuhu/py-plugin

报错信息：
![6V@XC}J2_XN(}`Q~CRIWK_2](https://user-images.githubusercontent.com/115034363/223973769-0afdbe1a-d983-404a-b8dd-20e423e4dc7b.gif)
![QQ图片20230309165516](https://user-images.githubusercontent.com/115034363/223974056-f8d096df-ddc7-43d6-b4e7-f4ce86f64466.png)

————————分割线————————

![QQ图片20230309164754](https://user-images.githubusercontent.com/115034363/223974161-000be21a-342a-4315-afd4-4fb38389a2a2.jpg)
![QQ图片20230309164746](https://user-images.githubusercontent.com/115034363/223974208-3f0bdc91-78e9-4b48-bce1-a57178eae1ef.png)

**Comment by ikechan8370** [comment]
现在还这样吗？群里有人反馈过 应该修好了

**Comment by muyun618** [comment]
> 现在还这样吗？群里有人反馈过 应该修好了

还是报错，之前是怎么修的？
群号是多少啊

**Comment by regaliaf** [comment]
这个问题是代理挂了。需要换一个新的API3的代理，就修好了。

**Comment by ikechan8370** [comment]
已修复
