### ISSUE TITLE
Error: TypeError: proxy is not a function

### ISSUE THREAD

**Issue by hcg-ace** [ikechan8370/chatgpt-plugin#239]
![image](https://user-images.githubusercontent.com/82381099/223984660-c09762a0-a062-4052-85ed-6d372810d232.png)

**Comment by HGC-ACE** [comment]
![Z_B1D1} P0VY(_%S E08L3P](https://user-images.githubusercontent.com/82381099/223985054-d6b72ac3-6d30-4013-ad37-29b06dfd27b0.png)

**Comment by hcg-ace** [comment]
![image](https://user-images.githubusercontent.com/82381099/223985459-0ce14d3c-c03a-42f7-af8f-67bf7ac3b74e.png)

**Comment by sainttas** [comment]
除非你的代理服务器是国外的，不然的话要使用反向代理，添加反代后proxy就可以空着了
![image](https://user-images.githubusercontent.com/112640225/223990012-cf377c27-1e5e-4d58-83e0-7c34b30796c3.png)
