### ISSUE TITLE
更新后遇到了TypeError问题..昨天用之前旧的是好用的，小白不太清楚问题原因求助

### ISSUE THREAD

**Issue by ikashana** [ikechan8370/chatgpt-plugin#24]
TypeError: this.chatGPTApi.getConversation is not a
function
    at chatgpt (file:///E:/yuanshen/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.
js:196:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PluginsLoader.deal (file:///E:/yuanshen/Yunzai-Bot/lib/plugins/load
er.js:251:52)

**Comment by ikechan8370** [comment]
> TypeError: this.chatGPTApi.getConversation is not a
> 
> function
> 
>     at chatgpt (file:///E:/yuanshen/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.
> 
> js:196:27)
> 
>     at runMicrotasks (<anonymous>)
> 
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 
>     at async PluginsLoader.deal (file:///E:/yuanshen/Yunzai-Bot/lib/plugins/load
> 
> er.js:251:52)
> 
> 

可能是chatgpt版本低了。pnpm update一下试试

**Comment by ikashana** [comment]
> > TypeError: this.chatGPTApi.getConversation is not a
> > function
> > ```
> > at chatgpt (file:///E:/yuanshen/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > js:196:27)
> > ```
> > at runMicrotasks (<anonymous>)
> > 
> > at processTicksAndRejections (node:internal/process/task_queues:96:5)
> > 
> > at async PluginsLoader.deal (file:///E:/yuanshen/Yunzai-Bot/lib/plugins/load
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > er.js:251:52)
> 
> 可能是chatgpt版本低了。pnpm update一下试试

执行了pnpm update后依旧还是这个问题..

**Comment by ikechan8370** [comment]
`pnpm ls -P` 看看输出的chatgpt版本，chatgpt在2.0之后才引入的conversation api，这个错应该大概率是版本问题。

**Comment by ikashana** [comment]
> `pnpm ls -P` 看看输出的chatgpt版本，chatgpt在2.0之后才引入的conversation api，这个错应该大概率是版本问题。

嗯，确实是版本问题。刚学了点点弄这个不太熟练，才想起单独看看。pnpm update之后chatgpt依旧是更新失败的，于是我删除了chatgpt然后重新安装了，刚问题解决了正打算来反馈一下哈哈哈哈，谢谢
