### ISSUE TITLE
对于浏览器模式验证码识别

### ISSUE THREAD

**Issue by fatebugs** [ikechan8370/chatgpt-plugin#241]
能否对《打码狗》平台进行支持，平台是国内的，而且价格很便宜

甚至能够一块钱一块钱的进行充值

一下是他们的文档地址
http://www.damagou.top/help.html

**Comment by ikechan8370** [comment]
浏览器模式不推荐使用了，即将移除。使用自建反代的API3模式可以完美替代

**Comment by fatebugs** [comment]
> 浏览器模式不推荐使用了，即将移除。使用自建反代的API3模式可以完美替代

你好，我使用Linux进行自建反代，但是出现了错误，我应该怎么解决，我的服务器是可以连接外网的

**Comment by fatebugs** [comment]
> 浏览器模式不推荐使用了，即将移除。使用自建反代的API3模式可以完美替代

现在直接使用Key调取API几乎都会被封号，所以我只能想办法在反代上了

**Comment by ikechan8370** [comment]
> > 浏览器模式不推荐使用了，即将移除。使用自建反代的API3模式可以完美替代
> 
> 现在直接使用Key调取API几乎都会被封号，所以我只能想办法在反代上了

封号和那个没关系。不用也一样封。每天都在用的人也大有人在。

**Comment by fatebugs** [comment]
> > > 浏览器模式不推荐使用了，即将移除。使用自建反代的API3模式可以完美替代
> > 
> > 
> > 现在直接使用Key调取API几乎都会被封号，所以我只能想办法在反代上了
> 
> 封号和那个没关系。不用也一样封。每天都在用的人也大有人在。

现在的反代我应该怎么配置呢，我docker跑起来之后访问就在报错中了

**Comment by Err0rCM** [comment]
目前已有[文档](https://chatgpt-docs.err0r.top/faq/reverseapi)和[作者博客](https://ikechan8370.com/archives/da-jian-chatgpt-guan-fang-fan-xiang-dai-li)，如有其他问题可进交流群询问
