### ISSUE TITLE
添加Bing网页端的问题推荐功能

### ISSUE THREAD

**Issue by SunnyDesignor** [ikechan8370/chatgpt-plugin#244]
希望在与Bing机器人发送聊天消息时附加上Bing网页端的问题回复推荐内容。

![image](https://user-images.githubusercontent.com/50539661/224470122-3f9c5549-f9f7-451a-a4df-ec9312d093c0.png)

**Comment by ikechan8370** [comment]
已添加，锅巴里有开关，默认没开
