### ISSUE TITLE
通信异常,错误信息如下Error: Error: OpenAl error 400:

### ISSUE THREAD

**Issue by BlueSky-ZH** [ikechan8370/chatgpt-plugin#245]
**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

请在此处描述您遇到的问题，包括出现问题的环境、您试图实现的功能以及错误信息等。请尽可能详细，以便其他人可以在自己的环境中复制问题。

## 预期行为

请描述您期望系统在出现问题时应该做什么。

## 实际行为

请描述您实际看到的行为。

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。
[https://img1.imgtp.com/2023/03/11/ELPdvk9Q.jpg](url)

**Comment by BlueSky-ZH** [comment]
使用的是API3模式，其他的设置保持默认，用了代理地址

**Comment by BlueSky-ZH** [comment]
![QQ图片20230311175302](https://user-images.githubusercontent.com/98683138/224477796-3bd8bddf-2e12-44b1-8a00-43ad8695f6a1.jpg)
怎么发图片啊。尴尬

**Comment by ikechan8370** [comment]
是持续发生的吗？

**Comment by ikechan8370** [comment]
还有你的插件版本是最新的吗

**Comment by BlueSky-ZH** [comment]
插件是今天拉去了gitee上的最新版，服务器是腾讯云学生机拉取不了GitHub
使用朋友发给我的代理地址去调用API就会出现400错误，使用其他在网上搜的代理地址直接连接不上

ikechan8370 ***@***.***>于2023年3月11日 周六18:41写道：

**Comment by Err0rCM** [comment]
大概率是代理问题，请检查代理
