### ISSUE TITLE
怎么让机器人不在引用对话对象的话

### ISSUE THREAD

**Issue by heisenyu** [ikechan8370/chatgpt-plugin#246]
我想在在两个机器人对话，但是一旦对上就无休止的@起来了，怎么让其在对话时，不再引用对话对象的话，应该修改源码的那个地方，大佬帮帮忙

**Comment by heisenyu** [comment]
找到了，把chat.js中的await this.reply(`${response}`, e.isGroup)注释掉，改成await this.reply(`${response}`, false)就行了。
没接触过js，真的太难了

**Comment by ikechan8370** [comment]
以后可能吧这个提出来配置项。主要是需求不是很高
