### ISSUE TITLE
有没有大佬给支个招啊，人快要疯了！经检测，Bing Token无效。来自Bing的错误提示：Sorry, you need to login first to access this service.

### ISSUE THREAD

**Issue by izumichan6** [ikechan8370/chatgpt-plugin#247]
人要疯了，不管怎么搞都是，经检测，Bing Token无效。来自Bing的错误提示：Sorry, you need to login first to access this service.
有NewBing的资格，自己在浏览器用没问题，
手动复制_U还是代码拿token都不行，重新登陆，清除cookie，清缓存，开无痕模式，挂代理，重置网络环境，啥啥都试过了，换了三个浏览器edge，google，火狐三个浏览器都不行，重装插件不行，重装云崽也不行，不管我怎么努力他都是经检测，Bing Token无效。来自Bing的错误提示：Sorry, you need to login first to access this service.
真的已经着不住了，服了啊

0|Yunzai-Bot  | [YzBot][21:30:45.312][INFO] succeed to send: [Private(
)] [回复]Bing Token设置成功
0|Yunzai-Bot  | [YzBot][21:30:45.744][ERRO] bing token 无效 {
0|Yunzai-Bot  |   result: {
0|Yunzai-Bot  |     value: 'UnauthorizedRequest',
0|Yunzai-Bot  |     message: 'Sorry, you need to login first to access this serv
ice.'
0|Yunzai-Bot  |   }
0|Yunzai-Bot  | }
0|Yunzai-Bot  | [YzBot][21:30:45.901][INFO] succeed to send: [Private(

**Comment by ikechan8370** [comment]
建议加群问群佬

**Comment by izumichan6** [comment]
> 建议加群问群佬

没瞅见群号在哪

**Comment by kinoyoki** [comment]
求个群号到处都找不到💦

**Comment by ikechan8370** [comment]
readme
