### ISSUE TITLE
触发模式问题

### ISSUE THREAD

**Issue by Cloud-Lj** [ikechan8370/chatgpt-plugin#25]
现在只能使用@触发，不能使用#chatgpt了吗

**Comment by ikechan8370** [comment]
根据本人和所在几个群的使用体验反馈，在v2版本（现在的默认分支）只保留了@触发方式。main分支的老版本仍支持两种方式。后续看情况考虑是否在v2也支持#chatgpt并增加这两种模式的切换功能。

**Comment by Cloud-Lj** [comment]
好的，感谢大佬，我去换成main的
