### ISSUE TITLE
我这是被他封了吗，我才发五六句呜呜呜

### ISSUE THREAD

**Issue by zyj542** [ikechan8370/chatgpt-plugin#250]
![截图_20230312052338](https://user-images.githubusercontent.com/83802475/224512151-8e175d5e-b3a8-4e2e-a8f3-ad245f8cfcfb.png)

**Comment by QPass** [comment]
同，第一天收到封API的邮件，第二天网页端也封了，可能是国内IP的原因？

**Comment by zyj542** [comment]
我靠我今天也被封了



在 2023-03-12 10:51:02，"QPass" ***@***.***> 写道：

同，第一天收到封API的邮件，第二天网页端也封了，可能是国内IP的原因？

**Comment by yelinlan** [comment]
我也是
