### ISSUE TITLE
按照教程搭反代时报错

### ISSUE THREAD

**Issue by KasumiYuku** [ikechan8370/chatgpt-plugin#251]
在运行~$ docker run -d -p 5555:3000 --name node-chatgpt-proxy --shm-size=1gb geyinchi/node-chatgpt-proxy时出现了：
docker: Error response from daemon: driver failed programming external connectivity on endpoint node-chatgpt-proxy (6314dc7ca1da2ebf0cfaeaebfcd89311b8d4de0b7f4753b29f2f048ec7c265e3):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 5555 -j DNAT --to-destination 172.17.0.2:3000 ! -i docker0: iptables: Invalid argument. Run `dmesg' for more information.
 (exit status 1)).的报错是什么原因：（

**Comment by ikechan8370** [comment]
你这是docker自己的问题 映射端口的错。跟镜像没关系 不行你就试试host模式。issue关闭了
