### ISSUE TITLE
添加ChatGLM支持

### ISSUE THREAD

**Issue by Zaphkito** [ikechan8370/chatgpt-plugin#254]
单纯想添加新的支持
ChatGLM支持本地搭建运行也可自行训练，适合拿来给云崽接脑子备用啥的
对应的项目地址
https://github.com/THUDM/ChatGLM-6B

**Comment by ikechan8370** [comment]
我有时间试试

**Comment by ikechan8370** [comment]
做了一版，效果还可以。但是不能用gradio因为要支持多人对话 参考readme
