### ISSUE TITLE
newbing Sydney模式下 没有正常结束对话

### ISSUE THREAD

**Issue by Lactococcuslactis** [ikechan8370/chatgpt-plugin#256]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述
newbing Sydney模式下 一段时间不聊,然后继续对话会返回UnauthorizedRequest: Sorry, you need to login first to access this service.  这时候发送 #结束对话就可以正常聊天了
请在此处描述您遇到的问题，包括出现问题的环境、您试图实现的功能以及错误信息等。请尽可能详细，以便其他人可以在自己的环境中复制问题。

## 预期行为
回答
请描述您期望系统在出现问题时应该做什么。

## 实际行为
UnauthorizedRequest: Sorry, you need to login first to access this service. 
请描述您实际看到的行为。

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境
linux docker
请提供您使用的任何相关信息，例如操作系统、版本、配置等。

## 可能的解决方案
#217 
如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。

**Comment by ikechan8370** [comment]
本质不是这个问题，属于偶发情况。也可能是微软那边的问题。
