### ISSUE TITLE
希望能加个禁止私聊或者黑名单

### ISSUE THREAD

**Issue by TiffanyChou21** [ikechan8370/chatgpt-plugin#257]
群太多了就很容易出现一些不太好的违禁词，一个一个加进去了但还是免不了屏蔽，现在是全局都关了私聊，但是除此以外的功能还是希望可以私聊开放的

**Comment by Err0rCM** [comment]
可在锅巴中配置，具体参考[此回复](https://github.com/ikechan8370/chatgpt-plugin/issues/228#issuecomment-1493249748)
