### ISSUE TITLE
Throttled: Request is throttled.

### ISSUE THREAD

**Issue by keongmeng** [ikechan8370/chatgpt-plugin#259]
与bing对话时会出现如图报错并且比较频繁。
![image](https://user-images.githubusercontent.com/128269361/226150062-0fe38536-101c-4089-96d6-3d4d41140104.png)
![image](https://user-images.githubusercontent.com/128269361/226150078-2b477afd-3d05-49ca-bcaa-77793a3f5ab4.png)

**Comment by keongmeng** [comment]
使用的是2.2.3版本

**Comment by Err0rCM** [comment]
#206
