### ISSUE TITLE
这个是什么原因导致的啊，求解答

### ISSUE THREAD

**Issue by qiufeng0** [ikechan8370/chatgpt-plugin#262]
## 问题描述
刚刚明明还可以用的，突然就这样了，是什么情况啊，希望大佬可以帮忙解答。
## 附加信息

![QQ图片20230321003721](https://user-images.githubusercontent.com/128288699/226410341-8d57474c-f4dd-45ba-bfec-c1939ef1050a.jpg)

**Comment by ikechan8370** [comment]
疑似openai调整了API，需要进行对应适配调整了。明天会修

**Comment by qiufeng0** [comment]
噢噢，知道了，谢谢大佬。那修好了之后我们还要对其进行什么调整嘛

**Comment by Err0rCM** [comment]
已修复
