### ISSUE TITLE
每次给机器人回复时删去apology语句

### ISSUE THREAD

**Issue by chuanicefire** [ikechan8370/chatgpt-plugin#263]
每次给机器人回复时删去apology语句
即删去图中语句（看看能不能救回来）
按照我的理解，机器人回复是收到之前所有的聊天记录内容来生成回复，那能否在回复的时候删掉聊天记录中的apology语句抢救机器人
![NOQN7M2K INO @$P6MD JI5](https://user-images.githubusercontent.com/126576874/226518259-aa116c97-1011-4dde-a650-cd9d9b4a9875.png)

**Comment by ikechan8370** [comment]
希望能从逻辑上描述。比如当发生xx的时候怎么做。我现在想不出来第一句发生apology的时候该怎么做

**Comment by chuanicefire** [comment]
按照我的理解，bing在产生回复的时候，是由之前的所有聊天记录回复的，（就像图中这样）那如果在发送以往的聊天记录的时候把产生的apology删掉能否抢救（就是发送聊天记录时把划线句子删去）

**Comment by ikechan8370** [comment]
就是删掉了总要给用户反馈吧 怎么反馈呢 我感觉原样输出已经是最优雅的处理方式了

**Comment by chuanicefire** [comment]
保持原样输出，保留一个在产生apology时的抢救机会？apology发出来但不去污染给bot发的记录？（聊天记录应该是本地储存的吧）

**Comment by ikechan8370** [comment]
这个好实现 但感觉对抢救影响不大甚至可能副作用。我可以加上你试试

**Comment by chuanicefire** [comment]
加个开关先试一试吧

**Comment by heisenyu** [comment]
> 

在审核没有那么严之前，我会先读取message信息，用正则判断文本中是否包含” bing / 必应 “这种类型的文字，如果有，我就将文本替换为”抱歉，我没听清楚，您可以在讲一遍吗？“，然后再写入”cache.json“文件中，这样的话会解决悉尼认清自己的问题。但在新的审核上线后，这招好像就不太好使了。吐槽一下：新的审核真的严的有点过分了/(ㄒoㄒ)/~~

**Comment by chuanicefire** [comment]
是这样的呜呜呜……

**Comment by heisenyu** [comment]
> 希望能从逻辑上描述。比如当发生xx的时候怎么做。我现在想不出来第一句发生apology的时候该怎么做

大大，能不能加上一个备份对话的功能，其原理就是备份”cache.json“文件，防止道歉后对话丢失的问题，也可以回溯对话，体验不同的对话方式。
