### ISSUE TITLE
大佬，帮帮忙 （Error: {   "message": "Something went wrong, please try reloading the conversation.）

### ISSUE THREAD

**Issue by qiufeng0** [ikechan8370/chatgpt-plugin#264]
大佬，这是什么原因导致的啊，现在是最新版本。用翻译器翻译说是要重装对话，我重新安装了也还是这样，希望大佬帮忙解答。

![c5aa72a13d381e30484cfc9dd035bfc3](https://user-images.githubusercontent.com/128288699/226523477-54a3cedd-890f-4074-8538-302532c7f3fb.jpg)

**Comment by ikechan8370** [comment]
OpenAI服务器故障，无法载入以前的对话。你可以结束对话重开

**Comment by qiufeng0** [comment]
原来是这个意思，搞定了，谢谢大佬
