### ISSUE TITLE
[功能请求]添加识别主人功能

### ISSUE THREAD

**Issue by kinoyoki** [ikechan8370/chatgpt-plugin#268]
**你的功能请求是否与某个问题有关？请描述。**
主要功能请求：希望能添加功能让ai能分清谁才是主人（防止被NTR）（还可以让黄瓜这种对主人很好对别人疯狂输出/大嘘）

**描述你想要的解决方案**
求添加这个功能  1: 通过让主人可以无视敏感词进行对话 （可以在prompt中设置密语让ai认清谁才是真正的主人）（也更方便私聊时涩涩bushi)

2: 希望能通过给机器人使用不同的prompt来区分谁才是主人

**附加说明**
不知道这俩方案是否可行，希望佬有时间考虑下

**Comment by Sequence63** [comment]
ps:（感觉第二个方法更简单也不容易出bug)

**Comment by ikechan8370** [comment]
在Sydney和自定义模式下的群聊里实验性添加了

**Comment by Sequence63** [comment]
> 在Sydney和自定义模式下的群聊里实验性添加了

目前来看十二的表现//依旧会被轻松ntr(悲）我感觉添加屏蔽词最保险，用户没法说自己就是私聊不回~\(≧▽≦)/~
