### ISSUE TITLE
[功能请求] 双触发模式

### ISSUE THREAD

**Issue by CC-3301** [ikechan8370/chatgpt-plugin#269]
请求开发者添加@和#chat的双触发模式，大佬辛苦！

**Comment by Err0rCM** [comment]
已实现

**Comment by CC-3301** [comment]
可能是我表诉有问题？希望的双触发模式是@和#chat都能触发，目前没看到锅巴和config文件里面有相关选项呢...

**Comment by Err0rCM** [comment]
> 可能是我表诉有问题？希望的双触发模式是@和#chat都能触发，目前没看到锅巴和config文件里面有相关选项呢...

请查看[文档](https://chatgpt-docs.err0r.top/admin/chat.html#%E7%A7%81%E8%81%8A%E6%9C%BA%E5%99%A8%E4%BA%BA%E5%AF%B9%E8%AF%9D)，你可能需要的是这个，该功能不需要配置
