### ISSUE TITLE
#chatgpt闭嘴 计时模块bug

### ISSUE THREAD

**Issue by VCMellon** [ikechan8370/chatgpt-plugin#272]
## 问题描述

使用【#chatgpt闭嘴】这一指令后，没到预定时间就会提前张嘴。

## 环境

yunzai版本：3.0.1
系统版本：Ubuntu 20.04 x86_64

## 附加信息
![({ C)6)(QV$3EPOS6A2D}RN](https://user-images.githubusercontent.com/65802731/227119471-926a38d9-3b7d-4a1b-bb59-445736339837.png)

**Comment by Err0rCM** [comment]
请检查redis等是否正常，需要更多信息

**Comment by Err0rCM** [comment]
暂未复现此问题，如果还有出现请重新打开issue
