### ISSUE TITLE
能否让VITS语音变得清晰

### ISSUE THREAD

**Issue by wzq10314** [ikechan8370/chatgpt-plugin#275]
**你的功能请求是否与某个问题有关？请描述。**
能否让VITS语音变得更加清晰。

**描述你想要的解决方案**
可以添加标清模式和高清模式。

**Comment by ElaineOwO** [comment]
复议，机器人发送的音质特别渣，，

**Comment by ikechan8370** [comment]
仿照vits插件试过 高清的电脑好像听不见 我在等oicq的那个pr

**Comment by wzq10314** [comment]
> 仿照vits插件试过 高清的电脑好像听不见 我在等oicq的那个pr

感谢！对了，关于文本图片语音模式切换能否也设置成管理员才可更改，多个群内经常会出现改来改去，这一改就是全局了
