### ISSUE TITLE
快捷换自设定名

### ISSUE THREAD

**Issue by chuanicefire** [ikechan8370/chatgpt-plugin#279]
能否加入qq指令快捷换自设定中bot名称和qq指令快速开关洗脑模式和设定洗脑强度的功能？（即图中三个功能）
![`6 U4@07D2}6(HG4Z$)26TT](https://user-images.githubusercontent.com/126576874/227618035-dbf8490d-e205-4722-b02b-c4d948a978ec.png)

**Comment by ikechan8370** [comment]
已实现
