### ISSUE TITLE
非法的语音因素

### ISSUE THREAD

**Issue by niucattle** [ikechan8370/chatgpt-plugin#280]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

ffmpeg配置没错,api调用成功，huggingface调用成功，云崽的config里无论填不填ffmpeg都会报错非法的语音因素

## 预期行为

正常生成语音

## 复制过程

发#chat你好，api调用成功，huggingface生成成功，报错非法的语音因素

## 环境

windows10 64位 4核8G

## 可能的解决方案

下载安装新的ffmpeg，没用。

## 附加信息
![W_9U$T~~@~{ _H%MF K_RO](https://user-images.githubusercontent.com/118875129/227679170-c61dd60c-7dc8-4f07-810b-5bb22c22486c.png)

**Comment by niucattle** [comment]
![image](https://user-images.githubusercontent.com/118875129/227679310-1c584acc-d96d-4144-b033-baadd3512427.png)

**Comment by niucattle** [comment]
![image](https://user-images.githubusercontent.com/118875129/227680151-df5b48af-9862-4a32-823c-bd073b8ea6b9.png)

**Comment by ikechan8370** [comment]
需要支持opencore-amr 自行搜索
