### ISSUE TITLE
合成语音发生错误

### ISSUE THREAD

**Issue by ZASENJC** [ikechan8370/chatgpt-plugin#285]
## 问题描述

合成语音发生错误，wav转amr出错，尝试FFmpeg命令行转码是正常的，求大佬解答是什么原因

## 附加信息

![11](https://user-images.githubusercontent.com/65362072/227725142-25e831e4-ccba-4dcf-8648-70a9689b2ceb.png)

![12](https://user-images.githubusercontent.com/65362072/227725148-64f35165-4723-43df-8d06-4e83bf9a85d5.png)

**Comment by ZASENJC** [comment]
有没有可能是采样率的问题呢

**Comment by sk856** [comment]
你看看机器人的ffmpeg路径填好了吗

**Comment by Err0rCM** [comment]
回复时间过长，如仍有问题请重开issue
