### ISSUE TITLE
更新后启动报错 删了重下和更新都试了

### ISSUE THREAD

**Issue by zwy321** [ikechan8370/chatgpt-plugin#29]
chatgpt插件已加载
0|Yunzai-Bot  | Can't load MathJax.js from file:///D:/工具/bot/Yunzai-Bot/node_modules/.pnpm/mathjax@2.7.9/node_modules/mathjax/unpacked/MathJax.js
0|Yunzai-Bot  | Error: Could not load script: "file:///D:/%E5%B7%A5%E5%85%B7/bot/Yunzai-Bot/node_modules/.pnpm/mathjax@2.7.9/node_modules/mathjax/unpacked/MathJax.js"
0|Yunzai-Bot  |     at D:\工具\bot\Yunzai-Bot\node_modules\.pnpm\jsdom@11.12.0\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:44:23
0|Yunzai-Bot  |     at Object.check (D:\工具\bot\Yunzai-Bot\node_modules\.pnpm\jsdom@11.12.0\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:76:11)
0|Yunzai-Bot  |     at ReadStream.<anonymous> (D:\工具\bot\Yunzai-Bot\node_modules\.pnpm\jsdom@11.12.0\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:95:12)
0|Yunzai-Bot  |     at ReadStream.wrappedEnqueued (D:\工具\bot\Yunzai-Bot\node_modules\.pnpm\jsdom@11.12.0\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:253:16)
0|Yunzai-Bot  |     at ReadStream.emit (node:events:513:28)
0|Yunzai-Bot  |     at emitErrorNT (node:internal/streams/destroy:151:8)
0|Yunzai-Bot  |     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
0|Yunzai-Bot  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) [Error: ENOENT: no such file or directory, open 'D:\%E5%B7%A5%E5%85%B7\bot\Yunzai-Bot\node_modules\.pnpm\mathjax@2.7.9\node_modules\mathjax\unpacked\MathJax.js'] {
0|Yunzai-Bot  |   errno: -4058,
0|Yunzai-Bot  |   code: 'ENOENT',
0|Yunzai-Bot  |   syscall: 'open',
0|Yunzai-Bot  |   path: 'D:\\%E5%B7%A5%E5%85%B7\\bot\\Yunzai-Bot\\node_modules\\.pnpm\\mathjax@2.7.9\\node_modules\\mathjax\\unpacked\\MathJax.js'

发送信息提示
OpenAI认证失败，请检查Token：Error: ChatGPT failed to refresh auth token. Error: 403 Forbidden
重新获取token没有用

**Comment by YujioNako** [comment]
似乎不是因为更新产生的问题，老版本也会有相同报错。怀疑是OpenAI接口的问题。

**Comment by xingranya** [comment]
![}1O PO`QGE5U0$C`@@DSG)V](https://user-images.githubusercontent.com/71560643/206938944-8fd464a9-3550-4949-ae21-c48d0b1ccdf4.png)
想知道我这种是什么情况，试过卸载重装，都不行，明明有这个文件啊

**Comment by L1uTongwei** [comment]
@ldcivan 我也出问题了

**Comment by Ansellyu** [comment]
我今天一样，应该是api的问题，403 Forbidden，没有权限访问此网站

**Comment by jkevinking** [comment]
我也出现这个问题了
]OpenAI认证失败，请检查Token：Error: ChatGPT failed to refresh auth token. Error: 403 Forbidden

**Comment by ikechan8370** [comment]
#30
