### ISSUE TITLE
Error with OpenAI API request: connect ETIMEDOUT xxx

### ISSUE THREAD

**Issue by imelonkid** [ikechan8370/chatgpt-plugin#290]
使用官方demo通过nodejs访问openAi提升上面异常
<img width="611" alt="image" src="https://user-images.githubusercontent.com/88540395/227837248-b1b9b5cd-db64-4806-97ec-bf50d1021390.png">

怎么解决呢？

备注：使用了VPN代理

**Comment by ikechan8370** [comment]
与本项目无关

**Comment by 41612196** [comment]
请问如何在代码里配置代理呢？

**Comment by JiaLinYou** [comment]
请问你解决了嘛？通过服务器代理的方式是否可行呢？
