### ISSUE TITLE
能不能写个管理员权限更改自己私人对话设定的功能

### ISSUE THREAD

**Issue by Diskanden** [ikechan8370/chatgpt-plugin#292]
设定每次都是全局的，我想用一个设定而其他的群友想用另外一个设定这种情况就很尴尬，能不能给一些人管理员权限让他们能更改他们自己对话的设定而不是全局设定

**Comment by 2ndelement** [comment]
建议设定独立用户化，只有我能玩，群友没法玩![-863e6458ba35859.gif](https://user-images.githubusercontent.com/72551339/228422154-29a6ed46-7c29-40e8-84fb-aa98781b7ca5.gif)

**Comment by ikechan8370** [comment]
会有的
