### ISSUE TITLE
api模式回复较长信息时出现通信错误

### ISSUE THREAD

**Issue by keongmeng** [ikechan8370/chatgpt-plugin#295]
![image](https://user-images.githubusercontent.com/128269361/228399007-0b8501f6-786c-442b-9495-672a15bb4a5e.png)
![image](https://user-images.githubusercontent.com/128269361/228399043-c9318ccb-793b-4cad-b2de-dedeecbcc4ad.png)

**Comment by keongmeng** [comment]
这是后台报错
![image](https://user-images.githubusercontent.com/128269361/228399351-73b62cbb-bbfd-48f2-a8eb-2e6b7e659e2e.png)

**Comment by Err0rCM** [comment]
图中报错最好能截到上下文，如能复现问题请重开issue
