### ISSUE TITLE
提示TypeError: Invalid argument type错误，机器人发送请稍等撤回后就没反应了

### ISSUE THREAD

**Issue by youbai520** [ikechan8370/chatgpt-plugin#296]
![Screenshot_2023-03-29-18-00-12-750_com sonelli juicessh-edit](https://user-images.githubusercontent.com/75999675/228500476-ceeb4c9d-5922-47eb-b6c6-04ffee3c763c.jpg)
提示这个错误
node版本18.14
系统Ubuntu 20.04

**Comment by Err0rCM** [comment]
如还能复现请重新打开issue
