### ISSUE TITLE
请教大佬们，TypeError:Config.blockWords.find is not a function咋回事啊？

### ISSUE THREAD

**Issue by 976863929** [ikechan8370/chatgpt-plugin#298]
![image](https://user-images.githubusercontent.com/44665525/228994179-5fa4d00e-2696-41e1-be6e-371222101799.png)
如图报错，请假大佬们是怎么回事啊？该咋处理啊？

**Comment by Err0rCM** [comment]
请仔细阅读issue模板并请提供更多信息，如有问题请重新打开issue
