### ISSUE TITLE
关于代码等输出不全、无法联系上下文等问题

### ISSUE THREAD

**Issue by ikechan8370** [ikechan8370/chatgpt-plugin#3]
发现有时让bot写代码会出现输出不全、不能理解上下文语境等情况，起初以为是qq官方的字数限制，后来发现是ooenai官方api的特性，单次输出不完整时，可通过Continue指令让ai继续接着上一句说。
但由于chatgpt模型发布时间较短，各个第三方api库明显存在一些不完善之处，比如本项目使用的nodejs库chatgpt-api对conversation的支持就不够好，导致官网支持的Continue指令在这里无法识别。
目前看到上游已有多位大佬指出该问题并进行了修改和pr，待作者确认合并后这边将第一时间跟进更新。

**Comment by hyhAsma** [comment]
支持一波，等更新~

**Comment by kanoha222** [comment]
支持

**Comment by lateautumn233** [comment]
> 发现有时让bot写代码会出现输出不全、不能理解上下文语境等情况，起初以为是qq官方的字数限制，后来发现是ooenai官方api的特性，单次输出不完整时，可通过Continue指令让ai继续接着上一句说。 但由于chatgpt模型发布时间较短，各个第三方api库明显存在一些不完善之处，比如本项目使用的nodejs库chatgpt-api对conversation的支持就不够好，导致官网支持的Continue指令在这里无法识别。 目前看到上游已有多位大佬指出该问题并进行了修改和pr，待作者确认合并后这边将第一时间跟进更新。

让ai自己修(
