### ISSUE TITLE
目前来看，ChatGPT 添加了 Cloudflare 认证

### ISSUE THREAD

**Issue by AiYuuki** [ikechan8370/chatgpt-plugin#30]
https://github.com/transitive-bullshit/chatgpt-api/issues/96
 
按照目前社区讨论，需要bot和登录设备于同一个 IP 地址下
 
![}4E7N5G5ONRB}GEOJK4{~0X](https://user-images.githubusercontent.com/28827378/206945892-5695dff4-2180-415b-aef0-cc60e900d37b.jpg)

**Comment by xingranya** [comment]
以后该怎么办呢

**Comment by ikechan8370** [comment]
这些库的作者们正在寻找解决办法，暂时只能按照作者给出的这个方法来了，我先测试一下是否可行

**Comment by lee-chard** [comment]
> 这些库的作者们正在寻找解决办法，暂时只能按照作者给出的这个方法来了，我先测试一下是否可行

怎么样，那对于我这种用轻量服务器的不就寄了

**Comment by ikechan8370** [comment]
![6f3f7bfcf05475bd25253ca1c1527188](https://user-images.githubusercontent.com/21212372/206959959-32af37c1-3079-4cbb-a487-57427e36f3a2.jpg)
试了一下本地使用代理登录获取对应两个token，服务器也配置clash tun模式代理使用相同ip，使用相同的UA，能够突破该限制。现在要做的就是实现token刷新的自动化了，一边等等上游，我这边也试试结合Yunzai现有的puppeteer浏览器实现外部更新的机制。

**Comment by ikechan8370** [comment]
![9c65c0f58470b2642cbe3c5ad7c21ded](https://user-images.githubusercontent.com/21212372/206962106-096e1de2-c8a6-49b7-9afa-96f256e7c9bd.jpg)
哈哈笑死

**Comment by habacat** [comment]
插眼，等等后续解决方案

**Comment by ikashana** [comment]
等后续解决方案_(:з)∠)_

**Comment by hyhAsma** [comment]
插眼等大佬解决方案（笔芯）

**Comment by akmioto** [comment]
插眼等大佬解决方案（笔芯）

**Comment by lee-chard** [comment]
作者更新了

**Comment by L1uTongwei** [comment]
> 作者更新了

现在可以用了没

**Comment by ikechan8370** [comment]
> 作者更新了

没看到更新啊？

**Comment by ikashana** [comment]
类似这种的使用官方API的方式是不是可行？https://github.com/easydu2002/chat_gpt_oicq/tree/dev-official

**Comment by jiut** [comment]
实测，使用这个api可行https://api.openai.com/v1/completions

**Comment by L1uTongwei** [comment]
@ikechan8370

**Comment by RyanJiang184** [comment]
@jiut 官方不是还没开放chatgpt API吗？能否请教一下

**Comment by ikechan8370** [comment]
下午肝了一版autologin分支，但苦于总遇到hCaptcha验证码，Cloudflare防的太狠了。只好增加了验证码插件，但都是付费的。我看上游api库也都是只能这么做，解决方案大同小异。由于不稳定且需要代理，暂时只用于测试，有兴趣的可以去试试。
（新冠了精神不佳先休息了，明天有精神再看看其他人怎么搞的）
还有官方API都不是和chatgpt一模一样的模型，不然谁会去用unofficial呢。

**Comment by L1uTongwei** [comment]
加油啊！

**Comment by RyanJiang184** [comment]
大佬新冠注意休息

**Comment by xfyNB** [comment]
没太看明白那个库的作者的解决方案应该怎么使用 : ( 能不能简单讲解一下，最起码我能先让它跑起来

**Comment by ikechan8370** [comment]
> 没太看明白那个库的作者的解决方案应该怎么使用 : ( 能不能简单讲解一下，最起码我能先让它跑起来

原理很简单。就是起一个无头浏览器模拟登录更新session和token。我一会用他的方案更新一下。但他的方案我这是通不过的，因为遇到有各种各样的反机器人验证码，而且每次都遇到三四个根本没法弄，必须配合手动去一个个解决。OpenAI真的是被逼急了。按照原作者的意见能够尽量减少出现验证码的频率但也不保准。比较理想的方式是部署在有图形界面的机器上，这样出了验证码还能手动点一点。

**Comment by ikechan8370** [comment]
![image](https://user-images.githubusercontent.com/21212372/207231045-70ea2f18-edba-4f73-b5b5-d438a7f48306.png)
OpenAI好像压力真的很大。代码写完都没法测试了

**Comment by ikechan8370** [comment]
OpenAI貌似还在不断增加验证码。晚上再看看吧。

**Comment by xfyNB** [comment]
> ![image](https://user-images.githubusercontent.com/21212372/207231045-70ea2f18-edba-4f73-b5b5-d438a7f48306.png) OpenAI好像压力真的很大。代码写完都没法测试了

我其实不介意官方出一个付费的API......价格合理我肯定会用的

**Comment by habacat** [comment]
昨天经常ai说着说着就显示红色感叹号了。官网也再说正在扩大服务能力。
话说，各位有没有免费的ai画图api？（本地没法搭）

**Comment by jiut** [comment]
> @jiut 官方不是还没开放chatgpt API吗？能否请教一下

我这个是在土块插件群里获得的脚本，目前还是在机器人上可用的。
https://www.nahida.vip/235/

**Comment by RyanJiang184** [comment]
> 我这个是在土块插件群里获得的脚本，目前还是在机器人上可用的。 https://www.nahida.vip/235/

去看了一下，chatgpt也是寄的，那个不一样。

**Comment by ikechan8370** [comment]
v2尝试使用api库作者的方法进行认证，但是问题仍然很多。
1. 必须使用本地chrome且不能无头模式，除非你确信你不会遇到任何验证码。这样用云端linux小机器搭建就不行了。
2. UA、ip和token都相同的情况下仍会遇到403，似乎相比昨天又增加了新的限制，等大佬探索。
3. 官网时不时崩或拒绝服务。

**Comment by ikechan8370** [comment]
高烧顶不住了🙏 有大佬愿意出手的欢迎提出见解或者pr

**Comment by habacat** [comment]
> 高烧顶不住了🙏 有大佬愿意出手的欢迎提出见解或者pr

大佬好好休息
