### ISSUE TITLE
关于打开读取聊天记录后Bing会出现重复@人和重复表情的问题

### ISSUE THREAD

**Issue by wzq10314** [ikechan8370/chatgpt-plugin#300]
开启读取聊天记录后使用#结束对话，#结束全部对话等命令，再次与Bing聊天，它回复时会重复@，结束对话几次就会重复@几次，并且如果让他使用qq表情，他也会重复发送多个相同的。除了关闭读取聊天记录外好像没找到解决办法，切换模式后在切回来也无效

**Comment by wzq10314** [comment]
问题如上

**Comment by ikechan8370** [comment]
免责声明：AI个人行为与插件无关
