### ISSUE TITLE
设置必应token失败

### ISSUE THREAD

**Issue by skepsun** [ikechan8370/chatgpt-plugin#301]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

刚git clone并安装的最新版本，使用#chatgpt设置必应token指令，返回请发送xxx之后，发送_U cookie无反应，后台报了一大堆错误，开头如下：
0|Yunzai-Bot  | TypeError: Cannot read properties of null (reading 'split')
0|Yunzai-Bot  |     at ChatgptManagement.saveBingToken (file:///root/Yunzai-Bot/plugins/chatgpt-plugin/apps/management.js:195:27)
0|Yunzai-Bot  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|Yunzai-Bot  | [YzBot][15:57:45.799][ERRO] TypeError: Cannot read properties of null (reading 'split')

## 预期行为

请描述您期望系统在出现问题时应该做什么。

## 实际行为

请描述您实际看到的行为。

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。

**Comment by d13187** [comment]
一样，我也是这样，不知怎么处理

**Comment by HalcyonAlcedo** [comment]
这存在于首次设置bingtoken的情况下，已知错误原因，一会修复
