### ISSUE TITLE
每次重启云崽bot都要重新扫码

### ISSUE THREAD

**Issue by 715494637** [ikechan8370/chatgpt-plugin#302]
每次node app登录或者重新启动bot都得重新扫码

![QQ图片20230331173807](https://user-images.githubusercontent.com/93782833/229085519-f004f93d-defe-452b-a8a8-acb09d9ea366.png)

**Comment by TsukinaKasumi** [comment]
换成icqq使用密码登录

**Comment by ikechan8370** [comment]
非插件问题，自行解决或加群问
