### ISSUE TITLE
bing模式下@模式下未屏蔽bot的群名片

### ISSUE THREAD

**Issue by liuzj288** [ikechan8370/chatgpt-plugin#307]
![image](https://user-images.githubusercontent.com/13833404/229355123-7666662e-da04-434d-999d-eabe7b15b692.png)

**Comment by ikechan8370** [comment]
已知问题，应该是群名片和昵称混淆的问题。好友群里at显示的好像是昵称，麻了。抽时间优化

**Comment by Err0rCM** [comment]
问题补充，目前仍能复现问题
情况一：

![image](https://user-images.githubusercontent.com/68117733/234348471-b265625f-52b0-4eca-8a7e-afd33b1c5951.png)
直接回复，不删除默认的那个@，无论在前在后写信息均无问题。

一旦删掉了默认回复的那个@，手动进行@就会出错

![image](https://user-images.githubusercontent.com/68117733/234348869-564e1d56-e195-4bf7-9fe5-01b2123ad6ee.png)

---

情况二：回复某条信息，直接@机器人，会把自己的名片送入会话

![image](https://user-images.githubusercontent.com/68117733/234349587-2f05e68a-22e0-4a91-ac62-939f945908b2.png)


![image](https://user-images.githubusercontent.com/68117733/234349664-6ca0d5c8-e259-4870-a234-224024fd8e76.png)
