### ISSUE TITLE
请问代理是获取哪里的代理啊

### ISSUE THREAD

**Issue by yuanpeiyang** [ikechan8370/chatgpt-plugin#308]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

请在此处描述您遇到的问题，包括出现问题的环境、您试图实现的功能以及错误信息等。请尽可能详细，以便其他人可以在自己的环境中复制问题。

## 预期行为

请描述您期望系统在出现问题时应该做什么。

## 实际行为

请描述您实际看到的行为。

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。

**Comment by yuanpeiyang** [comment]
大佬，我没找到是获取的哪里的代理（呜呜呜）

**Comment by ikechan8370** [comment]
哪里要求你用代理了？

**Comment by yuanpeiyang** [comment]
> 哪里要求你用代理了？

不是要在“plugins/chatgpt-plugin/config/config.json”给“proxy”配置代理吗，还有gpt的”key“

**Comment by TsukinaKasumi** [comment]
> 代理可以不用配置 key和反代地址配好就行了

**Comment by ikechan8370** [comment]
可能的话 最好用锅巴配置。proxy不是必填项，甚至apiKey也不是。

**Comment by yuanpeiyang** [comment]
> 可能的话 最好用锅巴配置。proxy不是必填项，甚至apiKey也不是。

好的，下了个锅巴插件，还是这个设置方便
