### ISSUE TITLE
关于SessionToken过期问题

### ISSUE THREAD

**Issue by wearshoes** [ikechan8370/chatgpt-plugin#31]
是否可以通过chatgpt-api提供的refreshAccessToken重新获取accessToken解决令牌过期的问题呢？

**Comment by ikechan8370** [comment]
ensureAuth方法中已经调用了该函数。目前OpenAI的策略是refreshToken很快就过期，此时你去官网也要重新登录。唯一解决方案就是实现自动的表单登录，等待上游大佬实现中。结合此次CF事件，看来是迫在眉睫了。如果他不做我也会做的。

**Comment by habacat** [comment]
插眼，等等诸位大佬出方案

**Comment by wufeng15226** [comment]
+1

**Comment by wearshoes** [comment]
OK 那就等待大佬们出手了
