### ISSUE TITLE
最新版本必应无法响应问题

### ISSUE THREAD

**Issue by norname-shine** [ikechan8370/chatgpt-plugin#311]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

请在此处描述您遇到的问题，包括出现问题的环境、您试图实现的功能以及错误信息等。请尽可能详细，以便其他人可以在自己的环境中复制问题。

## 预期行为

请描述您期望系统在出现问题时应该做什么。

## 实际行为

请描述您实际看到的行为。

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。

**Comment by norname-shine** [comment]
![image](https://user-images.githubusercontent.com/30834747/229500333-4148162c-aba9-4d9d-9656-76b3c47a9121.png)
报错如上。
![image](https://user-images.githubusercontent.com/30834747/229500620-c44e8892-7608-485a-a42d-e891a2bb1aae.png)
she回复的字段提示错误是:failed to parse response body.

**Comment by ghost** [comment]
代理挂上了吗😙

**Comment by TsukinaKasumi** [comment]
可以发送#结束对话重新试一次，可能是重定向到cn.bing导致创建对话失败了

**Comment by norname-shine** [comment]
> 可以发送#结束对话重新试一次，可能是重定向到cn.bing导致创建对话失败了

看来确实是的，我挂了全局代理就能用了
