### ISSUE TITLE
群员随便发的emoji机器人会回复`不支持合成`

### ISSUE THREAD

**Issue by NoroHime** [ikechan8370/chatgpt-plugin#313]
## 问题描述

群员随便发的emoji机器人会回复`不支持合成`

## 预期行为

并没有提及到机器人，不应对此做出回应

## 实际行为

![image](https://user-images.githubusercontent.com/25362335/229775199-26441435-a852-4941-b7af-4bcaa1a85c4a.png)

**Comment by 303251669** [comment]
有个缓兵之计可以让它不发出来不支持合成，进到云崽的Yunzai-Bot/plugins/chatgpt-plugin/apps这个文件夹，用记事本打开entertainment.js，然后大概在72行的样子找到这行代码await e.reply('不支持合成', true)，在它前面加上//，注释掉，就不会触发了，坏处就是你合成表情的时候，有些表情不支持合成你就收不到它的提示了。
