### ISSUE TITLE
使用 api模式 和api3模式的时候遇到了这两个问题 lnvalid url 与返回一些html标签

### ISSUE THREAD

**Issue by AltinaNissan** [ikechan8370/chatgpt-plugin#314]
![image](https://user-images.githubusercontent.com/107377630/229990703-07708be5-eee8-41c4-8ecb-c3878969226d.png)
这个是api3模式 
![b2d71ad0a7b447be8b3a7f91c8191861](https://user-images.githubusercontent.com/107377630/229990740-82f71dd1-bfbd-4646-99d8-7a7dbc66bdd9.jpg)
这个是api模式

**Comment by ikechan8370** [comment]
前者是上午Cloudflare的bug 已经修复。
后者信息不足无法确定原因

**Comment by AltinaNissan** [comment]
好的 非常感谢您的回复
