### ISSUE TITLE
Forbidden: Sorry, you are not allowed to access this service.bing绑定token后使用悉尼，自设定模式会出现这个，其他模式使用正常

### ISSUE THREAD

**Issue by 631481119** [ikechan8370/chatgpt-plugin#316]
这是截图
![PE93%R0IY4945B9455(5K A](https://user-images.githubusercontent.com/40414840/230289163-3ebb5728-cad8-4fa2-9721-b54c863ccfe3.png)
![`1( H_H@ 1R6X`A8`J9N~2K](https://user-images.githubusercontent.com/40414840/230289172-345aba96-5d5e-441d-a27b-e9df74277f1d.png)
已经在锅巴后台开启了bing强制反代

**Comment by 631481119** [comment]
![L9DY1ZY7A}I@@%Y@(AZDV22](https://user-images.githubusercontent.com/40414840/230289478-d631f4cb-2bbd-42ca-a87a-9bf539fd4fcc.png)
这是后台的报错

**Comment by Err0rCM** [comment]
原因可能有很多，如果可以的话请提供复现过程或者更换反代再试
