### ISSUE TITLE
最新版本日志问题

### ISSUE THREAD

**Issue by fatebugs** [ikechan8370/chatgpt-plugin#319]
不清楚是否是API3的问题，每次提问会将所有日志打印
![image](https://user-images.githubusercontent.com/65278566/230526509-95236d9c-72cf-4d0c-91a8-463a32e22f88.png)

**Comment by Err0rCM** [comment]
如果不需要的话可以[参照](https://chatgpt-docs.err0r.top/guide/config.html#%E9%85%8D%E7%BD%AE%E4%BF%A1%E6%81%AF)在配置项debug设置为false，或者在锅巴面板进行配置

**Comment by Qz-Sean** [comment]
> 如果不需要的话可以[参照](https://chatgpt-docs.err0r.top/guide/config.html#%E9%85%8D%E7%BD%AE%E4%BF%A1%E6%81%AF)在配置项 debug 设置为 false，或者在锅巴面板进行配置

好快🤣🤣，刚在群里看到你就已经回复了
