### ISSUE TITLE
关于能否添加proxy服务器的设置

### ISSUE THREAD

**Issue by ryousora** [ikechan8370/chatgpt-plugin#32]
![J PIM1Y9U504}R@8UUGIJT](https://user-images.githubusercontent.com/45556761/206991787-682fdede-18c2-441f-b929-cf1ebdf34fa1.png)
在ChatGPTAPI中没有发现代理服务器的相关参数设置

![TU~2TQ1(C5937Q0TPFOO@~P](https://user-images.githubusercontent.com/45556761/206992021-433c0db1-abd1-4d6d-96a1-95a15a29e2e1.png)
包里面手动加了代理设置也没有效果

开全局代理能用但是又会影响到其他模块的功能
能否有办法添加一个proxy的单独设置

**Comment by ikechan8370** [comment]
该库目前不支持proxy，已有issue在讨论，估计快了。
https://github.com/transitive-bullshit/chatgpt-api/issues/47
