### ISSUE TITLE
文字模式链接无法发送，报empty message

### ISSUE THREAD

**Issue by Chocolatemocha** [ikechan8370/chatgpt-plugin#320]
阿里云windows，插件在4月7日更新后，不开预览模式（锅巴面板也关闭了），还是使用传统的文字+转发链接消息模式（开了文字过长转图片），转发的链接都是empty message错误图，转发的链接消息都发不出来，4月7日前版本能正常发送；
试过换设定/重启都不行，只要文字模式，带链接百分百会触发；
4月7日下午更新版本后还是相同的错误，日志：

![D9__Q4K%9}}(YA05NV%}S8E](https://user-images.githubusercontent.com/42531322/230575293-962ee4eb-de2b-4f65-9aa6-f3a5942ae870.png)

![image](https://user-images.githubusercontent.com/42531322/230568969-0da1ece3-edfd-4c74-b9d8-85337b874d79.png)

**Comment by HalcyonAlcedo** [comment]
图片模式还会触发吗

**Comment by Chocolatemocha** [comment]
> 图片模式还会触发吗

1.直接传统模式-图片，不会触发；2.锅巴面板不开【全局图片】，仅开启【预览版本】，只触发过一次（报错也是api...-60，日志无报错，第二次之后好了。

**Comment by HalcyonAlcedo** [comment]
已经确认问题，修复已经提交等待合并
