### ISSUE TITLE
预览版图片模式的默认渲染服务器无法生成图片

### ISSUE THREAD

**Issue by Qz-Sean** [ikechan8370/chatgpt-plugin#322]
## 问题描述

预览版图片模式的默认渲染服务器可以正常渲染网页，但是无法通过puppeteer生成图片。其他插件的图片可正常通过puppeteer生成。

## 错误信息
![image](https://user-images.githubusercontent.com/56262913/230582226-15a6bc80-074d-476c-b5d7-b64825022d33.png)
![image](https://user-images.githubusercontent.com/56262913/230582271-29ade3be-9bc5-4686-b4e1-fa5758c975eb.png)
通过链接可以正常访问：
![image](https://user-images.githubusercontent.com/56262913/230583263-95fb1549-09ed-4b5e-8da4-c5ae912ddcae.png)
通过注释puppeteer.js的如下代码后得到以下输出：
![image](https://user-images.githubusercontent.com/56262913/230582554-e701432e-3595-42e4-8783-5f5a501e560b.png)
![image](https://user-images.githubusercontent.com/56262913/230582661-7fee283a-a0d7-4e89-9e2b-094dc4f1d7a2.png)
但最后仍无法生成图片：
![image](https://user-images.githubusercontent.com/56262913/230582847-ccbef526-063a-440b-b866-b31c073a6242.png)

## 环境
Windows 11
Chromium 112.0.5614.0 - Puppeteer v19.8.0 （之前使用最新的Chromium 和Puppeteer 版本也无法生成图片）
## 备注
群名片：ECHO - Elite Creative Hub Organizer

**Comment by HalcyonAlcedo** [comment]
这几次更新后还有问题吗，群里联系不上你

**Comment by Qz-Sean** [comment]
> 这几次更新后还有问题吗，群里联系不上你

![image](https://user-images.githubusercontent.com/56262913/230734210-b40bf865-853b-48cc-93ad-306d775c62c7.png)
还是不行诶🤕

**Comment by HalcyonAlcedo** [comment]
可以的话，把你的config给我，我部署一个跟你一样的环境试一下，还不行我就真没办法了，无法复现你的问题

**Comment by Qz-Sean** [comment]
> 可以的话，把你的 config 给我，我部署一个跟你一样的环境试一下，还不行我就真没办法了，无法复现你的问题
```json
{
  "defaultUseTTS": true,
  "defaultTTSRole": "",
  "alsoSendText": true,
  "ttsAutoFallbackThreshold": 200,
  "apiKey": "",
  "openAiBaseUrl": "https://openai-api.ikechan8370.com/v1",
  "openAiForceUseReverse": true,
  "toneStyle": "Custom",
  "sydney": "",
  "sydneyReverseProxy": "https://bing.ikechan8370.com",
  "sydneyForceUseReverse": true,
  "sydneyBrainWashName": "",
  "api": "https://chatgpt.ikechan8370.com/backend-api/conversation",
  "apiBaseUrl": "https://chatgpt.ikechan8370.com/backend-api",
  "apiForceUseReverse": true,
  "promptPrefixOverride": "",
  "assistantLabel": "",
  "chromePath": "D:\\Miao-Yunzai\\chrome-win\\chrome.exe",
  "debug": false,
  "sydneyFirstMessageTimeout": 60000,
  "ttsSpace": "http://127.0.0.1:7860",
  "noiseScaleW": 0.53,
  "initiativeChatGroups": [],
  "helloPrompt": "",
  "helloInterval": 2,
  "enableGroupContext": true,
  "groupContextLength": 100,
  "serverPort": 3322,
  "chatViewWidth": 600
}
```
**相关的环境是：Node V18.15.0、Chromium 112.0.5614.0、Puppeteer v19.8.0、Redis-x64-5.0.14.1、Win11 22H2**

**Comment by HalcyonAlcedo** [comment]
今天给另一个同样问题的人解决了，原因是Chromium 内存溢出，换成edge解决，你可以试下

**Comment by xinzhu666** [comment]
> ## 问题描述
> 预览版图片模式的默认渲染服务器可以正常渲染网页，但是无法通过puppeteer生成图片。其他插件的图片可正常通过puppeteer生成。
> 
我也是，唉，其他插件是可以生成图片的，chatgpt插件很短的回复都会图片生成失败，但是访问链接却可以查看图片。
系统配置肯定是足够的，Bot才占用300M的运存，Chrome渲染图片2%的CPU
