### ISSUE TITLE
bing token 长度小于 215 无法录入 token 数据

### ISSUE THREAD

**Issue by QaQ-top** [ikechan8370/chatgpt-plugin#325]
![image](https://user-images.githubusercontent.com/53463795/230706420-cf34d9a9-971b-453a-811d-0f955c30cf64.png)

![image](https://user-images.githubusercontent.com/53463795/230706413-e8e0f9b8-5acb-4378-a3af-032b87512caf.png)

![image](https://user-images.githubusercontent.com/53463795/230706438-8ef4e1f8-bb00-4e2c-8780-f2597157d80a.png)

![image](https://user-images.githubusercontent.com/53463795/230707387-8be70c2b-0a19-47bf-8ee3-428ba53a0eee.png)

重新登陆了几次都无法成功录入，都被这个条件限制了，这个条件是必须的吗？

**Comment by QaQ-top** [comment]
![image](https://user-images.githubusercontent.com/53463795/230706870-c4729f15-09c3-44b0-85c3-23e5a46d668e.png)
目前来看我这边一直都是 193，去掉这个限制会对程序造成什么影响吗？

**Comment by ikechan8370** [comment]
第一次见你这个问题 确定登录了嘛？首页右上角怎么没看到用户名和rewards

**Comment by QaQ-top** [comment]
> 第一次见你这个问题 确定登录了吗？首页右上角怎么没看到用户名和奖励

![image](https://user-images.githubusercontent.com/53463795/230707748-b0855468-dc49-4d30-bf8c-b9a883a2d404.png)

有登录的

**Comment by ikechan8370** [comment]
那你试试删掉那行限制的代码 看看是否真的能用

**Comment by QaQ-top** [comment]
> 那你试试删掉那行限制的代码 看看是否真的能用

![image](https://user-images.githubusercontent.com/53463795/230708558-4cc93c36-d7ef-4ac8-a915-9d1070e12f41.png)

![image](https://user-images.githubusercontent.com/53463795/230708403-1cf44dbb-1b19-459d-8ca9-1ca151f353d4.png)

![I@R%6BGU4K3C` 3~VUAXX9G](https://user-images.githubusercontent.com/53463795/230708392-181e819f-542a-4ca4-8b0d-40ba29c095cb.png)

是可以的，我这边 token 可能是短于 215 的

**Comment by ikechan8370** [comment]
了解了，看来这个token还不是固定的，之前两个月见到的都是215位，我改掉那个吧

**Comment by Err0rCM** [comment]
两月前token是固定的，微软可能改了设定

**Comment by Err0rCM** [comment]
fixed #340
