### ISSUE TITLE
是否考虑写一个群员自定义设定的功能

### ISSUE THREAD

**Issue by Diskanden** [ikechan8370/chatgpt-plugin#326]
群友可以用自定义设定指令设定只对自己生效的设定 不保存在prompts里

**Comment by hanhan258** [comment]
可以将prompt清空，然后把需要的设定以文字形式发给Bot，这样就可以实现每个人的设定不一样了，群友不发设定，就用默认为空的

**Comment by Diskanden** [comment]
> 可以将prompt清空，然后把需要的设定以文字形式发给Bot，这样就可以实现每个人的设定不一样了，群友不发设定，就用默认为空的

但是这样会抱歉诶，比直接导入效果差好多啊

**Comment by Diskanden** [comment]
> 可以将prompt清空，然后把需要的设定以文字形式发给Bot，这样就可以实现每个人的设定不一样了，群友不发设定，就用默认为空的

这样会抱歉，而且效果比较差，不如prompt导入好
