### ISSUE TITLE
语音无法发送的问题

### ISSUE THREAD

**Issue by dyt1993** [ikechan8370/chatgpt-plugin#327]
0|Yunzai-Bot  | [YzBot][00:08:17.186][WARN] vits api 当前为https://XXX/api/generate，已校正为https://XXX.space
0|Yunzai-Bot  | [YzBot][00:08:17.186][INFO] 正在使用接口https://XXX/api/generate
0|Yunzai-Bot  | [YzBot][00:08:29.508][INFO] {
0|Yunzai-Bot  |   data: [
0|Yunzai-Bot  |     '生成成功!',
0|Yunzai-Bot  |     {
0|Yunzai-Bot  |       name: '/tmp/tmpfpuygu64/tmpgxtsv9de.wav',
0|Yunzai-Bot  |       data: null,
0|Yunzai-Bot  |       is_file: true
0|Yunzai-Bot  |     },
0|Yunzai-Bot  |     '生成耗时 11.65 s'
0|Yunzai-Bot  |   ],
0|Yunzai-Bot  |   is_generating: false,
0|Yunzai-Bot  |   duration: 11.650573968887329,
0|Yunzai-Bot  |   average_duration: 9.59550944964091
0|Yunzai-Bot  | }
0|Yunzai-Bot  | [YzBot][00:08:29.508][INFO] 生成成功! 生成耗时 11.65 s
0|Yunzai-Bot  | [YzBot][00:08:31.586][ERRO] 发送消息错误:{"type":"record","file":"https://XXX.hf.space/file=/tmp/tmpfpuygu64/tmpgxtsv9de.wav"}
0|Yunzai-Bot  | [YzBot][00:08:31.586][ERRO] ApiRejection { code: -60, message: '音频转码到amr失败，请确认你的ffmpeg可以处理此转换' }

~/Yunzai-Bot# ffmpeg -version
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100

为什么我安装了ffmpeg还是无法发送语音包

**Comment by hanhan258** [comment]
请查看下面链接里的解决方法：https://www.wolai.com/4FCxxWAdjbrHF29MCJmAQK ， 如果还是不行，请进群：559567232

**Comment by dyt1993** [comment]
> 

# ffmpeg
ffmpeg_path: /usr/bin/ffmpeg
ffprobe_path: /usr/bin/ffprobe

修改了这两个配置并重启了yunzai，但是问题依旧，已申请加群，感谢

**Comment by Err0rCM** [comment]
如还有问题请重开issue
