### ISSUE TITLE
预览模式图片有概率返回空图片的情况

### ISSUE THREAD

**Issue by Cha-Sir** [ikechan8370/chatgpt-plugin#329]
## 问题描述

使用预览模式图片回复有概率返回空消息图片

触发概率不高,，很随机，很怪
![GP~ HKRJ3@YMZ5G@TD`1PXG](https://user-images.githubusercontent.com/128087429/230738414-c4f557ba-a9e6-4d6a-bdda-10af7c333ccd.gif)

错误日志：
[YzBot][14:02:15.774][INFO] {
  text: '{"text": "@露早的天狗 茶茶没有出bug啦，茶茶只是不想和你聊天而已~", "mood": "boredom"}',
  quote: [],
  suggestedResponses: '@茶茶 为什么不想和我聊天？\n@茶茶 你是不是生气了？\n@茶茶 那你想和谁聊天？',
  conversationId: '51D|BingProd|27C9743B2564325BF57DB181BE6DE78C64DB4893C4F71014895F358F2695B894',
  clientId: '985155495341411',
  invocationId: 1,
  conversationSignature: 'zoR7u2sFG7xs61sYO5CHC/EXIoKfYwE9CxV3imjZywA=',
  parentMessageId: '30816710-e949-4860-9fa6-f73533d8f96c',
  bingToken: '13CCNFcR6JXNbibCqzBiCb_AtjflhpzQVMkphGztBp2_MzI1MAZZxq3U0_HdrxDXBiUIR-lAKpAkX8SogkycC3YMKVBmbYZ7UAGKc4fK1TfNXdwuBaR6A_QgkbrX7aISS5CKZ-kvKKT97EHvQnGJECDjxmZxfjMY7roJKhKwF8_XX2Vzz5lAZUJXDcGpTExW85lceNMuYv2z9Ht57TqdduQ'
}
{"level":30,"time":1681020135778,"pid":2400,"hostname":"10_0_4_15","reqId":"req-29","req":{"method":"POST","url":"/cache","hostname":"127.0.0.1:3321","remoteAddress":"127.0.0.1","remotePort":58087},"msg":"incoming request"}
{"level":50,"time":1681020156783,"pid":2400,"hostname":"10_0_4_15","reqId":"req-29","req":{"method":"POST","url":"/cache","hostname":"127.0.0.1:3321","remoteAddress":"127.0.0.1","remotePort":58087},"res":{"statusCode":500},"err":{"type":"Error","message":"connect ETIMEDOUT 34.117.59.81:80","stack":"Error: connect ETIMEDOUT 34.117.59.81:80\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)","errno":-4039,"code":"ETIMEDOUT","syscall":"connect","address":"34.117.59.81","port":80},"msg":"connect ETIMEDOUT 34.117.59.81:80"}
{"level":30,"time":1681020156785,"pid":2400,"hostname":"10_0_4_15","reqId":"req-29","res":{"statusCode":500},"responseTime":21007.012300014496,"msg":"request completed"}
{"level":30,"time":1681020156953,"pid":2400,"hostname":"10_0_4_15","reqId":"req-2a","req":{"method":"GET","url":"/page/q85v6?qr=true","hostname":"127.0.0.1:3321","remoteAddress":"127.0.0.1","remotePort":58100},"msg":"incoming request"}
{"level":30,"time":1681020156956,"pid":2400,"hostname":"10_0_4_15","reqId":"req-2a","res":{"statusCode":200},"responseTime":2.313199996948242,"msg":"request completed"}
{"level":30,"time":1681020156987,"pid":2400,"hostname":"10_0_4_15","reqId":"req-2b","req":{"method":"GET","url":"/css/chunk-vendors.f10f650e.css","hostname":"127.0.0.1:3321","remoteAddress":"127.0.0.1","remotePort":58100},"msg":"incoming request"}
{"level":30,"time":1681020156990,"pid":2400,"hostname":"10_0_4_15","reqId":"req-2b","res":{"statusCode":304},"responseTime":2.858100175857544,"msg":"request completed"}
{"level":30,"time":1681020157004,"pid":2400,"hostname":"10_0_4_15","reqId":"req-2c","req":{"method":"GET","url":"/css/app.6561b27a.css","hostname":"127.0.0.1:3321","remoteAddress":"127.0.0.1","remotePort":58101},"msg":"incoming request"}
{"level":30,"time":1681020157005,"pid":2400,"hostname":"10_0_4_15","reqId":"req-2c","res":{"statusCode":304},"responseTime":1.2545998096466064,"msg":"request completed"}
{"level":30,"time":1681020157051,"pid":2400,"hostname":"10_0_4_15","reqId":"req-2d","req":{"method":"GET","url":"/js/chunk-vendors.bc8c7ae8.js","hostname":"127.0.0.1:3321","remoteAddress":"127.0.0.1","remotePort":58101},"msg":"incoming request"}
{"level":30,"time":1681020157053,"pid":2400,"hostname":"10_0_4_15","reqId":"req-2d","res":{"statusCode":304},"responseTime":1.4439001083374023,"msg":"request completed"}
{"level":30,"time":1681020157074,"pid":2400,"hostname":"10_0_4_15","reqId":"req-2e","req":{"method":"GET","url":"/js/app.4195158e.js","hostname":"127.0.0.1:3321","remoteAddress":"127.0.0.1","remotePort":58101},"msg":"incoming request"}
{"level":30,"time":1681020157075,"pid":2400,"hostname":"10_0_4_15","reqId":"req-2e","res":{"statusCode":304},"responseTime":1.1342999935150146,"msg":"request completed"}
{"level":30,"time":1681020157828,"pid":2400,"hostname":"10_0_4_15","reqId":"req-2f","req":{"method":"POST","url":"/page","hostname":"127.0.0.1:3321","remoteAddress":"127.0.0.1","remotePort":58101},"msg":"incoming request"}
{"level":50,"time":1681020157829,"pid":2400,"hostname":"10_0_4_15","reqId":"req-2f","req":{"method":"POST","url":"/page","hostname":"127.0.0.1:3321","remoteAddress":"127.0.0.1","remotePort":58101},"res":{"statusCode":500},"err":{"type":"Error","message":"ENOENT: no such file or directory, open 'resources\\ChatGPTCache\\page\\q85v6.json'","stack":"Error: ENOENT: no such file or directory, open 'resources\\ChatGPTCache\\page\\q85v6.json'\n    at Object.openSync (node:fs:594:3)\n    at Object.readFileSync (node:fs:462:35)\n    at Object.<anonymous> (file:///C:/yunzaibot/Yunzai-Bot/plugins/chatgpt-plugin/server/index.js:60:25)\n    at preHandlerCallback (C:\\yunzaibot\\Yunzai-Bot\\node_modules\\.pnpm\\fastify@4.15.0\\node_modules\\fastify\\lib\\handleRequest.js:128:37)\n    at preValidationCallback (C:\\yunzaibot\\Yunzai-Bot\\node_modules\\.pnpm\\fastify@4.15.0\\node_modules\\fastify\\lib\\handleRequest.js:112:5)\n    at handler (C:\\yunzaibot\\Yunzai-Bot\\node_modules\\.pnpm\\fastify@4.15.0\\node_modules\\fastify\\lib\\handleRequest.js:76:7)\n    at C:\\yunzaibot\\Yunzai-Bot\\node_modules\\.pnpm\\fastify@4.15.0\\node_modules\\fastify\\lib\\contentTypeParser.js:192:9\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    at done (C:\\yunzaibot\\Yunzai-Bot\\node_modules\\.pnpm\\fastify@4.15.0\\node_modules\\fastify\\lib\\contentTypeParser.js:186:14)\n    at Parser.defaultJsonParser [as fn] (C:\\yunzaibot\\Yunzai-Bot\\node_modules\\.pnpm\\fastify@4.15.0\\node_modules\\fastify\\lib\\contentTypeParser.js:292:5)","errno":-4058,"syscall":"open","code":"ENOENT","path":"resources\\ChatGPTCache\\page\\q85v6.json"},"msg":"ENOENT: no such file or directory, open 'resources\\ChatGPTCache\\page\\q85v6.json'"}
{"level":30,"time":1681020157830,"pid":2400,"hostname":"10_0_4_15","reqId":"req-2f","res":{"statusCode":500},"responseTime":1.7146000862121582,"msg":"request completed"}
{"level":30,"time":1681020157945,"pid":2400,"hostname":"10_0_4_15","reqId":"req-2g","req":{"method":"GET","url":"/fonts/fa-solid-900.ada6e6df.woff2","hostname":"127.0.0.1:3321","remoteAddress":"127.0.0.1","remotePort":58101},"msg":"incoming request"}
{"level":30,"time":1681020157947,"pid":2400,"hostname":"10_0_4_15","reqId":"req-2g","res":{"statusCode":304},"responseTime":1.277400016784668,"msg":"request completed"}
[YzBot][14:02:38.816][INFO] succeed to send: [Group(789582515)] [回复@露早的天狗][图片]

应该是q85v6.json文件没有生成的问题

windows server2019 datacenter

这个太神秘了，主要是在于触发时机十分随机

**Comment by HalcyonAlcedo** [comment]
原因已经查明，是在获取外网ip时接口访问失败导致，已经提交修复
