### ISSUE TITLE
填写好api或者使用bing的接口都显示TypeError [ERR_ INVALID_ URL]: Invalid URL

### ISSUE THREAD

**Issue by Sakurabluer** [ikechan8370/chatgpt-plugin#330]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

请在此处描述您遇到的问题，包括出现问题的环境、您试图实现的功能以及错误信息等。请尽可能详细，以便其他人可以在自己的环境中复制问题。

## 预期行为

请描述您期望系统在出现问题时应该做什么。

## 实际行为

请描述您实际看到的行为。

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。

**Comment by Sakurabluer** [comment]
![image](https://user-images.githubusercontent.com/102283052/230773650-13e7f150-b6d0-4771-84cf-478c6836f3c3.png)

**Comment by jusaclown** [comment]
遇到了同样的问题

**Comment by Err0rCM** [comment]
请仔细阅读issue模板，复制控制台的log日志，光靠这点信息无法排查问题

**Comment by aPG666a** [comment]
我也是这中问题，但是只有bing的用不了，其他的正常

**Comment by Sakurabluer** [comment]
已解决

**Comment by aPG666a** [comment]
已解决

**Comment by Woods998** [comment]
0|Yunzai-Bot  | [YzBot][09:45:38.778][INFO] {
0|Yunzai-Bot  |   previousConversation: {
0|Yunzai-Bot  |     sender: { user_id: 2642197264, nickname: 'Woods', card: 'Woods' },
0|Yunzai-Bot  |     ctime: '2023-05-08T01:45:38.778Z',
0|Yunzai-Bot  |     utime: '2023-05-08T01:45:38.778Z',
0|Yunzai-Bot  |     num: 0,
0|Yunzai-Bot  |     conversation: {}
0|Yunzai-Bot  |   }
0|Yunzai-Bot  | }
0|Yunzai-Bot  | [YzBot][09:45:38.778][MARK] {
0|Yunzai-Bot  |   conversation: {
0|Yunzai-Bot  |     conversationId: undefined,
0|Yunzai-Bot  |     parentMessageId: undefined,
0|Yunzai-Bot  |     clientId: undefined,
0|Yunzai-Bot  |     invocationId: undefined,
0|Yunzai-Bot  |     conversationSignature: undefined,
0|Yunzai-Bot  |     bingToken: undefined
0|Yunzai-Bot  |   }
0|Yunzai-Bot  | }
0|Yunzai-Bot  | [YzBot][09:45:38.778][MARK] using api mode
0|Yunzai-Bot  | [YzBot][09:45:38.780][ERRO] Error: TypeError [ERR_INVALID_URL]: Invalid URL
0|Yunzai-Bot  |     at chatgpt.sendMessage (file:///D:/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:1794:19)
0|Yunzai-Bot  |     at runMicrotasks (<anonymous>)
0|Yunzai-Bot  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|Yunzai-Bot  |     at async chatgpt.abstractChat (file:///D:/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:959:25)
0|Yunzai-Bot  |     at async chatgpt (file:///D:/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:751:5)
0|Yunzai-Bot  |     at async PluginsLoader.deal (file:///D:/Yunzai-Bot/lib/plugins/loader.js:251:52)
0|Yunzai-Bot  | {"level":30,"time":1683510338781,"pid":15352,"hostname":"Woods","reqId":"req-4h","req":{"method":"POST","url":"/cache","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57272},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510338783,"pid":15352,"hostname":"Woods","reqId":"req-4h","res":{"statusCode":200},"responseTime":1.7800000002607703,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510338793,"pid":15352,"hostname":"Woods","reqId":"req-4i","req":{"method":"GET","url":"/page/2fsgx?qr=true","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57273},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510338794,"pid":15352,"hostname":"Woods","reqId":"req-4i","res":{"statusCode":200},"responseTime":0.5759000000543892,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510338801,"pid":15352,"hostname":"Woods","reqId":"req-4j","req":{"method":"GET","url":"/css/chunk-vendors.0ede84b4.css","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57273},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510338803,"pid":15352,"hostname":"Woods","reqId":"req-4j","res":{"statusCode":304},"responseTime":1.369799999985844,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510338803,"pid":15352,"hostname":"Woods","reqId":"req-4k","req":{"method":"GET","url":"/css/app.13fc2dfe.css","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57274},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510338804,"pid":15352,"hostname":"Woods","reqId":"req-4k","res":{"statusCode":304},"responseTime":0.4908000002615154,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510338809,"pid":15352,"hostname":"Woods","reqId":"req-4l","req":{"method":"GET","url":"/js/chunk-vendors.94518e59.js","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57274},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510338809,"pid":15352,"hostname":"Woods","reqId":"req-4l","res":{"statusCode":304},"responseTime":0.3672000002115965,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510338809,"pid":15352,"hostname":"Woods","reqId":"req-4m","req":{"method":"GET","url":"/js/app.dac4caf6.js","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57273},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510338809,"pid":15352,"hostname":"Woods","reqId":"req-4m","res":{"statusCode":304},"responseTime":0.33680000016465783,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510339127,"pid":15352,"hostname":"Woods","reqId":"req-4n","req":{"method":"POST","url":"/page","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57273},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510339128,"pid":15352,"hostname":"Woods","reqId":"req-4n","res":{"statusCode":200},"responseTime":0.5108999996446073,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510339195,"pid":15352,"hostname":"Woods","reqId":"req-4o","req":{"method":"GET","url":"/live2dw/live2d-widget-model-default/assets/blandness.json","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57273},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510339196,"pid":15352,"hostname":"Woods","reqId":"req-4o","res":{"statusCode":304},"responseTime":0.7384999999776483,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510339196,"pid":15352,"hostname":"Woods","reqId":"req-4p","req":{"method":"GET","url":"/fonts/fa-solid-900.3eae9857.woff2","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57274},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510339197,"pid":15352,"hostname":"Woods","reqId":"req-4p","res":{"statusCode":304},"responseTime":0.5002000001259148,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510339203,"pid":15352,"hostname":"Woods","reqId":"req-4q","req":{"method":"GET","url":"/live2dw/live2d-widget-model-default/assets/moc/shizuku.moc","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57274},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510339204,"pid":15352,"hostname":"Woods","reqId":"req-4q","res":{"statusCode":304},"responseTime":0.4396000001579523,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510339231,"pid":15352,"hostname":"Woods","reqId":"req-4r","req":{"method":"GET","url":"/live2dw/live2d-widget-model-default/assets/moc/shizuku.1024/texture_00.png","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57274},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510339232,"pid":15352,"hostname":"Woods","reqId":"req-4s","req":{"method":"GET","url":"/live2dw/live2d-widget-model-default/assets/moc/shizuku.1024/texture_01.png","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57273},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510339232,"pid":15352,"hostname":"Woods","reqId":"req-4r","res":{"statusCode":304},"responseTime":0.9708000002428889,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510339232,"pid":15352,"hostname":"Woods","reqId":"req-4t","req":{"method":"GET","url":"/live2dw/live2d-widget-model-default/assets/moc/shizuku.1024/texture_02.png","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57275},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510339233,"pid":15352,"hostname":"Woods","reqId":"req-4s","res":{"statusCode":304},"responseTime":1.4095000000670552,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510339233,"pid":15352,"hostname":"Woods","reqId":"req-4t","res":{"statusCode":304},"responseTime":0.8390999999828637,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510339233,"pid":15352,"hostname":"Woods","reqId":"req-4u","req":{"method":"GET","url":"/live2dw/live2d-widget-model-default/assets/moc/shizuku.1024/texture_03.png","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57276},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510339234,"pid":15352,"hostname":"Woods","reqId":"req-4v","req":{"method":"GET","url":"/live2dw/live2d-widget-model-default/assets/moc/shizuku.1024/texture_04.png","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57277},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510339234,"pid":15352,"hostname":"Woods","reqId":"req-4w","req":{"method":"GET","url":"/live2dw/live2d-widget-model-default/assets/moc/shizuku.1024/texture_05.png","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57278},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510339234,"pid":15352,"hostname":"Woods","reqId":"req-4u","res":{"statusCode":304},"responseTime":0.7456999998539686,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510339234,"pid":15352,"hostname":"Woods","reqId":"req-4v","res":{"statusCode":304},"responseTime":0.677800000179559,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510339235,"pid":15352,"hostname":"Woods","reqId":"req-4w","res":{"statusCode":304},"responseTime":0.7142000002786517,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510339325,"pid":15352,"hostname":"Woods","reqId":"req-4x","req":{"method":"GET","url":"/live2dw/live2d-widget-model-default/assets/exp/f01.exp.json","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57278},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510339325,"pid":15352,"hostname":"Woods","reqId":"req-4y","req":{"method":"GET","url":"/live2dw/live2d-widget-model-default/assets/exp/f02.exp.json","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57277},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510339326,"pid":15352,"hostname":"Woods","reqId":"req-4x","res":{"statusCode":304},"responseTime":1.1272999998182058,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510339326,"pid":15352,"hostname":"Woods","reqId":"req-4z","req":{"method":"GET","url":"/live2dw/live2d-widget-model-default/assets/exp/f03.exp.json","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57276},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510339327,"pid":15352,"hostname":"Woods","reqId":"req-50","req":{"method":"GET","url":"/live2dw/live2d-widget-model-default/assets/exp/f04.exp.json","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57275},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510339327,"pid":15352,"hostname":"Woods","reqId":"req-51","req":{"method":"GET","url":"/live2dw/live2d-widget-model-default/assets/shizuku.physics.json","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57273},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510339327,"pid":15352,"hostname":"Woods","reqId":"req-52","req":{"method":"GET","url":"/live2dw/live2d-widget-model-default/assets/shizuku.pose.json","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57274},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510339327,"pid":15352,"hostname":"Woods","reqId":"req-4y","res":{"statusCode":304},"responseTime":1.75,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510339327,"pid":15352,"hostname":"Woods","reqId":"req-4z","res":{"statusCode":304},"responseTime":1.3318000002764165,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510339328,"pid":15352,"hostname":"Woods","reqId":"req-50","res":{"statusCode":304},"responseTime":1.0157999997027218,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510339328,"pid":15352,"hostname":"Woods","reqId":"req-51","msg":"Route GET:/live2dw/live2d-widget-model-default/assets/shizuku.physics.json not found"}
0|Yunzai-Bot  | {"level":30,"time":1683510339328,"pid":15352,"hostname":"Woods","reqId":"req-51","res":{"statusCode":404},"responseTime":1.1743999999016523,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510339328,"pid":15352,"hostname":"Woods","reqId":"req-53","req":{"method":"GET","url":"/live2dw/live2d-widget-model-default/assets/mtn/idle_02.mtn","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57278},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510339329,"pid":15352,"hostname":"Woods","reqId":"req-52","msg":"Route GET:/live2dw/live2d-widget-model-default/assets/shizuku.pose.json not found"}
0|Yunzai-Bot  | {"level":30,"time":1683510339329,"pid":15352,"hostname":"Woods","reqId":"req-52","res":{"statusCode":404},"responseTime":2.013800000306219,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510339329,"pid":15352,"hostname":"Woods","reqId":"req-53","res":{"statusCode":304},"responseTime":1.0955000002868474,"msg":"request completed"}
0|Yunzai-Bot  | {"level":30,"time":1683510339331,"pid":15352,"hostname":"Woods","reqId":"req-54","req":{"method":"GET","url":"/live2dw/live2d-widget-model-default/assets/mtn/idle_02.mtn","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57278},"msg":"incoming request"}
0|Yunzai-Bot  | {"level":30,"time":1683510339331,"pid":15352,"hostname":"Woods","reqId":"req-54","res":{"statusCode":304},"responseTime":0.4066999997012317,"msg":"request completed"}


同样报错，日志这么说
