### ISSUE TITLE
图片模式下配置无效的问题

### ISSUE THREAD

**Issue by heisenyu** [ikechan8370/chatgpt-plugin#331]
## 问题描述

在锅巴配置中，’图片引用消息‘和’启用二维码‘这两个选项无效，即使直接修改配置文件也是无效的。

![image](https://user-images.githubusercontent.com/52187367/230781465-2a01bdf8-35c4-4e19-8a67-8a0f0361b63c.png)

![image](https://user-images.githubusercontent.com/52187367/230781565-de53ad09-74ba-4cd6-8c23-07cd7ab83954.png)

**Comment by Err0rCM** [comment]
未发现有问题，请仔细阅读issue模板要求并提供相应日志和复现过程

**Comment by keongmeng** [comment]
我的也无效....

**Comment by HalcyonAlcedo** [comment]
> 我的也无效....

请提供一下使用的版本，config文件内容，开启调试选项后的一个对话过程日志，如果有条件提供一下后台配置中图片模式的截图

所有日志和图片中的敏感信息注意删除后再发

**Comment by heisenyu** [comment]
升级到最新版本已解决
