### ISSUE TITLE
部署在Linux中出现依赖下载问题

### ISSUE THREAD

**Issue by fatebugs** [ikechan8370/chatgpt-plugin#337]
Centos中貌似不支持node-silk依赖的安装，会显示以下错误，导致我现在直接启动不了了

![image](https://user-images.githubusercontent.com/65278566/231099147-103a2181-f0a6-4fd9-afd6-7add3c97ae73.png)

**Comment by HalcyonAlcedo** [comment]
centos 9 已安装编译环境 yarn安装node-silk无异常，香港服务器

**Comment by Err0rCM** [comment]
`Install faill Error: run install error, please remove node_modules before retry!`
以下内容来自于谷歌翻译：
`安装失败错误：运行安装错误，请在重试前删除 node_modules！`
