### ISSUE TITLE
socket hang up&429&time out

### ISSUE THREAD

**Issue by sk856** [ikechan8370/chatgpt-plugin#338]
## 问题描述

一会出现429的报错，一会出现socket hang up，一会出现time out，最近就没成功过

## 预期行为

请描述您期望系统在出现问题时应该做什么。

## 复制过程

 Error: FetchError: request to https://api.openai.com

/v1/chat/completions failed, reason: socket hang up
然后
TimeoutError: OpenAI timed out waiting for response
然后
Error: OpenAI error 429: { "error": { "message": "That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID af42b52f9af987ee356f902de5410c82 in your message.)", "type": "server_error", "param": null, "code": null } }

## 环境

使用的是API模式

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息

上面

**Comment by Err0rCM** [comment]
一般来说是网卡了，或者是正在回复其他人的会话，同一时间只能回复一个人和对话
