### ISSUE TITLE
出现错误：{"error":{"message":"Conversation not found","statusCode":404,"statusText":""}}

### ISSUE THREAD

**Issue by LuoXi2334** [ikechan8370/chatgpt-plugin#339]
不同的用户对于机器人发信息有的会404，有的不会404，尝试了用#结束对话也没有用![Screenshot_2023-04-12-07-41-04-620_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/110536861/231311663-2a732f8c-e57d-4d88-b16b-d85a259efa12.jpg)

![Screenshot_2023-04-12-07-42-45-122_com.tencent.mobileqq-edit.jpg](https://user-images.githubusercontent.com/110536861/231311726-f8992bdc-c98d-4792-85b4-ca1c2c18f4d6.jpg)

上面两个图分别是同时间，我自己的号(主人的号)，其他的号发信息得到是回复

**Comment by ikechan8370** [comment]
经典问题 你被其他插件抢指令了

**Comment by domadaaaa** [comment]
解决了吗

**Comment by ikechan8370** [comment]
![image](https://user-images.githubusercontent.com/21212372/231502132-f0005cfe-f6f8-4971-86e8-2af2f18fe71c.png)
这句话不是本插件的，出现这个就去排查一下是哪个插件抢指令了
