### ISSUE TITLE
加入使用gpt-4的模式

### ISSUE THREAD

**Issue by YuuinIH** [ikechan8370/chatgpt-plugin#348]
目前gpt4只能从设置面板来手动切换，对于gpt4有非常严格的使用限制，这使得群友用起来十分不便，当被限制时只能使用其他的模式。
希望能够实现一种方式让gpt-3.5和gpt-4进行共存。

想法是:
尝试添加了一个新模式#chat4
在该模式下，调用#chat4 会在当前回话的基础下，使用gpt4模型进行生成。

目前个人的实现:
添加了一个新模式#chat4，可以通过 '#chatgpt切换API4' 切换，也可以使用#chat4前缀 
可以基于已有的会话进行。与#chat3共享会话id。
已有的通过gpt4创建的会话可以使用gpt3.5继续，和原版相同。
与原版不同的是 使用gpt-3.5构建的会话上下文经过测试可以使用gpt4生成新的消息。

FAQ：
- why not bing?
   个人体感bing在一些场景下没有gpt-3.5效果好，例如询问专业问题等。
- why name chat4?
   顺水逐流。

其他可能有的问题:
- 对于满足以上要求，还有更好的实现方案吗？
- 设置内的使用gpt-4是否要去掉？
- 混合模型的会话可能会引起openai的注意 因为是非正常行为 可能存在风险 是否要加以限制?

**Comment by Err0rCM** [comment]
目前#chat命令用来指定不同的模式，使用#chat4可能会破坏现有配置结构

而且现在官网4切换使用gpt3.5后好像不支持切换回4，不知道会不会有风险

**Comment by YuuinIH** [comment]
> 目前#chat命令用来指定不同的模式，使用#chat4可能会破坏现有配置结构
> 
> 而且现在官网4切换使用gpt3.5后好像不支持切换回4，不知道会不会有风险


如果实现的话 改变配置结构可能是不可避免的……
可能考虑改成开关的方式而不是用新的模式？

对于官网的问题 可能考虑补充上切换的限制

**Comment by ghost** [comment]
api模式已支持
