### ISSUE TITLE
给 #chatgpt系统管理 增加提示或者群聊判断

### ISSUE THREAD

**Issue by JD1433223** [ikechan8370/chatgpt-plugin#350]
![IMG_20230414_125951.jpg](https://user-images.githubusercontent.com/113197081/231945844-845e8c9c-d7cb-4dcf-8163-3de7c39b4c23.jpg)
![IMG_20230414_130019.jpg](https://user-images.githubusercontent.com/113197081/231945876-5242e4c9-9a4a-44ac-a6d0-6516dfd31eba.jpg)
上午在群里面试功能不小心漏服务器的静态公网ip了，然后给有心之人利用了

**Comment by ghost** [comment]
这边建议频道也做个检测

**Comment by JD1433223** [comment]
> 这边建议频道也做个检测

判断!e.isPrivate就行了![-4a09fec1cc03827d.gif](https://user-images.githubusercontent.com/113197081/231982502-88d9a9d1-d30c-4490-a891-ef02503d0b0d.gif)

**Comment by Err0rCM** [comment]
和云崽添加ck/锅巴登录 一样只允许私聊也许可以

**Comment by HalcyonAlcedo** [comment]
可以加个配置，设置为可选项，原本设计上后台是可以所有人登陆的，不光管理者，用户登陆是可以看缓存数据和部分个人设置的修改的

**Comment by HalcyonAlcedo** [comment]
已经添加配置，默认关闭群获取，不过还是建议将服务器挂在反代和cdn后面，图片模式的二维码同样会暴露地址的
