### ISSUE TITLE
私聊系统管理bot会回复提示私聊发送命令

### ISSUE THREAD

**Issue by akmioto** [ikechan8370/chatgpt-plugin#354]
![~S%DAM8LM75N3B66ILTJY3S](https://user-images.githubusercontent.com/105832022/232179274-923eb9bc-b8d7-4998-9d40-bc9251450253.png)
![5X U0MC_34)ZBQZZB SV2XX](https://user-images.githubusercontent.com/105832022/232179280-b37b5598-ee40-4c26-bddf-faa506ca9976.png)
今天早上更新完新出现的bug

**Comment by Err0rCM** [comment]
目前没有出现此问题了，如还有问题请提供其他信息
