### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by wfqyys** [ikechan8370/chatgpt-plugin#358]
# 现在已经更新到最新版本

**在提交issue前确认我已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

后台面板中的API3的反代地址不会显示，但是锅巴里面有，我以为没有，填了一遍，然后，发现锅巴里的有，而且还和我在后台面板里填的不一样，现在，好像API3也没反应了

## 预期行为

修复一下

## 附加信息

![Screenshot_20230415_234543_com.arpaplus.adminhands.png](https://user-images.githubusercontent.com/82580667/232235017-81b1e4aa-17ed-4963-9c5e-81e12592d2db.png)

![Screenshot_20230415_234456.jpg](https://user-images.githubusercontent.com/82580667/232235019-cf00e71c-81bc-4141-ac8b-4432078a7090.jpg)

![Screenshot_20230415_232527_com.huawei.browser.png](https://user-images.githubusercontent.com/82580667/232235016-995971bf-1b5d-43bd-91c0-28440e4daaa8.png)

![Screenshot_20230415_232512_com.huawei.browser.png](https://user-images.githubusercontent.com/82580667/232235020-27495a7a-117e-47ed-b848-20a7f6a88cef.png)

**Comment by HalcyonAlcedo** [comment]
bug已知，本地已经修复好了，明天再提交

**Comment by wfqyys** [comment]
不好意思哈，我刚刚更新了一下依赖，API3可以用了，但是面板问题还在
