### ISSUE TITLE
有没有安卓手机获取new bing的token的方法

### ISSUE THREAD

**Issue by muyun618** [ikechan8370/chatgpt-plugin#367]
如题，pc不好上new bing，但是手机很简单

**Comment by Err0rCM** [comment]
[文档最后提了](https://chatgpt-docs.err0r.top/config/bing.html#%E6%96%B9%E6%B3%95%E4%BA%8C-%E6%89%8B%E5%8A%A8%E8%8E%B7%E5%8F%96)，简单不一定实用

如果懂代码的话手机也没问题，如果不懂代码的话可能也不会操作，建议还是用电脑

**Comment by XXX1124** [comment]
小黄鸟抓包

**Comment by ikechan8370** [comment]
现在不需要token了
