### ISSUE TITLE
建议机器人关闭私聊功能后可以选择不回复关闭私聊提示语

### ISSUE THREAD

**Issue by AshenAshes** [ikechan8370/chatgpt-plugin#369]
![QQ图片20230418132309](https://user-images.githubusercontent.com/39981645/232678806-84b12af5-990b-4d6b-9e48-64bf6e81f24c.jpg)
我关闭了机器人的chatgpt私聊功能，但有用户在使用别的功能的时候会触发私聊通道关闭的提示语，导致误会机器人关闭了整体的私聊功能。
希望作者大大能够允许机器人关闭chatgpt私聊功能的情况下，不回复“ChatGpt私聊通道已关闭”的提示语，以保证机器人其他日常功能的正常使用体验。

**Comment by Err0rCM** [comment]
这个问题需要讨论一下，因为本插件私聊是直接接收回复的，如果要解决的话或许可能要直接删掉关闭提醒
