### ISSUE TITLE
重定向次数过多{maximum redirect reached at:https://cn.bing.com/turing/conversation/create}

### ISSUE THREAD

**Issue by YHStar** [ikechan8370/chatgpt-plugin#371]
<img width="416" alt="图片1" src="https://user-images.githubusercontent.com/28947870/232702168-0eade938-8eb6-44c5-b2f2-125cf0456fd2.png">
已经开了clash 并且wget了youtube已经打通，可是用#bing聊天时显示重定向次数过多{maximum redirect reached at:https://cn.bing.com/turing/conversation/create}，但当我自己wget https://www.bing.com/turing/conversation/create时能得到正常回应，猜测模块没走代理（？

**Comment by YHStar** [comment]
<img width="767" alt="image" src="https://user-images.githubusercontent.com/28947870/232731990-f79e3a5d-5cdc-4371-b11c-f52717f3e04b.png">

**Comment by akmioto** [comment]
锅巴里面把代理填上

**Comment by YHStar** [comment]
> 

填了http://0.0.0.0:7890

**Comment by Err0rCM** [comment]
> > 
> 
> 填了http://0.0.0.0:7890

代理怎么能填http://0.0.0.0:7890。。填`http://localhost:7890` 或 `http://127.0.0.1:7890`，都表示本地回环地址

**Comment by czh249899518** [comment]
这个问题解决了吗，我这边还是不行，很奇怪，我用的是shadowsock。设置了代理，但是不知道代理上了没
