### ISSUE TITLE
API正常转换语音，但是机器人不发语音

### ISSUE THREAD

**Issue by SkyYeXianer** [ikechan8370/chatgpt-plugin#373]
我的机器人怎么样都发不了语音，我不知道为什么？
我的API是正常的可以转换语音
![image](https://user-images.githubusercontent.com/109300803/232945370-8b654ffb-7412-4f09-ac6c-ffcafc92c132.png)
我是有ffmpeg的，而且也添加进了环境变量。
node-silk也是正常安装进node_modules的
![image](https://user-images.githubusercontent.com/109300803/232956829-e7e216b3-d57f-4b86-a6ee-8e62380fb99b.png)
我的设置也没问题，全局语音，指令切换语音都试了
但是尝试了很多次，我甚至怀疑过是不是Q账号问题
各种控制变量，我就是找不出毛病。我是否还有没做到的地方？

**Comment by SkyYeXianer** [comment]
![image](https://user-images.githubusercontent.com/109300803/232947613-2a68b689-be86-4f89-bc2d-e957f0518fb8.png)
![image](https://user-images.githubusercontent.com/109300803/232947651-352f3174-78ef-4530-a995-53af6b04c9bb.png)
里面没有将wav转换amr的操作，也不报错，存在什么问题呢？

**Comment by SkyYeXianer** [comment]
![image](https://user-images.githubusercontent.com/109300803/232947718-54bf31c4-8db3-44dd-b7af-adb31de4f66c.png)

**Comment by yqs6666** [comment]
俺也一样
![image](https://user-images.githubusercontent.com/106430842/233030776-a4dbd0b7-3334-4194-bcbf-671be65a8dc2.png)

**Comment by SkyYeXianer** [comment]
![image](https://user-images.githubusercontent.com/109300803/233206650-718bd8d6-8612-4ce8-8620-8dfdf4a9c6a1.png)
多次测试有极罕见可能会发送出来，问题是网络延迟吗？

**Comment by SkyYeXianer** [comment]
其次我想问，为什么我本地部署的vits的API会错误？一样的步骤查的API

**Comment by Err0rCM** [comment]
尝试一下登录账号手动发一条语音，有屏蔽词还是权重太低的号语音和有些消息都发不出来，具体是tx的问题
