### ISSUE TITLE
第二次生成词云出错 

### ISSUE THREAD

**Issue by 127Wzc** [ikechan8370/chatgpt-plugin#377]
出现Jieba was loaded, could not load again
这边把chatgpt-plugin/utils/wordcloud/tokenizer.js:63 行的 nodejieba.load()
移动到 nodejieba = (await import('@node-rs/jieba')).default 之后 暂时解决了

**Comment by 127Wzc** [comment]
嗯，我这也是 个人群友会出现昵称，应该是昵称包含了空格导致的&nbsp;


wangzc
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月23日(星期天) 中午11:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ikechan8370/chatgpt-plugin] 第二次生成词云出错  (Issue #377)





  
出现Jieba was loaded, could not load again 这边把chatgpt-plugin/utils/wordcloud/tokenizer.js:63 行的 nodejieba.load() 移动到 nodejieba = (await ***@***.***/jieba')).default 之后 暂时解决了
  
我这么改后，统计好像连着群友的昵称一起统计了？

**Comment by Chocolatemocha** [comment]
> 嗯，我这也是 个人群友会出现昵称，应该是昵称包含了空格导致的&nbsp; wangzc ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年4月23日(星期天) 中午11:19 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [ikechan8370/chatgpt-plugin] 第二次生成词云出错 (Issue #377) 出现Jieba was loaded, could not load again 这边把chatgpt-plugin/utils/wordcloud/tokenizer.js:63 行的 nodejieba.load() 移动到 nodejieba = (await ***@***.***/jieba')).default 之后 暂时解决了 我这么改后，统计好像连着群友的昵称一起统计了？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

后面我又更新了一下插件到最新版（放弃修改），好像正常了？

**Comment by 127Wzc** [comment]
我刚拉了最新的，还是会有这种情况。 基本确定，出现群友昵称的情况就是他的昵称含有空格，被统计进去了后半部分
&nbsp;


wangzc
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月23日(星期天) 下午3:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ikechan8370/chatgpt-plugin] 第二次生成词云出错  (Issue #377)





  
嗯，我这也是 个人群友会出现昵称，应该是昵称包含了空格导致的&nbsp; wangzc @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年4月23日(星期天) 中午11:19 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [ikechan8370/chatgpt-plugin] 第二次生成词云出错 (Issue #377) 出现Jieba was loaded, could not load again 这边把chatgpt-plugin/utils/wordcloud/tokenizer.js:63 行的 nodejieba.load() 移动到 nodejieba = (await @./jieba')).default 之后 暂时解决了 我这么改后，统计好像连着群友的昵称一起统计了？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
后面我又更新了一下插件到最新版（放弃修改），好像正常了？

**Comment by 127Wzc** [comment]
对于这种感觉不太好直接从文本去拆分，也许可以从这个message入手


![image](https://user-images.githubusercontent.com/52766844/233826881-656fb393-c834-48a9-b06b-d6941ef6599e.png)





wangzc
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ikechan8370/chatgpt-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月23日(星期天) 下午3:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ikechan8370/chatgpt-plugin] 第二次生成词云出错  (Issue #377)





  
嗯，我这也是 个人群友会出现昵称，应该是昵称包含了空格导致的&nbsp; wangzc @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年4月23日(星期天) 中午11:19 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [ikechan8370/chatgpt-plugin] 第二次生成词云出错 (Issue #377) 出现Jieba was loaded, could not load again 这边把chatgpt-plugin/utils/wordcloud/tokenizer.js:63 行的 nodejieba.load() 移动到 nodejieba = (await @./jieba')).default 之后 暂时解决了 我这么改后，统计好像连着群友的昵称一起统计了？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
后面我又更新了一下插件到最新版（放弃修改），好像正常了？
