### ISSUE TITLE
重定向次数过多maximum redirect reached at: https://cn.bing.com/turing/conversation/create

### ISSUE THREAD

**Issue by CICILC** [ikechan8370/chatgpt-plugin#388]
![Screenshot_20230425_003333_QQ](https://user-images.githubusercontent.com/115946224/234063528-fdbaa324-39c2-4ea1-b565-e6e0d6546e2e.jpg)
这个问题我在其他issue了解过但是没有解决问题
我在本地服务器上部署的可以直接使用（不使用代理）
目前在华为云上重新部署的出现了重定向过多的情况 由于云服务器难以添加代理 有其他方式可以继续使用bing的吗 感谢解答

**Comment by Err0rCM** [comment]
基本上没办法，重定向cn就无法对话
