### ISSUE TITLE
请问这个puppeteer启动失败如何解决

### ISSUE THREAD

**Issue by Holytar** [ikechan8370/chatgpt-plugin#39]
0|Yunzai-Bot  | [YzBot][22:31:26.049][ERRO] puppeteer Chromium 启动失败
0|Yunzai-Bot  | [YzBot][22:31:26.050][ERRO] TypeError: Cannot read properties of undefined (reading 'newPage')
0|Yunzai-Bot  |     at ChatGPTPuppeteer.login (file:///root/Yunzai-Bot/plugins/chatgpt-plugin/utils/autoLogin.js:101:39)
0|Yunzai-Bot  |     at async chatgpt (file:///root/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:208:5)
0|Yunzai-Bot  |     at async PluginsLoader.deal (file:///root/Yunzai-Bot/lib/plugins/loader.js:251:52)
0|Yunzai-Bot  | [YzBot][22:31:26.051][ERRO] [chatgpt][chatgpt]
0|Yunzai-Bot  | [YzBot][22:31:26.052][ERRO] TypeError: Cannot read properties of undefined (reading 'close')
0|Yunzai-Bot  |     at ChatGPTPuppeteer.login (file:///root/Yunzai-Bot/plugins/chatgpt-plugin/utils/autoLogin.js:196:20)
0|Yunzai-Bot  |     at async chatgpt (file:///root/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:208:5)
0|Yunzai-Bot  |     at async PluginsLoader.deal (file:///root/Yunzai-Bot/lib/plugins/loader.js:251:52)

**Comment by ikechan8370** [comment]
请使用v2分支吧。autologin计划在CF的变态机器人验证面前似乎已经破产了。

**Comment by Holytar** [comment]
> 请使用v2分支吧。autologin计划在CF的变态机器人验证面前似乎已经破产了。
