### ISSUE TITLE
请问是否可以添加一个群聊的相关功能，这个功能能够可以对群友使用机器人ai聊天此事进行限制。功能具体实现如下：设置一个#chat打卡（类似），功能是统计群友的打卡，并在打卡时可以获取能量（或者其他的）。每次聊天时，群友需要消耗能量。当能量耗尽时无法继续聊天，需要在第二天再次打卡获取能量才可以。能量可以累计。当群聊开启这个功能，既可以让群友使用chatgpy插件，同时可以限制群友大量使用导致可能的崩溃

### ISSUE THREAD

**Issue by 870676759** [ikechan8370/chatgpt-plugin#391]
**你的功能请求是否与某个问题有关？请描述。**
问题的清晰而简明的描述。

**描述你想要的解决方案**
你想要发生什么的清晰而简明的描述。

**描述你已经考虑的替代方案**
对任何替代解决方案或功能的清晰简明的描述。

**附加说明**
在此处添加有关功能请求的任何其他说明、屏幕截图或者引用。

**Comment by 870676759** [comment]
这个是参考隔壁插件fanskeqs的。fans插件已经实现了这个功能，但是fans支持的ai没有本插件多

**Comment by ikechan8370** [comment]
我发现我也有这个需求了 下个大版本会考虑
