### ISSUE TITLE
Sorry, you need to login first to access this service.

### ISSUE THREAD

**Issue by CICILC** [ikechan8370/chatgpt-plugin#393]
![Screenshot_20230426_011924_QQ](https://user-images.githubusercontent.com/115946224/234353842-69f5737a-afd9-4796-a338-636579ba86d1.jpg)

bing模式偶尔才能正常使用 大部分情况需要登录 Sorry, you need to login first to access this service. 请问该怎么解决

**Comment by Diskanden** [comment]
你以前的旧token没删

**Comment by ws147** [comment]
我也遇到了，使用量一到20token就失效，拿同样的token绑定又能开始新一轮的20次

**Comment by CICILC** [comment]
> 你以前的旧token没删

应该是这样的 我换了个机器人和token就好了
