### ISSUE TITLE
Bing模式下会重复at

### ISSUE THREAD

**Issue by it-kirito** [ikechan8370/chatgpt-plugin#395]
# 首先夸一下Bing模式的表现，真的太棒了！希望这种获取群成员信息的能力也可以适配到其他模式下

## 问题描述

Bing模式下对话会出现多次@的情况，看目前表现好像是累加的

## 预期行为

回复行为最多有一个at就可以了

## 实际行为

请描述您实际看到的行为。

## 附加信息

![image](https://user-images.githubusercontent.com/66652239/234458997-5be0d495-887c-4bab-b688-99327e0f5f3b.png)
![image](https://user-images.githubusercontent.com/66652239/234459103-f7e0eb31-add9-4889-95e4-feac7ecec737.png)

**Comment by hsx-123** [comment]
是的，我也注意到了这个问题，我还以为只有我出问题了hh

**Comment by it-kirito** [comment]
看了下应该是Bing的行为，不是插件问题
