### ISSUE TITLE
按照Claude使用文档配置完毕出现下面的报错

### ISSUE THREAD

**Issue by Diskanden** [ikechan8370/chatgpt-plugin#396]
![-72f44154d2da26b0](https://user-images.githubusercontent.com/117650898/234572401-501afec1-e14e-42cd-a4dc-4d5a6091fc01.png)
如图，已经换了4个新号了配置机器人都是这样，现在看到这个就ptsd了

**Comment by Diskanden** [comment]
![Screenshot_2023-04-26-20-20-17-243_com termux](https://user-images.githubusercontent.com/117650898/234572716-a28d069f-d0cc-4151-a529-f8e7f3811e99.jpg)
具体报错

**Comment by HalcyonAlcedo** [comment]
有可能是依赖问题？更新依赖试试

**Comment by ikechan8370** [comment]
报错显示位置显示你之前存在对话 带着conversationID去slack然后slack说该对话已经不存在 结束对话再测试一下
ps：thread在slack里就是对话

**Comment by ikechan8370** [comment]
尤其是你换号 还带着原来号的thread去slack必定会报这个错 需要结束对话重开
