### ISSUE TITLE
使用v2版本，使用chromePath空值后启动失败

### ISSUE THREAD

**Issue by Holytar** [ikechan8370/chatgpt-plugin#40]
chromePath: ''

//然后

0|Yunzai-Bot  | [YzBot][23:06:16.764][MARK] puppeteer Chromium 启动中...
0|Yunzai-Bot  | [YzBot][23:06:16.811][ERRO] Error: An `executablePath` or `channel` must be specified for `puppeteer-core`
0|Yunzai-Bot  | [YzBot][23:06:16.812][ERRO] puppeteer Chromium 启动失败
0|Yunzai-Bot  | Error: Failed to launch the browser process! spawn /Applications/Google Chrome.app/Contents/MacOS/Google Chrome ENOENT
0|Yunzai-Bot  | TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
0|Yunzai-Bot  |     at onClose (/root/Yunzai-Bot/node_modules/.pnpm/puppeteer-core@19.4.0/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)
0|Yunzai-Bot  |     at ChildProcess.<anonymous> (/root/Yunzai-Bot/node_modules/.pnpm/puppeteer-core@19.4.0/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:293:24)
0|Yunzai-Bot  |     at ChildProcess.emit (node:events:513:28)
0|Yunzai-Bot  |     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
0|Yunzai-Bot  |     at onErrorNT (node:internal/child_process:476:16)
0|Yunzai-Bot  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
0|Yunzai-Bot  | [YzBot][23:06:16.827][ERRO] [chatgpt][chatgpt]
0|Yunzai-Bot  | [YzBot][23:06:16.828][ERRO] Error: Failed to launch the browser process! spawn /Applications/Google Chrome.app/Contents/MacOS/Google Chrome ENOENT
0|Yunzai-Bot  | TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
0|Yunzai-Bot  |     at onClose (/root/Yunzai-Bot/node_modules/.pnpm/puppeteer-core@19.4.0/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)
0|Yunzai-Bot  |     at ChildProcess.<anonymous> (/root/Yunzai-Bot/node_modules/.pnpm/puppeteer-core@19.4.0/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:293:24)
0|Yunzai-Bot  |     at ChildProcess.emit (node:events:513:28)
0|Yunzai-Bot  |     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
0|Yunzai-Bot  |     at onErrorNT (node:internal/child_process:476:16)
0|Yunzai-Bot  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

请问这个是什么问题

**Comment by 229450906** [comment]
![图片](https://user-images.githubusercontent.com/97822794/207377655-ca0e26b4-a930-4edc-967e-29072bd02ae1.png)
我也是这个问题

**Comment by wearshoes** [comment]
![image](https://user-images.githubusercontent.com/30278479/207404121-d035ba93-0cff-43be-8738-3ca0e726fc43.png)

同样的问题

**Comment by Qz-Sean** [comment]
![image](https://user-images.githubusercontent.com/56262913/207409957-7384d1c9-6e75-4d4d-830a-889f1a8777b2.png)
![image](https://user-images.githubusercontent.com/56262913/207409995-25bf6f6e-3a8c-4cd7-88bc-4b1efde72322.png)一样
