### ISSUE TITLE
KOOK版云崽报错

### ISSUE THREAD

**Issue by ayakasuki** [ikechan8370/chatgpt-plugin#406]
![image](https://user-images.githubusercontent.com/20859971/236308474-97efb6f3-97a4-4878-8112-6ae5e90b83ff.png)
如图，信息是发送成功了。但是不知道为什么是不是群号码太长，还是代码只做了QQ群号的

**Comment by ayakasuki** [comment]
但是私聊可以

**Comment by ayakasuki** [comment]
![image](https://user-images.githubusercontent.com/20859971/236317731-9ee8029b-53de-4ce0-81f7-036a126c12da.png)

**Comment by ayakasuki** [comment]
看出来了 好像是获取不到群信息

**Comment by ikechan8370** [comment]
可能有些版本没这个函数 我之后处理一下拿不到就不拿了 包括频道也是

**Comment by ayakasuki** [comment]
> 可能有些版本没这个函数 我之后处理一下拿不到就不拿了 包括频道也是

对 频道也是这个问题来着

**Comment by ayakasuki** [comment]
用chatgpt临时改了下**utils/face.js**，解决了下**KOOK、QQ频道**获取不到groupmembersmap函数，将获取 groupMembers 的代码包装在一个 try-catch 块中。如果获取 groupMembers 出现错误，就会抛出异常，然后在 catch 块中处理异常，不让它终止程序的执行。

_第467行开始_
```
export async function convertFaces (msg, handleAt = false, e) {
  handleAt = e?.isGroup && handleAt
  let groupMembers
  let groupCardQQMap = {}
  if (handleAt) {
    try {
      groupMembers = await e.group.getMemberMap()
    } catch (err) {
      console.error(`Failed to get group members: ${err}`)
    }
    if (groupMembers) {
      for (let key of groupMembers.keys()) {
        groupCardQQMap[groupMembers.get(key).card || groupMembers.get(key).nickname] = groupMembers.get(key).user_id
      }
    }
}
```

**Comment by ayakasuki** [comment]
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/20859971/defe4b85-92fc-4d8c-8291-12cc3e36c175)
现在可以用了
