### ISSUE TITLE
newbing显示对话过期

### ISSUE THREAD

**Issue by abc563216** [ikechan8370/chatgpt-plugin#407]
对话时回复InvalidSession: Conversation '51D|BingProd|FEB00D0BDD1D50C5D0E2CCF9BD045838DFC75A974678C03301D89307478373AE' doesn't exist or has expired. Conversations expire after 06:00:00. 如何解决？

**Comment by liuzj288** [comment]
#结束对话 或者 #结束全部对话

**Comment by abc563216** [comment]
解决了，感谢(≧∇≦)

**Comment by charles-debug** [comment]
遇到了同样的问题，且结束对话没效果
