### ISSUE TITLE
载入插件错误：chat

### ISSUE THREAD

**Issue by Kay2048** [ikechan8370/chatgpt-plugin#41]
![image](https://user-images.githubusercontent.com/115361381/207372409-8c5f280c-23a4-42f2-9bc3-31152e93c1da.png)
佬这个怎么解决呀

**Comment by Qz-Sean** [comment]
![image](https://user-images.githubusercontent.com/56262913/207372942-a07d6b40-3c55-4abc-a348-5f2d01c5a28f.png)
巧了我也是这个问题😂

**Comment by Inky-Moon** [comment]
> ![image](https://user-images.githubusercontent.com/115361381/207372409-8c5f280c-23a4-42f2-9bc3-31152e93c1da.png) 佬这个怎么解决呀

更新nodejs版本到大于等于18

**Comment by yyk725** [comment]
翻译：更新node.js到v18以上
建议去官网下载最新的node
地址：https://nodejs.org/en/download/

**Comment by Kay2048** [comment]
> 

![image](https://user-images.githubusercontent.com/115361381/207390421-369df13e-af2b-4412-9fe5-ab734ccd1c14.png)
更新完出现这个啥问题呀
