### ISSUE TITLE
使用claude模式报错，不知道为什么

### ISSUE THREAD

**Issue by heisenyu** [ikechan8370/chatgpt-plugin#413]
![image](https://user-images.githubusercontent.com/52187367/236889646-b78120f2-1ba0-483d-960f-ece29a1a1b40.png)

**Comment by ikechan8370** [comment]
你自己把频道删了

**Comment by heisenyu** [comment]
新建频道后，说是找不到频道，但是slack会话中有记录呀，这是什么情况呀
![image](https://user-images.githubusercontent.com/52187367/236995439-3b251544-2f6e-46b7-8610-766c169cc61c.png)
![image](https://user-images.githubusercontent.com/52187367/236995581-32bc095e-d1d5-4db8-bfb6-274cb715e5b3.png)
