### ISSUE TITLE
必应模式下fetch faild报错

### ISSUE THREAD

**Issue by liuzj288** [ikechan8370/chatgpt-plugin#414]
这几天出现的故障
![image](https://user-images.githubusercontent.com/13833404/236893006-8c8def71-9dc5-4dfd-acbc-f3a5f19a3eab.png)

**Comment by laoqin6** [comment]
和我一样也

**Comment by zyb666666** [comment]
请问解决了吗

**Comment by laoqin6** [comment]
重装我就好了 - -

**Comment by zyb666666** [comment]
需要配置代理吗

**Comment by labman010** [comment]
可能是什么网络问题bug吧，我直接重启服务器就好了
