### ISSUE TITLE
claude使用设定开启新对话被#claude抢走了

### ISSUE THREAD

**Issue by 127Wzc** [ikechan8370/chatgpt-plugin#415]
## 问题描述
本地已有设定‘李白-claude’
如题，使用指令 #claude开启新对话李白-claude 开启对话无法发送设定内容。猜测是#claude 抢走当作正常对话了，日志如下图
![image](https://user-images.githubusercontent.com/52766844/237033099-e20a6eb8-845f-4e03-8025-28c2556203a4.png)

![image](https://user-images.githubusercontent.com/52766844/237033119-2c8102d4-8fae-4cdd-bdcd-25e0f648f424.png)

## 预期行为
#claude和  #claude开启新对话 可以兼容对话

**Comment by ikechan8370** [comment]
修复了，再试试

**Comment by 127Wzc** [comment]
> 修复了，再试试

可以开启新对话了，但是开启新设定后自动发送一条了空白的@对话。可能和[#417 ]一样
<img width="403" alt="image" src="https://github.com/ikechan8370/chatgpt-plugin/assets/52766844/d60b636d-5da7-4724-b868-0e3edddeafca">

我这边的设置是独立设定
<img width="821" alt="image" src="https://github.com/ikechan8370/chatgpt-plugin/assets/52766844/11be3a30-bf3c-4250-8c46-7b23a137190c">
