### ISSUE TITLE
claude模式下自动发送空白信息

### ISSUE THREAD

**Issue by Selonite925** [ikechan8370/chatgpt-plugin#417]
claude模式下，记录了全局设定，私聊进行对话时，结束对话后，第一句对话前多发送了了一个隐形的@Claude 。会影响部分设定…
希望修复到旧版本，开启对话时只发送全局设定的部分
![-703b5a031e707ac4](https://github.com/ikechan8370/chatgpt-plugin/assets/123850126/3e2618e1-a4fd-4edd-a228-18e4ac1c6307)
![61cdf0496cb6e79e](https://github.com/ikechan8370/chatgpt-plugin/assets/123850126/02d88f69-1f8a-4602-9e72-b103581f971a)

**Comment by Selonite925** [comment]
![Screenshot_2023-05-10-08-48-31-26_2665fb67b16260a8d818298cef8dc107](https://github.com/ikechan8370/chatgpt-plugin/assets/123850126/b55aa9a1-b65e-459b-921a-711c64a1bbd2)
![Screenshot_2023-05-10-08-59-24-58_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/ikechan8370/chatgpt-plugin/assets/123850126/ac2adce1-d98a-4c59-8fbe-d35812b5e380)

这是另一个机器人并没有更新的版本，这个就不会出现一个空@claude

**Comment by ikechan8370** [comment]
我试试看我能否复现

**Comment by lelouchzhang** [comment]
同样的问题
环境：miao崽+最新版本chatgpt插件+开启全局prompt设定
结束全部对话后再开新对话时，发现qq向slack中先后发送了预设的设定和一个空消息
关闭全局设定-结束对话-单独发送消息没有上述情况。
换了个正常的设定，也是会有一个空at。删除工作区或是换号之类的没有测试。

**Comment by Selonite925** [comment]
![Screenshot_2023-05-11-20-43-25-83_abb9c8060a0a12c5ac89e934e52a2f4f](https://github.com/ikechan8370/chatgpt-plugin/assets/123850126/892c785c-127d-4a20-82c5-c93bbbf732d0)
今日已更新，仍旧发送空白回复

**Comment by bincooo** [comment]
这个是claude的道德警告，用message.metadata?.event_type判断一下。
可以参考一下这个https://github.com/bincooo/claude-api/blob/cbeb093847e23585963a1765d9fcf085be986938/src/index.ts#LL173C46-L173C46

**Comment by ikashana** [comment]
均更新至最新版本。也发现了这个问题，在填入设定后，会发送一个空对话，并且Claude会对艾特Claude本身做出回复。

![QQ图片20230523181514](https://github.com/ikechan8370/chatgpt-plugin/assets/115872923/94a06879-7299-44fa-85cc-8c7b278a9939)
