### ISSUE TITLE
支持讯飞星火大模型

### ISSUE THREAD

**Issue by TomyJan** [ikechan8370/chatgpt-plugin#419]
**你的功能请求是否与某个问题有关？请描述。**
请求增加讯飞星火大模型的支持, 这玩意还挺智能的, 在二次元等一些领域的回答甚至比gpt4强

**Comment by ikechan8370** [comment]
尝试支持了一下，看起来问题不大。看看他的登录token换的频繁不频繁了。
`#chatgpt设置星火token`
`#chatgpt切换星火`
欢迎反馈bug

**Comment by Uaena-wyy** [comment]
星火发乱码怎么回事

**Comment by Y-ygc** [comment]
怎么获取token

**Comment by TomyJan** [comment]
乱码是星火改请求了还是失效了?

> 尝试支持了一下，看起来问题不大。看看他的登录token换的频繁不频繁了。 `#chatgpt设置星火token` `#chatgpt切换星火` 欢迎反馈bug

今天乱码了, 看到上面也有人反馈, 是不是星火改请求了

**Comment by ikechan8370** [comment]
乱码需要结束对话 你们去网页版看一眼就知道了

**Comment by TomyJan** [comment]
> 乱码需要结束对话 你们去网页版看一眼就知道了

网页版看起来并没问题啊, 也在bot结束对话了 依然乱码

**Comment by aPG666a** [comment]
token获取的是哪个？
