### ISSUE TITLE
无法在chromium中正常登录openai账号

### ISSUE THREAD

**Issue by yyk725** [ikechan8370/chatgpt-plugin#42]
![image](https://user-images.githubusercontent.com/72236930/207379289-c80ebff5-3360-4480-a9c9-0a12f789687b.png)

**Comment by yyk725** [comment]
弹出的chrome窗口会在报错后自动关闭

**Comment by Kay2048** [comment]
我直接是启动失败

**Comment by yyk725** [comment]
观察了一下，问题是有时自动脚本无法成功控制浏览器点击“log in”按钮导致超时
并且在输入账号后和输入密码前多出了recaptcha导致自动脚本无法工作
手动操作登陆后仍然无法在chromium中获取到token

**Comment by Kay2048** [comment]
他们说的v2分支是什么

**Comment by yyk725** [comment]
github小白猜是这个↓
![image](https://user-images.githubusercontent.com/72236930/207588594-8a49aa3a-a252-4af4-833d-354c98a45e86.png)
