### ISSUE TITLE
QQ频道中使用

### ISSUE THREAD

**Issue by KasumiYuku** [ikechan8370/chatgpt-plugin#423]
QQ频道中使用插件提示
通信异常，错误信息如下：e.group.getMemberMap is not a function

**Comment by ayakasuki** [comment]
#406

**Comment by Y-ygc** [comment]
我也是这样，怎么办啊

**Comment by ayakasuki** [comment]
> 我也是这样，怎么办啊

把代码改一下

**Comment by Y-ygc** [comment]
> 怎么改

**Comment by ayakasuki** [comment]
> > 怎么改

https://github.com/ikechan8370/chatgpt-plugin/issues/406#issuecomment-1545346793

**Comment by ayakasuki** [comment]
#441 已经PR 等审核
