### ISSUE TITLE
希望可以给GPT添加言无不尽功能

### ISSUE THREAD

**Issue by 715494637** [ikechan8370/chatgpt-plugin#432]
参考项目https://github.com/xcanwin/KeepChatGPT/
希望可以添加一个言无不尽的功能，免去对机器人一直发继续的操作
而且一直发继续会是代码些许不连贯，得手动更改（论文也是）
加上这个功能就可以一拉拉到底
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/93782833/4980eb5c-587a-45e9-ad88-dc7a570ef048)

**Comment by ikechan8370** [comment]
我的后端已经支持了 等我有空做到插件里
