### ISSUE TITLE
关于插件5月18日更新后，云转码silk无法适配微软Azure语音合成问题

### ISSUE THREAD

**Issue by GuoDong114514** [ikechan8370/chatgpt-plugin#435]
5月18日更新前，微软Azure语音合成使用正常，更新后，后台显示云转码silk高清语音合成成功，但输出的语音无法播放。个别云转码silk高清语音合成失败的，可以正常播放。vits语音合成可以正常播放，目前仅发现微软Azure语音合成播放异常。

**Comment by ikechan8370** [comment]
今天全面更新了 可以再试试
