### ISSUE TITLE
无法识别getOpenAIAuth

### ISSUE THREAD

**Issue by wuweidmw** [ikechan8370/chatgpt-plugin#44]
![B8D5()RE{FCNE }VOHAIAH4](https://user-images.githubusercontent.com/104341076/207396393-fa8d4598-59a9-420a-8de0-065dc0f5d055.png)

**Comment by wearshoes** [comment]
更新chatgpt包

**Comment by wuweidmw** [comment]
> 更新chatgpt包

![K7LV62PI6`Y@07T{2VIE@8O](https://user-images.githubusercontent.com/104341076/207406603-5d8c31ce-7f1a-4269-83ca-03fb773b83f2.png)
那这个咋办

**Comment by wearshoes** [comment]
不用管

**Comment by wearshoes** [comment]
> > 更新chatgpt包
> 
> ![K7LV62PI6`Y@07T{2VIE@8O](https://user-images.githubusercontent.com/104341076/207406603-5d8c31ce-7f1a-4269-83ca-03fb773b83f2.png) 那这个咋办

不用管

**Comment by wuweidmw** [comment]
> > > 更新chatgpt包
> > 
> > 
> > ![K7LV62PI6'Y@07T{2VIE@8O](https://user-images.githubusercontent.com/104341076/207406603-5d8c31ce-7f1a-4269-83ca-03fb773b83f2.png)那这个咋办
> 
> 不用管

还是那样

**Comment by wearshoes** [comment]
> > > > 更新chatgpt包
> > > 
> > > 
> > > ![K7LV62PI6'Y@07T{2VIE@8O](https://user-images.githubusercontent.com/104341076/207406603-5d8c31ce-7f1a-4269-83ca-03fb773b83f2.png)那这个咋办
> > 
> > 
> > 不用管
> 
> 还是那样

你重启bot了嘛

**Comment by Qz-Sean** [comment]
![image](https://user-images.githubusercontent.com/56262913/207409312-990f0806-7c1a-436f-9e7f-2b59bbf147c7.png)
你这个路径怎么设置的

**Comment by Qz-Sean** [comment]
> 

害，你是Windows

**Comment by wearshoes** [comment]
> ![image](https://user-images.githubusercontent.com/56262913/207409312-990f0806-7c1a-436f-9e7f-2b59bbf147c7.png) 你这个路径怎么设置的

我不是win 我直接空字符串 但是一样不能用 感觉v2目前没考虑过非win系统

**Comment by wuweidmw** [comment]
> 

![X6Q39%SAW{JQWHT R$ 0K$A](https://user-images.githubusercontent.com/104341076/207412044-cdce14ec-3d11-4922-b441-14441f6e24c4.png)
我去更新了18但是就显示2503，换回16也是2503

**Comment by Qz-Sean** [comment]
> > ![image](https://user-images.githubusercontent.com/56262913/207409312-990f0806-7c1a-436f-9e7f-2b59bbf147c7.png) 你这个路径怎么设置的
> 
> 我不是win 我直接空字符串 但是一样不能用 感觉v2目前没考虑过非win系统

我感觉也是

**Comment by wuweidmw** [comment]
> > > > > 更新chatgpt包
> > > > 
> > > > 
> > > > ![K7LV62PI6'Y@07T{2VIE@8O](https://user-images.githubusercontent.com/104341076/207406603-5d8c31ce-7f1a-4269-83ca-03fb773b83f2.png)那这个咋办
> > > 
> > > 
> > > 不用管
> > 
> > 
> > 还是那样
> 
> 你重启bot了嘛

![IZ M(BO%ULD%B44TVL~`)81](https://user-images.githubusercontent.com/104341076/207420172-cff39675-2401-46a6-ac72-4350ad24a385.png)

**Comment by wearshoes** [comment]
一样 这个问题要等作者出解决方案了

**Comment by wearshoes** [comment]
> > > > > > 更新chatgpt包
> > > > > 
> > > > > 
> > > > > ![K7LV62PI6'Y@07T{2VIE@8O](https://user-images.githubusercontent.com/104341076/207406603-5d8c31ce-7f1a-4269-83ca-03fb773b83f2.png)那这个咋办
> > > > 
> > > > 
> > > > 不用管
> > > 
> > > 
> > > 还是那样
> > 
> > 
> > 你重启bot了嘛
> 
> ![IZ M(BO%ULD%B44TVL~`)81](https://user-images.githubusercontent.com/104341076/207420172-cff39675-2401-46a6-ac72-4350ad24a385.png)

一样 这个问题要等作者出解决方案了
