### ISSUE TITLE
Sydney接口403

### ISSUE THREAD

**Issue by it-kirito** [ikechan8370/chatgpt-plugin#440]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述
今天更新插件之后，Bing模式一直403，无法通过验证，尝试了重新获取token也不行。不知道是不是和反代地址更新有关
## 预期行为

请描述您期望系统在出现问题时应该做什么。

## 实际行为

![image](https://github.com/ikechan8370/chatgpt-plugin/assets/66652239/44a6797a-406e-47e0-9567-e2f34f325242)

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。

**Comment by ikechan8370** [comment]
今天微软屏蔽了国内ip，通通403.可以用代理或者把 【Sydney对话使用反代 】钩上

**Comment by ikechan8370** [comment]
然后确保日志输出时使用了wss://【反代】

**Comment by it-kirito** [comment]
> 今天微软屏蔽了国内ip，通通403.可以用代理或者把 【Sydney对话使用反代 】钩上

大佬的反代服务一直为爱发电吗😂

**Comment by ikechan8370** [comment]
> > 今天微软屏蔽了国内ip，通通403.可以用代理或者把 【Sydney对话使用反代 】钩上
> 
> 大佬的反代服务一直为爱发电吗😂

🥺有条件可以爱发电支持一下

**Comment by it-kirito** [comment]
> > > 今天微软屏蔽了国内ip，通通403.可以用代理或者把 【Sydney对话使用反代 】钩上
> > 
> > 
> > 大佬的反代服务一直为爱发电吗😂
> 
> 🥺有条件可以爱发电支持一下

好说好说，我先去注册一个爱发电账号
