### ISSUE TITLE
必应模式错误403

### ISSUE THREAD

**Issue by CICILC** [ikechan8370/chatgpt-plugin#442]
（给大佬发电啦~）
已经勾选了对话时也使用反代依然报错403 这该如何是好

**Comment by ikechan8370** [comment]
不应该，看看日志打印的使用的是wss://什么域名？

**Comment by CICILC** [comment]
![Screenshot_20230524_010928_Termux](https://github.com/ikechan8370/chatgpt-plugin/assets/115946224/a344d0d1-fecf-45a5-948a-7b880dbb8601)
![20230524_011347](https://github.com/ikechan8370/chatgpt-plugin/assets/115946224/980399f5-84a5-45e4-9e9a-16d2f4f6410b)
佬看看后台日志 我没看出来

**Comment by ikechan8370** [comment]
把debug打开再看看

**Comment by CICILC** [comment]
![Uploading Screenshot_20230524_012308_Termux.jpg…]()
我是重新安装的插件重新获取的ck

**Comment by CICILC** [comment]
![Screenshot_20230524_012308_Termux](https://github.com/ikechan8370/chatgpt-plugin/assets/115946224/8326719a-21fc-4688-b7cc-5a0f5918d670)
我是重新安装的插件 重新获取的ck

**Comment by ikechan8370** [comment]
是本插件的debug 锅巴里可以开 你应该是没有走反代才会403

**Comment by CICILC** [comment]
![Screenshot_20230524_012957_Termux](https://github.com/ikechan8370/chatgpt-plugin/assets/115946224/29bf5b2c-e70d-4b79-9940-b05fe39bbfdd)
ε(*´･ω･)з

**Comment by ikechan8370** [comment]
。懂了 你应该是bing模式不是sydney或自设定 那暂时好像没解 换Sydney吧

**Comment by CICILC** [comment]
好的我试试

**Comment by CICILC** [comment]
sydney或自设定确实可以使用
感谢大佬
(›´ω`‹ )

**Comment by leafLeaf9** [comment]
![QQ截图20230524123935](https://github.com/ikechan8370/chatgpt-plugin/assets/53334104/d5fbc7bb-8743-4d30-a4fb-2cbc1284946c)
我是sydney但还是403

**Comment by ikechan8370** [comment]
> ![QQ截图20230524123935](https://github.com/ikechan8370/chatgpt-plugin/assets/53334104/d5fbc7bb-8743-4d30-a4fb-2cbc1284946c)
> 
> 我是sydney但还是403

你发得日志这不还是直连？

**Comment by leafLeaf9** [comment]
> 

开启对话使用反代之后好了，刚才没看到前面的issue...
