### ISSUE TITLE
怎么配置poe?从控制台获取了cookie填进去返回cookie格式不对

### ISSUE THREAD

**Issue by TAROLRO** [ikechan8370/chatgpt-plugin#443]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

请在此处描述您遇到的问题，包括出现问题的环境、您试图实现的功能以及错误信息等。请尽可能详细，以便其他人可以在自己的环境中复制问题。

## 预期行为

请描述您期望系统在出现问题时应该做什么。

## 实际行为

请描述您实际看到的行为。

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。

**Comment by TAROLRO** [comment]
> # 请确保提出问题前更新到最新版本！！！！！！！！
> **请在提交issue前确认你已阅读了以下资料：**
> 
> * 项目的readme文件
> * 其他已有的Issue
> 
> 如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。
> 
> ## 问题描述
> 请在此处描述您遇到的问题，包括出现问题的环境、您试图实现的功能以及错误信息等。请尽可能详细，以便其他人可以在自己的环境中复制问题。
> 
> ## 预期行为
> 请描述您期望系统在出现问题时应该做什么。
> 
> ## 实际行为
> 请描述您实际看到的行为。
> 
> ## 复制过程
> 请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。
> 
> ## 环境
> 请提供您使用的任何相关信息，例如操作系统、版本、配置等。
> 
> ## 可能的解决方案
> 如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。
> 
> ## 附加信息
> 如果有任何其他信息，如日志、截图等，请在此处提供。

![~5LF$ZOZRSR}IHRK7QJ4CIC](https://github.com/ikechan8370/chatgpt-plugin/assets/133837188/1ba76833-ce5e-482a-9a4d-1efad7a7a3f8)

**Comment by ikechan8370** [comment]
p-b=xxx

**Comment by ikechan8370** [comment]
Poe封号频繁 不保证随时能用 建议谨慎使用

**Comment by TAROLRO** [comment]
![UK9@{WGUFL8~~H$6$KM~S{W](https://github.com/ikechan8370/chatgpt-plugin/assets/133837188/31e6ca4d-85ff-4e2c-a8a9-0632f96e5250)
成功了，谢谢佬，不过具体使用poe里面提供的gpt和Claude能在插件里切换吗？

**Comment by ikechan8370** [comment]
还不能 现在写死了a2 就是Claude
