### ISSUE TITLE
Claude通信异常 [ERRO] TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["User-Agent"]

### ISSUE THREAD

**Issue by RhoninSeiei** [ikechan8370/chatgpt-plugin#444]
症状与 https://github.com/ikechan8370/chatgpt-plugin/issues/424 提到的相同。删除依赖重新安装后，短时间恢复数分钟后又遭遇相同问题。

**Comment by TAROLRO** [comment]
同样遇到了这样的问题
![ZVG`)5I
Y08A65YTT{7QC](https://github.com/ikechan8370/chatgpt-plugin/assets/133837188/a0947b79-db4a-45d8-859c-49e2281e6672)

**Comment by RhoninSeiei** [comment]
直接node.js运行不会复现同样问题，npm/pnpm运行会稳定出现，怀疑是依赖版本或者脚本定义问题

**Comment by JY69** [comment]
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/123614017/b64ed7b2-fc59-4e1f-9b5f-af524957aa5c)
+1

**Comment by ghost** [comment]
都是pnpm干的！

**Comment by TAROLRO** [comment]
这个问题有人解决了嘛，蹲一蹲

**Comment by ghost** [comment]
用node app启动试试

**Comment by JY69** [comment]
> 用 node app启动试试

是使用node app启动的，也会出现这个。

**Comment by Fwindy** [comment]
这是项目依赖的slackapi的问题，具体问题出现在下述代码里，不同方法启动bot、不同环境都会导致process.title不同，所以会导致UA的问题

https://github.com/slackapi/node-slack-sdk/blob/3498055d6c86beb82d51ddd583e123461379f5b7/packages/web-api/src/instrument.ts#LL20C1-L20C1

解决方案太多了，一两行代码的事，自己写一个吧

**Comment by Selonite925** [comment]
> 这是项目依赖的slackapi的问题，具体问题出现在下述代码里，不同方法启动bot、不同环境都会导致process.title不同，所以会导致UA的问题
> 
> https://github.com/slackapi/node-slack-sdk/blob/3498055d6c86beb82d51ddd583e123461379f5b7/packages/web-api/src/instrument.ts#LL20C1-L20C1
> 
> 解决方案太多了，一两行代码的事，自己写一个吧

只能说大佬太高估我的编程能力了。要是会用两行代码解决的话我也不会上来问了。。
1不知道写什么
2不知道写好了放哪里
同样的问题，重装了依赖并没有解决，问题出现于今天更新了miao崽和插件之后。已尝试重装依赖和更新，重启，没解决=A=

**Comment by boool369** [comment]
所以现在有办法吗

**Comment by Selonite925** [comment]
> 所以现在有办法吗

有，切换apad协议可以用，但是代价是私聊会寄。根据大佬的说法是之后想办法把useragent固定即可

**Comment by HugeByte** [comment]
有一个解决方法可供参考
这个报错的原因是process.title导致，也就是机器人进程名
通过`ps -ef`可以查看框架的进程名
![1](https://github.com/ikechan8370/chatgpt-plugin/assets/40591485/43924ee4-9170-42a2-b2f9-55aea5ef351e)
此时的进程名可以看出来包含了框架名+qq号+协议，这里有中文，也就是大概率是因为中文导致
解决方法就是去掉进程名带的中文，修改框架中lib/config/init.js中的UpdateTitle()方法
根据自己运行的协议来将中文去掉
![2](https://github.com/ikechan8370/chatgpt-plugin/assets/40591485/a3726e81-c706-4a66-9178-aa3a6ff47e8f)
之后重启即可恢复正常
