### ISSUE TITLE
必应自定义模式状态下画图出现“绘图失败：Error: 绘图失败，请检查Bing token和代理/反代配置”这个是什么情况勒

### ISSUE THREAD

**Issue by ioewhj** [ikechan8370/chatgpt-plugin#449]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

请在此处描述您遇到的问题，包括出现问题的环境、您试图实现的功能以及错误信息等。请尽可能详细，以便其他人可以在自己的环境中复制问题。

## 预期行为

请描述您期望系统在出现问题时应该做什么。

## 实际行为

请描述您实际看到的行为。

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。

**Comment by ioewhj** [comment]
![IMG_0758](https://github.com/ikechan8370/chatgpt-plugin/assets/131784357/96c24fb1-edf2-4703-8518-0eeea1c0efdc)

**Comment by LIHAQ** [comment]
同问

**Comment by ikechan8370** [comment]
只能说是玄学。ip问题为主，反代一直在尝试调整，微软自己还天天报错。

**Comment by ghost** [comment]
先在官网画一次

**Comment by ioewhj** [comment]
> 先在官网画一次

可以用，感谢大佬

**Comment by ioewhj** [comment]
> 只能说是玄学。 ip问题为主，反代一直在尝试调整，微软自己还天天报错。

大佬加油，发个电支持此神级插件
