### ISSUE TITLE
弹出浏览器登录上去了 还是提示403

### ISSUE THREAD

**Issue by zwy321** [ikechan8370/chatgpt-plugin#45]
![image](https://user-images.githubusercontent.com/31528498/207467181-d4e20cd9-1310-4b6e-8e84-31249fbe9366.png)

**Comment by yyk725** [comment]
同样错误

**Comment by ikashana** [comment]
我也出现了这样的错误...插眼等个解决办法。

**Comment by ikechan8370** [comment]
目前我也是，正在测试各种可能的原因。第一天时候还是可以的。发自我的 iPhone在 2022年12月14日，07:26，zwy321 ***@***.***> 写道：﻿

**Comment by Jason-xy** [comment]
遇到了同样的问题。怀疑是调用Puppeteer时对浏览器添加了代理参数，但是在调用chatgpt-api的时候没走这个代理导致访问API的IP与刷新token的IP不匹配。我已经设置为了用Google账号登陆，在浏览器完成登录进入对话框之后确实没看到有对openai.com的请求经过代理服务器。也许独立IP的全局代理可以解决这个问题，但我当前网络环境不太方便测试。
![image](https://user-images.githubusercontent.com/53471811/207939128-17e19348-f6b3-4ffd-8e33-a2746a168f3f.png)

**Comment by ikechan8370** [comment]
当前要求必须同一ip，所以对网络环境要求比较高，由于chatgpt-api目前不支持代理选项，所以所在服务器可能需要全局的透明代理。而且即使这样也可能会403，仍在调查CF的探测手段。发自我的 iPhone在 2022年12月16日，02:30，Jason_xy ***@***.***> 写道：﻿
遇到了同样的问题。怀疑是调用Puppeteer时对浏览器添加了代理参数，但是在调用chatgpt-api的时候没走这个代理导致访问API的IP与刷新token的IP不匹配。我已经设置为了用Google账号登陆，在浏览器完成登录进入对话框之后确实没看到有对openai.com的请求经过代理服务器。也许独立IP的全局代理可以解决这个问题，但我当前网络环境不太方便测试。

**Comment by ikechan8370** [comment]
> 当前要求必须同一ip，所以对网络环境要求比较高，由于chatgpt-api目前不支持代理选项，所以所在服务器可能需要全局的透明代理。而且即使这样也可能会403，仍在调查CF的探测手段。发自我的 iPhone在 2022年12月16日，02:30，Jason_xy ***@***.***> 写道：﻿
> 遇到了同样的问题。怀疑是调用Puppeteer时对浏览器添加了代理参数，但是在调用chatgpt-api的时候没走这个代理导致访问API的IP与刷新token的IP不匹配。我已经设置为了用Google账号登陆，在浏览器完成登录进入对话框之后确实没看到有对openai.com的请求经过代理服务器。也许独立IP的全局代理可以解决这个问题，但我当前网络环境不太方便测试。
> 
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

chatgpt-api作者在最新版本提供了完全基于浏览器的版本，今天有空尝试一下，顺利的话估计能解决这些问题

**Comment by LanYunDev** [comment]
好耶!希望能解决~

**Comment by ikechan8370** [comment]
![f5faa3a5475625a2af6d5d9963f9a3ba](https://user-images.githubusercontent.com/21212372/208046387-21c47b42-9f9e-4822-89d7-ca4bddc77afa.jpg)
api作者提供这个方法验证是可行的，机器人久违地回复我了。等我整理一下逻辑推一下

**Comment by LingNc** [comment]
我这边还是登不上,403 Forbidden

**Comment by LanYunDev** [comment]
刚刚更新了试试看、、

**Comment by Jason-xy** [comment]
> 刚刚更新了试试看、、

遇到一个报错，是哪里没配置正确吗？
![image](https://user-images.githubusercontent.com/53471811/208127785-6db56bde-b890-411b-a7ab-954ae21631b1.png)
![image](https://user-images.githubusercontent.com/53471811/208127853-c8d8ece9-983b-4800-a79b-3871129ceb9b.png)

**Comment by LanYunDev** [comment]
<img width="736" alt="image" src="https://user-images.githubusercontent.com/95263282/208133448-3c460576-6956-4db3-88c3-137df1981df3.png">
俺也一样

**Comment by Jason-xy** [comment]
刚登陆的号，直接用浏览器对话也不行了
![image](https://user-images.githubusercontent.com/53471811/208133685-78353fd1-c162-4b0e-90ba-ee8501aa48ee.png)

**Comment by LanYunDev** [comment]
我用其他号发消息试了下,每发一条都要进行一次登录.设备mac系统最新版,chrome最新版,不知道为啥走的无痕模式.,
![IMG_CB5AF469C68F-1](https://user-images.githubusercontent.com/95263282/208135104-056cf094-accc-4e0e-be59-b0a3b17a213e.jpeg)

**Comment by LingNc** [comment]
> 

对，每次都要登录，不能衔接上下文了

**Comment by LingNc** [comment]
> 我用其他号发消息试了下,每发一条都要进行一次登录.设备mac系统最新版,chrome最新版,不知道为啥走的无痕模式., ![IMG_CB5AF469C68F-1](https://user-images.githubusercontent.com/95263282/208135104-056cf094-accc-4e0e-be59-b0a3b17a213e.jpeg)

对，每次都要登录，不能衔接上下文了
