### ISSUE TITLE
载入插件错误！SyntaxError: Unexpected token ':'   |   [Guoba] 载入guoba.support.js失败：Unexpected token ':'

### ISSUE THREAD

**Issue by FruityMaxine** [ikechan8370/chatgpt-plugin#454]
无法正常启动
<img width="719" alt="捕获" src="https://github.com/ikechan8370/chatgpt-plugin/assets/89344622/751fd24d-fbbb-49d8-81b4-5f747939e996">

node版本20.2

- 仅安装了此插件，仅重命名config配置文件，并未编辑，是想通过Guoba插件来进行配置，但遇到了问题，无法启动
## 预期行为

正常启动

## 实际行为

- 错误！
  错误消息中指出了一个语法错误："SyntaxError: Unexpected token ':'"。该错误发生在ESMLoader.moduleStrategy函数的第119行，ESMLoader.moduleProvider函数的第468行，以及async link函数的第67行。同时，还提到了在载入guoba.support.js时出现了类似的错误。

这个错误表明在解析代码时遇到了一个意外的令牌 "："，即冒号。这种情况通常是因为在代码中使用了不正确的语法或符号导致的。在这个特定的情况下，可能是由于Guoba插件的代码与当前环境或系统不兼容所导致的。

## 复制过程
cd Yunzai根目录
node app

## 环境
- 系统
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
- 内核
5.15.0-46-generic
- 硬件信息
525ugpt                     
    description: Computer
    product: KVM
    vendor: Red Hat
    version: RHEL 7.6.0 PC (i440FX + PIIX, 1996)
    width: 64 bits
    capabilities: smbios-2.8 dmi-2.8 vsyscall32
    configuration: boot=normal family=Red Hat Enterprise Linux uuid=92b7df26-53f6-4513-bb07-7f687ce569a0
  *-core
       description: Motherboard
       physical id: 0
     *-firmware
          description: BIOS
          vendor: SeaBIOS
          physical id: 0
          version: 1.11.0-2.el7
          date: 04/01/2014
          size: 96KiB
     *-cpu
          description: CPU
          product: Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
          vendor: Intel Corp.
          physical id: 400
          bus info: cpu@0
          version: 6.62.4
          slot: CPU 0
          size: 2GHz
          capacity: 2GHz
          width: 64 bits
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp x86-64 constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust smep erms xsaveopt arat md_clear
          configuration: cores=1 enabledcores=1 microcode=1 threads=1
     *-memory
          description: System Memory
          physical id: 1000
          size: 1GiB
          capacity: 1GiB
          capabilities: ecc
          configuration: errordetection=multi-bit-ecc
        *-bank
             description: DIMM RAM
             vendor: Red Hat
             physical id: 0
             slot: DIMM 0
             size: 1GiB
     *-pci
          description: Host bridge
          product: 440FX - 82441FX PMC [Natoma]
          vendor: Intel Corporation
          physical id: 100
          bus info: pci@0000:00:00.0
          version: 02
          width: 32 bits
          clock: 33MHz
        *-isa
             description: ISA bridge
             product: 82371SB PIIX3 ISA [Natoma/Triton II]
             vendor: Intel Corporation
             physical id: 1
             bus info: pci@0000:00:01.0
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: isa
             configuration: latency=0
           *-pnp00:00
                product: PnP device PNP0b00
                physical id: 0
                capabilities: pnp
                configuration: driver=rtc_cmos
           *-pnp00:01
                product: PnP device PNP0303
                physical id: 1
                capabilities: pnp
                configuration: driver=i8042 kbd
           *-pnp00:02
                product: PnP device PNP0f13
                physical id: 2
                capabilities: pnp
                configuration: driver=i8042 aux
           *-pnp00:03
                product: PnP device PNP0700
                physical id: 3
                capabilities: pnp
        *-ide
             description: IDE interface
             product: 82371SB PIIX3 IDE [Natoma/Triton II]
             vendor: Intel Corporation
             physical id: 1.1
             bus info: pci@0000:00:01.1
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: ide isa_compat_mode bus_master
             configuration: driver=ata_piix latency=0
             resources: irq:0 ioport:1f0(size=8) ioport:3f6 ioport:170(size=8) ioport:376 ioport:c0a0(size=16)
        *-usb
             description: USB controller
             product: 82371SB PIIX3 USB [Natoma/Triton II]
             vendor: Intel Corporation
             physical id: 1.2
             bus info: pci@0000:00:01.2
             version: 01
             width: 32 bits
             clock: 33MHz
             capabilities: uhci bus_master
             configuration: driver=uhci_hcd latency=0
             resources: irq:11 ioport:c040(size=32)
           *-usbhost
                product: UHCI Host Controller
                vendor: Linux 5.15.0-46-generic uhci_hcd
                physical id: 1
                bus info: usb@1
                logical name: usb1
                version: 5.15
                capabilities: usb-1.10
                configuration: driver=hub slots=2 speed=12Mbit/s
              *-usb
                   description: Human interface device
                   product: QEMU QEMU USB Tablet
                   vendor: QEMU
                   physical id: 1
                   bus info: usb@1:1
                   logical name: input5
                   logical name: /dev/input/event4
                   logical name: /dev/input/mouse2
                   version: 0.00
                   serial: 42
                   capabilities: usb-2.00 usb
                   configuration: driver=usbhid maxpower=100mA speed=12Mbit/s
        *-bridge
             description: Bridge
             product: 82371AB/EB/MB PIIX4 ACPI
             vendor: Intel Corporation
             physical id: 1.3
             bus info: pci@0000:00:01.3
             version: 03
             width: 32 bits
             clock: 33MHz
             capabilities: bridge
             configuration: driver=piix4_smbus latency=0
             resources: irq:9
        *-display
             description: VGA compatible controller
             product: GD 5446
             vendor: Cirrus Logic
             physical id: 2
             bus info: pci@0000:00:02.0
             logical name: /dev/fb0
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: vga_controller rom fb
             configuration: depth=16 driver=cirrus latency=0 resolution=1024,768
             resources: irq:0 memory:fc000000-fdffffff memory:febd4000-febd4fff memory:c0000-dffff
        *-network
             description: Ethernet controller
             product: Virtio network device
             vendor: Red Hat, Inc.
             physical id: 3
             bus info: pci@0000:00:03.0
             version: 00
             width: 64 bits
             clock: 33MHz
             capabilities: msix bus_master cap_list rom
             configuration: driver=virtio-pci latency=0
             resources: irq:10 ioport:c060(size=32) memory:febd5000-febd5fff memory:fe000000-fe003fff memory:feb80000-febbffff
           *-virtio0
                description: Ethernet interface
                physical id: 0
                bus info: virtio@0
                logical name: eth0
                serial: 00:16:3e:8b:d1:06
                capabilities: ethernet physical
                configuration: autonegotiation=off broadcast=yes driver=virtio_net driverversion=1.0.0 ip=198.52.123.145 link=yes multicast=yes
        *-multimedia
             description: Audio device
             product: 82801FB/FBM/FR/FW/FRW (ICH6 Family) High Definition Audio Controller
             vendor: Intel Corporation
             physical id: 4
             bus info: pci@0000:00:04.0
             logical name: card0
             logical name: /dev/snd/controlC0
             logical name: /dev/snd/hwC0D0
             logical name: /dev/snd/pcmC0D0c
             logical name: /dev/snd/pcmC0D0p
             version: 01
             width: 32 bits
             clock: 33MHz
             capabilities: msi bus_master cap_list
             configuration: driver=snd_hda_intel latency=0
             resources: irq:29 memory:febd0000-febd3fff
        *-scsi
             description: SCSI storage controller
             product: Virtio block device
             vendor: Red Hat, Inc.
             physical id: 5
             bus info: pci@0000:00:05.0
             version: 00
             width: 64 bits
             clock: 33MHz
             capabilities: scsi msix bus_master cap_list
             configuration: driver=virtio-pci latency=0
             resources: irq:10 ioport:c000(size=64) memory:febd6000-febd6fff memory:fe004000-fe007fff
           *-virtio1
                description: Virtual I/O device
                physical id: 0
                bus info: virtio@1
                logical name: /dev/vda
                size: 30GiB (32GB)
                capabilities: gpt-1.00 partitioned partitioned:gpt
                configuration: driver=virtio_blk guid=ce7dea5b-78a5-4752-91b0-301260c2d263 logicalsectorsize=512 sectorsize=512
              *-volume:0
                   description: EXT4 volume
                   vendor: Linux
                   physical id: 1
                   bus info: virtio@1,1
                   logical name: /dev/vda1
                   logical name: /
                   version: 1.0
                   serial: 4d1266d2-c1f9-4087-af92-2d60c8c153e4
                   size: 28GiB
                   capacity: 28GiB
                   capabilities: journaled extended_attributes large_files huge_files dir_nlink 64bit extents ext4 ext2 initialized
                   configuration: created=2022-08-03 08:15:04 filesystem=ext4 label=root lastmountpoint=/home/v49153/0 modified=2023-05-28 08:41:58 mount.fstype=ext4 mount.options=rw,relatime mounted=2023-05-28 08:41:20 name=Linux filesystem state=mounted
              *-volume:1
                   description: Linux swap volume
                   vendor: Linux
                   physical id: 2
                   bus info: virtio@1,2
                   logical name: /dev/vda2
                   version: 1
                   serial: 3be0b32c-08bb-4771-b4f7-e841b4dde448
                   size: 1022MiB
                   capacity: 1022MiB
                   capabilities: nofs swap initialized
                   configuration: filesystem=swap name=Linux swap pagesize=4096
        *-generic
             description: Unclassified device
             product: Virtio memory balloon
             vendor: Red Hat, Inc.
             physical id: 6
             bus info: pci@0000:00:06.0
             version: 00
             width: 64 bits
             clock: 33MHz
             capabilities: bus_master cap_list
             configuration: driver=virtio-pci latency=0
             resources: irq:11 ioport:c080(size=32) memory:fe008000-fe00bfff
           *-virtio2 UNCLAIMED
                description: Virtual I/O device
                physical id: 0
                bus info: virtio@2
                configuration: driver=virtio_balloon
  *-input:0
       product: Power Button
       physical id: 1
       logical name: input0
       logical name: /dev/input/event0
       capabilities: platform
  *-input:1
       product: AT Translated Set 2 keyboard
       physical id: 2
       logical name: input1
       logical name: /dev/input/event1
       logical name: input1::capslock
       logical name: input1::numlock
       logical name: input1::scrolllock
       capabilities: i8042
  *-input:2
       product: VirtualPS/2 VMware VMMouse
       physical id: 3
       logical name: input3
       logical name: /dev/input/event3
       logical name: /dev/input/mouse1
       capabilities: i8042
  *-input:3
       product: VirtualPS/2 VMware VMMouse
       physical id: 4
       logical name: input4
       logical name: /dev/input/event2
       logical name: /dev/input/mouse0
       capabilities: i8042

- 内存信息
                    total          used          free         shared   buff/cache   available
Mem:           969Mi       288Mi       220Mi       2.0Mi       459Mi       518Mi
Swap:          1.0Gi         1.0Mi          1.0Gi

## 可能的解决方案

未知

## config.js 如下：
{
  "blockWords": ["屏蔽词1", "屏蔽词b"],
  "promptBlockWords": ["屏蔽词1", "屏蔽词b"],
  "imgOcr": true,
  "defaultUsePicture": false,
  "defaultUseTTS": false,
  "defaultTTSRole": "纳西妲",
  "alsoSendText": false,
  "autoUsePicture": true,
  "autoUsePictureThreshold": 1200,
  "ttsAutoFallbackThreshold": 99,
  "conversationPreserveTime": 0,
  "toggleMode": "at",
  "quoteReply": true,
  "showQRCode": true,
  "cacheUrl": "https://content.alcedogroup.com",
  "cacheEntry": false,
  "apiKey": "",
  "openAiBaseUrl": "",
  "openAiForceUseReverse": false,
  "drawCD": 30,
  "model": "",
  "temperature": 0.8,
  "toneStyle": "balanced",
  "sydney": "",
  "sydneyReverseProxy": "",
  "sydneyForceUseReverse": false,
  "sydneyWebsocketUseProxy": false,
  "sydneyBrainWash": true,
  "sydneyBrainWashStrength": 15,
  "sydneyBrainWashName": "Sydney",
  "sydneyMood": false,
  "enableSuggestedResponses": false,
  "api": "",
  "apiBaseUrl": "",
  "apiForceUseReverse": false,
  "plus": false,
  "useGPT4": false,
  "promptPrefixOverride": "Your answer shouldn\"t be too verbose. Prefer to answer in Chinese.",
  "assistantLabel": "ChatGPT",
  "username": "",
  "password": "",
  "UA": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
  "headless": false,
  "chromePath": "",
  "2captchaToken": "",
  "proxy": "",
  "debug": true,
  "defaultTimeoutMs": 120000,
  "chromeTimeoutMS": 120000,
  "sydneyFirstMessageTimeout": 40000,
  "ttsSpace": "",
  "huggingFaceReverseProxy": "",
  "noiseScale": 0.6,
  "noiseScaleW": 0.668,
  "lengthScale": 1.2,
  "initiativeChatGroups": [],
  "enableDraw": true,
  "helloPrompt": "写一段话让大家来找我聊天。类似于“有人找我聊天吗？“这种风格，轻松随意一点控制在20个字以内",
  "helloInterval": 3,
  "helloProbability": 50,
  "chatglmBaseUrl": "http://localhost:8080",
  "allowOtherMode": true,
  "sydneyContext": "",
  "emojiBaseURL": "https://www.gstatic.com/android/keyboard/emojikitchen",
  "enableGroupContext": false,
  "groupContextLength": 50,
  "enableRobotAt": true,
  "maxNumUserMessagesInConversation": 20,
  "sydneyApologyIgnored": true,
  "enforceMaster": false,
  "enablePrivateChat": false,
  "groupWhitelist": [],
  "groupBlacklist": [],
  "ttsRegex": "/匹配规则/匹配模式",
  "baiduTranslateAppId": "",
  "baiduTranslateSecret": "",
  "azureTTSSpeaker": "zh-CN-XiaochenNeural",
  "azureTTSEmotion": false,
  "enhanceAzureTTSEmotion": false,
  "autoJapanese": false
}

**Comment by ghost** [comment]
能提供一下你的chatgpt-plugin文件夹吗

**Comment by FruityMaxine** [comment]
> 能提供一下你的chatgpt-plugin文件夹吗

整个文件夹吗？没法上传文件夹，我可以给你指定文件

**Comment by FruityMaxine** [comment]
重装解决问题，原因不明。
