### ISSUE TITLE
【功能请求】GPT人格预设模块，实现不同人格快速切换

### ISSUE THREAD

**Issue by FruityMaxine** [ikechan8370/chatgpt-plugin#456]
**你的功能请求是否与某个问题有关？请描述。**

- 否

**描述你想要的功能**

希望可以通过类似管理员指令：
- #预设 猫娘

自动切换为喵娘人格(手动配置过的或插件自带的)
而不必进入锅巴插件手动修改配置

**Comment by ghost** [comment]
你肯定没看帮助

**Comment by FruityMaxine** [comment]
> 你肯定没看帮助

好吧😥
