### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by luanyaolingwu** [ikechan8370/chatgpt-plugin#460]
**你的功能请求是否与某个问题有关？请描述。**
否。

**描述你想要的解决方案**
添加对MiraiConsole的支持，使其可以作为mirai的插件加载

**描述你已经考虑的替代方案**
mirai本身已有New Bing 插件
```
https://github.com/cssxsh/mirai-new-bing
```
但就目前来看，mirai本身new bing的插件易用性不如此插件，希望大佬做出对mcl的适配

**附加说明**
无。

**Comment by ikechan8370** [comment]
v3版本会拆分，然后考虑扩展到其他机器人框架
