### ISSUE TITLE
必应模式持续跳验证码

### ISSUE THREAD

**Issue by PrussianBlueCN** [ikechan8370/chatgpt-plugin#468]
CaptchaChallenge
User needs to solve CAPTCHA to continue.
undefined
重新设置token、换号设置token都不管用，浏览器上没遇到验证码，各种问题合集没见到这个问题

**Comment by ikechan8370** [comment]
不是很好复现，所以暂时不好处理

**Comment by ChaselDutt** [comment]
我也碰到了

[MiaoYz][17:25:38.940][ERRO] CaptchaChallenge
User needs to solve CAPTCHA to continue.
undefined
[MiaoYz][17:25:38.941][INFO] {
  text: 'CaptchaChallenge\nUser needs to solve CAPTCHA to continue.\nundefined',
  error: true
}

**Comment by linkin3958** [comment]
+1

**Comment by ikechan8370** [comment]
我要是能遇到就能尝试用2captcha绕过了。你们可以把token删除再试试，不带任何token去使用

**Comment by linkin3958** [comment]
> 我要是能遇到就能尝试用2captcha绕过了。你们可以把token删除再试试，不带任何token去使用

![image](https://github.com/ikechan8370/chatgpt-plugin/assets/131190774/669da3c5-bd1a-4f21-93c9-87d8e54ec573)
删除了token，但好像没用

**Comment by linkin3958** [comment]
可能是ip问题，我tm一顿换，然后就好了（

**Comment by Catrong** [comment]
必应模式的验证码不能用2captcha解决吗？为什么我设置了2captcha的token还是会跳验证码，而且自己用浏览器不会遇到验证码

**Comment by Guluniky** [comment]
打开newbing，然后随便输入一段话就会跳出验证码，点击确认就能恢复对话了

**Comment by syp1999** [comment]
> 打开newbing，然后随便输入一段话就会跳出验证码，点击确认就能恢复对话了

亲测有效，用同一个微软账户登录的浏览器打开NewBing聊天，会弹出人机验证，通过之后，Bot内聊天的验证就没了。非常感谢！
