### ISSUE TITLE
载入插件错误：chat

### ISSUE THREAD

**Issue by 199Sie** [ikechan8370/chatgpt-plugin#47]
安装方法均正确 nodejs的版本为18.12.1.0

![image_63](https://user-images.githubusercontent.com/77106879/207483096-1da43f52-ec93-4ecf-b1df-4c4ae3e0ce9a.png)

**Comment by yyk725** [comment]
uuid没装？（猜测
pnpm install uuid试试

**Comment by sora-yyds** [comment]
![image](https://user-images.githubusercontent.com/121120012/208721981-b8bd3f42-4dc0-4416-8fb8-32446c6b67da.png)
![image](https://user-images.githubusercontent.com/121120012/208722164-1d1ddaaf-a5e1-4576-adcc-cb32f00585f8.png)
按你说的装了uuid还是不行@Dream-yyk

**Comment by YunMu13** [comment]
同样，请问解决没?

**Comment by hello-2021** [comment]
> ![图像](https://user-images.githubusercontent.com/121120012/208721981-b8bd3f42-4dc0-4416-8fb8-32446c6b67da.png) ![图像](https://user-images.githubusercontent.com/121120012/208722164-1d1ddaaf-a5e1-4576-adcc-cb32f00585f8.png)按你说的装了uuid还是不行@Dream-yyk

我也是这个问题，一直提示找不到uuid
![image](https://user-images.githubusercontent.com/53700491/209952944-2212ed29-e541-4a73-a0a7-17ee787781b8.png)

**Comment by hello-2021** [comment]
同问

[YzBot][17:54:48.682][ERRO] 载入插件错误：chat
[YzBot][17:54:48.682][ERRO] Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'u
uid' imported from H:\projects\qqbot\Yunzai-Bot\plugins\chatgpt-plugin\utils\bro
wser.js
    at new NodeError (node:internal/errors:393:5)
    at packageResolve (node:internal/modules/esm/resolve:860:9)
    at moduleResolve (node:internal/modules/esm/resolve:909:20)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

已经通过 npm install uuid 安装了 uuid，试过-g全局安装，但是还是报错
看了下安装目录，貌似uuid没装上，但是再装也没用
C:\Users\...>npm install uuid

up to date, audited 5 packages in 1s

found 0 vulnerabilities

有没有办法解决，或者用其他方案替代uuid？
求助！！！

**Comment by YunMu13** [comment]
> 同问
> 
> [YzBot][17:54:48.682][ERRO] 载入插件错误：聊天 [YzBot][17：54：48.682][ERRO] 错误 [ERR_MODULE_NOT_FOUND]：找不到从 H：\projects\qqbot\Yunzai-Bot\plugins\chatgpt-plugin\utils\bro wser.js at new NodeError （node：internal/errors：393：5） at packageResolve （node：internal/modules/esm/resolve：860：9） at moduleResolve （node：internal/modules/esm/resolve：909：20） at defaultResolve （node：internal/modules/esm/resolve：1124：11） at nextResolve （node：internal/modules/esm/loader：163：28） at ESMLoader.resolve （node：internal/modules/esm/loader：841：30） at ESMLoader.getModuleJob （node：internal/modules/esm/loader：424：18） at ModuleWrap。（节点：内部/模块/ESM/module_job：76：40） at link （node：internal/modules/esm/module_job：75：36） { code： 'ERR_MODULE_NOT_FOUND' }
> 
> 已经通过 npm install uuid 安装了 uuid，试过-g全局安装，但是还是报错 看了下安装目录，貌似uuid没装上，但是再装也没用 C：\Users...>npm 安装 uuid
> 
> 最新，在 1 秒内审核了 5 个包装
> 
> 发现 0 个漏洞
> 
> 有没有办法解决，或者用其他方案替代uuid？ 求助!!!

**Comment by YunMu13** [comment]
> 同问
> 
> [YzBot][17:54:48.682][ERRO] 载入插件错误：聊天 [YzBot][17：54：48.682][ERRO] 错误 [ERR_MODULE_NOT_FOUND]：找不到从 H：\projects\qqbot\Yunzai-Bot\plugins\chatgpt-plugin\utils\bro wser.js at new NodeError （node：internal/errors：393：5） at packageResolve （node：internal/modules/esm/resolve：860：9） at moduleResolve （node：internal/modules/esm/resolve：909：20） at defaultResolve （node：internal/modules/esm/resolve：1124：11） at nextResolve （node：internal/modules/esm/loader：163：28） at ESMLoader.resolve （node：internal/modules/esm/loader：841：30） at ESMLoader.getModuleJob （node：internal/modules/esm/loader：424：18） at ModuleWrap。（节点：内部/模块/ESM/module_job：76：40） at link （node：internal/modules/esm/module_job：75：36） { code： 'ERR_MODULE_NOT_FOUND' }
> 
> 已经通过 npm install uuid 安装了 uuid，试过-g全局安装，但是还是报错 看了下安装目录，貌似uuid没装上，但是再装也没用 C：\Users...>npm 安装 uuid
> 
> 最新，在 1 秒内审核了 5 个包装
> 
> 发现 0 个漏洞
> 
> 有没有办法解决，或者用其他方案替代uuid？ 求助!!!
[#79 ](https://github.com/ikechan8370/chatgpt-plugin/issues/79#issuecomment-1364613114)我是#79解决的，你是在机器人根目录右键GIT here装的吗

**Comment by hello-2021** [comment]
> 


都试过
在根目录安装会直接卡死，我试过放置很久，到最后会报错

**Comment by hello-2021** [comment]
> > 同问
> > [YzBot][17:54:48.682][ERRO] 载入插件错误：聊天 [YzBot][17：54：48.682][ERRO] 错误 [ERR_MODULE_NOT_FOUND]：找不到从 H：\projects\qqbot\Yunzai-Bot\plugins\chatgpt-plugin\utils\bro wser.js at new NodeError （node：internal/errors：393：5） at packageResolve （node：internal/modules/esm/resolve：860：9） at moduleResolve （node：internal/modules/esm/resolve：909：20） at defaultResolve （node：internal/modules/esm/resolve：1124：11） at nextResolve （node：internal/modules/esm/loader：163：28） at ESMLoader.resolve （node：internal/modules/esm/loader：841：30） at ESMLoader.getModuleJob （node：internal/modules/esm/loader：424：18） at ModuleWrap。（节点：内部/模块/ESM/module_job：76：40） at link （node：internal/modules/esm/module_job：75：36） { code： 'ERR_MODULE_NOT_FOUND' }
> > 已经通过 npm install uuid 安装了 uuid，试过-g全局安装，但是还是报错 看了下安装目录，貌似uuid没装上，但是再装也没用 C：\Users...>npm 安装 uuid
> > 最新，在 1 秒内审核了 5 个包装
> > 发现 0 个漏洞
> > 有没有办法解决，或者用其他方案替代uuid？ 求助!!!
> > [#79 ](https://github.com/ikechan8370/chatgpt-plugin/issues/79#issuecomment-1364613114)我是#79解决的，你是在机器人根目录右键GIT here装的吗

都试过
在根目录安装会直接卡死，我试过放置很久，到最后会报错

**Comment by hello-2021** [comment]
> > 同问
> > [YzBot][17:54:48.682][ERRO] 载入插件错误：聊天 [YzBot][17：54：48.682][ERRO] 错误 [ERR_MODULE_NOT_FOUND]：找不到从 H：\projects\qqbot\Yunzai-Bot\plugins\chatgpt-plugin\utils\bro wser.js at new NodeError （node：internal/errors：393：5） at packageResolve （node：internal/modules/esm/resolve：860：9） at moduleResolve （node：internal/modules/esm/resolve：909：20） at defaultResolve （node：internal/modules/esm/resolve：1124：11） at nextResolve （node：internal/modules/esm/loader：163：28） at ESMLoader.resolve （node：internal/modules/esm/loader：841：30） at ESMLoader.getModuleJob （node：internal/modules/esm/loader：424：18） at ModuleWrap。（节点：内部/模块/ESM/module_job：76：40） at link （node：internal/modules/esm/module_job：75：36） { code： 'ERR_MODULE_NOT_FOUND' }
> > 已经通过 npm install uuid 安装了 uuid，试过-g全局安装，但是还是报错 看了下安装目录，貌似uuid没装上，但是再装也没用 C：\Users...>npm 安装 uuid
> > 最新，在 1 秒内审核了 5 个包装
> > 发现 0 个漏洞
> > 有没有办法解决，或者用其他方案替代uuid？ 求助!!!
> > [#79 ](https://github.com/ikechan8370/chatgpt-plugin/issues/79#issuecomment-1364613114)我是#79解决的，你是在机器人根目录右键GIT here装的吗

用您推荐的方法解决了，感谢！（不过好像有点容易掉线
