### ISSUE TITLE
bing模式Sydney与bing都无法使用

### ISSUE THREAD

**Issue by abc563216** [ikechan8370/chatgpt-plugin#477]
在使用Sydney时会出现request to https://666102.201666.xyz/turing/conversation/create failed, reason: connect ETIMEDOUT 2406:da14:4ce:fd3a:cc47:16f0:307b:4e12:443，而在切换成bing的三种模式时均有fetch failed报错

**Comment by ikechan8370** [comment]
域名AAAA记录忘了换，暂时删除该记录了。等一会缓存刷新应该就恢复了

**Comment by abc563216** [comment]
哦，好的
