### ISSUE TITLE
Cannot read properties of null (reading 'findIndex')

### ISSUE THREAD

**Issue by ldx1024** [ikechan8370/chatgpt-plugin#478]
重新安装了一遍plugin后只改变勾选了1.强制使用sydney反代2.对话使用sydney反代。并把bing模式改成了Sydney。输入#bing你好后运行持续了40多秒，相同的过程重复了三遍，最后Cannot read properties of null (reading 'findIndex')，命令行显示把消息抓回来了，
但是输出的时候出问题了

**Comment by ldx1024** [comment]
![微信图片_20230610145015](https://github.com/ikechan8370/chatgpt-plugin/assets/136151767/e1ce6c44-8026-4db6-b3f6-676b5f59cd2c)

**Comment by shui45** [comment]
同问，有解了吗
