### ISSUE TITLE
API3模式使用GPT4报错429

### ISSUE THREAD

**Issue by SmallSpider0** [ikechan8370/chatgpt-plugin#480]
出现错误：{"error":{"message":"Only one message at a time. Please allow any other responses to complete before sending another message, or wait one minute.","statusCode":429,"statusText":""}}

注：
插件已更新到最新版本，在网页端和app端可正常使用GPT4
插件API3模式可正常使用GPT3.5模型，而使用GPT4报错如上

**Comment by ikenxuan** [comment]
翻译过来，短时间请求次数过多

**Comment by SmallSpider0** [comment]
我确定不是请求过多的问题：首先，在bot报429错误的情况下，网页端GPT4可以正常使用。 其次，如果真的是短时间请求过多导致，我一个晚上（至少8小时）没用GPT4，这时间已经够长了，早上在bot中使用GPT4依旧报429错误。

**Comment by HumbleOrange** [comment]
我也遇到了这个问题

**Comment by RamSong** [comment]
出现错误：{"error":{"message":"Conversation not found","statusCode":404,"statusText":"","code":"conversation_not_found"}}
我是报404，api3

**Comment by boygoboy** [comment]
应该是接口坏了我测试了下也是报429，大概率是官方加了什么验证

**Comment by ikechan8370** [comment]
> 应该是接口坏了我测试了下也是报429，大概率是官方加了什么验证

对的，加了好几天了，加了session验证，目前只影响gpt4。我最近没时间研究这个，以后看能不能解决。

**Comment by boygoboy** [comment]
> > 应该是接口坏了我测试了下也是报429，大概率是官方加了什么验证
> 
> 对的，加了好几天了，加了session验证，目前只影响gpt4。我最近没时间研究这个，以后看能不能解决。

![image](https://github.com/ikechan8370/chatgpt-plugin/assets/63287495/764db8b0-aec7-41b2-a18d-c9f92a1808ae)
尴尬了 挺难搞的要逆向破解这两个接口过验证，加油大佬

**Comment by ikechan8370** [comment]
emmm。我没plus号，暂时不会做这个。

**Comment by boygoboy** [comment]
> emmm。我没plus号，暂时不会做这个。
那个获取arkose_token值的接口bda加密参数我把它破解了，但是请求是400可能有什么cf验证，下面是破解源码希望有帮助。
https://cowtransfer.com/s/625739fdba2147 点击链接查看 [ gpt-demo.rar ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 pc5zqm 查看；
点击获取bda大致会得到下面的结果：
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/63287495/456ad3e6-8986-4a71-80a3-67d654466727)
