### ISSUE TITLE
bing增加了验证机制，导致CaptchaChallenge报错

### ISSUE THREAD

**Issue by ZaraZackBee** [ikechan8370/chatgpt-plugin#503]
## 问题描述

bing的token获取方式（输入代码）貌似不能用了，不过手动获取还是没问题。这个不是我想问的，只是顺带提一下。

bing增加了类似验证的机制，导致CaptchaChallenge报错……尚不明确是我这边网页端进不去才出现的还是需要手动进入一次网页端问过话才算验证成功

## 复制过程

遇到报错——#chatgpt更新——强制更新——重启——还是不行——隔两天——还是不行——上网页端重新获取toiken——重定向——终于进入了网页端登录账号——#chat问话——还是不行——网页端向bing问话——显示“”验证成功”——#chat问话——恢复正常

## 环境

win11自搭建在电脑上的原版云崽

## 可能的解决方案

应该就是去网页端和bing说句话就能验证成功，但如果我没有被重定向，机器人能否自己解决验证问题呢？
![)TD_0S7SW684122%G`BS)PB](https://github.com/ikechan8370/chatgpt-plugin/assets/138028030/b1a4b80a-aa5a-4d3e-8375-d87ed4ef4093)

**Comment by ghost** [comment]
额

**Comment by ghost** [comment]
这都是好久之前的问题了

**Comment by Xcating** [comment]
不用看了，这个验证码是不可能免费给你解决的，不像米游社可以bypass

**Comment by Xcating** [comment]
刚刚看到，群主已经在做插件内手动过验证码了

**Comment by ikechan8370** [comment]
重构了反代机制 可以再使用一段时间看看还有没有验证码

**Comment by ZaraZackBee** [comment]
❤️❤️❤️❤️❤️，原来早就有这个情况的嘛，我倒是头一次遇到，也没在之前的报错里面找到，可能是太久远了~大佬太强辣！

**Comment by ikechan8370** [comment]
遇到验证码的解决方案：
1. 如果是用了自己的token，请像楼主一样登自己的号到网页版过码，如果还是不行就重新获取token，然后用`#chatgpt删除必应token`删掉机器人的对应token重新添加。
2. 如果上述方法不行，就删掉所有token，裸对话试试吧。
3. 仍然不行的，请在此issue分享你的经历，附上你使用的方法（代理/反代，哪个反代/自己怎么搭的反代等）

**Comment by AthanaD** [comment]
出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说的我就当作没看见。
CaptchaChallenge: User needs to solve CAPTCHA to continue.

**Comment by ikechan8370** [comment]
各位可以体验一下新的分支 captcha
在有token的情况下，出现验证码会自动尝试解决。
注意：无token的情况下不行
