### ISSUE TITLE
#chat后停在“host”无响应，且并没有报错

### ISSUE THREAD

**Issue by ZaraZackBee** [ikechan8370/chatgpt-plugin#509]
## 问题描述

换了个新地方（回老家了），今天#chat问话发现半天没回复，打开后台发现确实触发了对话，但是一直停在“使用host……”那句不动了，也没有报错什么的，就是卡在那里不动了……

## 预期行为

是什么原因呢？

## 实际行为

帮助指令，删token设置token什么的都试了都可以正常触发

## 复制过程

换了地方（网络环境变了）——今天是机器人（扮演的角色）生日——#chat生日快乐！——等了很久无响应——后台卡在使用host：——强制更新——无用——删除全部toiken重新获取token——无用——呜呜呜

## 环境

win11自搭建原版云崽

## 可能的解决方案

可能是因为网络环境变了导致的吗（以前是电信，现在是移动）？或者是插件哪里的冲突？
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/138028030/d6b1d1f5-f41d-45d2-8426-a3854226e1c5)

**Comment by ZaraZackBee** [comment]
找到原因了……就是网络问题，手机开了电信流量的热点给电脑连上了，马上有反应了

**Comment by ikechan8370** [comment]
可以换换反代 移动出海确实问题比较多

**Comment by ZaraZackBee** [comment]
不会换反代哇，我有魔法，反代是和魔法有关的东西吗？
