### ISSUE TITLE
chat.js的第217行多了个w

### ISSUE THREAD

**Issue by E-x-plosion** [ikechan8370/chatgpt-plugin#51]
![QQ截图20221214162458](https://user-images.githubusercontent.com/100987618/207544908-d908de70-59a1-4c17-870a-c1752348c865.png)
纯小白，谷歌翻译后对照着目录找出来的 -.-’
![QQ截图20221214163027](https://user-images.githubusercontent.com/100987618/207545629-6b9df591-b464-4b92-bd5f-43c425f50a60.png)

**Comment by zwy321** [comment]
这个我也看到了 删了没效果
