### ISSUE TITLE
Sydney模式下如何使用群管模式

### ISSUE THREAD

**Issue by KasumiYuku** [ikechan8370/chatgpt-plugin#510]
悉尼能用禁言、踢人之类的群管功能吗？

**Comment by ikechan8370** [comment]
近期会增加

**Comment by ikechan8370** [comment]
update：可以在API模式下用反代https://sydney.ikechan8370.com/v1 试试。悉尼实在是不听话，需要设定引导

**Comment by KasumiYuku** [comment]
> 

@ikechan8370 大佬，切换了API，反代填的这个但悉尼不说话
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/107661829/9d7df19a-52d0-47cc-8815-c829d17fa0a8)
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/107661829/86a1830d-f023-4e43-9433-25fb0fc35b6d)
