### ISSUE TITLE
能否增加Claude2的支持

### ISSUE THREAD

**Issue by gaozihuan0713** [ikechan8370/chatgpt-plugin#512]
**你的功能请求是否与某个问题有关？请描述。**
问题的清晰而简明的描述。

**描述你想要的解决方案**
你想要发生什么的清晰而简明的描述。

**描述你已经考虑的替代方案**
对任何替代解决方案或功能的清晰简明的描述。

**附加说明**
在此处添加有关功能请求的任何其他说明、屏幕截图或者引用。

**Comment by ikechan8370** [comment]
api有申请的办法了吗？

**Comment by bincooo** [comment]
> 

说的可能是web上的吧
https://github.com/bincooo/claude-api

**Comment by ikechan8370** [comment]
@bincooo 哇哦 等我过几天放假去看看
