### ISSUE TITLE
更新后 自设定bing报错Unexpected server response: 200

### ISSUE THREAD

**Issue by CC-3301** [ikechan8370/chatgpt-plugin#513]
[YzBot][23:50:59.965][MARK] 使用host：https://edgeservices.bing.com/edgesvc
[YzBot][23:51:00.511][MARK] use sydney websocket host: wss://sydney.bing.com
Error: Unexpected server response: 200
    at ClientRequest.<anonymous> (/root/Yunzai-Bot/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/websocket.js:888:7)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:695:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at TLSSocket.socketOnData (node:_http_client:536:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
[YzBot][23:51:01.085][ERRO] Error: Unexpected server response: 200
    at ClientRequest.<anonymous> (/root/Yunzai-Bot/node_modules/.pnpm/ws@8.13.0/node_modules/ws/lib/websocket.js:888:7)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:695:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at TLSSocket.socketOnData (node:_http_client:536:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by ikechan8370** [comment]
ip被微软拉黑就是这样的 200

**Comment by CC-3301** [comment]
出站用Cloudflare WARP这么干净的IP还是200，难搞
换了个冷门机房的自用代理IP提示要验证码
CaptchaChallenge
User needs to solve CAPTCHA to continue.
undefined

**Comment by ikechan8370** [comment]
> 出站用Cloudflare WARP这么干净的IP还是200，难搞
> 
> 换了个冷门机房的自用代理IP提示要验证码
> 
> CaptchaChallenge
> 
> User needs to solve CAPTCHA to continue.
> 
> undefined

cloudflare前天才刚刚全线被拉黑了

**Comment by S1mple-k** [comment]
> ip被微软拉黑就是
我用clash，选美国节点都出现了200错误，不知道咋解决

**Comment by S1mple-k** [comment]
> ip被微软拉黑就是这样的 200

我用clash选美国节点，也出现了200错误，不知道咋搞

**Comment by ikechan8370** [comment]
Azure都还存活，写了个用Azure serverless搭的教程：https://ikechan8370.com/archives/ji-yu-azure-container-web-applicationda-jian-mian-fei-bi-ying-fan-dai
也可以用我的反代或者自己找可用的ip，但是连续几轮封下来可用的ip实在越来越少了

**Comment by S1mple-k** [comment]
> Azure都还存活，写了个用Azure serverless搭的教程：https://ikechan8370.com/archives/ji-yu-azure-container-web-applicationda-jian-mian-fei-bi-ying-fan-dai 也可以用我的反代或者自己找可用的ip，但是连续几轮封下来可用的ip实在越来越少了

azure的注册好像有点难度（）

**Comment by S1mple-k** [comment]
> Azure都还存活，写了个用Azure serverless搭的教程：https://ikechan8370.com/archives/ji-yu-azure-container-web-applicationda-jian-mian-fei-bi-ying-fan-dai 也可以用我的反代或者自己找可用的ip，但是连续几轮封下来可用的ip实在越来越少了

azure的注册好像有点难度（）

**Comment by ikechan8370** [comment]
> > Azure都还存活，写了个用Azure serverless搭的教程：https://ikechan8370.com/archives/ji-yu-azure-container-web-applicationda-jian-mian-fei-bi-ying-fan-dai 也可以用我的反代或者自己找可用的ip，但是连续几轮封下来可用的ip实在越来越少了
> 
> azure的注册好像有点难度（）

那就用内置的反代吧 别折腾了

**Comment by S1mple-k** [comment]
> > > Azure都还存活，写了个用Azure serverless搭的教程：https://ikechan8370.com/archives/ji-yu-azure-container-web-applicationda-jian-mian-fei-bi-ying-fan-dai 也可以用我的反代或者自己找可用的ip，但是连续几轮封下来可用的ip实在越来越少了
> > 
> > 
> > azure的注册好像有点难度（）
> 
> 那就用内置的反代吧 别折腾了

那个，不好意思，我不是很明白“内置的反代”指的是什么，可以详细解释一下吗？谢谢了（我是门外汉）

**Comment by ikechan8370** [comment]
> > > > Azure都还存活，写了个用Azure serverless搭的教程：https://ikechan8370.com/archives/ji-yu-azure-container-web-applicationda-jian-mian-fei-bi-ying-fan-dai 也可以用我的反代或者自己找可用的ip，但是连续几轮封下来可用的ip实在越来越少了
> > > 
> > > 
> > > azure的注册好像有点难度（）
> > 
> > 
> > 那就用内置的反代吧 别折腾了
> 
> 那个，不好意思，我不是很明白“内置的反代”指的是什么，可以详细解释一下吗？谢谢了（我是门外汉）

就是锅巴或后台里打开对话使用反代 我在插件里放了一个自己搭的反代

**Comment by S1mple-k** [comment]
后台是指与AI聊天时开的两个CMD窗口吗？然后那个插件是pandoraAI本身那个文件夹吗？（实在惭愧，我没接触过这个领域，可能提的问题会有些好笑，请你见谅）

**Comment by S1mple-k** [comment]
> > > > > Azure都还存活，写了个用Azure serverless搭的教程：https://ikechan8370.com/archives/ji-yu-azure-container-web-applicationda-jian-mian-fei-bi-ying-fan-dai 也可以用我的反代或者自己找可用的ip，但是连续几轮封下来可用的ip实在越来越少了
> > > > 
> > > > 
> > > > azure的注册好像有点难度（）
> > > 
> > > 
> > > 那就用内置的反代吧 别折腾了
> > 
> > 
> > 那个，不好意思，我不是很明白“内置的反代”指的是什么，可以详细解释一下吗？谢谢了（我是门外汉）
> 
> 就是锅巴或后台里打开对话使用反代 我在插件里放了一个自己搭的反代

后天指的是与AI对话时打开的那两个CMD窗口吗？然后插件指的是pandoraAI本身吗？（可能提的问题会有点笨，请你见谅）

**Comment by hanhan258** [comment]
咱们插件没有用到pandoraAI，会不会是问错地方了？

**Comment by S1mple-k** [comment]
> 咱们插件没有用到pandoraAI，会不会是问错地方了？

啊？可能是吧（囧），因为我用npm run cli 也会出现这个问题，搜了unexpected server responses：200然后就顺着进来康康了（）话说这个是node-chatgpt-api相关的帖子吗？不是的话我面个壁先（悲）

**Comment by S1mple-k** [comment]
> 咱们插件没有用到pandoraAI，会不会是问错地方了？

啊？可能是吧（囧），因为我用npm run cli 也会出现这个问题，搜了unexpected server responses：200然后就顺着进来康康了（）对不起，我面壁思过先

**Comment by ikechan8370** [comment]
> > 咱们插件没有用到pandoraAI，会不会是问错地方了？
> 
> 啊？可能是吧（囧），因为我用npm run cli 也会出现这个问题，搜了unexpected server responses：200然后就顺着进来康康了（）对不起，我面壁思过先

问题是同一个问题。但显然不是一个项目。你要是有些编程和网络基础倒是可以弄明白自己解决。

**Comment by S1mple-k** [comment]
> > > 咱们插件没有用到pandoraAI，会不会是问错地方了？
> > 
> > 
> > 啊？可能是吧（囧），因为我用npm run cli 也会出现这个问题，搜了unexpected server responses：200然后就顺着进来康康了（）对不起，我面壁思过先
> 
> 问题是同一个问题。但显然不是一个项目。你要是有些编程和网络基础倒是可以弄明白自己解决。

ε=(´ο｀*)))唉，隔行如隔山，这些东西我理解起来都挺费劲的，不过一样的问题也许有共通的解决方案吧......感谢解答！（鞠躬）

**Comment by S1mple-k** [comment]
> > > 咱们插件没有用到pandoraAI，会不会是问错地方了？
> > 
> > 
> > 啊？可能是吧（囧），因为我用npm run cli 也会出现这个问题，搜了unexpected server responses：200然后就顺着进来康康了（）对不起，我面壁思过先
> 
> 问题是同一个问题。但显然不是一个项目。你要是有些编程和网络基础倒是可以弄明白自己解决。

ε=(´ο｀*)))唉，隔行如隔山，这些东西我理解起来都挺费劲的，不过一样的问题也许有共通的解决方案吧......感谢解答！（鞠躬）

**Comment by HalcyonAlcedo** [comment]
> > > > 咱们插件没有用到pandoraAI，会不会是问错地方了？
> > > 
> > > 
> > > 啊？ 可能是吧（囧），因为我用npm run cli 也会出现这个问题，搜了unexpected server responses：200然后就顺着进来康康了（）对不起，我面壁思过先
> > 
> > 
> > 问题是同一个问题。 但显然不是一个项目。 你要是有些编程和网络基础倒是可以弄明白自己解决。
> 
> ε=(´ο｀*)))唉，隔行如隔山，这些东西我理解起来都挺费劲的，不过一样的问题也许有共通的解决方案吧...... 感谢解答！ （鞠躬）

PandoraAI我记得没使用反代功能，而是用的代理，你需要一个代理服务器，然后将settings中的bingAiClient.proxy改为你的代理服务器地址，这样才行，或者去改下node-chatgpt的源码，让他支持反代也行

**Comment by HalcyonAlcedo** [comment]
> > 
> 
> > > > > > 咱们插件没有用到pandoraAI，会不会是问错地方了？
> > > > > 
> > > > > 
> > > > > 啊？ 可能是吧（囧），因为我用npm run cli 也会出现这个问题，搜了unexpected server responses：200然后就顺着进来康康了（）对不起，我面壁思过先
> > > > 
> > > > 
> > > > 问题是同一个问题。 但显然不是一个项目。 你要是有些编程和网络基础倒是可以弄明白自己解决。
> > > 
> > > 
> > > ε=(´ο｀*)))唉，隔行如隔山，这些东西我理解起来都挺费劲的，不过一样的问题也许有共通的解决方案吧...... 感谢解答！ （鞠躬）
> > 
> > 
> > PandoraAI我记得没使用反代功能，而是用的代理，你需要一个代理服务器，然后将settings中的bingAiClient.proxy改为你的代理服务器地址，这样才行，或者去改下node-chatgpt的源码，让他支持反代也行
> 
> settings中的bingAiClient.proxy我倒是改过了，没什么用，大多数时候都是跟这帖子一样的问题。node-chatgpt源码......大佬知道怎么弄吗？（麻瓜正在努力搞懂这些魔法，因为我的PandoraAI是朋友帮忙弄的，现在他也没辙了[摊手]）

在src/BingAIClient.js文件中的129行，改成
``` javascript
const ws = new WebSocket('wss://bing.ikechan8370.com/sydney/ChatHub', undefined, { agent, origin: 'https://edgeservices.bing.com' })
```
如果是自己部署的反代，自己改下反代地址

**Comment by HalcyonAlcedo** [comment]
哦对了，还有设置里的host也要改下，改成反代地址，上面这个代码的话，就改成https://bing.ikechan8370.com

**Comment by S1mple-k** [comment]
> 



> 哦对了，还有设置里的host也要改下，改成反代地址，上面这个代码的话，就改成https://bing.ikechan8370.com

我把文件的第129行替换了，也把origin的地址换成这个了，但是运行npm run cli的指令变成了这样


file:///D:/Program%20Files/node-chatgpt-api-main/src/BingAIClient.js:135
            const ws = new WebSocket('wss://sydney.bing.com/sydney/ChatHub', { agent });
                  ^

SyntaxError: Identifier 'ws' has already been declared
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)

**Comment by HalcyonAlcedo** [comment]
> 

我是node ./bin/server.js启动的，没用npm，话说这个应该去node-chatgpt项目去问，跟这个插件没关系

**Comment by S1mple-k** [comment]
> > 
> 
> 我是node ./bin/server.js启动的，没用npm，话说这个应该去node-chatgpt项目去问，跟这个插件没关系

明白了！非常感谢大佬的解答（鞠躬），我换了个ip算是勉强能用了哈哈哈哈（话说美国Ip也不能用真的离谱
）

**Comment by ikechan8370** [comment]
> > > 
> > 
> > 
> > 我是node ./bin/server.js启动的，没用npm，话说这个应该去node-chatgpt项目去问，跟这个插件没关系
> 
> 明白了！非常感谢大佬的解答（鞠躬），我换了个ip算是勉强能用了哈哈哈哈（话说美国Ip也不能用真的离谱 ）

和ip所在地基本没关系。要看ip属性
