### ISSUE TITLE
Sydney使用识别图片模式出错

### ISSUE THREAD

**Issue by Yoraka** [ikechan8370/chatgpt-plugin#517]
## 问题描述
![NROB2BCY%V }2AJYU6G2IIT](https://github.com/ikechan8370/chatgpt-plugin/assets/69870298/ef2504ec-47e3-46f2-a4f1-81b6809e469c)

更新后关掉原有ocr，开启Sydney图片识别，然后报错FormData is not defined

![N7%W7VS(GP%12@`HUN3GVQ2](https://github.com/ikechan8370/chatgpt-plugin/assets/69870298/41c786df-4032-456d-ba74-7c742cdfbb3a)

并且还会在后台不停输出[{"type":6}]

**Comment by HalcyonAlcedo** [comment]
你的node版本是多少

**Comment by Yoraka** [comment]
> 你的node版本是多少

16.17.0

**Comment by HalcyonAlcedo** [comment]
如果node版本小于18，可能不支持FormData，需要额外安装[form-data](https://www.npmjs.com/package/form-data)
在插件目录执行
npm install --save form-data
然后修改utils\SydneyAIClient.js
在第一行插入
``` javascript
import FormData from 'form-data'
```

**Comment by Yoraka** [comment]
> 如果node版本小于18，可能不支持FormData，需要额外安装[form-data](https://www.npmjs.com/package/form-data) 在插件目录执行 npm install --save form-data 然后修改utils\SydneyAIClient.js 在第一行插入
> 
> ```js
> import FormData from 'form-data'
> ```
已经执行了上面的更改
同样的输入
报错Unexpected end of JSON input

![image](https://github.com/ikechan8370/chatgpt-plugin/assets/69870298/f431dcd2-5a8b-4f70-ad54-91e7ec361baf)
form-data已经在nodemodules里面了
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/69870298/89198f76-aea7-4a18-9a73-d126db9e85dc)

**Comment by HalcyonAlcedo** [comment]
是国内服务器吧，国内服务器需要代理，要不等等更新，正在处理FormData和反代的问题。

**Comment by Yoraka** [comment]
> 是国内服务器吧，国内服务器需要代理，要不等等更新，正在处理FormData和反代的问题。

疼逊云的

**Comment by HalcyonAlcedo** [comment]
已经修复node版本兼容和地址访问问题，国内服务器请正确配置反代后使用
