### ISSUE TITLE
能否支持chatglm原版的的api，我看有个插件可以支持

### ISSUE THREAD

**Issue by liuzj288** [ikechan8370/chatgpt-plugin#520]
这个插件可以支持原版api

https://gitee.com/394911284/chatztc

**Comment by ikechan8370** [comment]
chatglm有openai兼容的api了

**Comment by liuzj288** [comment]
> chatglm有openai兼容的api了

弄了下似乎没成功，选的chatgpt api
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/13833404/68d9bed4-0afd-4b35-993e-60787235d51c)
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/13833404/ace7ff6c-b613-4572-ac61-73a5e5694f14)


chatglm后台提示方法不再支持？
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/13833404/1b3d5bda-7d7f-40f5-a280-488cf70bf8b3)

**Comment by ikechan8370** [comment]
我也遇到这个，是pydantic版本太高了,我安装了老版本就好了
或者参考这个issue https://github.com/THUDM/ChatGLM2-6B/issues/308

**Comment by liuzj288** [comment]
> 我也遇到这个，是pydantic版本太高了,我安装了老版本就好了 或者参考这个issue [THUDM/ChatGLM2-6B#308](https://github.com/THUDM/ChatGLM2-6B/issues/308)

你装的哪个版本？我按那个issue改openai.py结果提示400了
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/13833404/7f859fe1-cfe6-4ee0-9a64-7198d963c0f8)
![5dcee600ac00aa179030598e07c99634](https://github.com/ikechan8370/chatgpt-plugin/assets/13833404/2abb8dcb-9a90-4118-8662-57f8dfee0326)
