### ISSUE TITLE
使用微软云搭建了反代还是不能用吗......

### ISSUE THREAD

**Issue by ioewhj** [ikechan8370/chatgpt-plugin#529]
依旧显示要验证，在官网去又没验证码，而且给的www.bing.com/chat网址即使在开了代理的情况下打开，位置却是在是中国
![屏幕截图(26)](https://github.com/ikechan8370/chatgpt-plugin/assets/131784357/d727dc16-5a72-4a48-8900-974d464828de)

**Comment by ikechan8370** [comment]
你这知道都是国内版必应了，你觉得能行吗。必应也不是开了代理就一定能用

**Comment by ikechan8370** [comment]
还有验证码是跟着账号走的。和你用什么反代没关系。

**Comment by ioewhj** [comment]
> 你这知道都是国内版必应了，你觉得能行吗。必应也不是开了代理就一定能用

提出这个问题的原因是因为我在电脑上正常搜bing.com它会直接跳到代理那边，没有显示国内国际版，而刚刚我在同一代理的情况下搜bing.com\chat它显示了国内国际版，国家定的国内，然后刚刚我用手机也在同一代理的情况下bing.com也会分国内国际，所以可能是因为我电脑上有ck记录的原因吧:-D……

**Comment by ikechan8370** [comment]
> > 你这知道都是国内版必应了，你觉得能行吗。必应也不是开了代理就一定能用
> 
> 提出这个问题的原因是因为我在电脑上正常搜bing.com它会直接跳到代理那边，没有显示国内国际版，而刚刚我在同一代理的情况下搜bing.com\chat它显示了国内国际版，国家定的国内，然后刚刚我用手机也在同一代理的情况下bing.com也会分国内国际，所以可能是因为我电脑上有ck记录的原因吧:-D……

刚合并了captcha分支，增加了自动过码，如果只是为了验证码可以试试更新。

**Comment by ioewhj** [comment]
> > > 你这知道都是国内版必应了，你觉得能行吗。必应也不是开了代理就一定能用
> > 
> > 
> > 提出这个问题的原因是因为我在电脑上正常搜bing.com它会直接跳到代理那边，没有显示国内国际版，而刚刚我在同一代理的情况下搜bing.com\chat它显示了国内国际版，国家定的国内，然后刚刚我用手机也在同一代理的情况下bing.com也会分国内国际，所以可能是因为我电脑上有ck记录的原因吧:-D……
> 
> 刚合并了captcha分支，增加了自动过码，如果只是为了验证码可以试试更新。

微软还是太强势了，佬还是不要浪费时间折腾了

**Comment by ikechan8370** [comment]
> > > > 你这知道都是国内版必应了，你觉得能行吗。必应也不是开了代理就一定能用
> 
> > > 
> 
> > > 
> 
> > > 提出这个问题的原因是因为我在电脑上正常搜bing.com它会直接跳到代理那边，没有显示国内国际版，而刚刚我在同一代理的情况下搜bing.com\chat它显示了国内国际版，国家定的国内，然后刚刚我用手机也在同一代理的情况下bing.com也会分国内国际，所以可能是因为我电脑上有ck记录的原因吧:-D……
> 
> > 
> 
> > 刚合并了captcha分支，增加了自动过码，如果只是为了验证码可以试试更新。
> 
> 
> 
> 微软还是太强势了，佬还是不要浪费时间折腾了

没有啊。感觉微软已经很友好了。
