### ISSUE TITLE
废了，兄弟们散了吧

### ISSUE THREAD

**Issue by habacat** [ikechan8370/chatgpt-plugin#53]
废了，兄弟们散了吧
![微信图片_20221215201034](https://user-images.githubusercontent.com/41714213/207856282-2e346e0c-740c-4030-96fb-28dfd040e3f6.png)

枯了

**Comment by Shiyue00** [comment]
这个只需要等待一会就行了，而且也不是一小时限一次

**Comment by ikechan8370** [comment]
> 这个只需要等待一会就行了，而且也不是一小时限一次

具体频率限制清楚吗？好像不少人总触发这个 对机器人很不友好啊
