### ISSUE TITLE
#帮助建议更换为#chat帮助之类的

### ISSUE THREAD

**Issue by shirosoralumie648** [ikechan8370/chatgpt-plugin#54]
#帮助和yunzaibot默认的帮助好像是重复的
![}T1KPZ(} I9SI`HOO3ZH DQ](https://user-images.githubusercontent.com/92046446/207866547-9ff4ad6b-42ae-479e-91e5-660857f165eb.png)

**Comment by shirosoralumie648** [comment]
![W30{ C$U%4D`$8%7EZ}SB%K](https://user-images.githubusercontent.com/92046446/207875160-754ffd26-9e7c-476c-9af3-3faf5e6e4551.png)

**Comment by ikechan8370** [comment]
好像正则没写对。我试试 我记得设置的是#chatgpt帮助
