### ISSUE TITLE
[疑问]开启debug后，看到后台有输出disconnected，请问这是微软截断还是插件内设置的接收消息超时？

### ISSUE THREAD

**Issue by TaoXiaoBai** [ikechan8370/chatgpt-plugin#541]
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/28218925/ba05d976-78e9-42a5-8e44-bc88e6329fca)
如图的提示

**Comment by ikechan8370** [comment]
都不是 你图里这个应该是网络原因意外中止了

**Comment by TaoXiaoBai** [comment]
> 都不是 你图里这个应该是网络原因意外中止了

感谢佬回复，顺便问一下佬什么时候合并一下#530
