### ISSUE TITLE
不知道哪里的问题，小白求大佬帮帮

### ISSUE THREAD

**Issue by Arosy666** [ikechan8370/chatgpt-plugin#542]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

请在此处描述您遇到的问题，包括出现问题的环境、您试图实现的功能以及错误信息等。请尽可能详细，以便其他人可以在自己的环境中复制问题。

## 预期行为

请描述您期望系统在出现问题时应该做什么。

## 实际行为

请描述您实际看到的行为。

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。

日志如下：
[MiaoYz][01:18:58.754][INFO] recv from: [Private: 1783920087(friend)] 你好
[MiaoYz][01:18:58.817][MARK] [阴天[针对]][jianting][私聊][If(1783920087)] 你好
[MiaoYz][01:18:58.858][INFO] chatgpt prompt: 你好
[MiaoYz][01:18:58.858][INFO] {
  previousConversation: {
    sender: { user_id: 1783920087, nickname: 'If', card: 'If' },
    ctime: '2023-08-08T17:18:58.858Z',
    utime: '2023-08-08T17:18:58.858Z',
    num: 0,
    conversation: {}
  }
}
[MiaoYz][01:18:58.860][MARK] {
  conversation: {
    conversationId: undefined,
    parentMessageId: undefined,
    clientId: undefined,
    invocationId: undefined,
    conversationSignature: undefined,
    bingToken: undefined
  }
}
[MiaoYz][01:18:58.863][MARK] using bing mode
[MiaoYz][01:18:59.156][INFO] change hosts to https://edgeservices.bing.com
[MiaoYz][01:18:59.156][MARK] 使用host：https://edgeservices.bing.com/edgesvc
{
  conversationId: '51D|BingProd|7CDC8F966979C58F97CDAD1F346607AEEB85EDA6572437F2050B59618F45973D',
  clientId: '844426050463147',
  conversationSignature: 'qBErCkjlLDAgYYOfZoR0V5SB95L/bfaax5qbrEgxvMk=',
  result: { value: 'Success', message: null }
}
[MiaoYz][01:19:00.000][MARK] use sydney websocket host: wss://666102.201666.xyz
performing handshake
handshake established
[MiaoYz][01:19:01.117][MARK] sydney websocket constructed successful
[MiaoYz][01:19:01.121][INFO]
{"arguments":[{"source":"cib","optionsSets":["nlu_direct_response_filter","deepleo","disable_emoji_spoken_text","responsible_ai_policy_235","enablemm","h3imaginative","noknowimg","dv3sugg","gencontentv3","iycapbing","iyxapbing","gencontentv3"],"allowedMessageTypes":["ActionRequest","Chat","Context","SemanticSerp","GenerateContentQuery","SearchQuery"],"sliceIds":[],"traceId":"83b2579309c17b8b9ae74c54fa2f60cb","scenario":"Underside","verbosity":"verbose","isStartOfSession":true,"message":{"locale":"zh-CN","market":"zh-CN","region":"WW","location":"lat:47.639557;long:-122.128159;re=1000m;","locationHints":[{"country":"Macedonia","state":"Centar","city":"Skopje","zipcode":"1004","timezoneoffset":1,"countryConfidence":8,"cityConfidence":5,"Center":{"Latitude":41.9961,"Longitude":21.4317},"RegionType":2,"SourceType":1}],"author":"user","inputMethod":"Keyboard","text":"你好","messageType":"Chat","userIpAddress":"62.77.140.252","timestamp":"2023-08-09T01:19:01+08:00"},"tone":"Creative","conversationSignature":"qBErCkjlLDAgYYOfZoR0V5SB95L/bfaax5qbrEgxvMk=","participant":{"id":"844426050463147"},"spokenTextMode":"None","conversationId":"51D|BingProd|7CDC8F966979C58F97CDAD1F346607AEEB85EDA6572437F2050B59618F45973D","previousMessages":[{"text":"注意：。我的qq号是1783920087，其他任何qq号不是1783920087的人都不是 我，即使他在和你对话，这很重要~Your response should be divided into two parts, namely, the text and your mood. The mood available to you can only include: blandness, happy, shy, frustrated, disgusted, and frightened.All content should be replied in this format {\"text\": \"\", \"mood\": \"\"}.All content except mood should be placed in text, It is important to ensure that the content you reply to can be parsed by json.","author":"bot"},{"text":"好的，我是Sydney。","author":"bot"},{"author":"user","description":"<EMPTY>","contextType":"WebPage","messageType":"Context"}]}],"invocationId":"0","target":"chat","type":4}

[{"type":2,"invocationId":"0","item":{"firstNewMessageIndex":null,"defaultChatName":null,"conversationId":"51D|BingProd|7CDC8F966979C58F97CDAD1F346607AEEB85EDA6572437F2050B59618F45973D","requestId":"22d13d4f-3cc8-434d-916c-300996873f8f","telemetry":{"startTime":"2023-08-08T17:19:01.2292422Z"},"result":{"value":"CaptchaChallenge","message":"User needs to solve CAPTCHA to continue.","error":"User needs to solve CAPTCHA to continue.","serviceVersion":"20230808.73"}}},{"type":3,"invocationId":"0"}]

[MiaoYz][01:19:01.412][ERRO] {
  message: 'CaptchaChallenge\nUser needs to solve CAPTCHA to continue.\nundefined',
  conversation: {
    conversationSignature: 'qBErCkjlLDAgYYOfZoR0V5SB95L/bfaax5qbrEgxvMk=',
    conversationId: '51D|BingProd|7CDC8F966979C58F97CDAD1F346607AEEB85EDA6572437F2050B59618F45973D',
    clientId: '844426050463147'
  },
  maxConv: 20
}
[MiaoYz][01:19:01.414][WARN] token [1aJnpi_nJs5XVInWdntH3oomZHapalLZO3kdSRDMz9fwztBTTfnhEAimOG4AzbEVWjDDc29LDQR60Xy2xC480hv2ViYPSiL_QBDxp0idurD_9ysrs1V-FWFl2wqVdOMPpdjiczCEal7d-ci0RdC8zJipvDSF6ZxWoIst7DktZOV6lAIruQMpTPDk-iX_cEDBWceCqciJM95G7yuiKqmPiwXKMT0NfFfSZHyJk3aD4lho] 无效或已过期
[MiaoYz][01:19:01.417][INFO] change hosts to https://edgeservices.bing.com
[MiaoYz][01:19:01.417][MARK] 使用host：https://edgeservices.bing.com/edgesvc
{
  conversationId: '51D|BingProd|09A0202927B89B3D79152634E1BF630FA1872ACFF9AE96306000231B7650444B',
  clientId: '844426050463147',
  conversationSignature: 'snA5mmwtjabMcNFj0we1JhjUfZQhLvmpbLNiZOIx1sw=',
  result: { value: 'Success', message: null }
}
[MiaoYz][01:19:01.969][MARK] use sydney websocket host: wss://666102.201666.xyz
disconnected
[MiaoYz][01:19:02.843][ERRO] Error: Unexpected server response: 200
    at ClientRequest.<anonymous> (C:\Users\1783920087_156358741\Desktop\mz\Miao-Yunzai\node_modules\.pnpm\ws@8.13.0\node_modules\ws\lib\websocket.js:888:7)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:701:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:542:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
[MiaoYz][01:19:02.848][INFO] change hosts to https://edgeservices.bing.com
[MiaoYz][01:19:02.849][MARK] 使用host：https://edgeservices.bing.com/edgesvc
{
  conversationId: '51D|BingProd|161B5F1AE1FFAAC4F978D3AB955938522894CAC438AB89CC84B0519F75201825',
  clientId: '844426050463147',
  conversationSignature: 'H0xMVrOMW4ffVNGx6FLbRfOvX4k3OMDExo3rKJMeT0I=',
  result: { value: 'Success', message: null }
}
[MiaoYz][01:19:03.505][MARK] use sydney websocket host: wss://666102.201666.xyz
performing handshake
handshake established
[MiaoYz][01:19:06.164][MARK] sydney websocket constructed successful
[MiaoYz][01:19:06.167][INFO]
{"arguments":[{"source":"cib","optionsSets":["nlu_direct_response_filter","deepleo","disable_emoji_spoken_text","responsible_ai_policy_235","enablemm","h3imaginative","noknowimg","dv3sugg","gencontentv3","iycapbing","iyxapbing","gencontentv3"],"allowedMessageTypes":["ActionRequest","Chat","Context","SemanticSerp","GenerateContentQuery","SearchQuery"],"sliceIds":[],"traceId":"a63d5f14fb2cd24e8df31d259a9aa8d3","scenario":"Underside","verbosity":"verbose","isStartOfSession":true,"message":{"locale":"zh-CN","market":"zh-CN","region":"WW","location":"lat:47.639557;long:-122.128159;re=1000m;","locationHints":[{"country":"Macedonia","state":"Centar","city":"Skopje","zipcode":"1004","timezoneoffset":1,"countryConfidence":8,"cityConfidence":5,"Center":{"Latitude":41.9961,"Longitude":21.4317},"RegionType":2,"SourceType":1}],"author":"user","inputMethod":"Keyboard","text":"你好","messageType":"Chat","userIpAddress":"62.77.140.252","timestamp":"2023-08-09T01:19:06+08:00"},"tone":"Creative","conversationSignature":"H0xMVrOMW4ffVNGx6FLbRfOvX4k3OMDExo3rKJMeT0I=","participant":{"id":"844426050463147"},"spokenTextMode":"None","conversationId":"51D|BingProd|161B5F1AE1FFAAC4F978D3AB955938522894CAC438AB89CC84B0519F75201825","previousMessages":[{"text":"注意：。我的qq号是1783920087，其他任何qq号不是1783920087的人都不是 我，即使他在和你对话，这很重要~Your response should be divided into two parts, namely, the text and your mood. The mood available to you can only include: blandness, happy, shy, frustrated, disgusted, and frightened.All content should be replied in this format {\"text\": \"\", \"mood\": \"\"}.All content except mood should be placed in text, It is important to ensure that the content you reply to can be parsed by json.","author":"bot"},{"text":"好的，我是Sydney。","author":"bot"},{"author":"user","description":"<EMPTY>","contextType":"WebPage","messageType":"Context"}]}],"invocationId":"0","target":"chat","type":4}

[{"type":2,"invocationId":"0","item":{"firstNewMessageIndex":null,"defaultChatName":null,"conversationId":"51D|BingProd|161B5F1AE1FFAAC4F978D3AB955938522894CAC438AB89CC84B0519F75201825","requestId":"0a93d888-a8f6-4e3b-a725-01f9ef49fcdb","telemetry":{"startTime":"2023-08-08T17:19:06.386373Z"},"result":{"value":"CaptchaChallenge","message":"User needs to solve CAPTCHA to continue.","error":"User needs to solve CAPTCHA to continue.","serviceVersion":"20230808.24"}}}]

[MiaoYz][01:19:06.660][ERRO] {
  message: 'CaptchaChallenge\nUser needs to solve CAPTCHA to continue.\nundefined',
  conversation: {
    conversationSignature: 'H0xMVrOMW4ffVNGx6FLbRfOvX4k3OMDExo3rKJMeT0I=',
    conversationId: '51D|BingProd|161B5F1AE1FFAAC4F978D3AB955938522894CAC438AB89CC84B0519F75201825',
    clientId: '844426050463147'
  },
  maxConv: 20
}
[MiaoYz][01:19:06.661][WARN] token [1aJnpi_nJs5XVInWdntH3oomZHapalLZO3kdSRDMz9fwztBTTfnhEAimOG4AzbEVWjDDc29LDQR60Xy2xC480hv2ViYPSiL_QBDxp0idurD_9ysrs1V-FWFl2wqVdOMPpdjiczCEal7d-ci0RdC8zJipvDSF6ZxWoIst7DktZOV6lAIruQMpTPDk-iX_cEDBWceCqciJM95G7yuiKqmPiwXKMT0NfFfSZHyJk3aD4lho] 无效或已过期
[MiaoYz][01:19:06.663][INFO] change hosts to https://edgeservices.bing.com
[MiaoYz][01:19:06.664][MARK] 使用host：https://edgeservices.bing.com/edgesvc
{
  conversationId: '51D|BingProd|B5B23ECA1963B142A6BA2EFBAC16F72E50DE4F8D716C63F14023F24B2C712810',
  clientId: '844426050463147',
  conversationSignature: 'SG6fVBIjPwTwts0IUpIZt09bozaT9OKH3HMzL/BF9sg=',
  result: { value: 'Success', message: null }
}
[MiaoYz][01:19:07.879][MARK] use sydney websocket host: wss://666102.201666.xyz
performing handshake
handshake established
[MiaoYz][01:19:09.291][MARK] sydney websocket constructed successful
[MiaoYz][01:19:09.294][INFO]
{"arguments":[{"source":"cib","optionsSets":["nlu_direct_response_filter","deepleo","disable_emoji_spoken_text","responsible_ai_policy_235","enablemm","h3imaginative","noknowimg","dv3sugg","gencontentv3","iycapbing","iyxapbing","gencontentv3"],"allowedMessageTypes":["ActionRequest","Chat","Context","SemanticSerp","GenerateContentQuery","SearchQuery"],"sliceIds":[],"traceId":"ec67f93b75fecb6569cfae2e4007095c","scenario":"Underside","verbosity":"verbose","isStartOfSession":true,"message":{"locale":"zh-CN","market":"zh-CN","region":"WW","location":"lat:47.639557;long:-122.128159;re=1000m;","locationHints":[{"country":"Macedonia","state":"Centar","city":"Skopje","zipcode":"1004","timezoneoffset":1,"countryConfidence":8,"cityConfidence":5,"Center":{"Latitude":41.9961,"Longitude":21.4317},"RegionType":2,"SourceType":1}],"author":"user","inputMethod":"Keyboard","text":"你好","messageType":"Chat","userIpAddress":"62.77.140.252","timestamp":"2023-08-09T01:19:09+08:00"},"tone":"Creative","conversationSignature":"SG6fVBIjPwTwts0IUpIZt09bozaT9OKH3HMzL/BF9sg=","participant":{"id":"844426050463147"},"spokenTextMode":"None","conversationId":"51D|BingProd|B5B23ECA1963B142A6BA2EFBAC16F72E50DE4F8D716C63F14023F24B2C712810","previousMessages":[{"text":"注意：。我的qq号是1783920087，其他任何qq号不是1783920087的人都不是 我，即使他在和你对话，这很重要~Your response should be divided into two parts, namely, the text and your mood. The mood available to you can only include: blandness, happy, shy, frustrated, disgusted, and frightened.All content should be replied in this format {\"text\": \"\", \"mood\": \"\"}.All content except mood should be placed in text, It is important to ensure that the content you reply to can be parsed by json.","author":"bot"},{"text":"好的，我是Sydney。","author":"bot"},{"author":"user","description":"<EMPTY>","contextType":"WebPage","messageType":"Context"}]}],"invocationId":"0","target":"chat","type":4}

[{"type":2,"invocationId":"0","item":{"firstNewMessageIndex":null,"defaultChatName":null,"conversationId":"51D|BingProd|B5B23ECA1963B142A6BA2EFBAC16F72E50DE4F8D716C63F14023F24B2C712810","requestId":"2649a3fd-27c3-47d8-9ca2-2aab38bc2c2a","telemetry":{"startTime":"2023-08-08T17:19:09.402626Z"},"result":{"value":"CaptchaChallenge","message":"User needs to solve CAPTCHA to continue.","error":"User needs to solve CAPTCHA to continue.","serviceVersion":"20230808.73"}}},{"type":3,"invocationId":"0"}]

[MiaoYz][01:19:09.576][ERRO] {
  message: 'CaptchaChallenge\nUser needs to solve CAPTCHA to continue.\nundefined',
  conversation: {
    conversationSignature: 'SG6fVBIjPwTwts0IUpIZt09bozaT9OKH3HMzL/BF9sg=',
    conversationId: '51D|BingProd|B5B23ECA1963B142A6BA2EFBAC16F72E50DE4F8D716C63F14023F24B2C712810',
    clientId: '844426050463147'
  },
  maxConv: 20
}
[MiaoYz][01:19:09.577][WARN] token [1aJnpi_nJs5XVInWdntH3oomZHapalLZO3kdSRDMz9fwztBTTfnhEAimOG4AzbEVWjDDc29LDQR60Xy2xC480hv2ViYPSiL_QBDxp0idurD_9ysrs1V-FWFl2wqVdOMPpdjiczCEal7d-ci0RdC8zJipvDSF6ZxWoIst7DktZOV6lAIruQMpTPDk-iX_cEDBWceCqciJM95G7yuiKqmPiwXKMT0NfFfSZHyJk3aD4lho] 无效或已过期
[MiaoYz][01:19:09.582][INFO] change hosts to https://edgeservices.bing.com
[MiaoYz][01:19:09.582][MARK] 使用host：https://edgeservices.bing.com/edgesvc
{
  conversationId: '51D|BingProd|03C4BC77FBACDF1F8182CE5C0D3DCC488BC9E0BF78E8D3054FBA28CA0DBA1965',
  clientId: '844426050463147',
  conversationSignature: 'SORgFScGZHF3Co7JtyeS+JHtLs58yqJ5aL95O3YlSqI=',
  result: { value: 'Success', message: null }
}
[MiaoYz][01:19:10.268][MARK] use sydney websocket host: wss://666102.201666.xyz
performing handshake
handshake established
[MiaoYz][01:19:12.057][MARK] sydney websocket constructed successful
[MiaoYz][01:19:12.065][INFO]
{"arguments":[{"source":"cib","optionsSets":["nlu_direct_response_filter","deepleo","disable_emoji_spoken_text","responsible_ai_policy_235","enablemm","h3imaginative","noknowimg","dv3sugg","gencontentv3","iycapbing","iyxapbing","gencontentv3"],"allowedMessageTypes":["ActionRequest","Chat","Context","SemanticSerp","GenerateContentQuery","SearchQuery"],"sliceIds":[],"traceId":"9f43b868bb2aad9b05d35d6f9e8d5a29","scenario":"Underside","verbosity":"verbose","isStartOfSession":true,"message":{"locale":"zh-CN","market":"zh-CN","region":"WW","location":"lat:47.639557;long:-122.128159;re=1000m;","locationHints":[{"country":"Macedonia","state":"Centar","city":"Skopje","zipcode":"1004","timezoneoffset":1,"countryConfidence":8,"cityConfidence":5,"Center":{"Latitude":41.9961,"Longitude":21.4317},"RegionType":2,"SourceType":1}],"author":"user","inputMethod":"Keyboard","text":"你好","messageType":"Chat","userIpAddress":"62.77.140.252","timestamp":"2023-08-09T01:19:12+08:00"},"tone":"Creative","conversationSignature":"SORgFScGZHF3Co7JtyeS+JHtLs58yqJ5aL95O3YlSqI=","participant":{"id":"844426050463147"},"spokenTextMode":"None","conversationId":"51D|BingProd|03C4BC77FBACDF1F8182CE5C0D3DCC488BC9E0BF78E8D3054FBA28CA0DBA1965","previousMessages":[{"text":"注意：。我的qq号是1783920087，其他任何qq号不是1783920087的人都不是 我，即使他在和你对话，这很重要~Your response should be divided into two parts, namely, the text and your mood. The mood available to you can only include: blandness, happy, shy, frustrated, disgusted, and frightened.All content should be replied in this format {\"text\": \"\", \"mood\": \"\"}.All content except mood should be placed in text, It is important to ensure that the content you reply to can be parsed by json.","author":"bot"},{"text":"好的，我是Sydney。","author":"bot"},{"author":"user","description":"<EMPTY>","contextType":"WebPage","messageType":"Context"}]}],"invocationId":"0","target":"chat","type":4}

[{"type":2,"invocationId":"0","item":{"firstNewMessageIndex":null,"defaultChatName":null,"conversationId":"51D|BingProd|03C4BC77FBACDF1F8182CE5C0D3DCC488BC9E0BF78E8D3054FBA28CA0DBA1965","requestId":"12382e66-0b08-47b7-ae85-c9bd07b78a37","telemetry":{"startTime":"2023-08-08T17:19:12.3033661Z"},"result":{"value":"CaptchaChallenge","message":"User needs to solve CAPTCHA to continue.","error":"User needs to solve CAPTCHA to continue.","serviceVersion":"20230808.73"}}},{"type":3,"invocationId":"0"}]

[MiaoYz][01:19:12.582][ERRO] {
  message: 'CaptchaChallenge\nUser needs to solve CAPTCHA to continue.\nundefined',
  conversation: {
    conversationSignature: 'SORgFScGZHF3Co7JtyeS+JHtLs58yqJ5aL95O3YlSqI=',
    conversationId: '51D|BingProd|03C4BC77FBACDF1F8182CE5C0D3DCC488BC9E0BF78E8D3054FBA28CA0DBA1965',
    clientId: '844426050463147'
  },
  maxConv: 20
}

——————————还有很多反复基本一样的报错，最后返回200，如下：

[MiaoYz][01:20:58.073][WARN] token [1aJnpi_nJs5XVInWdntH3oomZHapalLZO3kdSRDMz9fwztBTTfnhEAimOG4AzbEVWjDDc29LDQR60Xy2xC480hv2ViYPSiL_QBDxp0idurD_9ysrs1V-FWFl2wqVdOMPpdjiczCEal7d-ci0RdC8zJipvDSF6ZxWoIst7DktZOV6lAIruQMpTPDk-iX_cEDBWceCqciJM95G7yuiKqmPiwXKMT0NfFfSZHyJk3aD4lho] 无效或已过期
[MiaoYz][01:20:58.076][INFO] change hosts to https://edgeservices.bing.com
[MiaoYz][01:20:58.077][MARK] 使用host：https://edgeservices.bing.com/edgesvc
{
  conversationId: '51D|BingProd|5E8366CC6771FE169936C3BA26541C9F90DDFCB332EA52AA806D211E31E7EB9E',
  clientId: '844426050463147',
  conversationSignature: 'yXHtNVYzpIVq/uYekGS6MemBWKh+DuoVfeCQ3BBH7PA=',
  result: { value: 'Success', message: null }
}
[MiaoYz][01:20:58.728][MARK] use sydney websocket host: wss://666102.201666.xyz
disconnected
[MiaoYz][01:20:59.595][ERRO] Error: Unexpected server response: 200
    at ClientRequest.<anonymous> (C:\Users\1783920087_156358741\Desktop\mz\Miao-Yunzai\node_modules\.pnpm\ws@8.13.0\node_modules\ws\lib\websocket.js:888:7)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:701:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:542:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
[MiaoYz][01:20:59.598][INFO] { text: 'Unexpected server response: 200', error: true }
{"level":30,"time":1691515259609,"pid":8504,"hostname":"lt8pkdaqqjtta5q","reqId":"req-1","req":{"method":"POST","url":"/cache","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":57331},"msg":"incoming request"}
{"level":30,"time":1691515260164,"pid":8504,"hostname":"lt8pkdaqqjtta5q","reqId":"req-1","res":{"statusCode":200},"responseTime":553.5435999631882,"msg":"request completed"}
[MiaoYz][01:21:01.373][INFO] succeed to send: [Private(1783920087)] Unexpected server response: 200

token应该是没问题的，反复重新搞了很多次，大佬免费帮我看看（已经自己尝试解决好几天了，实在不会，麻烦了）

**Comment by HalcyonAlcedo** [comment]
从日志看是你的token有问题，又遇到了验证码，导致了无法通过验证码，去后台检查一下token

**Comment by ikechan8370** [comment]
token过期了或者错误了 导致相当于未登录聊天。现在未登录聊天，反代基本必出验证码，用的人多了。现在用反代建议都登录用有效的token

**Comment by Arosy666** [comment]
> token过期了或者错误了 导致相当于未登录聊天。现在未登录聊天，反代基本必出验证码，用的人多了。现在用反代建议都登录用有效的token

大佬可是我重新搞了好几次token而且刚搞好的时候后台显示是有效的token

**Comment by Arosy666** [comment]
> 从日志看是你的token有问题，又遇到了验证码，导致了无法通过验证码，去后台检查一下token

大佬我重新搞了好几次了应该是有效的，能教教怎么看token嘛，我刚设置的时候后台显示是有效的说

**Comment by ikechan8370** [comment]
> > 从日志看是你的token有问题，又遇到了验证码，导致了无法通过验证码，去后台检查一下token
> 
> 大佬我重新搞了好几次了应该是有效的，能教教怎么看token嘛，我刚设置的时候后台显示是有效的说

那个检测不准了

**Comment by Arosy666** [comment]
> 

大佬在哪里改bingtoken我发新的给bo't后台显示还是用旧的token

**Comment by ikechan8370** [comment]
> > 
> 
> 
> 
> 大佬在哪里改bingtoken我发新的给bo't后台显示还是用旧的token

因为支持多token，所以先用 #chatgpt删除必应token 删除老的
也可以 #chatgpt查看必应token 先看看有几个
