### ISSUE TITLE
bing过验证过不了

### ISSUE THREAD

**Issue by d1h1r1** [ikechan8370/chatgpt-plugin#545]
经常请求超时

**Comment by ikechan8370** [comment]
正常 cf的验证码不稳定 多试试就好了
我手过都经常过不去

**Comment by d1h1r1** [comment]
是怎么通过cookie过验证码的呢，可以请教一下吗，谢谢

**Comment by d1h1r1** [comment]
这是我的qq：2322336498，希望能联系我，可付费

**Comment by ikechan8370** [comment]
原理就是自行模拟浏览器聊天 不是很稳定 暂时不准备公开

**Comment by d1h1r1** [comment]
我现在也失踪模拟浏览器登录发信息，但是只能账号登录，不能用cookie

**Comment by d1h1r1** [comment]
我现在也试着模拟浏览器登录发信息，但是只能账号登录，不能用cookie

**Comment by ikechan8370** [comment]
> 我现在也试着模拟浏览器登录发信息，但是只能账号登录，不能用cookie

啊 就直接替换_U cookie不就行了嘛

**Comment by d1h1r1** [comment]
我到时候试试，我之前在登陆界面用cookie登录没成功

**Comment by d1h1r1** [comment]
我之前用seleium过不了人机验证

**Comment by ikechan8370** [comment]
> 我之前用seleium过不了人机验证

直接用selenium大概是不行 试试直接CDP

**Comment by d1h1r1** [comment]
是用python编写的吗？
