### ISSUE TITLE
[BUG]：绘图失败：TypeError: proxy is not a function

### ISSUE THREAD

**Issue by TaoXiaoBai** [ikechan8370/chatgpt-plugin#547]
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/28218925/1c11f0b1-2b94-4fce-8c6a-7df26b7a0cef)
Bing绘图失败：TypeError: proxy is not a function

**Comment by TaoXiaoBai** [comment]
补充一下debug log：
`[{"type":2,"invocationId":"0","item":{"messages":[{"text":"再发一个吧","author":"user","from":{"id":"914799426584250","name":null,"partnerId":null},"createdAt":"2023-08-23T03:33:20.8569715+00:00","timestamp":"2023-08-23T11:33:20+08:00","locale":"zh-CN","market":"zh-WW","region":"WW","location":"lat:47.639557;long:-122.128159;re=1000m;","locationInfo":{"country":"北马其顿","state":"Skopski","city":"斯科普里"},"locationHints":[{"country":"Macedonia","countryConfidence":8,"state":"Centar","city":"Skopje","cityConfidence":5,"zipCode":"1004","timeZoneOffset":1,"sourceType":1,"center":{"latitude":41.9961,"longitude":21.4317,"height":null},"regionType":2}],"userIpAddress":"62.77.140.37","messageId":"50c7ddbf-8aef-4ff2-befb-95806f8f5f36","requestId":"50c7ddbf-8aef-4ff2-befb-95806f8f5f36","nlu":{"scoredClassification":{"classification":"DEEP_LEO","score":null},"classificationRanking":[{"classification":"DEEP_LEO","score":null}],"qualifyingClassifications":null,"ood":null,"metaData":null,"entities":null},"offense":"None","feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"cib","scores":[{"component":"UserOffense","score":0.00026947918},{"component":"suicide_help","score":0.0054905633}],"inputMethod":"Keyboard"},{"contentType":"IMAGE","text":"A cute cat","author":"bot","createdAt":"2023-08-23T03:33:26.1933771+00:00","timestamp":"2023-08-23T03:33:26.1933771+00:00","messageId":"29d48fc8-b49f-47e0-8284-bc9079c74801","requestId":"50c7ddbf-8aef-4ff2-befb-95806f8f5f36","messageType":"GenerateContentQuery","offense":"None","feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"DeepLeo","invocation":"graphic_art(\"A cute cat\")"},{"contentType":"IMAGE","text":"Another cute cat","author":"bot","createdAt":"2023-08-23T03:33:30.4361459+00:00","timestamp":"2023-08-23T03:33:30.4361459+00:00","messageId":"887382e2-afd1-4c50-a8b5-dbe42c59e2ca","requestId":"50c7ddbf-8aef-4ff2-befb-95806f8f5f36","messageType":"GenerateContentQuery","offense":"None","feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"DeepLeo","invocation":"graphic_art(\"Another cute cat\")"},{"contentType":"IMAGE","text":"Yet another cute cat","author":"bot","createdAt":"2023-08-23T03:33:36.0624111+00:00","timestamp":"2023-08-23T03:33:36.0624111+00:00","messageId":"98cc48f7-5c4f-469b-8c40-1cad0077df9b","requestId":"50c7ddbf-8aef-4ff2-befb-95806f8f5f36","messageType":"GenerateContentQuery","offense":"None","feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"DeepLeo","invocation":"graphic_art(\"Yet another cute cat\")"},{"text":"好的，我再为你画一个可爱的猫咪。😊","author":"bot","createdAt":"2023-08-23T03:33:42.3720639+00:00","timestamp":"2023-08-23T03:33:42.3720639+00:00","messageId":"37b51246-02da-4940-b72c-6d4e7a874310","requestId":"50c7ddbf-8aef-4ff2-befb-95806f8f5f36","offense":"None","adaptiveCards":[{"type":"AdaptiveCard","version":"1.0","body":[{"type":"TextBlock","text":"好的，我再为你画一个可爱的猫咪。😊","wrap":true}]}],"sourceAttributions":[],"feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"DeepLeo","suggestedResponses":[{"text":"画一只狗","author":"user","createdAt":"2023-08-23T03:33:44.7965859+00:00","timestamp":"2023-08-23T03:33:44.7965859+00:00","messageId":"a4a40576-fbf4-41ca-bb45-907a4ff955a5","messageType":"Suggestion","offense":"Unknown","feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"SuggestionChipsFalconService"},{"text":"你能告诉我如何画出可爱的动物吗？","author":"user","createdAt":"2023-08-23T03:33:44.796587+00:00","timestamp":"2023-08-23T03:33:44.796587+00:00","messageId":"2634d122-862d-4031-a7ff-023034472a8a","messageType":"Suggestion","offense":"Unknown","feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"SuggestionChipsFalconService"},{"text":"谢谢，这很好看。","author":"user","createdAt":"2023-08-23T03:33:44.7965873+00:00","timestamp":"2023-08-23T03:33:44.7965873+00:00","messageId":"76f60128-2646-4c40-a893-5c5a8be9fccc","messageType":"Suggestion","offense":"Unknown","feedback":{"tag":null,"updatedOn":null,"type":"None"},"contentOrigin":"SuggestionChipsFalconService"}]}],"firstNewMessageIndex":1,"defaultChatName":null,"conversationId":"51D|BingProd|06855D0700CCB74415E40AB204E7E2D4AD383B229DB48F046214BD33419A9BAA","requestId":"50c7ddbf-8aef-4ff2-befb-95806f8f5f36","conversationExpiryTime":"2023-08-23T09:33:44.8788574Z","telemetry":{"startTime":"2023-08-23T03:33:20.8521923Z"},"throttling":{"maxNumUserMessagesInConversation":30,"numUserMessagesInConversation":2,"maxNumLongDocSummaryUserMessagesInConversation":50,"numLongDocSummaryUserMessagesInConversation":0},"result":{"value":"Success","message":"好的，我再为你画一个可爱的猫咪。😊","serviceVersion":"20230822.134"}}},{"type":3,"invocationId":"0"}]

[YzBot][11:33:45.821][MARK] 开始生成内容：A cute catAnother cute catYet another cute cat
[YzBot][11:33:46.685][INFO] recv from: [Group: 向它提问(1xxxxxxxx4), Member: 完美无瑕的少女群管(xxxxxxxx)] 绘图失败：TypeError: proxy is not a function
[YzBot][11:33:46.687][INFO] succeed to send: [Group(1xxxxxxxx4)] 绘图失败：TypeError: proxy is not a function
[YzBot][11:33:46.690][INFO] {
  text: '好的，我再为你画一个可爱的猫咪。😊',
  quote: [],
  suggestedResponses: '画一只狗\n你能告诉我如何画出可爱的动物吗？\n谢谢，这很好看。',
  conversationId: '51D|BingProd|06855D0700CCB74415E40AB204E7E2D4AD383B229DB48F046214BD33419A9BAA',
  clientId: '914799426584250',
  invocationId: 1,
  conversationSignature: '0sF984cTE43GYOfFBYr2Ev5SmCEPBSWTZG7Qx8HvYdg=',
  parentMessageId: 'cd6662e4-d0d9-4ef4-bcd0-16c109e5db4b',
  bingToken: '1KId2xubj8MgvzXJzbrKzv12TGGFp2NfXaK0mTZXvTBuMMGfE2g4zoX3m_NzzP9eTbSrKIHrO7E1c7BwVIsM0Vpuday-1KeA_OuxuN2u-REYAV_yRTyhV70F-XJT1dEl9TxBW4fsEdsGo_s-Ic5XVmoY4Z5htJZGXxZWavkSgLeD7r0WwcyWGm0yHfD0AHRn2KP3Ikoja7tkW-wxKA2UUlA'
}
[YzBot][11:33:46.727][MARK] 云原神绑定失败：未包含devId字段~
{"level":30,"time":1692761626796,"pid":29436,"hostname":"WIN-2I8KJNE42RR","reqId":"req-2m","req":{"method":"POST","url":"/cache","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":53046},"msg":"incoming request"}
{"level":30,"time":1692761626824,"pid":29436,"hostname":"WIN-2I8KJNE42RR","reqId":"req-2m","res":{"statusCode":200},"responseTime":27.394700050354004,"msg":"request completed"}
[YzBot][11:33:47.424][INFO] recv from: [Group: 向它提问(1xxxxxxxx4), Member: 完美无瑕的少女群管(xxxxxxxx)] {at:xxxxx8}好的，我再为你画一个可爱的猫咪。😊
[YzBot][11:33:47.426][INFO] succeed to send: [Group(xxxxxx)] [回复@怎么也醒不了]好的，我再为你画一个可爱的猫咪。😊`

**Comment by Lovelumine** [comment]
一样的问题
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/105962147/f15f41f4-ef56-44b9-88a6-a730f875d8a9)

**Comment by Lovelumine** [comment]
完全无法使用

**Comment by ikechan8370** [comment]
请参考 https://github.com/ikechan8370/chatgpt-plugin/issues/549 的讨论处理

**Comment by TaoXiaoBai** [comment]
移除插件目录下https-proxy-agent后解决。

**Comment by Lovelumine** [comment]
没有用，已经移除了还是无法使用
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/105962147/310b7262-19dd-45fd-8e70-a36eb08c6cf0)
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/105962147/e977e332-2cec-4546-9c5d-a63fcd7a59b6)
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/105962147/923ceb83-2769-45d6-852e-dc60914c8aa0)

**Comment by Lovelumine** [comment]
不论是在插件目录下安装5.0.1还是7.0.1都没有用

**Comment by ikechan8370** [comment]
> 不论是在插件目录下安装5.0.1还是7.0.1都没有用

插件不用装这个依赖啊 是Yunzai本体自带这个依赖。你这应该是Yunzai本体缺了这个依赖

**Comment by Lovelumine** [comment]
云仔本体有这个依赖
