### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'conversationId')

### ISSUE THREAD

**Issue by Qz-Sean** [ikechan8370/chatgpt-plugin#55]
![KI 7FN_V1SHQGUDYH7M~(@E](https://user-images.githubusercontent.com/56262913/208121121-2e9e6e4b-ceee-44b1-b661-aa2a8b5a41bb.png)
账号密码没问题，这是碰到验证了吗

**Comment by Qz-Sean** [comment]
![image](https://user-images.githubusercontent.com/56262913/208122638-731b7c04-00fd-46e5-b2ee-efb2f09ed878.png)

**Comment by ikechan8370** [comment]
更新一下，然后清一下redis再看看。 用 `redis-cli` 连接到本地redis后，执行
```
del CHATGPT:CONVERSATIONS:<qq号>
```

**Comment by Qz-Sean** [comment]
![image](https://user-images.githubusercontent.com/56262913/208129086-8df9cd93-8cb0-44a6-baf8-f98f7b5bbf6e.png)
![image](https://user-images.githubusercontent.com/56262913/208129461-c967dcac-a293-4595-a9f5-13b11efd298f.png)
![image](https://user-images.githubusercontent.com/56262913/208129347-f8b98c4d-0a37-467d-b6b1-eda85bd71817.png)
还是不行
