### ISSUE TITLE
slack claude无限重复发送信息（claude 未响应）

### ISSUE THREAD

**Issue by ikashana** [ikechan8370/chatgpt-plugin#552]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

发送信息后，会非常快速的无限在slack艾特Claude，直到超时。

## 可能的解决方案

重复试验后，发现如果Claude及时完整的回复了，那么重发过程就会终止，但是未回复就会一直重发，而Claude会因为不断重复艾特不响应回复。

## 附加信息

![image](https://github.com/ikechan8370/chatgpt-plugin/assets/115872923/67482497-81a0-4c0d-a85d-102616a7e01c)

**Comment by heisenyu** [comment]
我也遇到这个问题

**Comment by ikashana** [comment]
> 我也遇到这个问题

你解决这个问题了么？
