### ISSUE TITLE
［功能请求］后台面板加入azure相关配置

### ISSUE THREAD

**Issue by TaoXiaoBai** [ikechan8370/chatgpt-plugin#555]

**Comment by HalcyonAlcedo** [comment]
至少，写点内容吧...比如加那些配置项，毕竟是不同作者开发的

**Comment by TaoXiaoBai** [comment]
> 至少，写点内容吧...比如加那些配置项，毕竟是不同作者开发的

主要是希望用户面板的模型选择可以选择azure，管理员配置可以跟锅巴里面一样填入API，部署名称和地址这些。

**Comment by HalcyonAlcedo** [comment]
已经添加，下次合并就有了

**Comment by TaoXiaoBai** [comment]
> 已经添加，下次合并就有了

![image](https://github.com/ikechan8370/chatgpt-plugin/assets/28218925/1c36b4c1-2dbe-4459-b6d5-4f3f84feb7df)
更新以后还是没有

**Comment by HalcyonAlcedo** [comment]
> > 已经添加，下次合并就有了
> 
> ![image](https://user-images.githubusercontent.com/28218925/266513445-1c36b4c1-2dbe-4459-b6d5-4f3f84feb7df.png) 更新以后还是没有

![image](https://github.com/ikechan8370/chatgpt-plugin/assets/41666148/73f2acd0-67b8-4a11-b6d3-0bf1a6257d50)
有的啊

**Comment by TaoXiaoBai** [comment]
> > > 已经添加，下次合并就有了
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/28218925/266513445-1c36b4c1-2dbe-4459-b6d5-4f3f84feb7df.png) 更新以后还是没有
> 
> ![image](https://user-images.githubusercontent.com/41666148/267031933-73f2acd0-67b8-4a11-b6d3-0bf1a6257d50.png) 有的啊

这是哪个界面啊，插件里面没看到
