### ISSUE TITLE
关于“Too many requests in 1 hour"

### ISSUE THREAD

**Issue by Shiyue00** [ikechan8370/chatgpt-plugin#56]
> 这个只需要等待一会就行了，而且也不是一小时限一次

具体频率限制清楚吗？好像不少人总触发这个 对机器人很不友好啊

_Originally posted by @ikechan8370 in https://github.com/ikechan8370/chatgpt-plugin/issues/53#issuecomment-1354303170_
      
使用同一个账号，设备，在同一时间进行了测试，结果：
使用机场的节点（机场节点很多人在用），就会导致对话一次后就提示这个
使用服务器自建节点（只有我自己用），就可以正常使用，于是猜测可能是IP的问题

但是发现discord上也有外国人遇到这个问题，那么是什么原因又不清楚了，只能说可以用这个方法暂时解决。
![image](https://user-images.githubusercontent.com/94933592/208134497-490977d3-bfe6-4b52-b36f-a32ee62b7abf.png)

**Comment by habacat** [comment]
![73124b616a4397e9835ada22520573f](https://user-images.githubusercontent.com/41714213/208233640-114cafae-58df-4e47-a215-dc97b21bc70a.png)

**Comment by habacat** [comment]
有用户反映貌似是ip问题。（可能）用的梯子如果是公共的，很多人同时用一个ip访问，chatgpt他那边就会做出限制。

**Comment by ikechan8370** [comment]
我用自用的节点确实还没遇到，不过我发的也不频繁
