### ISSUE TITLE
Organization ID如何获取

### ISSUE THREAD

**Issue by KasumiYuku** [ikechan8370/chatgpt-plugin#562]
Claude2的Organization ID如何获取

**Comment by hanhan258** [comment]
localStorage.getItem("lastActiveOrg");

**Comment by KasumiYuku** [comment]
> localStorage.getItem("lastActiveOrg");

谢谢

**Comment by ikechan8370** [comment]
> localStorage.getItem("lastActiveOrg");

tql 我都没发现

**Comment by KasumiYuku** [comment]
> > localStorage.getItem("lastActiveOrg");
> 
> tql 我都没发现

我填好了全部参数，为什么回复conversation creat error嘞
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/107661829/e3affffc-01f9-458c-af76-483d46f03eee)

**Comment by hanhan258** [comment]
> 

那你是怎么获取的，我也记一下

**Comment by ikechan8370** [comment]
> > > localStorage.getItem("lastActiveOrg");
> > 
> > 
> > tql 我都没发现
> 
> 我填好了全部参数，为什么回复conversation creat error嘞 ![image](https://user-images.githubusercontent.com/107661829/267608700-e3affffc-01f9-458c-af76-483d46f03eee.png)

1. 需要配置英美ip的代理
2. 有可能需要填自己的UA和指纹

**Comment by ikechan8370** [comment]
> > 
> 
> 那你是怎么获取的，我也记一下

忘了 好像是看的请求

**Comment by KasumiYuku** [comment]
> > > > localStorage.getItem("lastActiveOrg");
> > > 
> > > 
> > > tql 我都没发现
> > 
> > 
> > 我填好了全部参数，为什么回复conversation creat error嘞 ![image](https://user-images.githubusercontent.com/107661829/267608700-e3affffc-01f9-458c-af76-483d46f03eee.png)
> 
> 1. 需要配置英美ip的代理
> 2. 有可能需要填自己的UA和指纹

我Clash开了全局模式，UA用的是自己的，浏览器上可以用Claude.ai,但是插件提示conversation creat error

**Comment by ikechan8370** [comment]
https://chatgptplugin.ikechan8370.com/tutorial/claude.html
