### ISSUE TITLE
Error: OpenAI missing required apiKey

### ISSUE THREAD

**Issue by ZaraZackBee** [ikechan8370/chatgpt-plugin#566]
不知道是哪里出错了，更新了插件，也更新了api，重启后还是不能用，显示的就是这个，聊天记录发了一张图片
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/138028030/a9fa12b5-8459-426c-8cc3-b242be6b81b6)
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/138028030/ad374644-26dc-42af-8eb2-5be313c8e12d)

**Comment by TsukinaKasumi** [comment]
https://chatgptplugin.ikechan8370.com/guide/
