### ISSUE TITLE
对话时bot会无视或直接略过带有某些词组的对话

### ISSUE THREAD

**Issue by buyun14** [ikechan8370/chatgpt-plugin#568]
发现对话时bot会无视或直接略过带有某些词组的对话，目前发现有“幻影”“动态”等词，后台日志中显示bot没有对含有该类词组的对话进行任何处理和反馈，但奇怪的是我并没有设置之类的屏蔽词。

**Comment by ikechan8370** [comment]
可能是被其他优先级更高的插件截取了指令，没有进入到插件？
