### ISSUE TITLE
ubuntu22.04报错SyntaxError: The requested module 'chatgpt' does not provide an export named 'ChatGPTAPIBrowser'

### ISSUE THREAD

**Issue by cj0928** [ikechan8370/chatgpt-plugin#57]
![image](https://user-images.githubusercontent.com/104024133/208218006-111972d7-fc96-4af0-8bfa-9451febfd529.png)

![image](https://user-images.githubusercontent.com/104024133/208218082-36bc18bf-2539-418a-a6d4-50220d30336d.png)

**Comment by Qz-Sean** [comment]
更新一下`chatgpt`

**Comment by cj0928** [comment]
> 更新一下`chatgpt`

还真是，更新完就好了
