### ISSUE TITLE
vits语音api获取不到，在复制空间这步就卡住了

### ISSUE THREAD

**Issue by bai125** [ikechan8370/chatgpt-plugin#570]
![6`37W%2J009HWFW)_KKUGGT](https://github.com/ikechan8370/chatgpt-plugin/assets/146201660/556e07fa-21ee-405a-8be6-5f6a3ee5cdc5)
![XGD~TS%AP3I8QCBU6GQDLNN](https://github.com/ikechan8370/chatgpt-plugin/assets/146201660/b3ebe5e9-ff4a-4148-bcee-fc49bb61a699)
![0E QK{9UPXG2VV(7)E_~0HI](https://github.com/ikechan8370/chatgpt-plugin/assets/146201660/3430b391-4955-41a2-bc32-7c2a54c9b5a3)
请看，我的最后一张是公开的，所以我觉得应该和私人没关系，希望大佬可以解决一下

**Comment by bai125** [comment]
私人我也试过，代码没注意是不是一样的但都是错误

**Comment by gyh354** [comment]
同样的问题

**Comment by Inky-Moon** [comment]
我也是遇到了一样的问题

**Comment by misaka20002** [comment]
我可以复制，
你也可以直接用报脸别人现成的
