### ISSUE TITLE
 TypeError: Cannot read properties of undefined (reading 'exception')

### ISSUE THREAD

**Issue by TaoXiaoBai** [ikechan8370/chatgpt-plugin#572]
必应自定义模式失效了，换节点和token都没有用。

`[{"type":2,"invocationId":"0","item":{"firstNewMessageIndex":null,"defaultChatName":null,"conversationId":"51D|BingProd|8351B9BB030B0A0BB594FE49B357C65FBD22352593EEB417EFC130A0C66954AE","requestId":"048a2a97-466e-4332-b2c0-1878c38915c3","telemetry":{"startTime":"2023-10-02T15:58:20.3440293Z"},"result":{"value":"UnauthorizedRequest","message":"Cannot retrieve user status.","error":"UnauthorizedRequest","renewCert":true,"serviceVersion":"20230929.136"}}},{"type":3,"invocationId":"0"}]

[MiaoYz][23:58:20.607][ERRO] {
  message: 'UnauthorizedRequest\nUnauthorizedRequest\nundefined',
  conversation: {
    conversationSignature: '+1SJBbsg1vnlxTfmufsTWerF5/hQdjNNE6DQyKR2ae8=',
    conversationId: '51D|BingProd|8351B9BB030B0A0BB594FE49B357C65FBD22352593EEB417EFC130A0C66954AE',
    clientId: '03ECC6E5CC9861EE132BD57BCD41605E'
  },
  maxConv: 30
}
[MiaoYz][23:58:20.615][ERRO] TypeError: Cannot read properties of undefined (reading 'exception')
    at chatgpt.sendMessage (file:///I:/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:1735:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async chatgpt.abstractChat (file:///I:/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:1055:25)
    at async chatgpt (file:///I:/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:821:5)
    at async PluginsLoader.deal (file:///I:/Miao-Yunzai/lib/plugins/loader.js:269:54)
{"level":30,"time":1696262300625,"pid":22604,"hostname":"WIN-2I8KJNE42RR","reqId":"req-cx","req":{"method":"POST","url":"/cache","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":63232},"msg":"incoming request"}
{"level":30,"time":1696262300640,"pid":22604,"hostname":"WIN-2I8KJNE42RR","reqId":"req-cx","res":{"statusCode":200},"responseTime":15.034299850463867,"msg":"request completed"}
{"level":30,"time":1696262300905,"pid":22604,"hostname":"WIN-2I8KJNE42RR","reqId":"req-cy","req":{"method":"GET","url":"/page/1109y?qr=false","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":63233},"msg":"incoming request"}
{"level":30,"time":1696262300912,"pid":22604,"hostname":"WIN-2I8KJNE42RR","reqId":"req-cy","res":{"statusCode":200},"responseTime":6.375999927520752,"msg":"request completed"}
{"level":30,"time":1696262300939,"pid":22604,"hostname":"WIN-2I8KJNE42RR","reqId":"req-cz","req":{"method":"GET","url":"/live2d/live2dcubismcore.min.js","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":63233},"msg":"incoming request"}
{"level":30,"time":1696262300943,"pid":22604,"hostname":"WIN-2I8KJNE42RR","reqId":"req-cz","res":{"statusCode":304},"responseTime":4.000799894332886,"msg":"request completed"}
{"level":30,"time":1696262300948,"pid":22604,"hostname":"WIN-2I8KJNE42RR","reqId":"req-d0","req":{"method":"GET","url":"/js/chunk-vendors.b7a1d693.js","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":63236},"msg":"incoming request"}
{"level":30,"time":1696262300950,"pid":22604,"hostname":"WIN-2I8KJNE42RR","reqId":"req-d0","res":{"statusCode":304},"responseTime":1.9800000190734863,"msg":"request completed"}
{"level":30,"time":1696262300951,"pid":22604,"hostname":"WIN-2I8KJNE42RR","reqId":"req-d1","req":{"method":"GET","url":"/css/chunk-vendors.0ede84b4.css","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":63239},"msg":"incoming request"}
{"level":30,"time":1696262300952,"pid":22604,"hostname":"WIN-2I8KJNE42RR","reqId":"req-d2","req":{"method":"GET","url":"/css/app.a18150c7.css","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":63240},"msg":"incoming request"}
{"level":30,"time":1696262300954,"pid":22604,"hostname":"WIN-2I8KJNE42RR","reqId":"req-d3","req":{"method":"GET","url":"/js/app.9eedf06d.js","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":63241},"msg":"incoming request"}
{"level":30,"time":1696262300957,"pid":22604,"hostname":"WIN-2I8KJNE42RR","reqId":"req-d1","res":{"statusCode":304},"responseTime":5.198899984359741,"msg":"request completed"}
{"level":30,"time":1696262300957,"pid":22604,"hostname":"WIN-2I8KJNE42RR","reqId":"req-d2","res":{"statusCode":304},"responseTime":5.097399950027466,"msg":"request completed"}
{"level":30,"time":1696262300958,"pid":22604,"hostname":"WIN-2I8KJNE42RR","reqId":"req-d3","res":{"statusCode":304},"responseTime":4.222399950027466,"msg":"request completed"}
{"level":30,"time":1696262301982,"pid":22604,"hostname":"WIN-2I8KJNE42RR","reqId":"req-d4","req":{"method":"POST","url":"/page","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":63241},"msg":"incoming request"}
{"level":30,"time":1696262301985,"pid":22604,"hostname":"WIN-2I8KJNE42RR","reqId":"req-d4","res":{"statusCode":200},"responseTime":2.5723001956939697,"msg":"request completed"}
{"level":30,"time":1696262302051,"pid":22604,"hostname":"WIN-2I8KJNE42RR","reqId":"req-d5","req":{"method":"GET","url":"/fonts/fa-solid-900.3eae9857.woff2","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":63241},"msg":"incoming request"}
{"level":30,"time":1696262302052,"pid":22604,"hostname":"WIN-2I8KJNE42RR","reqId":"req-d5","res":{"statusCode":304},"responseTime":1.0947999954223633,"msg":"request completed"}`

**Comment by TaoXiaoBai** [comment]
换了好几遍token后突然能用了，很怪，先关掉了（

**Comment by ikechan8370** [comment]
这是你token过期了
