### ISSUE TITLE
这个是没开代理的原因还是？

### ISSUE THREAD

**Issue by cj0928** [ikechan8370/chatgpt-plugin#58]
![image](https://user-images.githubusercontent.com/104024133/208234541-982d3eb3-1ecf-4625-b37a-3de188daf229.png)
![image](https://user-images.githubusercontent.com/104024133/208234504-460a5505-3527-4331-9651-e47c991c5aa6.png)

**Comment by mlaswt** [comment]
昨天还没这问题 今天更新了我也报错了 不过内容不一样
