### ISSUE TITLE
参考文档里面那个鹤望兰版本的打不开

### ISSUE THREAD

**Issue by Inky-Moon** [ikechan8370/chatgpt-plugin#582]
点开就显示这个，不知道什么原因
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/84265441/78f70aff-da44-43d6-8377-14a9604984fb)

**Comment by ikechan8370** [comment]
那个没了（wolai收费了） 迁移到我的网站了，但可能更新不是那么勤

**Comment by ikechan8370** [comment]
readme已更新
