### ISSUE TITLE
在miao-yunzai（喵崽）转入ntqq后无法在群聊使用@触发回复只能使用#chat触发回复

### ISSUE THREAD

**Issue by yuanban** [ikechan8370/chatgpt-plugin#587]
#问题描述
在miao-yunzai（喵崽）转入ntqq后无法在群聊使用@触发回复只能使用#chat触发回复，希望作者大佬能解决这个问题

**Comment by ikechan8370** [comment]
本人测试可以，你能说一下你的环境？

**Comment by yuanban** [comment]
环境：Windows Server2019 nodejs18.17.0  Redis 5.0.14.1

**Comment by yuanban** [comment]
喵崽使用的是最新版本

**Comment by yuanban** [comment]
重装完解决了谢谢大佬
