### ISSUE TITLE
没有回复，也没有错误提示

### ISSUE THREAD

**Issue by M0refish** [ikechan8370/chatgpt-plugin#59]
![image](https://user-images.githubusercontent.com/120435537/208243565-5b8b68db-144c-4c87-8f63-bbfc7285e56e.png)
Centos里，已经设置关闭interface，也设置了chrome路径，2captchaToken，
但就是没回复，也没提示错误。。
![image](https://user-images.githubusercontent.com/120435537/208243787-0f90adaf-a0f4-41a6-8742-73cd8c18afb7.png)

**Comment by Qz-Sean** [comment]
![5L}Z VU`WKK3NRCL~Y9`BIU](https://user-images.githubusercontent.com/56262913/208246498-b655019e-ca86-4479-9c47-c2a3240b21c3.png)
会在划线处卡很久，然后报状态码401。同centos，配置和你一样。

**Comment by cj0928** [comment]
> ![5L}Z VU`WKK3NRCL~Y9`BIU](https://user-images.githubusercontent.com/56262913/208246498-b655019e-ca86-4479-9c47-c2a3240b21c3.png)
> 
> 会在划线处卡很久，然后报状态码401。同centos，配置和你一样。

ubuntu，遇到了同样的问题，我是广东的腾讯云

**Comment by L1ttleBad** [comment]
node js 的chatgpt包正在高强度更新，3.0.0版本之后api基本都变了，作者用的是他自己写的内容，似乎有点跟不上openai的变化

**Comment by ikechan8370** [comment]
已经修复了 not signed in得问题。一个很蠢的问题

**Comment by ikechan8370** [comment]
> node js 的chatgpt包正在高强度更新，3.0.0版本之后api基本都变了，作者用的是他自己写的内容，似乎有点跟不上openai的变化

不是自己写的，是把api的部分代码抄过来了，做了一些修改适配Yunzai插件的运行模式。
