### ISSUE TITLE
私聊中的文件读取

### ISSUE THREAD

**Issue by Yoraka** [ikechan8370/chatgpt-plugin#592]
私聊里发文件的时候会直接触发bing回复(一般会回复“你发的离线文件是啥”)，能否在prompt为[离线文件]时触发固定回复，顺便提醒一下使用者要通过引用文件消息才能触发文件读取功能。
还可以增加一个清空received文件夹的指令？
另外，还希望在调用文件读取时覆盖掉config里的SydneyContext，目前它在SydneyAIClient里是被context覆盖的，这样子一旦设置了context就用不了文件读取功能了

**Comment by ikechan8370** [comment]
第一个和第三个面包你的意思了。
第二个是指清理本地存储的文件的意思吗？

这些问题感觉都还挺有用，找时间修复一下

**Comment by Yoraka** [comment]
> 第一个和第三个面包你的意思了。 第二个是指清理本地存储的文件的意思吗？
> 
> 这些问题感觉都还挺有用，找时间修复一下

第二个是那个意思，但想了下还是直接去服务器删文件可能比较好。

**Comment by ikechan8370** [comment]
嗯嗯 也可以改成定时清理 防止占用太多空间

**Comment by ikechan8370** [comment]
not stale
