### ISSUE TITLE
在discord上的撤回信息问题

### ISSUE THREAD

**Issue by myself147** [ikechan8370/chatgpt-plugin#593]
在qq和tg中，撤回信息功能正常，但是在discord中，不只是撤回删除预设的思考中信息，会连用户提问的信息一并删除，导致只留下最后的提问回复，尝试过调整身份组令bot禁止删除信息，但将会导致报错。

**Comment by ikechan8370** [comment]
这个撤回应该不受插件控制。
可以先用 #chatgpt关闭确认 关掉这个确认信息

**Comment by myself147** [comment]
了解，关闭后就正常了！
