### ISSUE TITLE
文件读取中的PPTX读取问题

### ISSUE THREAD

**Issue by Yoraka** [ikechan8370/chatgpt-plugin#595]
nodejs-pptx是不是读取不了pptx里的内容，element里面是空的，最后拼了一串\n出来。
而且好像网上没有能读pptx内容的module？

**Comment by ikechan8370** [comment]
我也遇到了 全是\n 不知道是不是js不太能读

**Comment by Yoraka** [comment]
> 我也遇到了 全是\n 不知道是不是js不太能读

手搓吧(
