### ISSUE TITLE
请求支持讯飞星火大模型3.0版本

### ISSUE THREAD

**Issue by Oishiimono** [ikechan8370/chatgpt-plugin#597]
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/34758515/3ecc6b1a-f451-4714-ab4d-ded69aac5aef)
当前已支持1.0、2.0

![image](https://github.com/ikechan8370/chatgpt-plugin/assets/34758515/7d8174e9-460d-4099-a5ae-42dd73a726d3)
目前讯飞已推出3.0

如果方便的话推荐进行支持，感谢大佬~

**Comment by ikechan8370** [comment]
#598 Alcedo佬已经适配
