### ISSUE TITLE
插件报错，没有返回

### ISSUE THREAD

**Issue by ChthollyWn** [ikechan8370/chatgpt-plugin#6]
![image](https://user-images.githubusercontent.com/85938618/206140120-91aa10f9-a76f-44dd-9ef0-7d809e645ce3.png)
这是日志的输出，而且有时输出的速度特别慢

**Comment by ChthollyWn** [comment]
命令是 介绍一下米哈游
好像是使用长中文就会报这个503错误

**Comment by ChthollyWn** [comment]
![image](https://user-images.githubusercontent.com/85938618/206142021-152205c3-fbd6-4849-8b32-37f617d8740c.png)
使用英文可以正常交流

**Comment by habacat** [comment]
试了下，中文在很多情况下会报503错误，也不知道为啥

**Comment by ikechan8370** [comment]
503今天我也遇到了。就是超时了，可能是中文处理的慢+网络原因？而且发现503一天之内不定期出现，每次持续时间长短不定，过一会再试就好了。

**Comment by ikechan8370** [comment]
昨晚很严重，今天白天就很好，OpenAI服务器问题
