### ISSUE TITLE
API3的反代是有时候用不了还是已经不能用了啊up主

### ISSUE THREAD

**Issue by henghengkan** [ikechan8370/chatgpt-plugin#600]
{
    "status": 404,
    "statusText": "",
    "body": {
        "detail": "Not Found"
    },
    "error": {
        "statusCode": 404,
        "statusText": ""
    }

**Comment by ikechan8370** [comment]
几个月没维护这个了，有待调查

**Comment by henghengkan** [comment]
> 几个月没维护这个了，有待调查

哎，可惜没有自建API的钱钱
up主后面加的那些模式指令是#chatgpt切换GLM或者星火吗，还有这个星火是一定要key么，配置cookie不可以直接用啊API都是要钱的呜呜呜，gpt新号的5$快没了 T - T

**Comment by henghengkan** [comment]
星火是免费的，我爱你讯飞

**Comment by ikechan8370** [comment]
通义千问 星火 文心一言都有免费额度
文心一言4.0近期内会支持

**Comment by henghengkan** [comment]
> 几个月没维护这个了，有待调查

我星火key开的是3.0就是那个体验版吗？大大

**Comment by henghengkan** [comment]
那个cookie还有助手接口是什么啊，up你说明文档没写，我在聊天界面一开开发者就白了

**Comment by ikechan8370** [comment]
你确认看过文档了？
https://chatgptplugin.ikechan8370.com/tutorial/xinghuo.html

**Comment by henghengkan** [comment]
> 你确认看过文档了？ [https://chatgptplugin.ikechan8370.com/tutorial/xinghuo.html  [https://chatgptplugin.ikechan8370.com/tutorial/xinghuo.html ](https://chatgptplugin.ikechan8370.com/tutorial/xinghuo.html) ](https://chatgptplugin.ikechan8370.com/tutorial/xinghuo.html)

我的，哈哈，但是我自己解决了F12变白
![屏幕截图 2023-10-27 213358](https://github.com/ikechan8370/chatgpt-plugin/assets/120463504/b5127695-ac66-49eb-9fcb-00c4283d56bf)
点这个它会变成手机模式然后再进去那个网址就可以了
