### ISSUE TITLE
关于读取群聊聊天记录

### ISSUE THREAD

**Issue by suzuka-suzuka** [ikechan8370/chatgpt-plugin#601]
读取聊天记录的时候能不能忽略机器人自己发的消息，用必应的自定义模式感觉就是因为读了机器人本身之前发的消息所以才会导致回复的内容很相似甚至完全相同。

**Comment by ikechan8370** [comment]
关于这个，有时候确实会导致复读，有时候会帮助理解逻辑
后续版本会加个配置项 是否读取bot本身发的消息
