### ISSUE TITLE
ChatGPT API3模式下对话，机器人回复“没有任何回复”

### ISSUE THREAD

**Issue by OMGLogic** [ikechan8370/chatgpt-plugin#602]
已确认更新到最新版本
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/67633987/af5178ca-5b58-42b6-b09d-54bf80a9f20b)
API3模式下，给机器人发消息，机器人回复“没有任何回复”，如下图所示
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/67633987/a42fc2f6-eb36-44a0-b6c3-a0be5fb08964)
登录openai官网，发现对话记录如图
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/67633987/62788892-9761-4d2f-9411-d2b1ea25c0e5)
尝试过结束对话以及重装插件，均没有效果

**Comment by ikechan8370** [comment]
OpenAI防护升级 API3暂时不可用

**Comment by henghengkan** [comment]
你竟然弄了反代，哇哦
