### ISSUE TITLE
通信异常,错误信息如下 Cannot read properties of undefined (reading 'quote')

### ISSUE THREAD

**Issue by orangegnar** [ikechan8370/chatgpt-plugin#604]
![IMG_20231030_031420](https://github.com/ikechan8370/chatgpt-plugin/assets/149192276/2194e2b7-c85e-485f-b6f2-f6fbab15583f)
已切换文字方式回答，但仍输出图片，并告知通信异常,错误信息如下
Cannot read properties of undefined (reading 'quote')

**Comment by TsukinaKasumi** [comment]
把报错部分的完整日志发出来看看
