### ISSUE TITLE
bing悉尼/chat无法使用

### ISSUE THREAD

**Issue by luluxiaoyu** [ikechan8370/chatgpt-plugin#605]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

使用bing悉尼时，bot返回invalid url：/sydney/chathub？sec-access-token=xxx
使用正常的三个选项则返回null

## 预期行为

返回正常信息

## 实际行为

返回错误

## 复制过程

#bing你好

## 环境

win10ltsc2101+node18+miao yunzai

## 可能的解决方案

更新插件，关掉反向代理，配置http代理

## 附加信息

http代理没问题（api3正常使用）

**Comment by ikechan8370** [comment]
你应该是勾选了对话使用反代，同时删掉了反代，就会这样。
你要是不想用反代，就不要勾选对话使用反代。
三种正常模式不是本插件维护的，不知道上游依赖是否更新了，以后会删掉。

**Comment by luluxiaoyu** [comment]
![IMG_9016](https://github.com/ikechan8370/chatgpt-plugin/assets/58876608/7fff1619-b26f-4f43-8f1d-0de67cbfbe1b)
现在返回Unexpected server response: 200

**Comment by luluxiaoyu** [comment]
直接用反代而不是代理的话看日志好像是有验证码

**Comment by ikechan8370** [comment]
不用反代200不是很正常 提问之前先去搜搜已有的issue

**Comment by ikechan8370** [comment]
如果验证码且无法自动解决 要手动去网页上对话一次

**Comment by ikechan8370** [comment]
验证码跟着账号的 和ip无关

**Comment by luluxiaoyu** [comment]
用反代的话那个验证码，我挂代理上网页版能正常对话，没出验证码

**Comment by ikechan8370** [comment]
1. 验证码和用不用反代没有任何关系
2. 如果你网页不出码，日志有验证码，就检查token是否是一致的，是否配置了多个token。

**Comment by luluxiaoyu** [comment]
token一致，我删除了所有token再重新去网页获取了token并添加，控制台报有验证码，但是我在刚刚获取token的网页上对话了几次均没出现验证码

**Comment by ikechan8370** [comment]
有图吗？没见过你说的这种情况

**Comment by luluxiaoyu** [comment]
![Uploading IMG_90
![IMG_9017](https://github.com/ikechan8370/chatgpt-plugin/assets/58876608/f3f7371c-a8fe-4f4c-abca-a4545bb9eca9)
![IMG_9018](https://github.com/ikechan8370/chatgpt-plugin/assets/58876608/c520d46d-6ad4-424c-b702-0ba4cd07eb25)
![IMG_9019](https://github.com/ikechan8370/chatgpt-plugin/assets/58876608/1814b2b3-0ed9-467e-b618-f0e802511d7e)

**Comment by ikechan8370** [comment]
没截全 下面的warn说的是什么？

**Comment by luluxiaoyu** [comment]
token过期 或者去对话

**Comment by ikechan8370** [comment]
推了一个更新，你看能否解决你的问题

**Comment by luluxiaoyu** [comment]
bot报错：出现必应验证码，尝试解决中
验证码解决失败: Request is throttled
网页版依旧未出现验证码

**Comment by luluxiaoyu** [comment]
今早我重新注册了一个美区账户，验证码一下子就出来了，并且可以用
怀疑是账户问题。。？

**Comment by unknown10777** [comment]
我的报错是Error: no captcha source
请问这个该如何解决？

**Comment by luluxiaoyu** [comment]
> 我的报错是Error: no captcha source 请问这个该如何解决？

进网页版看看有没验证，这几天好像没法自动过

**Comment by unknown10777** [comment]
有验证，目测这个问题出现了两周

**Comment by luluxiaoyu** [comment]
> 有验证，目测这个问题出现了两周

验证完也不行？

**Comment by unknown10777** [comment]
验证完是可以正常响应的，但是过一周又会captcha

**Comment by luluxiaoyu** [comment]
> 验证完是可以正常响应的，但是过一周又会captcha

一周算不错了啊，我的现在每天都得手动过一次：）
