### ISSUE TITLE
Bing验证失效

### ISSUE THREAD

**Issue by bincooo** [ikechan8370/chatgpt-plugin#608]
你好，Bing验证目前还可用嘛

**Comment by ikechan8370** [comment]
你手动能过吗 我网页上手动也过不了了 比较无解。

**Comment by bincooo** [comment]
手动可以，自动打勾

**Comment by ikechan8370** [comment]
我也自动打勾 但是会无限循环。现在服务端就是这样 无限出码

**Comment by bincooo** [comment]
好吧，微软罪该万死

**Comment by TaoXiaoBai** [comment]
> 我也自动打勾 但是会无限循环。现在服务端就是这样 无限出码

佬还考虑修自动过码吗？顺带一提无限出码大概率是IP黑了（

**Comment by ikechan8370** [comment]
> > 我也自动打勾 但是会无限循环。现在服务端就是这样 无限出码
> 
> 佬还考虑修自动过码吗？顺带一提无限出码大概率是IP黑了（

不是ip问题。是单纯的_U不可以了。需要其他Cookie，目前不好判断。可能以后会撤掉这个选项，改为本地验证，但是比较吃配置。

**Comment by TaoXiaoBai** [comment]
> > > 我也自动打勾 但是会无限循环。现在服务端就是这样 无限出码
> > 
> > 
> > 佬还考虑修自动过码吗？顺带一提无限出码大概率是IP黑了（
> 
> 不是ip问题。是单纯的_U不可以了。需要其他Cookie，目前不好判断。可能以后会撤掉这个选项，改为本地验证，但是比较吃配置。

好好好，等佬后面更新了
