### ISSUE TITLE
miao-yunzai+ntqq转发消息报错

### ISSUE THREAD

**Issue by Chocolatemocha** [ikechan8370/chatgpt-plugin#609]
环境：miao-yunzai+NTQQ，icqq版本0.6.2，nodejs v19。
问题描述：本体和插件都更新到最新了，遇到转发消息（包括必应带链接的转发/设定列表）会报错。（给本体发#日志，没出现此问题）。不太清楚是哪里问题，麻烦大佬们有空看看
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/42531322/f3713150-8a77-44f6-a1b9-35005e53fea5)

**Comment by ikechan8370** [comment]
我试试 记得很早就修复了
