### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'delay' imported

### ISSUE THREAD

**Issue by XiaoGuoLiZi** [ikechan8370/chatgpt-plugin#61]
![image](https://user-images.githubusercontent.com/109161009/208248767-dfdf3e68-9248-498d-8ee8-a938610f92b9.png)
更新后报错

**Comment by sasakiyuki9** [comment]
一样的情况 
![图片](https://user-images.githubusercontent.com/120835596/208264949-67b5437d-bba5-4179-82c2-4298579a72e1.png)

**Comment by Inky-Moon** [comment]
pnpm install -w delay

**Comment by Inky-Moon** [comment]
缺什么package，就用pnpm install -w加包名安装就好了

**Comment by TomyJan** [comment]
开发大大 up 下 readme

**Comment by Tigercrl** [comment]
pnpm install -w uuid delay
