### ISSUE TITLE
bing报错引用报错Cannot read properties of undefined (reading 'nickname ')，星火3.0支持

### ISSUE THREAD

**Issue by ikashana** [ikechan8370/chatgpt-plugin#610]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

1.星火暂时不支持3.0模型，3.0暂时使用不了。
2.bing模式下能够正常对话，但是对于引用的出处报错 “Cannot read properties of undefined (reading 'nickname ')”

另外slack Claude是不是用不了了？我看好像提示要收费了还是什么？

**Comment by ikechan8370** [comment]
没有看懂你的问题

**Comment by ikashana** [comment]
> 没有看懂你的问题

是两个问题

一是星火有V3.0的模型了，我看锅巴的配置选择里没有3.0，还只有V1.0 2.0和助手的可选。

二是bing模式，我问她问题可以正常回复，但是在引用的来源那条消息，提示的是Cannot read properties of undefined (reading 'nickname ')

![image](https://github.com/ikechan8370/chatgpt-plugin/assets/115872923/d74860c1-b3ea-4d6d-a953-5bbd6c8e2495)

**Comment by ikechan8370** [comment]
锅巴没加3.0选项，可以用工具箱或者改配置文件。我抽空给锅巴加上

第二个需要日志

**Comment by ikashana** [comment]
> 锅巴没加3.0选项，可以用工具箱或者改配置文件。我抽空给锅巴加上
> 
> 第二个需要日志

好的好的，谢谢大佬。工具箱还没用过，我去找来看看

第二个看后台错误信息是这样的
[YzBot][13:16:46.139][ERRO] TypeError: Cannot read properties of undefined (rea
ding 'nickname')
    at makeForwardMsg (file:///E:/yuanshen/Yunzai-Bot/plugins/chatgpt-plugin/ut
ils/common.js:107:24)
    at chatgpt.abstractChat (file:///E:/yuanshen/Yunzai-Bot/plugins/chatgpt-plu
gin/apps/chat.js:1340:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async chatgpt.bing (file:///E:/yuanshen/Yunzai-Bot/plugins/chatgpt-plugi
n/apps/chat.js:1442:5)
    at async PluginsLoader.deal (file:///E:/yuanshen/Yunzai-Bot/lib/plugins/loa
der.js:251:52)
{"level":30,"time":1700111806142,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-13","req":{"method":"POST","url":"/cache","hostname":"127.0.0.1:3321","r
emoteAddress":"::ffff:127.0.0.1","remotePort":60959},"msg":"incoming request"}
{"level":30,"time":1700111806148,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-13","res":{"statusCode":200},"responseTime":5.491999998688698,"msg":"req
uest completed"}
{"level":30,"time":1700111806170,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-14","req":{"method":"GET","url":"/page/red4p?qr=true","hostname":"127.0.
0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":60960},"msg":"incomin
g request"}
{"level":30,"time":1700111806172,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-14","res":{"statusCode":200},"responseTime":1.4184000045061111,"msg":"re
quest completed"}
{"level":30,"time":1700111806187,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-15","req":{"method":"GET","url":"/live2d/live2dcubismcore.min.js","hostn
ame":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":60960},"m
sg":"incoming request"}
{"level":30,"time":1700111806188,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-15","res":{"statusCode":304},"responseTime":1.4716999977827072,"msg":"re
quest completed"}
{"level":30,"time":1700111806191,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-16","req":{"method":"GET","url":"/css/chunk-vendors.0ede84b4.css","hostn
ame":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":60961},"m
sg":"incoming request"}
{"level":30,"time":1700111806191,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-17","req":{"method":"GET","url":"/css/app.a18150c7.css","hostname":"127.
0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":60962},"msg":"incom
ing request"}
{"level":30,"time":1700111806192,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-16","res":{"statusCode":304},"responseTime":1.3813999965786934,"msg":"re
quest completed"}
{"level":30,"time":1700111806193,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-17","res":{"statusCode":304},"responseTime":1.1599999964237213,"msg":"re
quest completed"}
{"level":30,"time":1700111806207,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-18","req":{"method":"GET","url":"/js/chunk-vendors.b7a1d693.js","hostnam
e":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":60962},"msg
":"incoming request"}
{"level":30,"time":1700111806208,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-18","res":{"statusCode":304},"responseTime":0.7608000040054321,"msg":"re
quest completed"}
{"level":30,"time":1700111806248,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-19","req":{"method":"GET","url":"/js/app.9eedf06d.js","hostname":"127.0.
0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":60962},"msg":"incomin
g request"}
{"level":30,"time":1700111806249,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-19","res":{"statusCode":304},"responseTime":0.5989999994635582,"msg":"re
quest completed"}
{"level":30,"time":1700111806862,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-1a","req":{"method":"POST","url":"/page","hostname":"127.0.0.1:3321","re
moteAddress":"::ffff:127.0.0.1","remotePort":60962},"msg":"incoming request"}
{"level":30,"time":1700111806863,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-1a","res":{"statusCode":200},"responseTime":1.0733999982476234,"msg":"re
quest completed"}
{"level":30,"time":1700111806980,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-1b","req":{"method":"GET","url":"/live2d/Murasame/Murasame.model3.json",
"hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":609
62},"msg":"incoming request"}
{"level":30,"time":1700111806981,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-1b","res":{"statusCode":304},"responseTime":0.8516000062227249,"msg":"re
quest completed"}
{"level":30,"time":1700111806990,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-1c","req":{"method":"GET","url":"/fonts/fa-solid-900.3eae9857.woff2","ho
stname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":60962}
,"msg":"incoming request"}
{"level":30,"time":1700111806991,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-1c","res":{"statusCode":304},"responseTime":0.59009999781847,"msg":"requ
est completed"}
{"level":30,"time":1700111807026,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-1d","req":{"method":"GET","url":"/live2d/Murasame/Murasame.moc3","hostna
me":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":60962},"ms
g":"incoming request"}
{"level":30,"time":1700111807027,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-1e","req":{"method":"GET","url":"/live2d/Murasame/Murasame.4096/texture_
00.png","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remoteP
ort":60961},"msg":"incoming request"}
{"level":30,"time":1700111807028,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-1d","res":{"statusCode":304},"responseTime":1.5314999967813492,"msg":"re
quest completed"}
{"level":30,"time":1700111807030,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-1e","res":{"statusCode":304},"responseTime":2.1920999959111214,"msg":"re
quest completed"}
{"level":30,"time":1700111807109,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-1f","req":{"method":"GET","url":"/live2d/Murasame/motion/motion01.motion
3.json","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remoteP
ort":60961},"msg":"incoming request"}
{"level":30,"time":1700111807110,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-1f","res":{"statusCode":304},"responseTime":0.8879999965429306,"msg":"re
quest completed"}
{"level":30,"time":1700111807165,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-1g","req":{"method":"GET","url":"/live2d/Murasame/Murasame.physics3.json
","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":6
0961},"msg":"incoming request"}
{"level":30,"time":1700111807165,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-1g","res":{"statusCode":304},"responseTime":0.7663999944925308,"msg":"re
quest completed"}
{"level":30,"time":1700111807179,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-1h","req":{"method":"GET","url":"/live2d/Murasame/motion/motion01.motion
3.json","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remoteP
ort":60961},"msg":"incoming request"}
{"level":30,"time":1700111807180,"pid":6668,"hostname":"WIN-5HVU61VTPIO","reqId
":"req-1h","res":{"statusCode":304},"responseTime":0.5183999985456467,"msg":"re
quest completed"}

**Comment by ikechan8370** [comment]
你是什么适配器啊？是icqq吗？

**Comment by ikashana** [comment]
> 你是什么适配器啊？是icqq吗？

我的是OICQ吧

**Comment by ikechan8370** [comment]
oicq？要不你加群来问？

**Comment by ikashana** [comment]
> oicq？要不你加群来问？



> oicq？要不你加群来问？

我应该是在那个1600个人的群里的！太多人了，不太懂就不太好意思找人问_(:з)∠)_

**Comment by ikechan8370** [comment]
> > oicq？要不你加群来问？
> 
> > oicq？要不你加群来问？
> 
> 我应该是在那个1600个人的群里的！太多人了，不太懂就不太好意思找人问_(:з)∠)_

你这个错确实没见过。是缺失了e.bot，这怎么可能呢。除非是自己改过或者版本特别老的机器人？

**Comment by ikashana** [comment]
> > > oicq？要不你加群来问？
> > 
> > 
> > > oicq？要不你加群来问？
> > 
> > 
> > 我应该是在那个1600个人的群里的！太多人了，不太懂就不太好意思找人问_(:з)∠)_
> 
> 你这个错确实没见过。是缺失了e.bot，这怎么可能呢。除非是自己改过或者版本特别老的机器人？

可能是比较老的了？我yunzai仓库没了后我就没更新本体了所以应该是2月份最后更新yunzai？没切换去喵崽什么的，感觉能用就一直用了_(:з)∠)_，我也是第一次遇到这个问题，而且我记得之前bing没有这个验证之前，我也有用过bing模式，是可以正常发送过来这些引用出处的信息的...
