### ISSUE TITLE
Claude2已更新模型

### ISSUE THREAD

**Issue by KasumiYuku** [ikechan8370/chatgpt-plugin#612]
需要更改请求的版本号至2.1才能使用
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/107661829/fd6573de-6522-4493-beb3-868dc10c2a56)

**Comment by ikechan8370** [comment]
少年不来个PR吗

**Comment by ZHAOZ1491** [comment]
这个是在chat.js修改吗

**Comment by ikashana** [comment]
> 少年不来个PR吗

同样遇到这个问题。请问PR是指哪个？

**Comment by KasumiYuku** [comment]
> > 少年不来个PR吗
> 
> 同样遇到这个问题。请问PR是指哪个？

改Util的Claude.ai里的
