### ISSUE TITLE
#chatgpt系统管理登录失败

### ISSUE THREAD

**Issue by Fahaxikiii** [ikechan8370/chatgpt-plugin#617]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

使用chronocat登录并在miao-yunzai的config中跳过icqq登录，无法使用机器人qq作为用户名登录
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/93320886/f0a4de2b-8d05-46d2-bbf5-761516377efe)

## 预期行为

请描述您期望系统在出现问题时应该做什么。

## 实际行为

![image](https://github.com/ikechan8370/chatgpt-plugin/assets/93320886/96062218-8dd0-4c55-a667-675f0ca8d613)

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息

![image](https://github.com/ikechan8370/chatgpt-plugin/assets/93320886/3404417f-3ee3-4923-a1d6-eea1501a616b)

**Comment by ikechan8370** [comment]
使用旁边那个指纹按钮登录

**Comment by Fahaxikiii** [comment]
> 使用旁边那个指纹按钮登录

啊这

**Comment by Fahaxikiii** [comment]
> 使用旁边那个指纹按钮登录
Request failed with status code 500
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/93320886/70e0b714-100f-4ca7-9dd9-caef41869418)

**Comment by ikechan8370** [comment]
后台报什么错了？

**Comment by Fahaxikiii** [comment]
> 后台报什么错了？
点指纹只有这个
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/93320886/85136923-033c-47e8-9f0d-f1f80c34c3cc)

**Comment by Inky-Moon** [comment]
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/84265441/3b7b61f3-eaac-417a-8a6d-2f4169579eca)
我也遇到了同样的问题，用指纹登录后台出来的是这个

**Comment by ikechan8370** [comment]
你们是最新版吗？

**Comment by Inky-Moon** [comment]
> 你们是最新版吗？

插件和喵崽都是最新，llqqnt插件也是最新的，chronocat插件是能找到的最新版
我先前已经和我自己群的一些群友讨论过，把什么都更新了一遍似乎还是不行

**Comment by ikechan8370** [comment]
> > 你们是最新版吗？
> 
> 插件和喵崽都是最新，llqqnt插件也是最新的，chronocat插件是能找到的最新版 我先前已经和我自己群的一些群友讨论过，把什么都更新了一遍似乎还是不行

那可能是因为最近本体和其他插件变动更新了才不行的。等我有空也找个qqnt的更新一下测试一下 我这测试shamrock是能用的

**Comment by ikechan8370** [comment]
> > 后台报什么错了？
> > 点指纹只有这个
> > ![image](https://private-user-images.githubusercontent.com/93320886/287755892-85136923-033c-47e8-9f0d-f1f80c34c3cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NDE1NTgsIm5iZiI6MTcwMTg0MTI1OCwicGF0aCI6Ii85MzMyMDg4Ni8yODc3NTU4OTItODUxMzY5MjMtMDMzYy00N2U4LTlmMGQtZjFmODBjMzRjM2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA1NDA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljOTkzMDA1MDFkZmRkYjIyNWY3MGQ3MmRkMjFmMWI1ZDA2MjkxNTY4MDE3MTkyYTgzY2E0NGFiMTYwMzBjZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ae3eoVeik_iN9PQOAO78J_XEyviUEUaIHXk5oc8o5CM)

这个可以直接用这个code登录就i行了
