### ISSUE TITLE
Bing绘图失败

### ISSUE THREAD

**Issue by KasumiYuku** [ikechan8370/chatgpt-plugin#621]
使用必应绘图时提示【绘图失败：Error: 绘图失败，请检查Bing token和代理/反代配置】，必应反代设置的是”https://bing.ikechan8370.com“
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/107661829/ddfcfdfa-41a5-4679-8636-296cd4291484)

**Comment by ikechan8370** [comment]
有时间修 好久没维护 有些服务器都过期没续费了。
