### ISSUE TITLE
API3模式下无法验证账户（gpt4）

### ISSUE THREAD

**Issue by JensonCXH** [ikechan8370/chatgpt-plugin#628]
在使用gpt4模型后显示：
出现错误：{"error":{"message":"Could not parse your authentication token. Please try signing in again.","statusCode":401,"statusText":""}}
然后切回3.5也是这样子了。目前api可用，api3无法使用。

**Comment by MapleRen** [comment]
同样问题，api3下的gpt4目前应该是使用不了的，切换回3.5提示这个的话大概率是redis的token没有更新成功，用#chatgpt设置token更新一次就好了。
