### ISSUE TITLE
建议加入触发方式选择

### ISSUE THREAD

**Issue by Inky-Moon** [ikechan8370/chatgpt-plugin#63]
v2现在似乎只有@bot这一种触发方式，很容易造成误触发，希望把之前发送#chatgpt触发的方式加回来

**Comment by hyhAsma** [comment]
我不会看正则，但是我猜应该是apps/chat.js里的第51行，你可以改成自定义的比如'#chat'进行匹配吧

**Comment by Kay2048** [comment]
同 怎么把@触发改成之前那样关键词触发
