### ISSUE TITLE
#gpt翻日 和 chatgpt语音转日语 功能，只能翻译前30个左右的汉字

### ISSUE THREAD

**Issue by misaka20002** [ikechan8370/chatgpt-plugin#634]
## 问题描述

#gpt翻日 和 chatgpt语音转日语 功能，只能翻译前30个左右的汉字。

## 预期行为

希望能翻译一整段文本

## 实际行为

只能翻译前30个左右的汉字

## 复制过程

#gpt翻日 据路特斯官方称，当前路特斯 ELETRE 车型正在申报工信部 L3 准入试点，力争成为首批进入 L3 级自动驾驶准入试点的车型，路特斯致力于成为高级别自动驾驶赛道的先行者。

IT之家注意到，路特斯高快路领航功能已涵盖了北京、上海、广州、深圳、杭州、无锡等国内 22 个城市，预计在 2024 年第一季度将拓展至全国。路特斯 ELETRE 智能驾驶系统可实现按导航限速自动控制车辆目标车速，避免车辆超速行驶；能实现智能巡航控制、自动汇入、自动汇出匝道、车道居中保持、大车避让、智能变道等主要功能，并通过驾驶员状态监测摄像头，对驾驶员的接管状态进行实时监控。

## 环境

android9
miui12
zerotermux
Ubuntu

## 可能的解决方案

希望能新增百度翻译/有道翻译api的功能，毕竟获取这两个key很容易。

## 附加信息

![image](https://github.com/ikechan8370/chatgpt-plugin/assets/40714502/64d5e528-57a6-49bc-9b7e-d302dbb05a6e)

**Comment by ikechan8370** [comment]
翻译接口有问题，目前翻译改成了基于AI的了，目前支持openai、gemini、星火和通义千问
