### ISSUE TITLE
是否与wechat或是ap-plugin有冲突？

### ISSUE THREAD

**Issue by Lavanille777** [ikechan8370/chatgpt-plugin#635]
在wechat中无论如何设置，（API 模式）总是会携带上下文（1w+tokens），已关闭群聊上下文，允许机器人读取近期 0 条消息。
在wechat中设置 OpenAI 服务器地址无效，必须打开强制使用反代。
在wechat中设置 AI 风格无效

**Comment by ikechan8370** [comment]
没有听说类似的事情，检查一下配置是否应用了？
