### ISSUE TITLE
无法在QQ频道使用chatgpt接口，也就是API模式。

### ISSUE THREAD

**Issue by 2595001965** [ikechan8370/chatgpt-plugin#636]
## 问题描述

经过实验，chatgpt插件能正常使用bing，星火等模型。只是在使用gpt接口，也就是API模式时。私聊会提示“频道不存在”，有时也能正常问答，群聊会提示“通信异常”，日志是“TypeError: e.bot.getGroupMemberInfo is not a function”。

## 预期行为

在私聊时，能够正常使用API模式。
群聊时，能够正常回复。

## 实际行为

私聊时有时不回复。
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/53131003/d041fb9b-0f93-417b-9bb8-0ba43629a107)
后台日志报错（即使正常回复也会报错）：
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/53131003/7f9b2fee-1e14-42be-b759-ab6a1c686d76)

频道群聊时，聊天界面报错
![7930c09971a55c6ba110714c256b3a4c](https://github.com/ikechan8370/chatgpt-plugin/assets/53131003/7724d4a7-a7de-4f0c-bac3-e9edacfa805f)
后台日志报错:
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/53131003/98bf5070-6da1-4a7c-8b95-ee4a1f465ec1)

## 复制过程

刚安装插件时是可以正常使用的，过了一两天后才有这个问题。

## 环境

Ubuntu20.04，trss云崽，插件里装了delay包。全部图形化操作。

## 可能的解决方案

系统设置快照并还原，也没有用。会不会是腾讯把我的频道屏蔽了，bot获取不到频道？

**Comment by ikechan8370** [comment]
什么适配器？

**Comment by 2595001965** [comment]
用的trss云崽。在关掉智能模式之后就好了。
