### ISSUE TITLE
功能请求：适配支持讯飞星火3.5及锅巴

### ISSUE THREAD

**Issue by Oishiimono** [ikechan8370/chatgpt-plugin#638]
**描述你想要的解决方案**
看大佬是否方面，增加讯飞星火3.5版本接入选项，以及适配锅巴

**附加说明**
![fc1977b5c00c615406c9e6ea26bcdaef](https://github.com/ikechan8370/chatgpt-plugin/assets/34758515/b672608e-d41f-48c8-8e4b-e4cb12c1f683)

**Comment by ikechan8370** [comment]
3.5好像还挺好的
