### ISSUE TITLE
兼容性请求

### ISSUE THREAD

**Issue by luanyaolingwu** [ikechan8370/chatgpt-plugin#641]
**你的功能请求是否与某个问题有关？请描述。**
已尝试其它bingai验证码服务，感觉还算好用

**附加说明**
已经尝试对话功能，可正常使用; 可否尝试兼容第三方Bing验证码服务? (不一定安全)
https://github.com/Harry-zklcdc/go-bingai-pass

对方[演示网站](https://bingai-az.zklcdc.xyz/web/)

**Comment by ikechan8370** [comment]
现在_U过不了
