### ISSUE TITLE
连接QQbot不兼容

### ISSUE THREAD

**Issue by jym2009** [ikechan8370/chatgpt-plugin#648]
## 问题描述 在使用lainplugin连接到qqbot时使用chatgpt会报错:group members.keys is not a function or its return value is not iterable.环境:node.18.19.0  QQbot平台

请在此处描述您遇到的问题，包括出现问题的环境、您试图实现的功能以及错误信息等。请尽可能详细，以便其他人可以在自己的环境中复制问题。

## 预期行为 正常相应

请描述您期望系统在出现问题时应该做什么。

## 实际行为 报错group members.keys is not a function or its return value is not iterable.

请描述您实际看到的行为。

## 复制过程 使用lainplugin连接qqbot后，将回答方式改为#chat后，@机器人/chat

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境Windowsserver2019 node18.19.0 QQbot平台

请提供您使用的任何相关信息，例如操作系统、版本、配置等。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息
![a1d7e5869068df75ccbc4a71229b9fcc](https://github.com/ikechan8370/chatgpt-plugin/assets/152615428/d7e7b8d5-46af-4192-b413-616212d18a6e)
![44EBBC83A14D2685CF8599E384086DF6](https://github.com/ikechan8370/chatgpt-plugin/assets/152615428/40cd4357-c84c-4656-a520-eaac29d133b1)

如果有任何其他信息，如日志、截图等，请在此处提供。

**Comment by ikechan8370** [comment]
lain适配器返回与icqq格式不一致。我协调一下

**Comment by ikechan8370** [comment]
更新Lain 看是否解决

**Comment by jym2009** [comment]
解决了
