### ISSUE TITLE
我qq老被冻结，然后想转qq频道的机器人 下载了插件Lain-plugin 但是报错了

### ISSUE THREAD

**Issue by wzwei1990** [ikechan8370/chatgpt-plugin#651]
我qq老被冻结，然后想转qq频道的机器人 下载了插件Lain-plugin 但是报错了
![微信图片_20240222165420](https://github.com/ikechan8370/chatgpt-plugin/assets/41670762/fdd30c9f-8cca-4ea1-afc6-1466d963c5f0)
之后会考虑适配qq频道吗
![微信图片_20240222165707](https://github.com/ikechan8370/chatgpt-plugin/assets/41670762/df0f8bab-0871-43d0-9770-14d697969ffd)

**Comment by ikechan8370** [comment]
lain更新了吗？前几天记得解决了qqbot的 只有频道报错吗？

**Comment by wzwei1990** [comment]
> lain更新了吗？前几天记得解决了qqbot的 只有频道报错吗？

个人只能申请qq频道机器人  猫崽的插件命令可以用

**Comment by KasumiYuku** [comment]
lain插件不是已经跑路了吗

**Comment by wzwei1990** [comment]
> lain插件不是已经跑路了吗

但是跑的最晚的😂 其他跑的更早

**Comment by ikechan8370** [comment]
晚点我看下

**Comment by wzwei1990** [comment]
> 晚点我看下

好的 谢谢  感觉频道的机器人有搞头  其他都被🐧围追堵截

**Comment by ikechan8370** [comment]
频道是不是要没了？

**Comment by wzwei1990** [comment]
> 频道是不是要没了？

没有吧 我刚申请的频道机器人 https://bot.q.qq.com/wiki/#_3-%E4%B8%AA%E4%BA%BA%E4%B8%BB%E4%BD%93%E5%85%A5%E9%A9%BB
![b8ad7ebd1b98092d0d60932e9df2cbf](https://github.com/ikechan8370/chatgpt-plugin/assets/41670762/84acc33c-dd6e-411b-95c6-e51c89bc42aa)

**Comment by wzwei1990** [comment]
> > 频道是不是要没了？
> 
> 没有吧 我刚申请的频道机器人 https://bot.q.qq.com/wiki/#_3-%E4%B8%AA%E4%BA%BA%E4%B8%BB%E4%BD%93%E5%85%A5%E9%A9%BB ![b8ad7ebd1b98092d0d60932e9df2cbf](https://private-user-images.githubusercontent.com/41670762/307212978-84acc33c-dd6e-411b-95c6-e51c89bc42aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTgwNzksIm5iZiI6MTcwODY1Nzc3OSwicGF0aCI6Ii80MTY3MDc2Mi8zMDcyMTI5NzgtODRhY2MzM2MtZGQ2ZS00MTFiLTk1YzYtZTUxYzg5YmM0MmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDAzMDkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZWEzODU4ODZkNGI4Mjg1MWQ3YzY4NDc4ZjEwYjI3OWJhODIyYjIxYzUyZDhmNjIyZDU5YTVjMzZhMDBjYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.laRky3ihHGLD9Y6ozti_ArlLTI4E9HeS1VddycnesNg)

刚刚百度了一下  好像冻结过的qq不给频道 我的两个小号冻结过加入不了我大号的频道 没冻结的小号可以加入😅

**Comment by ikechan8370** [comment]
更新Lain 我那边push了

**Comment by wzwei1990** [comment]
> 更新Lain 我那边push了

试了一下，不报错了  但at机器人没反应  chatgpt好像识别不了
![32b6e6732c2a537a564983c966fd402](https://github.com/ikechan8370/chatgpt-plugin/assets/41670762/e7df4694-b11b-4123-91b4-6f9eab0815a7)

**Comment by ikechan8370** [comment]
频道和qqbot貌似只能前缀模式

**Comment by wzwei1990** [comment]
chatgpt前缀也不行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月24日(周六) 晚上6:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ikechan8370/chatgpt-plugin] 我qq老被冻结，然后想转qq频道的机器人 下载了插件Lain-plugin 但是报错了 (Issue #651)




 
频道和qqbot貌似只能前缀模式

**Comment by wzwei1990** [comment]
我看喵崽命令是可以实现at的
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/41670762/81a08bff-f561-4342-90c4-336926637db9)

**Comment by ikechan8370** [comment]
什么前缀？你得调前缀模式

**Comment by wzwei1990** [comment]
> 什么前缀？你得调前缀模式

哦 那不太方便了 允许其他模式也不能用#chat吧？
![1708914020179](https://github.com/ikechan8370/chatgpt-plugin/assets/41670762/64347290-6e4e-4d84-9f24-e14029346eed)

**Comment by ikechan8370** [comment]
> > 什么前缀？你得调前缀模式
> 
> 哦 那不太方便了 允许其他模式也不能用#chat吧？ ![1708914020179](https://private-user-images.githubusercontent.com/41670762/307645685-64347290-6e4e-4d84-9f24-e14029346eed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTQ3MDUsIm5iZiI6MTcwODkxNDQwNSwicGF0aCI6Ii80MTY3MDc2Mi8zMDc2NDU2ODUtNjQzNDcyOTAtNmU0ZS00ZDg0LTlmMjQtZTE0MDI5MzQ2ZWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDAyMjY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MzA5NzkyNDE2NGE2OGI3ODQ4N2IxM2ZjMWI0NTI1YzEwMWExZjNkMTNiMDczOGNlN2JhZjZlYWZjZjExYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g8k1Q3y5YVRfnEhjSc3Sd92setIMMLnmnDFGWxnYKYU)

不可以，可以用其他模式的前缀
