### ISSUE TITLE
有个新平台coze,请求适配

### ISSUE THREAD

**Issue by FSHebe233** [ikechan8370/chatgpt-plugin#654]
字节的新平台,可以免费用GPT4。官方支持挺多平台的,包括slack。如果能适配的话非常感谢

**Comment by ikechan8370** [comment]
coze已经有开源的接入discord的版本了，可以转为openapi的格式直接用，部署还算简单。slack尝试了对接没有成功。目前不打算在插件端直接接入。

**Comment by FSHebe233** [comment]
> coze已经有开源的接入discord的版本了，可以转为openapi的格式直接用，部署还算简单。 slack尝试了对接没有成功。 目前不打算在插件端直接接入。

已经部署了,在OpenAI API服务器地址填入coze proxy接口以及填入正确设置好的API,还是通信异常,报错:
"error":"message": {
   "Incorrect APl key provided: sk123. You can find your AP1 key at https://platform.openai.com/account/api-keys.""type": 
   "invalid_request_error",
   "param": null.
   "code": "invalid_api_key"
   
在NextChat上能正常使用
