### ISSUE TITLE
Trss官bot适配器报错

### ISSUE THREAD

**Issue by KasumiYuku** [ikechan8370/chatgpt-plugin#657]
## 问题描述

###使用Trss的官方Bot适配器触发本插件，发送消息的时候报错，拉取的是本插件的btn分支

## 预期行为

###向群聊发送API返回的消息

## 实际行为

###终端报错：
 [stack]: 'TypeError: button_square is not iterable\n' +
    '    at QQBotAdapter.makeButtons (file:///C:/Users/Administrator/Desktop/Bot/%E5%B0%8F%E9%B1%BC/kokomi-trss/plugins/QQBot-Plugin/index.js:206:30)\n' +
    '    at QQBotAdapter.makeMsg (file:///C:/Users/Administrator/Desktop/Bot/%E5%B0%8F%E9%B1%BC/kokomi-trss/plugins/QQBot-Plugin/index.js:489:31)\n' +
    '    at QQBotAdapter.sendMsg (file:///C:/Users/Administrator/Desktop/Bot/%E5%B0%8F%E9%B1%BC/kokomi-trss/plugins/QQBot-Plugin/index.js:555:25)\n' +
    '    at QQBotAdapter.sendGroupMsg (file:///C:/Users/Administrator/Desktop/Bot/%E5%B0%8F%E9%B1%BC/kokomi-trss/plugins/QQBot-Plugin/index.js:573:17)\n' +
    '    at data.reply (file:///C:/Users/Administrator/Desktop/Bot/%E5%B0%8F%E9%B1%BC/kokomi-trss/plugins/QQBot-Plugin/index.js:810:30)\n' +
    '    at e.reply (file:///C:/Users/Administrator/Desktop/Bot/%E5%B0%8F%E9%B1%BC/kokomi-trss/lib/plugins/loader.js:513:21)\n' +
    '    at chatgpt.reply (file:///C:/Users/Administrator/Desktop/Bot/%E5%B0%8F%E9%B1%BC/kokomi-trss/plugins/chatgpt-plugin/apps/chat.js:306'... 86 more characters,
  [message]: 'button_square is not iterable'
}
{"level":30,"time":1709380589618,"pid":4504,"hostname":"iZekygn1pnhup2Z","reqId":"req-1","req":{"method":"POST","url":"/cache","hostname":"127.0.0.1:3321","remoteAddress":"::ffff:127.0.0.1","remotePort":54791},"msg":"incoming request"}

## 附加信息
![d4a290093c8c3c7117ffb59866cd4e1f](https://github.com/ikechan8370/chatgpt-plugin/assets/107661829/efe7e90e-2aa9-452f-b991-eb5a8c0435a0)
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/107661829/26ec5731-5f09-49a3-b3c2-18aaafb2200f)

**Comment by KasumiYuku** [comment]
忘记补充了，用的是ChatGPT-Plugin的btn分支

**Comment by ikechan8370** [comment]
该分支不支持qqbot

**Comment by ikechan8370** [comment]
目前只适配了icqq和lain的shamrock 
qqbot用户建议根据适配器自己适配
