### ISSUE TITLE
【功能请求】希望能能将“本群闭嘴”“开口”等字眼替换成比较温和的词汇

### ISSUE THREAD

**Issue by ElaineOwO** [ikechan8370/chatgpt-plugin#660]
比如本群上班，本群开启
       本群下班，本群关闭
以及其他交互文本
这样听起来比较温和些嘛QuQ
之前pr过一次不知道为什么又改回去了（悲 [https://github.com/ikechan8370/chatgpt-plugin/pull/431](url)

**Comment by ikechan8370** [comment]
什么时候变回去的😧

**Comment by ElaineOwO** [comment]
> 什么时候变回去的😧

我也不知道，，不过还是麻烦大佬再改一下啦

**Comment by ElaineOwO** [comment]
> 什么时候变回去的😧

https://github.com/ikechan8370/chatgpt-plugin/compare/v2...ElaineOwO:chatgpt-plugin:v2 看了一下仍然可以覆盖 只是改变了文本应该不会有冲突
