### ISSUE TITLE
对话白名单失效？

### ISSUE THREAD

**Issue by 006lp** [ikechan8370/chatgpt-plugin#665]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述
我使用trss-yunzai3.1.3部署本项目截至目前的最新版本，设置的是#chat 模式，但在群聊中除了我（机器人的主人）外，其他人无法与bot聊天。

## 预期行为

其他人能够通过#chat聊天

## 实际行为

在日志中发现，只有我输入#chat被识别成chatgpt插件，其他人发#chat只被识别成正常对话。

## 复制过程

暂时不清楚

## 环境

debian 12，trss-yunzai 3.1.3,本项目截至目前最新版

## 可能的解决方案

一开始我以为是忘记了配置对话白名单，但通过这样配置（见附加信息）之后，并重启，其他人仍然无法与bot聊天。

## 附加信息

![IMG_20240314_000423.jpg](https://github.com/ikechan8370/chatgpt-plugin/assets/144674902/cdd5929a-3cc6-46b7-88bc-6e09d90e3aa5)

**Comment by 006lp** [comment]
可能是队列的问题？
我稍后会试试#清空队列。
不过想问一下不同用户输入#chat时，必须要等上一个人结束对话才能开始下一个用户的对话吗？
我的意思是，现在是不是下面的情况：
例如
A：#chat 你好
Bot：你好有什么可以帮您。
B：#chat 你好
此时无法回复，在队列中？
是不是只有当A：#结束对话，Bot才会回复B?

**Comment by ikechan8370** [comment]
不进插件的话和插件没关系 找适配器原因
