### ISSUE TITLE
生成的语音无法播放并且控制台有错误

### ISSUE THREAD

**Issue by yamadafz** [ikechan8370/chatgpt-plugin#670]
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/98805571/6c4f27a5-d026-46d3-9a54-c73222afbac1)
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/98805571/82080325-991b-4d24-97ba-411da15b2a76)

**Comment by ikechan8370** [comment]
说明一下你的环境 yunzai版本 icqq版本

**Comment by yamadafz** [comment]
> 说明一下你的环境 yunzai版本 icqq版本

用的是TRSS-Yunzai[https://github.com/TimeRainStarSky/Yunzai](url),然后协议端用的是LLOneBot都是最新的版本

**Comment by ikechan8370** [comment]
明白了 语音目前没适配这些适配器
我也没有用过llonebot之类的
有空我再看看

**Comment by yamadafz** [comment]
> 明白了 语音目前没适配这些适配器 我也没有用过llonebot之类的 有空我再看看

我又搞了半天把node-silk装上了，然后又识别不到配置文件的地址555
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/98805571/cfef2e9b-f547-4dca-aa22-1bbaec1da1a6)

**Comment by Liccsu** [comment]
> 明白了 语音目前没适配这些适配器 我也没有用过llonebot之类的 有空我再看看

我也遇到同样的问题了，与他一样，现在是TypeError: Cannot read properties of undefined (reading 'ffmpeg_path')，对了我用的是最新版[TRSS-Yunzai](https://github.com/TimeRainStarSky/Yunzai)，我看它配置文件里没有`ffmpeg_path`这一项配置，但是呢，椰奶插件又能正常发语音，然后我又看了下椰奶，它的`upoadRecord`也是写的`Bot.config.ffmpeg_path`，但是有一个细节是llonebot需要配置`ffmpeg`(我llonbot在docker里)，如果没配置的话哪怕宿主机配置了ffmpeg也发不了语音

**Comment by yamadafz** [comment]
> > 明白了 语音目前没适配这些适配器 我也没有用过llonebot之类的 有空我再看看
> 
> 我也遇到同样的问题了，与他一样，现在是TypeError: Cannot read properties of undefined (reading 'ffmpeg_path')，对了我用的是最新版[TRSS-Yunzai](https://github.com/TimeRainStarSky/Yunzai)，我看它配置文件里没有`ffmpeg_path`这一项配置，但是呢，椰奶插件又能正常发语音，然后我又看了下椰奶，它的`upoadRecord`也是写的`Bot.config.ffmpeg_path`，但是有一个细节是llonebot需要配置`ffmpeg`(我llonbot在docker里)，如果没配置的话哪怕宿主机配置了ffmpeg也发不了语音

没用的我把ffmpeg_path硬编码后还是会报第一张图的错

**Comment by Liccsu** [comment]
> > > 明白了 语音目前没适配这些适配器 我也没有用过llonebot之类的 有空我再看看
> > 
> > 
> > 我也遇到同样的问题了，与他一样，现在是TypeError: Cannot read properties of undefined (reading 'ffmpeg_path')，对了我用的是最新版[TRSS-Yunzai](https://github.com/TimeRainStarSky/Yunzai)，我看它配置文件里没有`ffmpeg_path`这一项配置，但是呢，椰奶插件又能正常发语音，然后我又看了下椰奶，它的`upoadRecord`也是写的`Bot.config.ffmpeg_path`，但是有一个细节是llonebot需要配置`ffmpeg`(我llonbot在docker里)，如果没配置的话哪怕宿主机配置了ffmpeg也发不了语音
> 
> 没用的我把ffmpeg_path硬编码后还是会报第一张图的错

建议参考椰奶插件，反正椰奶插件能发语音，但我不会，懒得看了😪,等大佬看

**Comment by yamadafz** [comment]
``

> > > > 明白了 语音目前没适配这些适配器 我也没有用过llonebot之类的 有空我再看看
> > > 
> > > 
> > > 我也遇到同样的问题了，与他一样，现在是TypeError: Cannot read properties of undefined (reading 'ffmpeg_path')，对了我用的是最新版[TRSS-Yunzai](https://github.com/TimeRainStarSky/Yunzai)，我看它配置文件里没有`ffmpeg_path`这一项配置，但是呢，椰奶插件又能正常发语音，然后我又看了下椰奶，它的`upoadRecord`也是写的`Bot.config.ffmpeg_path`，但是有一个细节是llonebot需要配置`ffmpeg`(我llonbot在docker里)，如果没配置的话哪怕宿主机配置了ffmpeg也发不了语音
> > 
> > 
> > 没用的我把ffmpeg_path硬编码后还是会报第一张图的错
> 
> 建议参考椰奶插件，反正椰奶插件能发语音，但我不会，懒得看了😪,等大佬看

我现在换回miao版云崽加签名了，llonbot确实稳但没办法，顺便把vits升级成vits2，默认的说话不够流畅
