### ISSUE TITLE
使用TRSS-Yunzai图片回复失败: page.waitForTimeout is not a function 

### ISSUE THREAD

**Issue by huvz04** [ikechan8370/chatgpt-plugin#673]
系统：Windows Server 2022
CPU：Intel N8505
内存: 16G
Node版本：20.11.0
Yunzai：Trss应用端

![控制台](https://foruda.gitee.com/images/1711866442035825912/32994299_11134269.png "屏幕截图")

猜测可能是本地TRSS使用的puppeteer版本和之前喵崽不一样的问题. 
喵崽 是21.11.0版本的puppeteer
TRSS 是22.6.1版本的puppeteer
建议更换waitForTimeout函数

**Comment by ikechan8370** [comment]
#674
