### ISSUE TITLE
【功能请求】添加更多AI

### ISSUE THREAD

**Issue by MapleLeaf2007** [ikechan8370/chatgpt-plugin#675]
天工AI助手 https://work.tiangong.cn/home/writting
360智脑 https://ai.360.com
腾讯混元 https://hunyuan.tencent.com
盘古大模型 https://www.huaweicloud.com/product/pangu
Kimi https://kimi.moonshot.cn

**Comment by ayakasuki** [comment]
kimi还是挺有用的 在最近比较火的国内AI 还挺好用 不过好像还没开饭API的调用
