### ISSUE TITLE
【小白提问】要怎样从github源换成gitee源呢

### ISSUE THREAD

**Issue by ElaineOwO** [ikechan8370/chatgpt-plugin#676]
RT   用github的仓库更新成功率比较随机...该如何换成gitee仓库呢

**Comment by ikechan8370** [comment]
试试 `git remote set-url origin https://gitee.com/ikechan/chatgpt-plugin.git`

**Comment by ElaineOwO** [comment]
> 试试 `git remote set-url origin https://gitee.com/ikechan/chatgpt-plugin.git`

试了下好像没反应，是在chatgpt插件目录下使用嘛？

**Comment by ikechan8370** [comment]
> > 试试 `git remote set-url origin https://gitee.com/ikechan/chatgpt-plugin.git`
> 
> 试了下好像没反应，是在chatgpt插件目录下使用嘛？

对

**Comment by ElaineOwO** [comment]
> > > 试试 `git remote set-url origin https://gitee.com/ikechan/chatgpt-plugin.git`
> > 
> > 
> > 试了下好像没反应，是在chatgpt插件目录下使用嘛？
> 
> 对

嗯。。输入后按回车了但是没有什么反应，我先观察一阵子更新还会不会失败吧

**Comment by ikechan8370** [comment]
@ElaineOwO 没有反应是正常的呀

**Comment by ElaineOwO** [comment]
> @ElaineOwO 没有反应是正常的呀

嗯。。貌似没再出现更新失败了 谢谢大佬啦
