### ISSUE TITLE
修改了账号密码但是仍然使用旧的登录

### ISSUE THREAD

**Issue by Inky-Moon** [ikechan8370/chatgpt-plugin#68]
我第一次修改的账号密码后来发现打错字了，就去重新修改，结果插件似乎不认新的配置，仍然尝试使用错误的账号信息登录，导致每次都只能返回通信状态异常，我尝试删掉配置文件重新git pull结果没有用

**Comment by Inky-Moon** [comment]
补充：甚至把整个插件删掉再git clone都没用

**Comment by makerhxc** [comment]
数据在redis里边，看一下CHATGPT:API_OPTION这个字段
