### ISSUE TITLE
艾特机器人提问时报错

### ISSUE THREAD

**Issue by shiyu223** [ikechan8370/chatgpt-plugin#682]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述
艾特bot有时候能按照设定回答，但有时候会报错，报错之后就不会回答了

## 预期行为

艾特bot需及时回答

## 实际行为

请描述您实际看到的行为。

## 复制过程

重新配置gpt的api后再次启用然后出现问题

## 环境

操作系统为ubuntu 20.04.4 LTS x86_64、云崽版本为3.1.3，GPT插件版本为2.8.1。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息

日志截图
![QQ截图20240504143647](https://github.com/ikechan8370/chatgpt-plugin/assets/107821610/4ecdf509-1f85-4600-bd7d-a7463850ef35)

**Comment by HalcyonAlcedo** [comment]
这是请求meme接口时超时，应该不是GPT插件的问题，建议去meme发
这个接口应该是通的，尝试ping一下看看是不是服务器的网络问题
