### ISSUE TITLE
最近一次更新后与QQbot插件不兼容

### ISSUE THREAD

**Issue by Lovelumine** [ikechan8370/chatgpt-plugin#687]
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/105962147/2eb923ad-a45b-4103-b8ae-2eb05a0c221a)
最近一次更新后与QQbot插件不兼容，卸载此插件后恢复正常
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/105962147/bf66363b-e7bf-4cf4-bf08-2bd9afbae3e7)

**Comment by ikechan8370** [comment]
https://github.com/ikechan8370/chatgpt-plugin/blob/1e4764fd140b4f3ef6b01e2b185a713dd2524d2d/server/index.js#L446C4-L451C7

qqbot适配器可能缺少该函数 @HalcyonAlcedo 这里新加的这个能不能跳过？

**Comment by HalcyonAlcedo** [comment]
这个pickMember函数在很多地方都被调用了，估计使用其他功能时也会报错，我先修一下后台这里的

**Comment by HalcyonAlcedo** [comment]
已经修复#689 
目前无法调用的情况下at的目标用qq号替换
