### ISSUE TITLE
配置文件里面有个地方需要改进

### ISSUE THREAD

**Issue by Inky-Moon** [ikechan8370/chatgpt-plugin#69]
![image](https://user-images.githubusercontent.com/84265441/208393466-7b3e7776-113c-4a8f-a639-c743e277a8ee.png)
这个地方作者按照Windows的文件系统路径格式预先指定了chrome路径，但是这样的话对于使用bot自带puppeteer的、自己的chrome不装在那个位置的或者干脆不用windows用linux的人来说会不会造成困扰？可能有的人没有注意这一行然后就尝试运行就会报错。
可能作者是想用这个路径作为一个例子，那么建议用注释的形式，然后这一行路径留空。

**Comment by ayakasuki** [comment]
是的 我的就是linux ubuntu20.04
