### ISSUE TITLE
通义千问对话400错误

### ISSUE THREAD

**Issue by xingyu42** [ikechan8370/chatgpt-plugin#696]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

进行对话一直400错误尝试过结束全部对话
![414f75c3e9cecefff012faebfc39f6ab](https://github.com/ikechan8370/chatgpt-plugin/assets/52421598/d76544e7-e4bc-41fc-88b3-1e91ba7fd402)
Error: Qwen error 400: {"code":"InvalidParameter","message":"Role must be user or assistant and Content length must be greater than 0","request_id":"a1a17b2c-ab3a-9b6f-8994-858509d1361b"}
## 预期行为

请描述您期望系统在出现问题时应该做什么。

## 实际行为

请描述您实际看到的行为。

## 复制过程

请详细描述如何复制这个问题，包括所有必要的步骤、输入、任何错误信息以及输出。

## 环境

请提供您使用的任何相关信息，例如操作系统、版本、配置等。

## 可能的解决方案

如果您已经尝试了一些解决方案，请在此处描述这些解决方案，并说明是否有效。

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。

**Comment by ayakasuki** [comment]
我这边是出现错误：Error: Qwen error 400: {"code":"InvalidParameter","message":"Tool names are not allowed to be [search]","request_id":"0e81dae8-3613-9932-9e31-be3eaab5cf86"}

**Comment by xingyu42** [comment]
新版本问题修复

**Comment by xingyu42** [comment]
> 我这边是出现错误：Error: Qwen error 400: {"code":"InvalidParameter","message":"Tool names are not allowed to be [search]","request_id":"0e81dae8-3613-9932-9e31-be3eaab5cf86"}

你这个应该关闭智能模式就好了
