### ISSUE TITLE
全局模式无反应

### ISSUE THREAD

**Issue by xingyu42** [ikechan8370/chatgpt-plugin#698]
## 问题描述
无论是全局图片还是语音都是输出文本，单独开启的话正常用
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/52421598/7189320c-8800-432d-9696-84a8e9991878)

**Comment by ikechan8370** [comment]
全局优先级低于个人 你这是正常的

**Comment by xingyu42** [comment]
> 全局优先级低于个人 你这是正常的

那这是怎么用的，个人设定过后就只能手动设置，其他没设置的就用全局这样吗

**Comment by xingyu42** [comment]
> > 全局优先级低于个人 你这是正常的
> 
> 那这是怎么用的，个人设定过后就只能手动设置，其他没设置的就用全局这样吗

好吧看来是这样的
