### ISSUE TITLE
插件与云崽扫码登录功能冲突

### ISSUE THREAD

**Issue by Ray-lea** [ikechan8370/chatgpt-plugin#699]
## 问题描述

使用trss-yunzai扫码登录时，出现与本插件冲突的提示，卸载本插件后使用扫码登录功能正常使用

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。
```
[TRSSYz][23:08:07.791][ERRO] [米哈游登录(miHoYoLoginQRCode)][*********, ************
][#扫码登录] TypeError: Cannot read properties of undefined (reading 'gl')
    at Proxy.<anonymous> (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/plugins/chatgpt-plugin/server/index.js:465:43)
    at Proxy.emit (node:events:526:35)
    at miHoYoLogin.makeMessage (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/plugins/TRSS-Plugin/Apps/miHoYoLogin.js:266:9)
    at miHoYoLogin.miHoYoLoginQRCode (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/plugins/TRSS-Plugin/Apps/miHoYoLogin.js:258:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PluginsLoader.deal (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/lib/plugins/loader.js:253:41) {
  [stack]: "TypeError: Cannot read properties of undefined (reading 'gl')\n" +
    '    at Proxy.<anonymous> (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/plugins/chatgpt-plugin/server/index.js:465:43)\n' +
    '    at Proxy.emit (node:events:526:35)\n' +
    '    at miHoYoLogin.makeMessage (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/plugins/TRSS-Plugin/Apps/miHoYoLogin.js:266:9)\n' +
    '    at miHoYoLogin.miHoYoLoginQRCode (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/plugins/TRSS-Plugin/Apps/miHoYoLogin.js:258:34)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async PluginsLoader.deal (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/lib/plugins/loader.js:253:41)',
  [message]: "Cannot read properties of undefined (reading 'gl')"
```

**Comment by 127Wzc** [comment]
+1 看了下 chatgpt-plugin/server/index.js 拦截了所有消息 
扫码登录 后 机器人会主动发个登录的信息 但是主动消息没有e.bot 导致，做了判断后可以登录了，
但是会自动引发一个自己对话自己的ai对话，这个server不太用不知道干嘛的，这么拦截会不会不太好啊，之前有个强制拦截所有消息的就很烦给它卸载了
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/52766844/d4abba20-e3ae-445e-8586-dbf1df74e0af)

![image](https://github.com/ikechan8370/chatgpt-plugin/assets/52766844/752eae30-7b78-4246-bbb3-5e9caad526d8)

**Comment by 127Wzc** [comment]
当前trss和chatgpt均为回答时的最新版本

排查发现`#扫码登录`两个问题
1. 扫码确认后 机器人主动发的消息没有e.bot 导致异常 
 [      group_name: e.group_name || e.bot.gl?.get(e.group_id)?.group_name || e.group_id](https://github.com/ikechan8370/chatgpt-plugin/blob/01425103f4ac9219df1db50416265213ea5058fc/server/index.js#L465)
 
2. 指令正则匹配插件规则走到chat.js的这个方法里去了 过滤上面异常1后，机器人会自己和自己开启一次对话
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/52766844/e13cb73f-9e51-4c36-a76a-c94beb0b0c6c)

![image](https://github.com/ikechan8370/chatgpt-plugin/assets/52766844/1add2fc0-bd15-489e-b88e-10a947504808)

**Comment by 127Wzc** [comment]
> 当前trss和chatgpt均为回答时的最新版本
> 
> 排查发现`#扫码登录`两个问题
> 
> 1. 扫码确认后 机器人主动发的消息没有e.bot 导致异常
>    [      group_name: e.group_name || e.bot.gl?.get(e.group_id)?.group_name || e.group_id](https://github.com/ikechan8370/chatgpt-plugin/blob/01425103f4ac9219df1db50416265213ea5058fc/server/index.js#L465)
> 2. 指令正则匹配插件规则走到chat.js的这个方法里去了 过滤上面异常1后，机器人会自己和自己开启一次对话
>    ![image](https://private-user-images.githubusercontent.com/52766844/332355164-e13cb73f-9e51-4c36-a76a-c94beb0b0c6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODM5NzIsIm5iZiI6MTcxNjI4MzY3MiwicGF0aCI6Ii81Mjc2Njg0NC8zMzIzNTUxNjQtZTEzY2I3M2YtOWU1MS00YzM2LWE3NmEtYzk0YmViMGIwYzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA5Mjc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljODljMGE1MjAzMWZhNWU1MjhiNDdiYmQ5MTFmN2I4ZjRiMTMwMjhmMDhlNTU4NjdkMTg4YzI2YzIxMjhkNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.moEO20x2hWlm12kQ-D7zUgZ1rPKuG5x_f-7ATXfos9U)
> 
> ![image](https://private-user-images.githubusercontent.com/52766844/332357254-1add2fc0-bd15-489e-b88e-10a947504808.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODM5NzIsIm5iZiI6MTcxNjI4MzY3MiwicGF0aCI6Ii81Mjc2Njg0NC8zMzIzNTcyNTQtMWFkZDJmYzAtYmQxNS00ODllLWI4OGUtMTBhOTQ3NTA0ODA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA5Mjc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmYmM4ODBhZTE0OWUxOGU5NjY5ZGMyMWQ1MmQwZWIzOGY3NDMxZTI4MzEyMWQ4ODdmYzY2NmEyMzA5MTY3NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.boAWxRb8IalmYBsiZBXvv1_Tan8b1UBRr8vlfp5x3l8)

临时解决方案，因为我这边不用 @对话 所以直接改了正则。期待修复
![image](https://github.com/ikechan8370/chatgpt-plugin/assets/52766844/5add1f8c-b1aa-4a40-ae21-cfd48c77eca4)

**Comment by fsqhn** [comment]
> 当前trss和chatgpt均为回答时的最新版本
> 
> 排查发现`#扫码登录`两个问题
> 
> 1. 扫码确认后 机器人主动发的消息没有e.bot 导致异常
>    [      group_name: e.group_name || e.bot.gl?.get(e.group_id)?.group_name || e.group_id](https://github.com/ikechan8370/chatgpt-plugin/blob/01425103f4ac9219df1db50416265213ea5058fc/server/index.js#L465)
> 2. 指令正则匹配插件规则走到chat.js的这个方法里去了 过滤上面异常1后，机器人会自己和自己开启一次对话
>    ![image](https://private-user-images.githubusercontent.com/52766844/332355164-e13cb73f-9e51-4c36-a76a-c94beb0b0c6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MTkyMDksIm5iZiI6MTcxODcxODkwOSwicGF0aCI6Ii81Mjc2Njg0NC8zMzIzNTUxNjQtZTEzY2I3M2YtOWU1MS00YzM2LWE3NmEtYzk0YmViMGIwYzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDEzNTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NDhjZDE0MDc4Njc0YjVhYzc3ZDY5ZDA4ZGM4MWI2NzU0OTgyNmRkMzVhMGE1ZmFhZWJjZjZmNjI0Y2Q1NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OCXyKmBXSZQADCOn-U44J1PjAWcgjlPSI5AafoX1JpQ)
> 
> ![image](https://private-user-images.githubusercontent.com/52766844/332357254-1add2fc0-bd15-489e-b88e-10a947504808.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MTkyMDksIm5iZiI6MTcxODcxODkwOSwicGF0aCI6Ii81Mjc2Njg0NC8zMzIzNTcyNTQtMWFkZDJmYzAtYmQxNS00ODllLWI4OGUtMTBhOTQ3NTA0ODA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDEzNTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZGJlMmU1MDQ5ZGM3ZmExZTAxYWU3MmUxOGZiOWZlNTEzYmYxMTQzOWYwOTM2ZmM1YjJmZDBhNjllNGIzY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x2h_eG-ffwL3340ZhK6tExrwzgLWYUHOqSvwkr81IBo)

跑去找时雨佬说了下，时雨佬说已经修了。更新trsst-plugin就行。感谢各位大佬。
