### ISSUE TITLE
插件报错

### ISSUE THREAD

**Issue by lateautumn233** [ikechan8370/chatgpt-plugin#7]
![Screenshot_2022-12-07-19-29-35-557_com sonelli juicessh](https://user-images.githubusercontent.com/63851402/206168181-e1e0ed3c-221a-4ac5-9240-c15838593788.jpg)

不知道什么原因

**Comment by lateautumn233** [comment]
好吧是我依赖没更新

**Comment by hyhAsma** [comment]
老哥请问chatgpt是更到2.0.1吗？我这边更完后uuid的依赖给乱了，老哥方便的话能否说一下您当前yunzai项目里的uuid版本是多少？

**Comment by GLASSYsky258** [comment]
> 老哥请问chatgpt是更到2.0.1吗？我这边更完后uuid的依赖给乱了，老哥方便的话能否说一下您当前yunzai项目里的uuid版本是多少？

试试根目录下用   pnpm up --latest  指令

**Comment by hyhAsma** [comment]
好的，十分感谢
