### ISSUE TITLE
载入时报错

### ISSUE THREAD

**Issue by ynuzhui** [ikechan8370/chatgpt-plugin#702]
Miao-Yunzai载入chatgpt-plugin时
控制台报错
<img width="753" alt="屏幕截图 2024-07-03 003005" src="https://github.com/ikechan8370/chatgpt-plugin/assets/112922728/ff5965f6-3fed-451f-bbb8-da7160872eea">
<img width="758" alt="屏幕截图 2024-07-03 003023" src="https://github.com/ikechan8370/chatgpt-plugin/assets/112922728/3ba4d41e-7715-4fd5-8918-b66401432b82">
请问如何解决这个问题

**Comment by ikechan8370** [comment]
可能是网络问题可执行文件没有正确下载 可以卸载重装@node-rs/jieba这个依赖
