### ISSUE TITLE
必应验证码的问题

### ISSUE THREAD

**Issue by ghost** [ikechan8370/chatgpt-plugin#704]
每次对话有一半概率会返回出码，但你再问一次就能正常回复（前往bing网页实际并没有出码的情况），有没有可能把出码后返回的逻辑改为重新请求一次，连续3次后再返回出码（只是提个设想）

**Comment by ikechan8370** [comment]
如果登陆了出验证码是不会消失的。你的会消失应该是因为没有登陆或者token无效/失效，，用的无token模式

**Comment by ghost** [comment]
> 如果登陆了出验证码是不会消失的。你的会消失应该是因为没有登陆或者token无效/失效，，用的无token模式

可能是吧，但是刚刚我使用#chatgpt查看必应token   显示有012共三个，然后我尝试#chatgpt删除必应token（也试过加上012的单独标号）回复删除成功，但#chatgpt查看必应token依旧存在

**Comment by ghost** [comment]
> 如果登陆了出验证码是不会消失的。你的会消失应该是因为没有登陆或者token无效/失效，，用的无token模式

手动删掉redis中存储的必应token后重新设置一个token解决了此问题
