### ISSUE TITLE
载入时报错

### ISSUE THREAD

**Issue by S-t-e-v-e-e** [ikechan8370/chatgpt-plugin#709]
# 请确保提出问题前更新到最新版本！！！！！！！！

**请在提交issue前确认你已阅读了以下资料：**

- 项目的readme文件
- 其他已有的Issue

如果你的问题已经在readme或其他Issue中得到解答，我们很可能不会回复。请确保你的问题是一个新的问题。

## 问题描述

载入时报错

## 预期行为

正常启动

## 实际行为

![image](https://github.com/user-attachments/assets/2938ce14-9f19-4211-90ee-408f431506c4)

## 环境

OS: Arch Linux on Windows 10 x86_64
Miao-Yunzai 3.13

## 可能的解决方案

删除插件重新安装，未解决

## 附加信息

如果有任何其他信息，如日志、截图等，请在此处提供。

**Comment by ikechan8370** [comment]
可能是openai新版改了API。试着固定了openai版本 更新重新装依赖试试
