### ISSUE TITLE
还是Not signed in 

### ISSUE THREAD

**Issue by M0refish** [ikechan8370/chatgpt-plugin#71]
![image](https://user-images.githubusercontent.com/120435537/208502900-8b057f6c-a0df-498e-b8f6-4429203fdce4.png)
求助大佬~
还是报错，not signed in 不知道问题出在哪里，centos
![image](https://user-images.githubusercontent.com/120435537/208500908-5e7e6439-0bb5-4a87-8d67-8908e79311ac.png)

**Comment by cj0928** [comment]
+1

**Comment by XiaoGuoLiZi** [comment]
我也是

**Comment by ikechan8370** [comment]
请更新一下试试，修复了另一个可能导致这个报错的问题

**Comment by M0refish** [comment]
> 请更新一下试试，修复了另一个可能导致这个报错的问题

![image](https://user-images.githubusercontent.com/120435537/208678187-eb597256-7302-4466-807f-a439866a5a3d.png)
更新后报这个错，而且我的2captcha网站上一直也没有用量显示。
