### ISSUE TITLE
显示国家或地区不支持，疑似代理地址不生效

### ISSUE THREAD

**Issue by CGangel** [ikechan8370/chatgpt-plugin#710]
已经设置了代理地址，但是似乎依然调用了openai的官方地址，最终显示国家或地区不支持
![image](https://github.com/user-attachments/assets/1966c636-478a-4794-a14c-d90bde87ee62)
![image](https://github.com/user-attachments/assets/b99ea8b3-5857-4be2-8772-4453ea416d38)

**Comment by ikechan8370** [comment]
你开的是反代 把强制使用反代勾上

**Comment by CGangel** [comment]
> 你开的是反代 把强制使用反代勾上

之前用国内的服务器，直接填反代就行了。换成香港的服务器后就这样了。大概是它检测到香港ip，以为开了代理就不用反代了吧。
