### ISSUE TITLE
在文本模式下临时使用图片回复 

### ISSUE THREAD

**Issue by CICILC** [ikechan8370/chatgpt-plugin#713]
在此处添加有关功能请求的任何其他说明、屏幕截图或者引用。
由于询问某些公式时QQ内回复的公式部分不是错乱就是干脆不显示公式 但是大部分情况下问的是普通问题 需要复制回复的内容 只能是文本格式回复 所以临时切换成图片回复会更方便使用

所以能否添加一个 #chat图片（内容）  在默认文本回复的情况下临时使用图片回复 
或同时回复文本和图片（也可转发为合并消息）
![image](https://github.com/user-attachments/assets/813977ca-b6b1-4bd0-840a-6700d27a5dd5)
![image](https://github.com/user-attachments/assets/245ef12e-807b-4d87-be6d-c3a43954061f)

**Comment by ikechan8370** [comment]
支持了#图片chat1、#图片gemini、#图片chat 这样。at模式暂时不支持。
