### ISSUE TITLE
与OpenAI通信异常，请稍后重试：TypeError: this.browser.pages is not a function

### ISSUE THREAD

**Issue by 229450906** [ikechan8370/chatgpt-plugin#72]
![图片](https://user-images.githubusercontent.com/97822794/208670923-851b8935-9cb7-469d-b7e7-a5b4b312c70b.png)

**Comment by CUZNIL** [comment]
![image](https://user-images.githubusercontent.com/76582404/208918259-1bdcb99c-0322-42df-a2d5-33dadb16c4b0.png)
一样的问题

**Comment by wufeng15226** [comment]
+1

**Comment by purelolly** [comment]
Missing X server or $DISPLAY

xvfb

**Comment by purelolly** [comment]
![85 2N LI{OIFB`T4`)%C})V](https://user-images.githubusercontent.com/78009999/209222440-7fb8f1c6-d777-4e6b-aaad-6bc9ed5733ff.png)

headless: true

**Comment by psernokx** [comment]
> ![85 2N LI{OIFBT4)%C})V](https://user-images.githubusercontent.com/78009999/209222440-7fb8f1c6-d777-4e6b-aaad-6bc9ed5733ff.png)
> 
> headless: true

这是哪一个文件嘞

**Comment by wayner6** [comment]
+1

**Comment by cXp1r** [comment]
+2

**Comment by yellowpeachxgp** [comment]
TypeError: this.browser.pages is not a function
我也一样的问题
![image](https://user-images.githubusercontent.com/52021975/212530067-3ea5a63e-7c89-4dbd-9a90-c26b764306c7.png)

**Comment by xiaopebaka** [comment]
同样的问题啊 大佬们解决了吗

**Comment by xiaopebaka** [comment]
<img width="645" alt="iShot_2023-01-29_01 54 46" src="https://user-images.githubusercontent.com/57299718/215278896-f0a98e79-2d30-4062-9d42-7023422978ba.png">

**Comment by xiaopebaka** [comment]
忘了讲服务器状况了  树莓派4 装的debian 云仔可以用  chatgpt的设置里也写好了/usr/bin/chromium-browser 还是不太行
