### ISSUE TITLE
对图片进行回复的问题

### ISSUE THREAD

**Issue by SaltyFishAB** [ikechan8370/chatgpt-plugin#720]
[MiaoYz][23:59:37.690][INFO] chatgpt prompt: test
[MiaoYz][23:59:38.416][INFO] File downloaded successfully! URL: https://gchat.qpic.cn/gchatpic_new/502767030/726751510-3149327918-0D2EF3FC88DCA30C2EC1CE294F092130/0?term=2&is_origin=0, Destination: /home/user/Miao-Yunzai/data/chatgpt/ocr/0D2EF3FC88DCA30C2EC1CE294F092130.png
munmap_chunk(): invalid pointer
Aborted (core dumped)
 ELIFECYCLE  Command failed with exit code 134.
在Gemini模式下对图片进行回复时会出现无效的指针导致云崽直接崩溃

**Comment by kvcfdd** [comment]
把模型换成gemini-1.5-flash好像可以解决

**Comment by xingyu42** [comment]
依旧奔溃了
![image](https://github.com/user-attachments/assets/a7b59db0-d793-43f1-a32d-78f68b8c0d11)
