### ISSUE TITLE
替换gemini为gpt-4o的识图

### ISSUE THREAD

**Issue by ZHAOZ1491** [ikechan8370/chatgpt-plugin#728]
**你的功能请求是否与某个问题有关？请描述。**
问题的清晰而简明的描述。
![Screenshot_2024-11-25-15-33-24-072_com.tencent.mobileqq.jpg](https://github.com/user-attachments/assets/38a44f9a-08e7-4bf5-a863-b3f5d9dd73a5)

gemini的识图有时会出现不稳定的情况，且识别率偏低，不如4o，且关键字识图不够人性化。还有就是对于ntqq的引用图片无法识别。
**描述你想要的解决方案**
你想要发生什么的清晰而简明的描述。
替换gemini识图为gpt-4o，反代和apikey和chat1共用(模型名固定为4o和聊天的模型互不影响),另外判断用户是否引用图片，当引用图片则触发识图，将识图结果发送给#chat1，让chat1觉得是他自己看到的，而后将内容详细描述出来。最后就是对ntqq引用图片的支持
**描述你已经考虑的替代方案**
对任何替代解决方案或功能的清晰简明的描述。
有朋友利用ai写了相关的方案(非程序员，仅仅实现功能不够细化)，但是我想由作者来添加这些功能  以便后续功能能够正常更新而不会发生因为修改内容而造成的各种报错。

**附加说明**
在此处添加有关功能请求的任何其他说明、屏幕截图或者引用。

**Comment by ikechan8370** [comment]
可以考虑 有时间我加一下

**Comment by ZHAOZ1491** [comment]
> 可以考虑 有时间我加一下
大佬是加qq吗？

**Comment by ZHAOZ1491** [comment]
> 可以考虑 有时间我加一下

大佬威武
