### ISSUE TITLE
感觉nonebot的chatgpt功能挺好，能不能借鉴一下doge

### ISSUE THREAD

**Issue by yyk725** [ikechan8370/chatgpt-plugin#74]
nonebot里的chatgpt插件可以直接调用系统里已登录的浏览器请求，所以没有验证码之类的东西，而且还能保持上下文在同一对话里
就是偶尔不响应正则……
要不去借鉴一下（

**Comment by ikechan8370** [comment]
> nonebot里的chatgpt插件可以直接调用系统里已登录的浏览器请求，所以没有验证码之类的东西，而且还能保持上下文在同一对话里
> 
> 就是偶尔不响应正则……
> 
> 要不去借鉴一下（

具体哪个项目？可以发个链接吗？

**Comment by wearshoes** [comment]
> > nonebot里的chatgpt插件可以直接调用系统里已登录的浏览器请求，所以没有验证码之类的东西，而且还能保持上下文在同一对话里
> > 就是偶尔不响应正则……
> > 要不去借鉴一下（
> 
> 具体哪个项目？可以发个链接吗？

大概是这个？
https://github.com/A-kirami/nonebot-plugin-chatgpt

**Comment by Dream-yyk** [comment]
卧槽我忘记发了c
