### ISSUE TITLE
抢云崽本体指令(表情包)

### ISSUE THREAD

**Issue by CUZNIL** [ikechan8370/chatgpt-plugin#75]
![QMR25({`D9X%J}$@%51O_E0](https://user-images.githubusercontent.com/76582404/208919415-1d03e191-1a11-44af-a5aa-575e97764d0e.png)
如图所示，表情包被chatgpt抢了
![RY7T({3 46T4K81SJS8 %{C](https://user-images.githubusercontent.com/76582404/208919674-6b508109-d29c-463e-8531-6c23d6b71fb6.png)
如图，屏蔽后可以正常使用
![image](https://user-images.githubusercontent.com/76582404/208919729-550582de-82ce-41d6-a525-2e617cb9362d.png)

**Comment by Kay2048** [comment]
不仅这个 记得和一个ai也冲突 建议还是做成之前那样#chatgpt触发比较好或者可以自己选择触发方式

**Comment by rnadow** [comment]
> 

加一，我的喵喵插件也废了，顺便问下最后那个管理屏蔽的是什么插件？

**Comment by ikechan8370** [comment]
> > 
> 
> 加一，我的喵喵插件也废了，顺便问下最后那个管理屏蔽的是什么插件？

喵喵不会受影响吧？我这正常用的呢。

**Comment by rnadow** [comment]
> 

我的没反应，难道是其他问题？

**Comment by rnadow** [comment]
> 

我的不行，其他问题导致的？

**Comment by ikechan8370** [comment]
> 

是最新版本吗？你检查一下本插件`apps/chat.js`里的priority,默认15000实测应该没问题，不行就调大一点。

**Comment by rnadow** [comment]
> > 
> 
> 是最新版本吗？你检查一下本插件`apps/chat.js`里的priority,默认15000实测应该没问题，不行就调大一点。

昨天刚刚安的这个插件，加了个0，重启也没用，打算改改正则

**Comment by rnadow** [comment]
> > > 
> > 
> > 
> > 加一，我的喵喵插件也废了，顺便问下最后那个管理屏蔽的是什么插件？
> 
> 喵喵不会受影响吧？我这正常用的呢。

不好意思，刚看到输出是喵喵缺少模块了，抱歉

**Comment by rnadow** [comment]
> 

最后那个是什么插件啊，问问
