### ISSUE TITLE
报错：ChatGPTAPI error 429

### ISSUE THREAD

**Issue by bi-zx** [ikechan8370/chatgpt-plugin#78]
![image](https://user-images.githubusercontent.com/79581178/209438501-c663620e-7cff-495d-8d9a-d926087ec32a.png)
云崽本体部分完全正常，chatgpt-plugin部分存在问题：
Chromium界面启动一次，只能回复一次问题，第二次会报error 429。重启Chromium示例或者重启系统后问题完全复现。
系统版本如下：
![image](https://user-images.githubusercontent.com/79581178/209438687-bbe569ee-8be3-48e0-b800-c53ef07ea139.png)

**Comment by ikechan8370** [comment]
429是ip问题吧，我这里用自用的ip没有出现类似的问题
#53

**Comment by 693093880** [comment]
使用当前节点发送的请求太多，我换了个节点就好了
