### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by psernokx** [ikechan8370/chatgpt-plugin#79]
Cannot find package 'uuid' imported from /home/lighthouse/Yunzai-Bot/plugins/chatgpt-plugin/utils/browser.js

**Comment by bi-zx** [comment]
缺少package，试试这个：
```
npm install -g cnpm --registry=https://registry.npm.taobao.org
cnpm install uuid
```

**Comment by psernokx** [comment]
已解决 谢谢

**Comment by psernokx** [comment]
> 



> 缺少package，试试这个：
> 
> ```
> npm install -g cnpm --registry=https://registry.npm.taobao.org
> cnpm install uuid
> ```



> 缺少package，试试这个：
> 
> ```
> npm install -g cnpm --registry=https://registry.npm.taobao.org
> cnpm install uuid
> ```

已解决  谢谢
