### ISSUE TITLE
Index.js中修改了账号和密码，但登录显示的是另外一个账号

### ISSUE THREAD

**Issue by ClaypotRice** [ikechan8370/chatgpt-plugin#81]
因为我有google chrome 这个软件，所以以前登录的是我的google账号，并且是以Google账号方式登录。现在改为了账号和密码登录，我再创建了一个账号。由账号密码登录的。 我按照readme的要求输入了账号和密码在config/index.js中。但是当它运行打开chrome的时候是输入了我的账号，就是和我在index.js输入不一样的。怎么解决这问题？我很确定我把chrome的账号密码自动输入关了。
<img width="437" alt="Screenshot 2022-12-26 200952" src="https://user-images.githubusercontent.com/105097979/209609765-a1fb509b-4acc-4d75-8a75-d66cefe4dbf0.png">
![Uploading Screenshot_20221226_080811.png…]()

**Comment by ClaypotRice** [comment]
<img width="724" alt="Screenshot_20221226_080811" src="https://user-images.githubusercontent.com/105097979/209609943-ef03a963-4aa4-4040-be5b-1eedc6c32583.png">
这是index.js 截图

**Comment by ikechan8370** [comment]
应该是redis中的缓存，这里我没处理，你先清掉这个key吧，redis-cli进入后执行`del CHATGPT:API_OPTION`
