### ISSUE TITLE
载入插件错误：chat    Cannot find package 'uuid'

### ISSUE THREAD

**Issue by Sagili365** [ikechan8370/chatgpt-plugin#82]
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'uuid' imported from /root/0/Yunzai-Bot/plugins/chatgpt-plugin/utils/browser.js
![image](https://user-images.githubusercontent.com/102888970/209638445-e0caed91-69dc-415e-945b-90b74b402fc6.png)
是浏览器什么问题吗？
另外想问一下有没有这个插件相关的交流群啥的

**Comment by bi-zx** [comment]
[#79 ](https://github.com/ikechan8370/chatgpt-plugin/issues/79)

**Comment by Sagili365** [comment]
已解决，非常感谢
