### ISSUE TITLE
puppeteer Chromium 启动失败

### ISSUE THREAD

**Issue by Sagili365** [ikechan8370/chatgpt-plugin#84]
![image](https://user-images.githubusercontent.com/102888970/209772725-460e2090-3634-450c-bdcb-f9e8dfdaba90.png)
其他插件好像可以正常启动puppeteer Chromium，但是chatgpt插件好像启动的时候出了点问题，怎么解决啊，config如下
![image](https://user-images.githubusercontent.com/102888970/209773089-cf800b99-9667-4ae9-bf01-2aae4a7d416e.png)

**Comment by ikechan8370** [comment]
目前基本不能使用puppeteer Chromium，要使用非无头的浏览器，需要有图形界面。

**Comment by wearshoes** [comment]
> 目前基本不能使用puppeteer Chromium，要使用非无头的浏览器，需要有图形界面。

大佬方便抽空看看这个文章吗？
https://scrapeops.io/web-scraping-playbook/how-to-bypass-cloudflare/
