### ISSUE TITLE
载入插件错误：chat

### ISSUE THREAD

**Issue by YunMu13** [ikechan8370/chatgpt-plugin#85]
如图
![微信截图_20221228174628](https://user-images.githubusercontent.com/109336408/209792651-c6520b37-ab54-46c5-b6e5-26369e090b90.png)
安装依赖库的时候出现以下
![微信截图_20221228174707](https://user-images.githubusercontent.com/109336408/209792777-5c9e59ea-2a49-4db6-be2a-c5e4810fac84.png)

**Comment by bi-zx** [comment]
[#79](https://github.com/ikechan8370/chatgpt-plugin/issues/79)
[#82](https://github.com/ikechan8370/chatgpt-plugin/issues/82)

**Comment by YunMu13** [comment]
非常感谢
