### ISSUE TITLE
国外代理需要一直挂着吗

### ISSUE THREAD

**Issue by YunMu13** [ikechan8370/chatgpt-plugin#86]
服务器架设在国内，开机登陆的时候没挂代理显示not available地区服务问题，登录后能关了代理吗

**Comment by YunMu13** [comment]
![Screenshot_2022_1229_011956](https://user-images.githubusercontent.com/109336408/209849121-dad34eef-c5db-4434-89cb-b39e982c8dda.png)

**Comment by ikechan8370** [comment]
不能。现在限制很严格

**Comment by YunMu13** [comment]
ok
