### ISSUE TITLE
插件载入失败

### ISSUE THREAD

**Issue by yuorchu** [ikechan8370/chatgpt-plugin#88]
什么都尝试过了但是还是错误
![Screenshot_20221231_132717](https://user-images.githubusercontent.com/106755538/210126302-815b2b29-fbcf-4f3f-962a-289e977989d1.jpg)

**Comment by Yuchu135** [comment]
发现是在根目录，不过没有报错但没有反应

**Comment by ikechan8370** [comment]
是不是有字符串没加引号？

**Comment by yuorchu** [comment]
> 是不是有字符串没加引号？

都加了啊
![Uploading Screenshot_20230103_171647.jpg…]()

**Comment by yuorchu** [comment]
> 是不是有字符串没加引号？

都加了啊
![Uploading Screenshot_20230103_171647.jpg…]()
