### ISSUE TITLE
报错Unauthorized

### ISSUE THREAD

**Issue by 1935220968** [ikechan8370/chatgpt-plugin#9]
完整报错，请问是什么没有授权
Error: ChatGPT failed to refresh auth token. Error:
Unauthorized
    at ChatGPTAPI.refreshAccessToken (file:///G:/redis-windows-7.0.4/Yunzai-Bot/
node_modules/.pnpm/chatgpt@2.0.3/node_modules/chatgpt/build/index.js:259:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTAPI.ensureAuth (file:///G:/redis-windows-7.0.4/Yunzai-Bot/no
de_modules/.pnpm/chatgpt@2.0.3/node_modules/chatgpt/build/index.js:225:12)
    at async chatgpt (file:///G:/redis-windows-7.0.4/Yunzai-Bot/plugins/chatgpt/
index.js:117:5)
    at async PluginsLoader.deal (file:///G:/redis-windows-7.0.4/Yunzai-Bot/lib/p
lugins/loader.js:251:52)

**Comment by ikechan8370** [comment]
检查一下token是否复制错了？复制的是否是正确的token？
如果不行可以跟踪一下这个issue：https://github.com/transitive-bullshit/chatgpt-api/issues/43。
原作者让试一试退出登录重新登录用新的token试试

**Comment by 1935220968** [comment]
token没问题，每次都确认过，也重新登录重置过，不知道为什么，

**Comment by ikechan8370** [comment]
> token没问题，每次都确认过，也重新登录重置过，不知道为什么，

试过清除所有缓存了嘛？
![image](https://user-images.githubusercontent.com/21212372/206351745-b0022f62-5d4a-48eb-a868-25df86b37dc1.png)
比如这个
官方网页版是能正常对话的？

**Comment by 1935220968** [comment]
奥我去试试，官方网站的确正常对话

**Comment by 1935220968** [comment]
![image](https://user-images.githubusercontent.com/71560643/206352138-bfda7711-39d3-4691-8962-298555308841.png)
哦豁，这个是怎么回事

**Comment by ikechan8370** [comment]
第一次见到这个提示欸。是不是注册和登录ip所属国家地区对不上被标记了？

**Comment by 1935220968** [comment]
有可能，我买的号，现在是日本东京

**Comment by cj0928** [comment]
![image](https://user-images.githubusercontent.com/104024133/206361239-57e3fd38-b3fa-47c1-bd43-7c14c0654afc.jpeg)

**Comment by 1935220968** [comment]
咱俩一样

**Comment by ikechan8370** [comment]
有这个问题的去官网登录一下看看能不能正常使用？

**Comment by 1935220968** [comment]
刚刚清除了缓存，还是这个样子
![image](https://user-images.githubusercontent.com/71560643/206375512-247c5593-4338-40ca-88f0-5c7a8ebcdb53.png)

**Comment by 1935220968** [comment]
ok刚刚登录可以用了，不知道原因是什么，挺奇妙的，感谢大佬们
