### ISSUE TITLE
linux（centos）系统现在可以正常使用了吗，装了好几次了都没成功，好多报错0.0

### ISSUE THREAD

**Issue by SakuragiKuroko** [ikechan8370/chatgpt-plugin#93]

**Comment by ikechan8370** [comment]
只要依赖装好，不缺依赖就不会报错吧。linux可以正常使用，需要准备好代理和XServer也就是界面，按照readme可以装一个简单的xvfb。

**Comment by Qz-Sean** [comment]
> 只要依赖装好，不缺依赖就不会报错吧。linux可以正常使用，需要准备好代理和XServer也就是界面，按照readme可以装一个简单的xvfb。

![image](https://user-images.githubusercontent.com/56262913/211538378-e30f96ad-799a-4bc9-a8ab-9c3565063834.png)
![image](https://user-images.githubusercontent.com/56262913/211537752-5a4fe09b-007a-444d-822c-a920561ab8ff.png)
连接不上服务器咋整

**Comment by Qz-Sean** [comment]
> 

![image](https://user-images.githubusercontent.com/56262913/211541918-c0096107-eb79-41a4-867a-aabbe1f43aba.png)
![image](https://user-images.githubusercontent.com/56262913/211541967-82f2890f-026f-4a7f-bdc5-1e317ea3d439.png)
装了这两个还是不行

**Comment by Qz-Sean** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/56262913/211541918-c0096107-eb79-41a4-867a-aabbe1f43aba.png) ![image](https://user-images.githubusercontent.com/56262913/211541967-82f2890f-026f-4a7f-bdc5-1e317ea3d439.png) 装了这两个还是不行

![image](https://user-images.githubusercontent.com/56262913/211542302-42537ba0-37e4-439b-862f-0fc43df6f4fd.png)

**Comment by SanQianQVQ** [comment]
对于 CentOS7，此问题已于 https://github.com/ikechan8370/chatgpt-plugin/pull/110 解决
