### ISSUE TITLE
Error: SyntaxError: Unexpected non-whitespace character after JSON at position 4

### ISSUE THREAD

**Issue by EternisField** [ikechan8370/chatgpt-plugin#95]
0|Yunzai-Bot  | [YzBot][12:40:46.853][ERRO] Error: SyntaxError: Unexpected non-whitespace character after JSON at position 4
0|Yunzai-Bot  |     at ChatGPTPuppeteer.sendMessage (file:///C:/Users/Administrator/Desktop/Yunzai-Bot/Yunzai-Bot/plugins/chatgpt-plugin/utils/browser.js:496:21)
0|Yunzai-Bot  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|Yunzai-Bot  |     at async chatgpt (file:///C:/Users/Administrator/Desktop/Yunzai-Bot/Yunzai-Bot/plugins/chatgpt-plugin/apps/chat.js:231:22)
0|Yunzai-Bot  |     at async PluginsLoader.deal (file:///C:/Users/Administrator/Desktop/Yunzai-Bot/Yunzai-Bot/lib/plugins/loader.js:251:52) {
0|Yunzai-Bot  |   statusCode: undefined,
0|Yunzai-Bot  |   statusText: undefined
0|Yunzai-Bot  | }

突然就出现了这个问题，求解答

**Comment by ikechan8370** [comment]
更新一下亲测可用了。openai不知道后端改了什么东西。仿照chatgpt-api的做法加了个检查。
