### ISSUE TITLE
启动无报错，对话报错，与OpenAI通信异常

### ISSUE THREAD

**Issue by rinhon** [ikechan8370/chatgpt-plugin#98]
与OpenAI通信异常，请稍后重试：Error: net::ERR_PROXY_CONNECTION_FAILED at https://chat.openai.com/chat

系统是Ubuntu Server 20.04 LTS 64bit

我以为是外网的问题，因为用的谷歌账号，所以就装了个v2ray客户端
测试 curl –socks5 127.0.0.1:10808 https://www.google.com/
返回的网页代码，应该是通了
但是还是报错通信异常,无论挂着梯子还是不挂都通信异常

这是配置文件
![image](https://user-images.githubusercontent.com/54661549/212285910-88054078-1a4f-4f79-9bc6-98bcd3cbd304.png)

**Comment by ikechan8370** [comment]
PROXY变量没填吧

**Comment by rinhon** [comment]
> PROXY变量没填吧

大佬，这个变量怎么填
填 端口号
还是
127.0.0.1：端口号

应该是我服务器梯子没搭好的原因，代理服务器是没问题

**Comment by ikechan8370** [comment]
http://127.0.0.1:xxxx
或者socks5://127.0.0.1:xxxx
就是完整的代理地址

> > PROXY变量没填吧
> 
> 大佬，这个变量怎么填 填 端口号 还是 127.0.0.1：端口号
> 
> 应该是我服务器梯子没搭好的原因，代理服务器是没问题

**Comment by rinhon** [comment]
> http://127.0.0.1:xxxx 或者socks5://127.0.0.1:xxxx 就是完整的代理地址
> 
> > > PROXY变量没填吧
> > 
> > 
> > 大佬，这个变量怎么填 填 端口号 还是 127.0.0.1：端口号
> > 应该是我服务器梯子没搭好的原因，代理服务器是没问题

好的，感谢大佬
